import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_5.csv"
SQL_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_5.sql"

ROWS = [
    ("Cografya", 1, "Map projection çi dike?", "Rûyê gerstêrka dorpêçkirî li ser rûyekî vekirî nîşan dide.", "Tenê rêya avê di nav çiyayên de nîşan dide.", "Gerstêrkê ji navenda wê veqetîne.", "Her cihê li ser Erdê bi heman awayî mezin dike.", "A", "USGS map projectionê wekî rêbazeke nîşandana hemû an beşek ji Erdê ya dorpêçkirî li ser rûyekî teswîr dike.", "Map Projections – USGS", "https://www.usgs.gov/publications/map-projections"),
    ("Cografya", 2, "Çima tu nexşeyekê nikarî bi temamî wekî kopiyeke bêxelet a Erdê bibînî?", "Ji ber ku rûyê dorpêçkirî divê li ser rûyekî rast bê veguhastin û di vê pêvajoyê de hin taybetmendî diguhere.", "Ji ber ku Erd her roj ji navê xwe derdikeve.", "Ji ber ku nexşe tenê ji bo avê tê çêkirin.", "Ji ber ku hemû nexşe bi heman pîvanê hatine çêkirin.", "A", "USGS diyar dike ku projeksiyon veguhastina rûyê dorpêçkirî bo rûyekî rast e; ji ber vê yekê pêdivî ye hin taybetmendî bên hilbijartin.", "Map Projections – USGS", "https://www.usgs.gov/publications/map-projections"),
    ("Cografya", 2, "Di nexşeyekê de, projeksiyona wekhev-rû çi tiştî diparêze?", "Rêjeya rûberê herêmên li ser nexşeyê bi rêjeya wan a li ser Erdê re nêzîk dike.", "Hemû goşeyên herêmê bê xelet diparêze.", "Hemû dûrahiyan di her rêyekê de yek dike.", "Rengê hemû welatan bi heman awayî dike.", "A", "Projeksiyona wekhev-rû ji bo berawirdkirina rûberê herêmên cûda tê bikaranîn; ew ne pêwîst e goşe û dûrahiyan jî biparêze.", "Map Projections – USGS", "https://pubs.usgs.gov/gip/70047422/report.pdf"),
    ("Cografya", 3, "Kengî nexşeyekê bi projeksiyona cuda ji nexşeyeke din re dikare bêtir guncaw be?", "Dema ku armanc cuda be, wekî pîvandina rûber, dûrahî, goşe an rêya rêwîtiyê.", "Dema ku tu dixwazî hemû taybetmendiyên Erdê bê xelet nîşan bidî.", "Dema ku pîvan û armanc di nexşeyê de ne girîng in.", "Dema ku tu dixwazî tenê navê welatan binivîsî.", "A", "USGS dibêje hilbijartina projeksiyonê bi taybetmendiya ku divê bê parastin û bi armanca bikaranînê ve girêdayî ye.", "Map Projections – USGS", "https://pubs.usgs.gov/gip/70047422/report.pdf"),
    ("Ziman", 1, "Li gorî UNESCO, çima zimanên di xeterê de divê bêne belgekirin?", "Ji bo ku ziman, zanîn û şêwazên vegotinê yên civakê ji bo nifşên paşerojê bên parastin.", "Ji bo ku hemû zimanên din ji perwerdehiyê bên derxistin.", "Ji bo ku ziman tenê wekî mijara muzean bê bikaranîn.", "Ji ber ku ziman qet naguherin.", "A", "Belgekirin dikare deng, peyv, vegotin û zanîna zimanekî biparêze; ew divê bi rêzgirtina maf û razîbûna civakê bê kirin.", "Linguistic Diversity and Language Endangerment – UNESCO", "https://ich.unesco.org/doc/src/00142-EN.pdf"),
    ("Ziman", 2, "Di parastina zimanekî kêm-bikarhatî de, çima axêverên wê civakê divê roleke navendî hebin?", "Ji ber ku ew li ser wate, bikaranîn, vegotin û hewcedariyên rast ên zimanê xwe zanîna herî nêzîk hene.", "Ji ber ku kesên derveyî her tim zimanê wan ji wan baştir dizanin.", "Ji ber ku ziman tenê bi ferhengê tê parastin.", "Ji ber ku axêver divê ji pêvajoya belgekirinê bêne dûrxistin.", "A", "Belgekirina zimanî dema ku bi axêver û civakê re tê çêkirin, hem rastiya agahiyê hem jî rêzgirtina mafên wan baştir diparêze.", "Linguistic Diversity and Language Endangerment – UNESCO", "https://ich.unesco.org/doc/src/00142-EN.pdf"),
    ("Ziman", 2, "Cûrbecûrbûna zimanî ji bo çandê çi dide?", "Rêbazên cuda yên fikirîn, bîranîn, vegotin û têgihiştina cîhanê diparêze.", "Tenê hejmarê zimanên di ferhengê de zêde dike.", "Hemû zimanên din ji hev cuda dike û astengiyê çêdike.", "Dibe sedem ku ziman qet neguhere.", "A", "UNESCO zimanên cuda bi cûrbecûrbûna çandî û bi parastina zanîn, bîr û vegotinên civakan re girêdide.", "Linguistic Diversity and Language Endangerment – UNESCO", "https://ich.unesco.org/doc/src/00142-EN.pdf"),
    ("Ziman", 3, "Di siyaseta zimanî ya adil de, kîjan rêbaz herî guncaw e?", "Gihiştina perwerde û agahiyê bi zimanên cuda, bi şertê ku maf û hewcedariyên civakan bên hesibandin.", "Qebûlkirina tenê yek ziman di hemû qadên jiyanê de.", "Qedexekirina zimanên malbatê ji jiyana giştî.", "Bihêzkirina zimanekî bi rakirina hemû zimanên din.", "A", "Rêbaza pirzimanî dikare gihiştina wekhev û beşdarbûna civakî zêde bike, dema ku bi şertên herêmî û mafên axêveran re were saz kirin.", "Media and Information Literacy – UNESCO", "https://www.unesco.org/en/multilingualism-linguistic-diversity?hub=67103"),
    ("Paradigma", 1, "Li gorî UNESCO, medya û jêderên agahiyê nirxandin çi beşek ji çi jêhatîbûnê ye?", "Beşek ji jêhatîbûna medya û agahiyê ye ku gihiştin, analîz, nirxandin û afirandina naverokê dihewîne.", "Beşek ji jêhatîbûna ku tenê li ser çêkirina reklaman raweste.", "Rêbazek e ku naveroka dîjîtal bê lêkolîn bê pejirandin.", "Tenê jêhatîbûna bikaranîna amûra elektronîk e.", "A", "UNESCO medya û jêhatîbûna agahiyê bi gihiştin, analîz, nirxandin û afirandina naverokê bi awayekî rexneyî re pênase dike.", "Media and Information Literacy – UNESCO", "https://www.unesco.org/en/ami"),
    ("Paradigma", 2, "Kesek agahiyek li ser torê dibîne. Kîjan gav bi medya û agahiyê re herî berpirsiyar e?", "Çavkaniyê, tarîxê, delîlên wê û armanca naverokê kontrol bike berî ku wê parve bike.", "Ji ber ku gelek kesan ew parve kiriye, rast qebûl bike.", "Tenê li ser wêneyê naverokê biryar bide.", "Naverokê bê nav û bê çavkanî bi lez parve bike.", "A", "UNESCO nirxandina çavkanî, armanc û delîlan wekî beşeke bingehîn a medya û agahiyê dide naskirin.", "Media and Information Literacy – UNESCO", "https://www.unesco.org/en/articles/media-and-information-literacy"),
    ("Paradigma", 2, "Çima medya û agahiyê bi beşdarbûna civakî re têkildar e?", "Ji ber ku kesên ku agahiyê bi rexne dinirxînin dikarin di nîqaş û biryardan de bi berpirsiyarî beşdar bibin.", "Ji ber ku medya divê tenê ji bo şahiyê bê bikaranîn.", "Ji ber ku beşdarbûn bi gihiştina agahiyê re têkildar nîne.", "Ji ber ku naveroka medyayê qet bandorê li civakê nake.", "A", "UNESCO medya û agahiyê bi civaka agahdar, beşdar û li hember naveroka şaş berxwedêr re girê dide.", "Media and Information Literacy – UNESCO", "https://www.unesco.org/en/ami"),
    ("Paradigma", 3, "Di nirxandina naveroka dîjîtal de, çima divê armanca nivîskar an saziya wê jî bê pirsîn?", "Ji ber ku armanc dikare awayê hilbijartina daneyan, ziman û dîtina mijarê bandor bike.", "Ji ber ku armanc her tim rastbûna naverokê nîşan dide.", "Ji ber ku armancê naverokê qet naguhere.", "Ji ber ku tenê navnîşana malperê bes e.", "A", "Nirxandina çavkaniyê tenê bi nav û şêwaza nivîsê nayê temamkirin; armanc û şertên hilberîna naverokê jî girîng in.", "Media and Information Literacy – UNESCO", "https://www.unesco.org/mil4teachers/en/introduction"),
    ("Çand", 1, "Li gorî UNESCO, di mîrasa bê-maddî ya xwarinê de çi tê parastin?", "Pratîkên çandin, amadekirin û xwarina xwarinê, ne tenê navê xwarinê.", "Tenê navê xwarinên herêmî.", "Tenê amûrên ku di aşxaneyê de tên bikaranîn.", "Tenê hilberîna pîşesazî ya xwarinê.", "A", "UNESCO diyar dike ku li ser navnîşên mîrasa bê-maddî pratîk û rêbazên çandin, amadekirin û xwarinê tên parastin, ne tenê xwarin wekî berhem.", "Food and Intangible Heritage – UNESCO", "https://www.unesco.org/en/articles/food-and-intangible-heritage-flavourful-relationship"),
    ("Çand", 2, "Çima kevneşopiyên xwarinê dikarin ji bo dîroka civakê çavkaniyeke girîng bin?", "Ji ber ku ew bîr, hawirdor, danûstandina çandî, kar û jiyana rojane di nav pratîkên xwarinê de nîşan didin.", "Ji ber ku xwarin tenê bi tamê ve tê pênasekirin.", "Ji ber ku kevneşopiyên xwarinê bi civakê re têkildar nînin.", "Ji ber ku xwarin divê ji şertên hawirdorê bê veqetandin.", "A", "UNESCO pratîkên xwarinê bi dîrok, bîr, birêvebirina hawirdorê, danûstandina çandî û jiyana civakî re girêdide.", "Food and Intangible Heritage – UNESCO", "https://www.unesco.org/en/articles/food-and-intangible-heritage-flavourful-relationship"),
    ("Muzîk", 2, "Di parastina muzîka kevneşopî de, çima hînkirina nifş bi nifş girîng e?", "Ji ber ku şêwaz, repertuwar, teknîk û wateya pratîkê di nav jiyanê de tê veguhastin.", "Ji ber ku muzîk divê ji performansa zindî bê dûrxistin.", "Ji ber ku tenê tomarkirina dengê dikare hemû wateyê biparêze.", "Ji ber ku hunermendên ciwan nikarin tiştekî nû fêr bibin.", "A", "UNESCO mîrasa bê-maddî wekî zanîn û jêhatîbûnên ku ji nifşekê bo nifşekî din tên veguhastin dide pênasekirin.", "Performing Arts – UNESCO", "https://ich.unesco.org/en/performing-arts-00054"),
    ("Muzîk", 3, "Kîjan nêrîn di derbarê muzîka kevneşopî de bi rêz û berdewamiyê re li hev tê?", "Muzîk dikare hem li ser bingeha kevneşopiyê were parastin hem jî di performansên nû de were afirandin.", "Muzîk tenê dema ku qet naguhere dikare rast bimîne.", "Guhertin di hemû rewşan de wateya muzîkê ji holê radike.", "Kevneşopî û afirandin nikarin di heman pratîkê de hebin.", "A", "Mîrasa zindî dikare bi şertên nû re biguhere, bê ku têkiliya wê bi bîr û zanîna berê winda bibe.", "What is Intangible Cultural Heritage? – UNESCO", "https://ich.unesco.org/en/what-is-intangible-heritage-00003?lang=en"),
]

FIELDS = ["id", "category_key", "language_code", "prompt", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "difficulty", "source_title", "source_url", "publication_status", "quality_note"]

def q(v):
    return "'" + v.replace("'", "''") + "'"

def main():
    with CSV_OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        for i, row in enumerate(ROWS, 1):
            category, difficulty, prompt, a, b, c, d, correct, explanation, title, url = row
            w.writerow({"id": f"general5_{i:04d}", "category_key": category, "language_code": "ku-kmr", "prompt": prompt, "option_a": a, "option_b": b, "option_c": c, "option_d": d, "correct_option": correct, "explanation": explanation, "difficulty": difficulty, "source_title": title, "source_url": url, "publication_status": "PENDING_EDITORIAL_APPROVAL", "quality_note": "Kategori bazlı, kaynaklı ve özgün olarak hazırlandı; ikinci editoryal kontrol bekliyor."})
    values = []
    for category, difficulty, prompt, a, b, c, d, correct, explanation, title, url in ROWS:
        values.append("(" + ", ".join(["(select id from public.categories where name = " + q(category) + ")", q("ku-kmr"), q(prompt), q(a), q(b), q(c), q(d), q(correct), q(explanation), str(difficulty), "false", q("multiple_choice"), "NULL", q(url)]) + ")")
    SQL_OUT.write_text("-- Cografya, ziman, medya okuryazarligi, gıda mirasi ve muzik paketi.\n-- Canli yayin icin onaylanmadi.\ninsert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values\n" + ",\n".join(values) + ";\n", encoding="utf-8")
    print(f"wrote {len(ROWS)} rows")

if __name__ == "__main__":
    main()
