import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_OUT = ROOT / "supabase" / "2026-07-14_movement_sources_question_wave_3.csv"
SQL_OUT = ROOT / "supabase" / "2026-07-14_movement_sources_question_wave_3.sql"

ROWS = [
    ("Ziman", 2, "Ronahî di têkiliya xwe ya bi Hawarê re çawa tê pênasekirin?", "Wekî pêvekeke wêneyî ya kovara Hawarê.", "Wekî rojnameyekê ku li Qahîreyê di sala 1898an de dest pê kir.", "Wekî kovareke ku tenê li ser muzîka klasîk a Kurdî nivîsî.", "Wekî pirtûkxaneya fermî ya Kongra Star.", "A", "Katalogên pirtûkxaneyê Ronahî wekî pêveka wêneyî ya kovara Kurdî Hawarê nîşan didin; weşandina wê li Şamê di 1942–1945an de hatiye tomar kirin.", "Ronahî – CiNii Journals", "https://ci.nii.ac.jp/ncid/AB00048098", "Kısa bir yayın ilişkisini tarih ve tür bilgisiyle birlikte ölçüyor."),
    ("Ziman", 3, "Di pênaseya Pirtûkxaneya Jinên Kurdistanê de, pirtûka destpêkê ya Jineolojî bi çi awayî tê naskirin?", "Wekî danasîna kurt a Jineolojî, zanista jinê û jiyanê.", "Wekî ferhengoka erebî-Kurmancî ya Ehmedê Xanî.", "Wekî arşîva kovara Hawarê ya di Şamê de.", "Wekî pirtûka rêzimanê ji bo xwendekarên zaravayê Soranî.", "A", "Pirtûkxane û navenda arşîvê pirtûkê wekî danasîna kurt a Jineolojî, ku bi zanista jinê û jiyanê tê naskirin, pêşkêş dike.", "Kurdish Women’s Library – What is Jineolojî", "https://pirtukxaneyajinenkurdistan.com/en/post/what-is-jineoloji/", "Hareketin kendi eğitim materyalini, başka bir klasik eserle karıştırmadan ölçüyor."),
    ("Edebiyat", 3, "Pirtûka Revolution in Rojava: Democratic Autonomy and Women’s Liberation li ser kîjan du mijarên sereke raweste?", "Xweseriya demokratîk û azadiya jinan li Kurdistana Sûriyê.", "Rêzimanê Hawarê û dîroka Mem û Zînê.", "Tenê muzîka dengbêjan û stranên Newrozê.", "Tenê dîroka aborî ya Zagrosê û çiyayên Bahtiyarî.", "A", "Nav û danasîna pirtûkê dîroka ceribandina Rojava bi xweseriya demokratîk û azadiya jinan ve girê dide.", "Revolution in Rojava – Pluto Press / David Graeber", "https://davidgraeber.org/books/revolution-in-rojava/", "Kitap başlığını iki kavramın ilişkisi üzerinden ölçüyor; hareket propagandası gibi yazılmadı."),
    ("Edebiyat", 3, "Pirtûka Women in the Kurdish Movement: Mothers, Comrades, Goddesses kîjan perspektîfê dide pêş?", "Lêkolînek femînîst li ser jinên ku rolên li ser wan hatine ferz kirin diguherînin û dikevin pêşiya tevgera siyasî.", "Lêkolînek tenê li ser avakirina çiyayên Zagrosê.", "Ferhengokeke ku peyvên Hawarê bi erebî rave dike.", "Pirtûka stranên olî ya ku bi dengbêjî ve têkildar nîne.", "A", "Danasîna Springer pirtûkê wekî lêkolînek rexneyî-femînîst dide naskirin ku li ser jinên di tevgera Kurdî de û guherîna nasnameyên wan raweste.", "Women in the Kurdish Movement – Springer", "https://link.springer.com/book/10.1007/978-3-030-24744-7", "Kitabın konu alanını, başlıktaki üç metafora indirgemeden açıklıyor."),
    ("Dîrok", 2, "Ronahî li gorî katalogê di kîjan demê de li Şamê hatiye çapkirin?", "1942–1945",
     "1932–1935", "1898–1902", "1960–1963", "A", "Katalogê CiNii Ronahî wekî weşanek li Şamê di navbera 1942 û 1945an de dide tomar kirin.", "Ronahî – CiNii Journals", "https://ci.nii.ac.jp/ncid/AB00048098", "Hawar dönemiyle karıştırılabilecek yakın tarihler çeldirici olarak kullanıldı."),
    ("Dîrok", 3, "Li gorî lêkolîna Cambridge, kovara Jineolojî ji kîjan salê ve hatiye weşandin?", "Ji sala 2016an ve.", "Ji sala 1932an ve.", "Ji sala 1898an ve.", "Ji sala 2022an ve.", "A", "Chaptersa Cambridge dibêje ku kovara Jineolojî ji sala 2016an ve tê weşandin û di nav çalakiyên hilberîna zanîna tevgera jinan de cih digire.", "The Kurdish Women’s Freedom Movement – Cambridge", "https://www.cambridge.org/core/books/kurdish-womens-freedom-movement/pkk-a-womans-party/A154F270788B30BB87C8705A5C3E794C", "Yayın başlangıcını Hawar ve Kurdistan gazetesiyle karıştırmayan bir tarih sorusu."),
    ("Cografya", 2, "Pirtûka Revolution in Rojava li ser kîjan herêmê di nav sernavê xwe de raweste?", "Li Kurdistana Sûriyê.", "Li ser giravên Egeyê.", "Li bakurê Afrîkayê.", "Li navenda deşta Hindistanê.", "A", "Sernavê pirtûkê bi awayekî eşkere xweseriya demokratîk û azadiya jinan li Kurdistana Sûriyê dide nîşandan.", "Revolution in Rojava – David Graeber", "https://davidgraeber.org/books/revolution-in-rojava/", "Coğrafya sorusu, kitabın başlığındaki bölgesel bağlamı ölçüyor."),
    ("Cografya", 3, "Li gorî lêkolîna Cambridge, komîteyên Jineolojî ji qadeke herêmî wêdetir li ku deran hatine avakirin?", "Li çar parçeyên Kurdistanê, Ewropayê û paşê li Amerîkaya Latîn.", "Tenê li Şamê û Qahîreyê.", "Tenê li navendên akademîk ên Ewropayê.", "Tenê li bajarên ku Hawar lê abonî bû.", "A", "Lêkolînê dibêje ku komîteyên Jineolojî li çar parçeyên Kurdistanê û Ewropayê hatine avakirin û paşê li Amerîkaya Latîn jî belav bûne.", "The Kurdish Women’s Freedom Movement – Cambridge", "https://www.cambridge.org/core/books/kurdish-womens-freedom-movement/pkk-a-womans-party/A154F270788B30BB87C8705A5C3E794C", "Hareketin ulus-aşırı ağını tek bir merkezle sınırlandırmıyor."),
    ("Çand", 2, "Di 10 salên yekem ên Jineolojî Dergisî de, li gorî dîroka kovarê, çend dosyayên tematik hatine amadekirin?", "33 dosya.", "10 dosya.", "57 dosya.", "100 dosya.", "A", "Dîroka kovarê dibêje ku di 10 salên yekem de 33 dosyayên tematik hatine amadekirin, ji krîza zanistên civakî heta konfederalîzma jinan.", "Jineolojî Magazine at 10 Years Old", "https://jineoloji.eu/en/2025/06/29/jineoloji-magazine-at-10-years-old-the-reunion-of-knowledge-stolen-from-women-with-women-part-1/", "Sayıyı ezberletmek yerine dergi dosyalarının kapsamını da açıklamada veriyor."),
    ("Çand", 3, "Di dîroka Jineolojî Dergisî de, kîjan mijar wekî dosyaya tematik hatiye lîstekirin?", "Ziman, kirin û teorîya baş û xweş di çarçoveya etîk û estetîkê de.", "Tenê hesabkirina bacên bazirganiyê.", "Tenê nexşeya rêyên hesinî yên Ewropayê.", "Tenê teknîka çêkirina amûrên avjeniyê.", "A", "Di lîsteya dosyayan de dosyaya etîk-estetîk mijarên ziman, kirin û teorîya baş û xweş bi hev re dide naskirin.", "Jineolojî Magazine at 10 Years Old", "https://jineoloji.eu/en/2025/06/29/jineoloji-magazine-at-10-years-old-the-reunion-of-knowledge-stolen-from-women-with-women-part-1/", "Kültür/estetik başlığını hareket dergisinin gerçek dosya listesine bağladı."),
    ("Muzîk", 2, "Di lîsteya dosyayên Jineolojî Dergisî de, kîjan mijar herî nêzîkî têkiliya huner û jiyanê ye?", "Etîk û estetîk: berxwedana baş û xweş di dîroka civakî de.", "Tenê rêzikên hilbijartina komîteyên siyasî.", "Tenê dîroka çapkirina Rojnameya Kurdistanê.", "Tenê rêbazên avakirina çiyayên Bahtiyarî.", "A", "Dîroka kovarê du dosyayên etîk û estetîk bi ziman, kirin, berxwedan û teorîya baş û xweş ve girêdide; ev mijar li nêzî huner û jiyanê ye.", "Jineolojî Magazine at 10 Years Old", "https://jineoloji.eu/en/2025/06/29/jineoloji-magazine-at-10-years-old-the-reunion-of-knowledge-stolen-from-women-with-women-part-1/", "Müzik kategorisini dar anlamda enstrüman sorusuna çevirmeyip estetik tartışmaya bağlıyor."),
    ("Muzîk", 3, "Di pirtûka Revolution in Rojava de, muzîk wekî mijara sereke ya sernavê li kîjan mijarê re têkildar tê xwendin?", "Bi jiyana civakî û azadiya jinan re, di nav ceribandina xweseriya demokratîk de.", "Bi ferhengoka Nûbihara Biçûkan re.", "Bi kronolojiya kovara Ronahî re.", "Bi geologyaya çiyayên Bahtiyarî re.", "A", "Danasîna pirtûkê muzîkê wekî mijara sereke ya sernavê nade; naveroka wê li ceribandina civakî ya xweseriya demokratîk û azadiya jinan e.", "Revolution in Rojava – Pluto Press", "https://davidgraeber.org/books/revolution-in-rojava/", "Olumsuz köklü soru: müziği kitaba zorla bağlamak yerine kitabın gerçek kapsamını ayırt ediyor."),
    ("Siyaset", 3, "Li gorî danasîna pirtûka Revolution in Rojava, «konfederalîzma demokratîk» wekî çi tê şirovekirin?", "Demokrasiyeke civakî û komunal ku bi xweseriya demokratîk û azadiya jinan re tê pêwendîkirin.", "Dewleteke navendî ku hemû biryarên herêmî ji navendê dide.", "Rêbazek tenê ji bo çapkirina kovaran.", "Rêxistineke ku ji civakê û kooperatîfan dûr e.", "A", "Danasîna pirtûkê ceribandina Rojava wekî demokrasiyeke komunal û xweseriya demokratîk nîşan dide û azadiya jinan di nav wê de cih dide.", "Revolution in Rojava – David Graeber", "https://davidgraeber.org/books/revolution-in-rojava/", "Kavram hareketin deneyimi ve kitabın sunumu üzerinden ölçülüyor; genel slogan tekrarı değil."),
    ("Siyaset", 3, "Li gorî lêkolîna Cambridge, Jineolojî ji bo tevgera jinan bi kîjan karê re tê girêdan?", "Bi hilberîna zanîna femînîst û avakirina bingehên zanistî yên civaka wekhev re.", "Bi rakirina hemû lêkolînên li ser jinan.", "Bi vegerandina tenê li wêjeya klasîk a erebî.", "Bi cihgirtina tenê di medyaya bazirganî de.", "A", "Lêkolîna Cambridge Jineolojî bi hilberîna zanîna femînîst û bi hewildana avakirina bingehên zanistî yên civakeke wekhev re têkildar dike.", "Beyond Feminism? Jineolojî – Cambridge Core", "https://www.cambridge.org/core/journals/politics-and-gender/article/beyond-feminism-jineoloji-and-the-kurdish-womens-freedom-movement/540F612294D931881942FA74EB5F7C61", "Akademik çalışma, hareketin kendi iddiası ile akademik çözümlemeyi birbirine karıştırmadan kullanıldı."),
    ("Paradigma", 3, "Li gorî danasîna Pirtûkxaneya Jinên Kurdistanê, Jineolojî ji kîjan çavkaniyê re tê xwarin?", "Ji ezmûnên têkoşînên jinan li Kurdistanê û li cîhanê.", "Ji tenê yek pirtûka dîrokî ya li Şamê.", "Ji tenê dîroka dewletên Ewropayê.", "Ji tenê nivîsarên zanistên xwezayî.", "A", "Danasîn dibêje ku Jineolojî ji ezmûnên tevgera azadiya jinên Kurdistanê û ji têkoşînên jinan li cîhanê xwar dibe.", "Kurdish Women’s Library – What is Jineolojî", "https://pirtukxaneyajinenkurdistan.com/en/post/what-is-jineoloji/", "Paradigmanın kaynak iddiasını kuruma ait eğitim metniyle sınırlı tuttu."),
    ("Paradigma", 3, "Di xwendina akademîk a Jineolojî de, çima gotina «wêdetir ji femînîzmê» divê bi baldarî bê fêmkirin?", "Ji ber ku ev gotin parçeyek ji xwe-pênaseya tevgerê ye û lêkolîner ew bi teorî û pratîkên tevgerê re dide nîqaşkirin.", "Ji ber ku ev gotin îspat dike ku hemû femînîst li ser hemû mijaran heman ramanê hene.", "Ji ber ku ev gotin Jineolojî ji her cure lêkolîna akademîkê cuda dike.", "Ji ber ku ev gotin tê wateya ku dîroka femînîzmê tune ye.", "A", "Lêkolînên akademîk ev îfade wekî iddiayek û mijara nîqaşê pêşkêş dikin; ew ne rastiyeke ku hemû lêkolîner bi yek awayî pejirandine.", "Beyond Feminism? Jineolojî – Cambridge Core", "https://www.cambridge.org/core/journals/politics-and-gender/article/beyond-feminism-jineoloji-and-the-kurdish-womens-freedom-movement/540F612294D931881942FA74EB5F7C61", "İfade, hareketin öz iddiası olarak çerçevelendi; tartışmalı üstünlük iddiası mutlak gerçek yapılmadı."),
]

FIELDS = ["id", "category_key", "language_code", "prompt", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "difficulty", "source_title", "source_url", "publication_status", "quality_note"]

def q(value):
    return "'" + value.replace("'", "''") + "'"

def main():
    with CSV_OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        for i, row in enumerate(ROWS, 1):
            category, difficulty, prompt, a, b, c, d, correct, explanation, title, url, note = row
            w.writerow({"id": f"movement3_{i:04d}", "category_key": category, "language_code": "ku-kmr", "prompt": prompt, "option_a": a, "option_b": b, "option_c": c, "option_d": d, "correct_option": correct, "explanation": explanation, "difficulty": difficulty, "source_title": title, "source_url": url, "publication_status": "PENDING_EDITORIAL_APPROVAL", "quality_note": note})
    values = []
    for category, difficulty, prompt, a, b, c, d, correct, explanation, title, url, note in ROWS:
        values.append("(" + ", ".join(["(select id from public.categories where name = " + q(category) + ")", q("ku-kmr"), q(prompt), q(a), q(b), q(c), q(d), q(correct), q(explanation), str(difficulty), "false", q("multiple_choice"), "NULL", q("movement_sources_question_wave_3")]) + ")")
    SQL_OUT.write_text("-- Hareket basın-yayın ve kitap kaynaklarından üretilen üçüncü el yazımı paket.\n-- Canlı yayın için onaylanmadı.\ninsert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values\n" + ",\n".join(values) + ";\n", encoding="utf-8")
    print(f"wrote {len(ROWS)} rows")

if __name__ == "__main__":
    main()
