import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_1.csv"
SQL_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_1.sql"

ROWS = [
    ("Ziman", 1, "Kîjan rêza zimanên fermî yên Neteweyên Yekbûyî rast e?", "Erebî, Çînî, Îngilîzî, Fransî, Rûsî û Spanî.", "Kurmancî, Soranî, Zazakî, Erebî, Îngilîzî û Fransî.", "Latînî, Yewnanî, Farsî, Erebî, Rûsî û Çînî.", "Îngilîzî, Almanî, Îtalî, Spanî, Japonî û Hindî.", "A", "Li gorî malpera Neteweyên Yekbûyî, şeş zimanên fermî Erebî, Çînî, Îngilîzî, Fransî, Rûsî û Spanî ne.", "Official Languages – United Nations", "https://www.un.org/en/our-work/official-languages"),
    ("Ziman", 2, "Li gorî UNESCO, ziman di kevneşopiyên devkî de kîjan erkê girîng dike?", "Wekî amûrekî veguhastina zanîn, nirxên civakî û bîranîna komî.", "Wekî amûrekî ku çîrokên devkî ji civakê cuda dike.", "Wekî şertê ku hemû çîrok tenê bi nivîsê werin vegotin.", "Wekî navê yekîneyeke siyasî ya navneteweyî.", "A", "UNESCO dibêje kevneşopiyên devkî û ziman zanîn, nirxên civakî û bîranîna komî ji nifşekê bo nifşekî din digihînin.", "Oral Traditions and Expressions – UNESCO", "https://ich.unesco.org/en/oral-traditions-and-expressions-00053"),
    ("Dîrok", 2, "Di Şoreşa Fransayê de, Danezana Mafên Mirov û Welatiyê di kîjan salê de hate pejirandin?", "1789an.", "1804an.", "1917an.", "1945an.", "A", "Danezana Mafên Mirov û Welatiyê di çarçoveya Şoreşa Fransayê de di sala 1789an de hate pejirandin.", "French Revolution – Encyclopaedia Britannica", "https://www.britannica.com/event/French-Revolution"),
    ("Dîrok", 3, "Şoreşa Haîtî çi wekî encameke dîrokî girîng dide nîşandan?", "Serhildana bi ser ketî ya koleyan li dijî serdestîya kolonyalî ya Fransayê û damezrandina Haîtî ya serbixwe di 1804an de.", "Girtina Stenbolê ji aliyê Fransayê ve di 1789an de.", "Damezrandina Neteweyên Yekbûyî di 1945an de.", "Guherîna alfabeya Hawarê di 1932an de.", "A", "Şoreşa Haîtî ji 1791 heta 1804 dom kir û bi serketina serhildana koleyan û serxwebûna Haîtî re encam da.", "Haitian Revolution – Encyclopaedia Britannica", "https://www.britannica.com/event/Haitian-Revolution"),
    ("Dîrok", 2, "Meşa Xwê ya Gandhi di sala 1930an de li dijî kîjan polîtîkayê bû?", "Li dijî monopola û bacê xwê ya hukûmeta Brîtanyayê li Hindistanê.", "Li dijî qedexeya zimanên herêmî ya UNESCO.", "Li dijî avakirina Neteweyên Yekbûyî.", "Li dijî weşandina kovara Hawarê.", "A", "Meşa Xwê çalakiyeke ne-şîddetî ya neobedîya medenî bû ku monopola xwê û bacê ya Brîtanyayê li Hindistanê dike hedef.", "Gandhi’s Salt March – TIME", "https://time.com/3741458/influential-protests/"),
    ("Dîrok", 3, "Di tevgera serxwebûna Hindistanê de, «neobedîya medenî» bi kîjan awayî tê fêmkirin?", "Bi redkirina çalak a qanûnên adaletsiz û bi protestoya civakî, bi girîngiya rêbaza ne-şîddetî di hin qonaxan de.", "Bi qebûlkirina bê şert a hemû qanûnên kolonyalî.", "Bi rakirina hemû çalakiyên civakî ji tevgerê.", "Bi tenê bi weşandina pirtûkên edebî.", "A", "Di çalakiyên serxwebûna Hindistanê de neobedîya medenî redkirina çalak a qanûnên kolonyalî bû; rêbaza ne-şîddetî di gelek qonaxan de girîng bû.", "Indian Independence Movement – historical overview", "https://en.wikipedia.org/wiki/Indian_independence_movement"),
    ("Cografya", 2, "Haîtî li ser kîjan giravê ye?", "Li ser girava Hispaniola, di Karayîbê de.", "Li ser girava Sicilia, di Deryaya Spî de.", "Li ser girava Java, di Asyayê de.", "Li ser girava Sakhalin, di Okyanûsa Pasîfîk de.", "A", "Haîtî li beşa rojavayî ya girava Hispaniola ya li Karayîbê ye; beşa rojhilatê giravê Komara Domînîkanê ye.", "Haiti – Encyclopaedia Britannica", "https://www.britannica.com/place/Haiti"),
    ("Cografya", 2, "Di çarçoveya UNESCO de, çima kevneşopiyên komên cuda bi heman navê «mirasê devkî» dikarin bên dîtin?", "Ji ber ku mirasê devkî dikare di nav komên cuda de were parvekirin, were adaptekirin û bi nifşan re biguhere.", "Ji ber ku UNESCO tenê mirasa yek welatê qebûl dike.", "Ji ber ku kevneşopî divê her tim heman formê biparêze.", "Ji ber ku mirasê devkî tenê li bajarên mezin heye.", "A", "UNESCO mirasa bê-maddî wekî tiştekî dinamik û berfireh dide pênasekirin ku dikare di nav komên cuda de were parvekirin û biguhere.", "What is Intangible Cultural Heritage? – UNESCO", "https://ich.unesco.org/en/what-is-intangible-heritage-00003?lang=en"),
    ("Çand", 2, "Li gorî UNESCO, kîjan yek ji qadên mirasa bê-maddî ye?", "Kevneşopiyên devkî û hunerên performansê.", "Tenê avahiyên kevirî yên kevn.", "Tenê arşîvên dewletê.", "Tenê pere û amûrên bazirganiyê.", "A", "UNESCO di nav qadên mirasa bê-maddî de kevneşopiyên devkî, hunerên performansê, pratîkên civakî, zanînên li ser xwezayê û hunera destkariyê dide hejmartin.", "Intangible Heritage Domains – UNESCO", "https://ich.unesco.org/en/intangible-heritage-domains-00052"),
    ("Çand", 3, "Li gorî UNESCO, çi taybetmendî mirasa bê-maddî ji miraseke tenê muze-yê cuda dike?", "Ew di jiyanê de tê domandin, diguhere û ji nifşekê bo nifşekî din tê veguhastin.", "Ew divê her tim bê guherîn bimîne.", "Ew tenê li ser dîroka padîşahan raweste.", "Ew tenê bi tiştên maddî tê pênasekirin.", "A", "UNESCO mirasa bê-maddî wekî miraseke zindî dide pênasekirin ku di veguhastinê de diguhere û di jiyana rojane ya koman de wate digire.", "Frequently Asked Questions – UNESCO Intangible Heritage", "https://ich.unesco.org/en/faq-01058"),
    ("Muzîk", 2, "Li gorî UNESCO, stran û helbestên destanî di kîjan qadê de dikarin cih bigirin?", "Di kevneşopiyên devkî û hunerên performansê de.", "Tenê di arşîvên siyasî de.", "Tenê di qadên geologyayê de.", "Tenê di ferhengên aborî de.", "A", "UNESCO di nav kevneşopiyên devkî de stran, helbestên destanî, çîrok, lavik û performansên devkî dide nîşandan.", "Oral Traditions and Expressions – UNESCO", "https://ich.unesco.org/en/oral-traditions-and-expressions-00053"),
    ("Muzîk", 3, "Di mirasa bê-maddî de, çima performansa stranekê tenê bi nivîsa wê nayê pîvan?", "Ji ber ku deng, awayê gotinê, hereket, têkiliya hunermend û temaşevanan jî beşên performansê ne.", "Ji ber ku nivîs û deng di hemû çandan de heman tişt in.", "Ji ber ku stran divê bê temaşevan bê pêşkêşkirin.", "Ji ber ku UNESCO hunerên performansê qebûl nake.", "A", "UNESCO balê dikişîne ser pêvajoya performansê û dibêje ku deng, intonasyon, hereket û têkiliya performêr û temaşevanan dikarin beşên mirasê bin.", "Oral Traditions and Expressions – UNESCO", "https://ich.unesco.org/en/oral-traditions-and-expressions-00053"),
    ("Siyaset", 2, "Di rêxistina Neteweyên Yekbûyî de, zimanpirrî çi armancê alîkar dike?", "Beşdarbûna wekhev û têgihiştina zelal di nav dewletên cuda de.", "Kêmkirina hewcedariya wergerê bi rakirina zimanên din.", "Hilbijartina yek ziman wekî zimanê hemû gelan.", "Qedexekirina axaftina zimanên nefermî.", "A", "Neteweyên Yekbûyî dibêje zimanpirrî têgihiştin, tolerans û beşdarbûna dewletên endam di karê rêxistinê de zêde dike.", "Multilingualism – United Nations", "https://www.un.org/sg/en/multilingualism/index.shtml"),
    ("Siyaset", 3, "Di danezanê mafên mirovan a Şoreşa Fransayê de, kîjan têgeh bi taybetî tê pêşxistin?", "Azadî û wekheviya mafan.", "Serweriya kolonyalî û dabeşkirina nijadî.", "Qanûna monopola xwê.", "Rakirina zimanpirrî ji rêxistinên navneteweyî.", "A", "Danezana 1789an maf û azadiyê di nav têgehên bingehîn ên xwe de dixe pêş; ew nivîs di dîroka mafên mirovan de girîng e.", "French Revolution – Encyclopaedia Britannica", "https://www.britannica.com/event/French-Revolution"),
    ("Paradigma", 3, "Çima divê Şoreşa Haîtî tenê wekî şerê serxwebûnê neyê xwendin?", "Ji ber ku ew bi li dijî kolederiyê, serdestîya kolonyalî û mafên mirovan re jî têkildar bû.", "Ji ber ku ew qet bi ser neket.", "Ji ber ku ew tenê guhertina alfabeyê bû.", "Ji ber ku ew tenê tevgera hunerî bû.", "A", "Şoreşa Haîtî hem li dijî serdestîya kolonyalî hem li dijî kolederiyê bû; ji ber vê yekê tenê bi serxwebûnê sînordar kirina wê kêm e.", "Haitian Revolution – Encyclopaedia Britannica", "https://www.britannica.com/event/Haitian-Revolution"),
    ("Paradigma", 3, "Di xwendina tevgerên gelan de, çima divê rêbaz û şertên her tevgerê ji hev bên veqetandin?", "Ji ber ku dîrok, şertên civakî, armanc û rêbazên wan dikarin cuda bin.", "Ji ber ku hemû tevgerên gelan heman encam û heman rêbaz hene.", "Ji ber ku şertên herêmî di dîrokê de qet bandor nakin.", "Ji ber ku tenê navê rêberê tevgerê dikare hemû tişt rave bike.", "A", "Lêkolîna tevgerên gelan divê şertên dîrokî, armanc, rêbaz û dengên komên cuda li ber çavan bigire; yek model ji bo hemû tevgeran kêm e.", "Comparative framing based on UNESCO and UN context", "https://ich.unesco.org/en/what-is-intangible-heritage-00003?lang=en"),
]

FIELDS = ["id", "category_key", "language_code", "prompt", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "difficulty", "source_title", "source_url", "publication_status", "quality_note"]

def q(v): return "'" + v.replace("'", "''") + "'"

def main():
    with CSV_OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS); w.writeheader()
        for i, row in enumerate(ROWS, 1):
            category, difficulty, prompt, a, b, c, d, correct, explanation, title, url = row
            w.writerow({"id": f"general1_{i:04d}", "category_key": category, "language_code": "ku-kmr", "prompt": prompt, "option_a": a, "option_b": b, "option_c": c, "option_d": d, "correct_option": correct, "explanation": explanation, "difficulty": difficulty, "source_title": title, "source_url": url, "publication_status": "PENDING_EDITORIAL_APPROVAL", "quality_note": "Genel kültür ve dünya tarihinden, kapsayıcı ve kaynaklı biçimde elle yazıldı; ikinci editoryal kontrol bekliyor."})
    values=[]
    for category, difficulty, prompt, a, b, c, d, correct, explanation, title, url in ROWS:
        values.append("(" + ", ".join(["(select id from public.categories where name = " + q(category) + ")", q("ku-kmr"), q(prompt), q(a), q(b), q(c), q(d), q(correct), q(explanation), str(difficulty), "false", q("multiple_choice"), "NULL", q("general_culture_question_wave_1")]) + ")")
    SQL_OUT.write_text("-- Genel kültür, dünya hareketleri, halklar ve dillerden üretilen ilk paket.\n-- Canlı yayın için onaylanmadı.\ninsert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values\n" + ",\n".join(values) + ";\n", encoding="utf-8")
    print(f"wrote {len(ROWS)} rows")

if __name__ == "__main__": main()
