import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_2.csv"
SQL_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_2.sql"

ROWS = [
    ("Ziman", 2, "Li gorî UNESCO, Dekada Navneteweyî ya Zimanên Gelên Xwecihî kîjan salan dihewîne?", "2022–2032.", "2003–2013.", "1932–1942.", "2010–2020.", "A", "UNESCO dibêje ku Neteweyên Yekbûyî Dekada Navneteweyî ya Zimanên Gelên Xwecihî ji 2022 heta 2032an ragihandiye.", "Multilingualism and Linguistic Diversity – UNESCO", "https://www.unesco.org/en/multilingualism-linguistic-diversity?hub=67103"),
    ("Ziman", 3, "Li gorî UNESCO, «Universal Acceptance» di cîhê dîjîtal de çi armancê dike?", "Navên domain û navnîşanên e-nameyê bi her ziman, nivîs û karakterî re bixebitin.", "Tenê navnîşanên bi alfabeya latînî qebûl bike.", "Hemû zimanên kêm-bikarhatî ji internetê dûr bixe.", "Tenê yek ziman ji bo hemû platforman hilbijêre.", "A", "UNESCO Universal Acceptance wekî prensîbek ji bo jîngeheke dîjîtal a zimanpirr dide naskirin ku domain û e-name bi her ziman û nivîsê re bixebitin.", "Multilingualism and Linguistic Diversity – UNESCO", "https://www.unesco.org/en/multilingualism-linguistic-diversity?hub=67103"),
    ("Dîrok", 2, "Şoreşa Meksîkayê bi gelemperî di kîjan salê de dest pê kir?", "1910an.", "1789an.", "1804an.", "1947an.", "A", "Şoreşa Meksîkayê di sala 1910an de dest pê kir û ji bo salên dirêj guhertinên siyasî û civakî li pey xwe anîn.", "Mexican Revolution – Encyclopaedia Britannica", "https://www.britannica.com/event/Mexican-Revolution"),
    ("Dîrok", 3, "Di dîroka Afrîkaya Başûr de, hilbijartina 1994an çima girîng bû?", "Ji ber ku hilbijartina neteweyî ya yekem a bi beşdarbûna hemû nijadên sereke re bû û destpêka demokrasiyeke nû bû.", "Ji ber ku wê yekem car apartheid ava kir.", "Ji ber ku wê Rêya Îpekê ji nû ve vekir.", "Ji ber ku wê zimanên fermî ji nav birin.", "A", "Hilbijartina 1994an di Afrîkaya Başûr de di qonaxa derketina ji apartheidê û avakirina rêveberiyeke demokratîk de bû.", "South Africa – Encyclopaedia Britannica", "https://www.britannica.com/place/South-Africa/From-apartheid-to-democracy"),
    ("Dîrok", 2, "Rêya Îpekê çi bû?", "Toreke rê û bazirganiyê ku herêmên Asyayê, Rojhilatê Navîn û Ewropa bi hev ve girê dida.", "Tenê yek rêya asfaltî ya di nav Çînê de.", "Tenê rêya deryayî ya di nav Okyanûsa Atlantîkê de.", "Tenê navê kovareke dîrokî ya li Şamê.", "A", "Rêya Îpekê navê toreke rê û têkiliyên bazirganiyê ye ku di navbera herêmên Asyayê, Rojhilatê Navîn û Ewropayê de danûstandin hêsan dikir.", "Silk Road – Encyclopaedia Britannica", "https://www.britannica.com/topic/Silk-Road-trade-route"),
    ("Dîrok", 3, "Apartheid di dîroka Afrîkaya Başûr de bi kîjan awayî tê pênasekirin?", "Pergaleke cudakirina nijadî û siyasî ya ku mafên piraniya gelê sînordar dikir.", "Rêbazeke parastina mirasa bê-maddî ya UNESCO.", "Cureyekî perwerdehiya zimanpirr.", "Toreke bazirganiyê ya di navbera Asya û Ewropayê de.", "A", "Apartheid pergaleke cudakirina nijadî û siyasî bû ku di Afrîkaya Başûr de maf û beşdarbûna piraniya gelê sînordar dikir.", "South Africa – Encyclopaedia Britannica", "https://www.britannica.com/place/South-Africa/From-apartheid-to-democracy"),
    ("Cografya", 2, "Li gorî UNESCO, peyva «peyzaja çandî» çi têkiliyê di navbera mirovan û xwezayê de nîşan dide?", "Têkiliyeke dîrokî û domdar ku mirov û civak bi hawirdorê re ava kiriye.", "Têkiliyeke ku mirov ji xwezayê bi tevahî cuda dike.", "Tenê nexşeyeke avahiyên bajarî bê hawirdor.", "Tenê qadeke ku qet ji aliyê mirovan ve nehatiye bikaranîn.", "A", "UNESCO peyzajên çandî wekî encama têkiliya dirêj a mirov, civak û hawirdorê dide pênasekirin.", "Cultural Landscapes – UNESCO World Heritage Centre", "https://whc.unesco.org/en/culturallandscape"),
    ("Cografya", 2, "Li gorî UNESCO, cihên Mirasê Cîhanê li ser kîjan bingehê wekî mirasa hemû gelan tên dîtin?", "Li ser bingeha ku nirxa wan ji sînorên welatekî wêdetir e.", "Tenê li ser bingeha ku hemû li paytextan in.", "Tenê li ser bingeha ku tenê yek gel wan ava kiriye.", "Li ser bingeha ku mirov divê ji wan dûr bimînin.", "A", "Navenda Mirasê Cîhanê dibêje cihên lîsteyê, bêyî ku li kîjan welatê bin, ji aliyê hemû gelên cîhanê ve wekî miras tên dîtin.", "World Heritage – UNESCO", "https://whc.unesco.org/en/about/"),
    ("Çand", 2, "Li gorî UNESCO, çandî-diversîte çi dide nîşandan?", "Rêyên cuda yên ku kom û civak çanda xwe nîşan didin, digihînin û pêş dixin.", "Yek rêbazê ku divê hemû civak bişopînin.", "Tenê dabeşkirina mirovan li gorî welatê wan.", "Tenê parastina avahiyên kevn.", "A", "UNESCO çandî-diversîte bi awayên cuda yên derbirîna, hilberîna, belavkirina û parvekirina çandê ve girê dide.", "Diversity of Cultural and Natural Heritage – UNESCO", "https://whc.unesco.org/en/glossary/231"),
    ("Çand", 3, "Li gorî UNESCO, çima civak divê di parastina mirasa xwe de rolekî bingehîn hebe?", "Ji ber ku civakên ku mirasê çêdikin û didomînin divê wê wekî mirasa xwe nas bikin.", "Ji ber ku tenê sazîyên navneteweyî dikarin mirasê nas bikin.", "Ji ber ku miras tenê piştî ku ji jiyanê were rakirin dipareze.", "Ji ber ku miras divê ji komên ku wê diafirînin ve bê veqetandin.", "A", "UNESCO dibêje mirasa bê-maddî tenê dema ku kom, komik an kesên wê çêdikin wê wekî mirasa xwe nas bikin tê parastin.", "What is Intangible Cultural Heritage? – UNESCO", "https://ich.unesco.org/en/what-is-intangible-heritage-00003?lang=en"),
    ("Muzîk", 2, "Di qadên mirasa bê-maddî ya UNESCO de, muzîk û dans di kîjan komê de ne?", "Di hunerên performansê de.", "Di zanînên li ser xwezayê de tenê.", "Di arşîvên dewletê de tenê.", "Di şertên hilbijartina siyasî de.", "A", "UNESCO hunerên performansê wekî qadeke mirasa bê-maddî dide naskirin û muzîk û dans di nav vê qadê de cih digirin.", "Intangible Heritage Domains – UNESCO", "https://ich.unesco.org/en/intangible-heritage-domains-00052"),
    ("Muzîk", 3, "Di peyzajên çandî de, muzîk û huner çawa dikarin bi cografyayê re têkildar bibin?", "Bi vegotineke ku têkiliya civakê bi hawirdor, dîrok û jiyana herêmê nîşan dide.", "Bi rakirina hawirdorê ji hemû çalakiyên çandî.", "Bi şertê ku huner divê tenê li muzeê bê pêşkêşkirin.", "Bi şertê ku muzîk ji civakê bi tevahî cuda be.", "A", "Peyzajê çandî têkiliya mirov û hawirdorê nîşan dide; muzîk û huner dikarin bîranîn, dîrok û jiyana vê têkiliyê vegotin.", "Cultural Landscapes – UNESCO World Heritage Centre", "https://whc.unesco.org/en/culturallandscape"),
    ("Siyaset", 2, "Li gorî UNESCO, zimanpirrî çawa beşdarbûna civakî zêde dike?", "Bi hêsankirina gihiştina agahiyê û bikaranîna zimanên xwecihî di jiyana giştî û dîjîtal de.", "Bi şertê ku tenê yek ziman bê bikaranîn.", "Bi kêmkirina gihiştina komên marjînal bo agahiyê.", "Bi rakirina zimanên xwecihî ji jiyana giştî.", "A", "UNESCO zimanpirrî bi beşdarbûn, gihiştina agahiyê, parastina mirasê û hêzkirina komên marjînal û gelên xwecihî re girê dide.", "Multilingualism and Linguistic Diversity – UNESCO", "https://www.unesco.org/en/multilingualism-linguistic-diversity?hub=67103"),
    ("Siyaset", 3, "Li gorî UNESCO, armanca sereke ya siyaseta çandî-diversîteyê çi ye?", "Parastin û pêşxistina cûrbecûrbûna çandî û avakirina dialoga navçandî.", "Avakirina yek rêbazê çandî ji bo hemû gelan.", "Rakirina çandên herêmî ji jiyana giştî.", "Cudakirina komên çandî ji hev.", "A", "UNESCO parastina cûrbecûrbûna çandî, dialoga navçandî û rêzgirtina ji derbirînên cuda wekî armancên sereke dide naskirin.", "Culture and Cultural Diversity – UNESCO", "https://www.unesco.org/en/culture?language=en"),
    ("Paradigma", 3, "Li gorî rêberiya UNESCO ya perwerdehiya navçandî, çima cudahiya çandî divê bi hêz û şertên civakî re bê xwendin?", "Ji ber ku komên çandî her tim bi awayekî wekhev gihiştina hêz û derbirînê nînin.", "Ji ber ku çand qet bi siyaset û aboriyê re têkildar nîne.", "Ji ber ku hemû komên civakî di hemû şertan de heman imkan hene.", "Ji ber ku cudahiya çandî tenê mijareke muzîkê ye.", "A", "Rêberiya UNESCO balê dikişîne ser vê yekê ku komên çandî ne her tim gihiştina wekhev bi hêz û derbirîna xwe hene; ji ber vê yekê şertên civakî jî girîng in.", "Guidelines on Intercultural Education – UNESCO", "https://unesdoc.unesco.org/in/rest/annotationSVC/DownloadWatermarkedAttachment/attach_import_c86aa337-73af-4adb-bbe3-f7ae0e8126cc?_=147878eng.pdf"),
    ("Paradigma", 3, "Di xwendina cîhanî ya halk hareketan de, çima divê serpêhatiya komên herêmî bê guhdarîkirin?", "Ji ber ku zanîn û bîranîna koman dikare aliyên dîrokê nîşan bide ku ji çavkaniyên navendî re ne xuya ne.", "Ji ber ku çavkaniyên herêmî hemû caran bê xeletî ne.", "Ji ber ku çavkaniyên navendî qet ne girîng in.", "Ji ber ku dîrok tenê bi serpêhatiya yek kesî tê nivîsandin.", "A", "Guhdarîkirina dengên herêmî dibe ku dîrokê berfirehtir bike; ev ne tê wateya ku hemû çavkaniyek bê rexne bê qebûlkirin.", "Comparative cultural-history framing – UNESCO", "https://whc.unesco.org/document/6856"),
]

FIELDS = ["id", "category_key", "language_code", "prompt", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "difficulty", "source_title", "source_url", "publication_status", "quality_note"]

def q(v): return "'" + v.replace("'", "''") + "'"

def main():
    with CSV_OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS); w.writeheader()
        for i, row in enumerate(ROWS, 1):
            category, difficulty, prompt, a, b, c, d, correct, explanation, title, url = row
            w.writerow({"id": f"general2_{i:04d}", "category_key": category, "language_code": "ku-kmr", "prompt": prompt, "option_a": a, "option_b": b, "option_c": c, "option_d": d, "correct_option": correct, "explanation": explanation, "difficulty": difficulty, "source_title": title, "source_url": url, "publication_status": "PENDING_EDITORIAL_APPROVAL", "quality_note": "Genel kültürden, kapsayıcı ve kaynaklı biçimde elle yazıldı; ikinci editoryal kontrol bekliyor."})
    values=[]
    for category, difficulty, prompt, a, b, c, d, correct, explanation, title, url in ROWS:
        values.append("(" + ", ".join(["(select id from public.categories where name = " + q(category) + ")", q("ku-kmr"), q(prompt), q(a), q(b), q(c), q(d), q(correct), q(explanation), str(difficulty), "false", q("multiple_choice"), "NULL", q("general_culture_question_wave_2")]) + ")")
    SQL_OUT.write_text("-- Genel kültür, ülkeler, halklar, diller ve dünya tarihinden ikinci paket.\n-- Canlı yayın için onaylanmadı.\ninsert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values\n" + ",\n".join(values) + ";\n", encoding="utf-8")
    print(f"wrote {len(ROWS)} rows")

if __name__ == "__main__": main()
