import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_6.csv"
SQL_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_6.sql"

ROWS = [
    ("Dîrok", 1, "Rêyên Îpekê di dîroka cîhanê de bi çi awayî tên naskirin?", "Wek torên rêyên ku civakên Asya, Asyaya Navîn, Rojhilat û Rojava bi hev ve girê didan.", "Wek rêyekê ku tenê ji bo veguhastina îpekê hatiye çêkirin.", "Wek sînorê yek dewletê ku qet neguhere.", "Wek rêyên ku tenê di navbera du bajarên Ewropayê de hebûn.", "A", "UNESCO Rêyên Îpekê wek torên rêyên têkildar dide naskirin ku civakên Asya, Asyaya Navîn, Rojhilata Nêzîk û herêmên din bi hev ve girê didan.", "Silk Roads: Chang'an–Tianshan Corridor – UNESCO", "https://whc.unesco.org/en/list/1442/"),
    ("Dîrok", 2, "Di Rêyên Îpekê de, ji bilî malan, çi tiştên din di navbera civakan de diguhestin?", "Fikir, zanîn, bawerî, huner û şêwazên jiyanê jî dikaribûn bi rêya têkiliyên dirêj dûr bigihîjin herêmên din.", "Tenê pere û amûrên şer.", "Tenê zimanekî yekane.", "Tenê avahiyên ku ji cihê xwe nayên guhestin.", "A", "UNESCO bandorên Rêyên Îpekê bi danûstandina aborî, civakî û çandî re girêdide; rêwîtiya malan bi guherîna fikir û zanînê re jî têkildar bû.", "Silk Roads Programme – UNESCO", "https://www.unesco.org/en/silkroads?itok=djK9Uqx7"),
    ("Dîrok", 2, "Çima dîroka Rêyên Îpekê nikare tenê wek dîroka bazirganiyê bê xwendin?", "Ji ber ku tevgera mirovan li ser wan rêyan bandorên siyasî, civakî û çandî jî çêkir.", "Ji ber ku bazirganî di wan rêyan de qet nehat kirin.", "Ji ber ku hemû civakên li ser rêyan yek çand bûn.", "Ji ber ku rêyên îpekê tenê di sedsala nûjen de hatin çêkirin.", "A", "UNESCO diyar dike ku tevgera dirêj-dûr li ser Rêyên Îpekê bandorên fireh li ser civakên ku hev re rû bi rû dibûn çêkir.", "Silk Roads: Chang'an–Tianshan Corridor – UNESCO", "https://whc.unesco.org/en/list/1442/"),
    ("Dîrok", 3, "Di parastina malperên dîrokî yên Rêyên Îpekê de, çima hevkariya çend welatan girîng e?", "Ji ber ku rê û dîroka wan ji sînorên yek welatê derbas dibe û bi hev re têgihiştina mîrasê baştir dike.", "Ji ber ku yek welat dikare hemû dîroka herêmê bê nîqaş nûsîne.", "Ji ber ku malperên dîrokî ji civakên herêmî veqetandî ne.", "Ji ber ku hevkarî tenê ji bo sazkirina rêyên nû ye.", "A", "Proje û malperên Rêyên Îpekê gelek herêm û dewlet digirin; parastina wan bi hevkariya navneteweyî û bi rêzgirtina civakên herêmî re pêwendîdar e.", "Silk Roads Programme – UNESCO", "https://www.unesco.org/en/silkroads?itok=djK9Uqx7"),
    ("Siyaset", 1, "Li gorî Danezana Gerdûnî ya Mafên Mirovan, ew danezan çi armanc dide pêş?", "Wek standardeke hevpar ji bo rêzgirtin û parastina maf û azadiyên bingehîn ên hemû mirovan.", "Wek qanûnek ku tenê ji bo yek bajarê taybet e.", "Wek peymaneke bazirganiyê di navbera dewletan de.", "Wek belgeyek ku mafên mirovan ji perwerdehiyê dûr dixe.", "A", "Neteweyên Yekbûyî Danezanê wek standardeke hevpar ji bo hemû gel û neteweyan dide pêşkêşkirin.", "Universal Declaration of Human Rights – United Nations", "https://www.un.org/en/about-us/universal-declaration-of-human-rights/"),
    ("Siyaset", 2, "Di Danezana Mafên Mirovan de, çima perwerde wekî amûreke girîng tê dîtin?", "Ji bo ku rêzgirtina maf û azadiyan bi hînkirin û fêrbûnê ve were pêşxistin.", "Ji ber ku perwerde divê tenê ji bo kesên dewlemend be.", "Ji ber ku perwerde mafên mirovan kêm dike.", "Ji ber ku hînkirin bi jiyana civakî re têkildar nîne.", "A", "Danezanê daxwaz dike ku rêzgirtina maf û azadiyan bi rêya hînkirin û perwerdehiyê bê pêşxistin.", "Universal Declaration of Human Rights – United Nations", "https://www.un.org/en/about-us/universal-declaration-of-human-rights/"),
    ("Siyaset", 2, "Kîjan nêrîn bi awayekî rast mafên mirovan wekî mafên gerdûnî dide naskirin?", "Maf dikarin ji bo hemû mirovan bêyî cudahî li ser bingeha nasname, ol, ziman an cihê jiyanê bên parastin.", "Maf tenê ji bo kesên ku wekhev fikirîn derbasdar in.", "Maf bi xwezayê ve tenê ji bo yek komê hatine veqetandin.", "Maf divê li gorî hêza aborî ya kesan bên dayîn.", "A", "Danezana Gerdûnî ya Mafên Mirovan li ser rêzgirtina maf û azadiyên bingehîn ên hemû mirovan disekine.", "Universal Declaration of Human Rights – United Nations", "https://www.un.org/en/about-us/universal-declaration-of-human-rights/"),
    ("Siyaset", 3, "Çima parastina mafên mirovan bi zanîna civakê û beşdarbûna wê re têkildar e?", "Ji ber ku kesên agahdar dikarin mafên xwe nas bikin, binpêkirinê bibînin û di çareseriya civakî de beşdar bibin.", "Ji ber ku beşdarbûn divê ji pêvajoya mafan bê veqetandin.", "Ji ber ku mafên mirovan tenê ji bo dadgehê ne.", "Ji ber ku zanîn dikare rêzgirtina mafan kêm bike.", "A", "Danezanê perwerde û agahiyê wek rêyek ji bo pêşxistina rêzgirtina maf û azadiyan dide naskirin.", "Universal Declaration of Human Rights – United Nations", "https://www.un.org/en/about-us/universal-declaration-of-human-rights/"),
    ("Edebiyat", 1, "Di navbera çandên cuda de, çima wergerandin ji bo edebiyatê girîng e?", "Ji ber ku dikare çîrok, helbest û fikirên zimanekî bigihîne xwînerên zimanên din.", "Ji ber ku wergerandin divê nivîsê ji çanda wî veqetîne.", "Ji ber ku wergerandin tenê ji bo belgeyên teknîkî ye.", "Ji ber ku pirtûk divê tenê bi yek ziman bêne xwendin.", "A", "Wergerandin deriyekî di navbera ziman û çandan de vedike; ew dikare gihiştina çîrok û fikirên cuda berfireh bike.", "UNESCO Digital Library", "https://unesdoc.unesco.org/en/bibliotheque"),
    ("Edebiyat", 2, "Çima pirtûkxaneyek navneteweyî dikare ji bo lêkolîna çandî çavkaniyeke hêja be?", "Ji ber ku berhem û belgeyên ji qad û zimanên cuda berhev dike û gihiştina zanînê hêsan dike.", "Ji ber ku pirtûkxane tenê pirtûkên yek welatê diparêze.", "Ji ber ku lêkolîner nikarin çavkaniyên pirtûkxaneyê berawird bikin.", "Ji ber ku pirtûkxane naveroka xwe ji civakê veşêre.", "A", "UNESCO Library berhemên li ser perwerde, çand, zanistên civakî û qadên din ji çavkaniyên navneteweyî berhev dike.", "UNESCO Library", "https://www.uil.unesco.org/en/library"),
    ("Edebiyat", 3, "Di xwendina pirtûkekê ya ji çandeke din de, kîjan rêbaz herî baş e?", "Hem naveroka nivîsê hem şertên dîrokî û çandî yên ku nivîs tê de hatiye afirandin binirxîne.", "Tenê navê nivîskarê binêre û naverokê derbas bike.", "Çanda nivîsê bi çand û jiyana xwe re wekhev bihesibîne.", "Hemû wateyên çandî ji nivîsê derxe.", "A", "Xwendina berawirdkar şertê dîrokî, zimanî û civakî jî li gel naveroka nivîsê dihesibîne.", "UNESCO Digital Library", "https://unesdoc.unesco.org/library/about"),
    ("Ziman", 1, "Li gorî UNESCO, perwerdeya pirzimanî dikare çi encamê bide?", "Dikare fêrbûn û beşdarbûna xwendekarên ku zimanên cuda diaxivin zêde bike.", "Dikare hemû zimanên malbatê ji dibistanê derxîne.", "Dikare gihiştina zanînê tenê ji bo zimanekî sînorkirî bike.", "Dikare zimanê dayikê ji jiyana xwendekarê veqetîne.", "A", "UNESCO perwerdeya pirzimanî bi fêrbûna berfireh, gihiştina wekhev û beşdarbûna xwendekarên zimanên cuda re girêdide.", "Languages Matter – UNESCO", "https://www.unesco.org/en/articles/languages-matter-global-guidance-multilingual-education?hub=370"),
    ("Ziman", 2, "Çima zimanê ku zarok di malê de hîn dibe dikare di destpêka perwerdehiyê de hêja be?", "Ji ber ku ew dikare bibe bingeha têgihiştinê, derbirînê û fêrbûna zimanên din.", "Ji ber ku zarok divê tenê bi zimanê malê re bimîne.", "Ji ber ku zimanê malê her tim ji zimanên din hêsantir e.", "Ji ber ku zimanê malê bi hînkirinê re têkildar nîne.", "A", "Rêbernameya UNESCO zimanê malê û zimanên din wekî beşên ku dikarin fêrbûn û beşdarbûna zarokan piştgirî bikin dinirxîne.", "Languages Matter – UNESCO", "https://www.unesco.org/en/articles/languages-matter-global-guidance-multilingual-education?hub=370"),
    ("Ziman", 3, "Di polên pirzimanî de, çima materyalên fêrbûnê divê bi şertên herêmî re bên guncandin?", "Ji ber ku ziman, çand û şertên fêrbûnê di nav civak û herêmên cuda de yek nînin.", "Ji ber ku materyalên hemû welatan her tim wekhev in.", "Ji ber ku şertên herêmî di fêrbûnê de bandor nakin.", "Ji ber ku guncandin tenê ji bo wêneyan pêwîst e.", "A", "UNESCO diyar dike ku siyaseta pirzimanî divê bi konteksta civakî û zimanî ya xwendekaran re were guncandin.", "Languages Matter – UNESCO", "https://www.unesco.org/en/articles/languages-matter-global-guidance-multilingual-education?hub=370"),
    ("Cografya", 1, "Li gorî UNESCO, peyzaja çandî çi têkiliyekê di navbera mirovan û hawirdorê de nîşan dide?", "Têkiliya dîrokî û zindî ya mirov bi xwezayê û bi awayên bikaranîna erdê.", "Tenê dîmenê xwezayî yê bê mirov.", "Tenê avahiyên ku li bajaran hatine çêkirin.", "Tenê cihên ku qet nehatine bikaranîn.", "A", "UNESCO peyzajên çandî wekî cihên ku têkiliya mirovan û hawirdorê, karên erdê û şopên dîrokî nîşan didin dide pênasekirin.", "Cultural Landscapes – UNESCO World Heritage Centre", "https://whc.unesco.org/en/culturallandscape"),
    ("Cografya", 2, "Çima parastina peyzajên çandî dikare bi bikaranîna domdar a erdê re têkildar be?", "Ji ber ku parastina wan dikare hem nirxên xwezayî biparêze hem jî rêbazên kevneşopî yên bikaranîna erdê bidomîne.", "Ji ber ku parastin divê her bikaranîna erdê rawestîne.", "Ji ber ku peyzajên çandî ji xwezayê bê girêdan in.", "Ji ber ku rêbazên kevneşopî li ser hawirdorê bandor nakin.", "A", "UNESCO diyar dike ku parastina peyzajên çandî dikare rêbazên domdar ên bikaranîna erdê û nirxên xwezayî biparêze an bihêz bike.", "Cultural Landscapes – UNESCO World Heritage Centre", "https://whc.unesco.org/en/culturallandscape"),
]

FIELDS = ["id", "category_key", "language_code", "prompt", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "difficulty", "source_title", "source_url", "publication_status", "quality_note"]

def q(v):
    return "'" + v.replace("'", "''") + "'"

def main():
    with CSV_OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        for i, row in enumerate(ROWS, 1):
            category, difficulty, prompt, a, b, c, d, correct, explanation, title, url = row
            w.writerow({"id": f"general6_{i:04d}", "category_key": category, "language_code": "ku-kmr", "prompt": prompt, "option_a": a, "option_b": b, "option_c": c, "option_d": d, "correct_option": correct, "explanation": explanation, "difficulty": difficulty, "source_title": title, "source_url": url, "publication_status": "PENDING_EDITORIAL_APPROVAL", "quality_note": "Kategori bazlı, kaynaklı ve özgün olarak hazırlandı; ikinci editoryal kontrol bekliyor."})
    values = []
    for category, difficulty, prompt, a, b, c, d, correct, explanation, title, url in ROWS:
        values.append("(" + ", ".join(["(select id from public.categories where name = " + q(category) + ")", q("ku-kmr"), q(prompt), q(a), q(b), q(c), q(d), q(correct), q(explanation), str(difficulty), "false", q("multiple_choice"), "NULL", q(url)]) + ")")
    SQL_OUT.write_text("-- Dîrok, mafên mirovan, edebiyat, pirzimanî û peyzajên çandî.\n-- Canli yayin icin onaylanmadi.\ninsert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values\n" + ",\n".join(values) + ";\n", encoding="utf-8")
    print(f"wrote {len(ROWS)} rows")

if __name__ == "__main__":
    main()
