import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_8.csv"
SQL_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_8.sql"

ROWS = [
    ("Çand", 1, "Li gorî UNESCO, çima hunera destkarî di nav mîrasa bê-maddî de taybet e?", "Ji ber ku zanîn, teknîk û jêhatîbûn di berhemekî maddî de xuya dibin.", "Ji ber ku hunera destkarî tenê berhemên pîşesazî çêdike.", "Ji ber ku hûnermend divê qet rêbazê xwe neguhere.", "Ji ber ku destkarî bi civak û veguhastina zanînê re têkildar nîne.", "A", "UNESCO hunera destkarî wekî yek ji wateyên herî berbiçav ên mîrasa bê-maddî dide naskirin, ji ber ku jêhatîbûna bê-maddî di berhemekî dîtbar de tê nîşandan.", "Traditional Craftsmanship – UNESCO", "https://ich.unesco.org/en/traditional-craftsmanship-00057"),
    ("Çand", 2, "Di parastina destkariyekî kevneşopî de, çima tenê parastina berhemê bes nake?", "Ji ber ku divê zanîn, teknîk û rêbaza hînkirina wê jî bê parastin.", "Ji ber ku berhem divê ji hildêrên wê bê veqetandin.", "Ji ber ku tenê rengê berhemê wateya mîrasê dide.", "Ji ber ku hînkirin nikare di destkariyê de rolek bilîze.", "A", "Mîrasa destkarî bi zanîn û jêhatîbûna hildêrên wê ve zindî ye; parastina berhemê bê parastina pêvajoyê têr nake.", "Traditional Craftsmanship – UNESCO", "https://ich.unesco.org/en/traditional-craftsmanship-00057"),
    ("Çand", 2, "Çima globalîzasyon dikare ji bo hin formên destkariyê zehmetî çêbike?", "Ji ber ku berhemên standard û hilberîna girseyî dikarin daxwaz û şertên veguhastina destkariyê kêm bikin.", "Ji ber ku globalîzasyon her tim destkariyê zêde dike.", "Ji ber ku destkarî tenê di civakên bê têkiliyê de heye.", "Ji ber ku berhemên girseyî her tim zanîna destkaran diparêzin.", "A", "UNESCO balê dikişîne ku globalîzasyon dikare domandina formên kevneşopî yên destkariyê bixe xeterê.", "Traditional Craftsmanship – UNESCO", "https://ich.unesco.org/en/traditional-craftsmanship-00057"),
    ("Çand", 3, "Kîjan plan ji bo domandina destkariyê bi rêzgirtina civakê re herî guncaw e?", "Hînkirina ciwanan ji aliyê hildêrên civakê ve, bi şertê ku teknîk dikarin bi şertên nû re biguhezin.", "Rakirina hildêrên kevneşopî ji pêvajoya hînkirinê.", "Guhertina hemû berhemên destkarî bi berhemên pîşesazî.", "Parastina teknîkê bi qedexekirina hemû afirandinên nû.", "A", "Parastina mîrasa zindî hînkirina zanînê ji nifşekê re û mafê civakê di afirandin û guhertinê de bi hev re hesib dike.", "Traditional Craftsmanship – UNESCO", "https://ich.unesco.org/en/traditional-craftsmanship-00057"),
    ("Muzîk", 1, "Di muzîkê de, 'zanîn û jêhatîbûn' çi dikare dihewîne?", "Çêkirina amûrê, lêdana wê, şêwaza stranê û rêbaza hînkirina wê.", "Tenê navê hunermendê.", "Tenê cihê ku konser lê tê kirin.", "Tenê jimara temaşevanan.", "A", "Muzîk wek mîrasa zindî ne tenê deng e; ew dikare zanîn, teknîk, repertuwar û rêbaza veguhastina wan dihewîne.", "Performing Arts – UNESCO", "https://ich.unesco.org/en/performing-arts-00054"),
    ("Muzîk", 2, "Çima amûrên muzîkê dikarin bi hawirdor û jiyana civakê re têkildar bibin?", "Ji ber ku materyal, şêwaza çêkirinê û bikaranîna wan dikare zanîna herêmî û şertên jiyanê nîşan bide.", "Ji ber ku amûrên muzîkê ji hawirdorê qet materyal nagirin.", "Ji ber ku amûr tenê ji bo nîşandana dewlemendiyê ye.", "Ji ber ku muzîk ji jiyana rojane bê girêdan e.", "A", "UNESCO hunerên performansê bi zanîna civakan, hawirdor û pratîkên din ên mîrasa bê-maddî re têkildar dibîne.", "Performing Arts – UNESCO", "https://ich.unesco.org/en/performing-arts-00054"),
    ("Muzîk", 3, "Di parastina muzîkekî kevneşopî de, çima tomarkirin û performansa zindî divê bi hev re bên bikaranîn?", "Tomarkirin dîlê dide, performansa zindî jî têkiliya civakî û şertên vegotinê diparêze.", "Ji ber ku yek ji wan divê hemû pratîkê bi temamî li cihê ya din bigire.", "Ji ber ku performansa zindî nikare zanînê bigihîne.", "Ji ber ku tomarkirin her guhertinê ji holê radike.", "A", "Mîrasa muzîkî hem bi belgekirina dengê hem jî bi jiyana civakî ya performansê tê parastin; yek rêbaz tenê hemû aliyên wê nagire.", "Performing Arts – UNESCO", "https://ich.unesco.org/en/performing-arts-00054"),
    ("Edebiyat", 1, "Li gorî UNESCO, ziman di kevneşopiyên devkî de çi rolê dileyze?", "Wek serişteya veguhastina çîrok, gotin, zanîn û bîra civakî.", "Wek astengiyek ku divê ji vegotinê bê rakirin.", "Wek amûrek ku tenê ji bo belgeyên fermî ye.", "Wek tiştekî ku bi çandê re têkildar nîne.", "A", "UNESCO kevneşopiyên devkî û zimanê ku wan digihîne nifşên din wek beşên girîng ên mîrasa bê-maddî dide naskirin.", "Intangible Cultural Heritage – UNESCO", "https://ich.unesco.org/en/what-is-intangible-heritage-00003?lang=en"),
    ("Edebiyat", 2, "Çima çîrokek devkî dikare di performansên cuda de hinekî biguheze û dîsa mîras bimîne?", "Ji ber ku veguhastina devkî dubarekirin, afirandin û adaptasyona li gorî temaşevan dihewîne.", "Ji ber ku mîras divê her tim bê deng bê vegotin.", "Ji ber ku guherîn her tim nîşana wendabûna çandê ye.", "Ji ber ku performans ji çîrokê bi temamî cuda ye.", "A", "UNESCO mîrasa devkî wek pratîkeke zindî dide dîtin ku di veguhastinê de dikare bi şert û temaşevan re biguheze.", "Oral Traditions and Expressions – UNESCO", "https://ich.unesco.org/en/oral-traditions-and-expressions-00053"),
    ("Edebiyat", 3, "Di xwendina gotinekê ya devkî de, çima deng û şertê performansê jî girîng in?", "Ji ber ku ritm, rawestan, deng û têkiliya bi temaşevanan re dikarin wateya gotinê biguherînin.", "Ji ber ku naveroka gotinê qet bi performansê re têkildar nîne.", "Ji ber ku gotinên devkî divê bê deng bên nivîsandin.", "Ji ber ku deng tenê ji bo muzîkê wate heye.", "A", "Kevneşopiya devkî ne tenê nivîsa peyvan e; awayê vegotinê û şertê civakî jî beşek ji wateya wê ne.", "Oral Traditions and Expressions – UNESCO", "https://ich.unesco.org/en/oral-traditions-and-expressions-00053"),
    ("Dîrok", 1, "Li gorî UNESCO, mîrasa bê-maddî çawa bi dîroka civakekê re têkildar e?", "Pratîk û zanînên ku ji nifşên berê tên û di jiyana îroyîn de tên nûkirin, bîra dîrokî digihînin nifşên din.", "Ji ber ku dîrok tenê di avahiyên kevn de tê dîtin.", "Ji ber ku pratîkên îro nikarin tiştekî li ser dîrokê bibêjin.", "Ji ber ku mîras divê ji jiyana rojane bê veqetandin.", "A", "UNESCO mîrasa bê-maddî wekî kevneşopiyên ji bav û kalan hatine mîrasgirtin û di heman demê de zindî û nûkirî dide pênasekirin.", "What is Intangible Cultural Heritage? – UNESCO", "https://ich.unesco.org/en/what-is-intangible-heritage-00003?lang=en"),
    ("Dîrok", 2, "Çima dîroka destkariyekê divê tenê bi dîroka berhemên wê neyê sînorkirin?", "Ji ber ku dîrokê zanîn, malbat, şertên aborî û rêbaza veguhastina teknîkê jî dihewîne.", "Ji ber ku berhem qet bi jiyana mirovan re têkildar nîne.", "Ji ber ku destkarî tenê berhemên bêwate çêdike.", "Ji ber ku teknîkên kevn nikarin di civakê de bên hînkirin.", "A", "Lêkolîna destkariyê dema ku jêhatîbûn, hildêr, şertên jiyanê û veguhastina zanînê jî dihese, dîroka wê berfirehtir dike.", "Traditional Craftsmanship – UNESCO", "https://ich.unesco.org/en/traditional-craftsmanship-00057"),
    ("Dîrok", 3, "Di belgekirina mîrasa zindî de, çima dîroka nivîskî û bîra civakî divê bi hev re bên xwendin?", "Ji ber ku belgeyên nivîskî û bîra jiyînê aliyên cuda yên heman pêvajoyê nîşan didin.", "Ji ber ku yek ji wan her tim şaş e.", "Ji ber ku bîra civakî nikare agahî bide.", "Ji ber ku nivîs her tim hemû dengên civakê dihewîne.", "A", "Mîrasa zindî bi tecrûbeya hildêrên wê re tê jiyîn; berawirdkirina belge û bîrê dibe sedem ku hem delîl hem jî sînor bêne dîtin.", "What is Intangible Cultural Heritage? – UNESCO", "https://ich.unesco.org/en/what-is-intangible-heritage-00003?lang=en"),
    ("Paradigma", 1, "Li gorî UNESCO, di çarçoveya AI ya xwendekaran de 'mirov-navend' çi dide pêş?", "Kapasîte, maf, nirx û berpirsiyariya mirovan di sêwirandin û bikaranîna AI de.", "Rakirina mirovan ji hemû pêvajoyên biryardan.", "Bikaranîna AI bêyî ku bandora wê li civakê bê pirsîn.", "Pîvandina AI tenê bi lez û çiqas erzan bûna wê.", "A", "UNESCO xwendekarên AI wek afirîner û hemwelatiyên berpirsiyar dibîne û aliyê mirov-navend bi maf û berpirsiyariyê ve girêdide.", "AI Competency Framework for Students – UNESCO", "https://www.unesco.org/en/articles/ai-competency-framework-students?hub=66973"),
    ("Paradigma", 2, "Kîjan gav di bikaranîna naveroka ku AI afirandiye de bi nêrîna zanistî re guncaw e?", "Naverokê bi çavkaniyên serbixwe, delîl û sînorên amûrê re kontrol bike.", "Ji ber ku naverok ji makîneyê hatiye, rast qebûl bike.", "Tenê rêzimanê naverokê kontrol bike.", "Naverokê bê nîqaş wek delîla dawî parve bike.", "A", "Nêrîna rexneyî pêdivî dike ku encamên AI bên pirsîn û bi delîl û çavkaniyên serbixwe re bên berawirdkirin.", "AI Competency Framework for Students – UNESCO", "https://www.unesco.org/en/articles/ai-competency-framework-students?hub=66973"),
    ("Paradigma", 3, "Çima AI ya berdewam û tevgerbar divê bi şertên herêmî re bê sêwirandin?", "Ji ber ku gihiştin, bingeha teknîkî, ziman, çand û hewcedariyên civakan li herêmên cuda wekhev nînin.", "Ji ber ku teknolojî her tim li hemû cihan bi heman awayî tê bikaranîn.", "Ji ber ku şertên herêmî li ser AI bandor nakin.", "Ji ber ku sêwirana AI divê ji bikarhêneran bê veqetandin.", "A", "Çarçoveya UNESCO li ser sêwirana inclusive û berdewam raweste; şertên herêmî di gihiştin û bikaranîna berpirsiyar de girîng in.", "AI Competency Framework for Students – UNESCO", "https://www.unesco.org/en/articles/ai-competency-framework-students?hub=66973"),
]

FIELDS = ["id", "category_key", "language_code", "prompt", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "difficulty", "source_title", "source_url", "publication_status", "quality_note"]

def q(v):
    return "'" + v.replace("'", "''") + "'"

def main():
    with CSV_OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        for i, row in enumerate(ROWS, 1):
            category, difficulty, prompt, a, b, c, d, correct, explanation, title, url = row
            w.writerow({"id": f"general8_{i:04d}", "category_key": category, "language_code": "ku-kmr", "prompt": prompt, "option_a": a, "option_b": b, "option_c": c, "option_d": d, "correct_option": correct, "explanation": explanation, "difficulty": difficulty, "source_title": title, "source_url": url, "publication_status": "PENDING_EDITORIAL_APPROVAL", "quality_note": "Kategori bazlı, kaynaklı ve özgün olarak hazırlandı; ikinci editoryal kontrol bekliyor."})
    values = []
    for category, difficulty, prompt, a, b, c, d, correct, explanation, title, url in ROWS:
        values.append("(" + ", ".join(["(select id from public.categories where name = " + q(category) + ")", q("ku-kmr"), q(prompt), q(a), q(b), q(c), q(d), q(correct), q(explanation), str(difficulty), "false", q("multiple_choice"), "NULL", q(url)]) + ")")
    SQL_OUT.write_text("-- Çand, muzîk, edebiyat, dîrok û AI okuryazarligi.\n-- Canli yayin icin onaylanmadi.\ninsert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values\n" + ",\n".join(values) + ";\n", encoding="utf-8")
    print(f"wrote {len(ROWS)} rows")

if __name__ == "__main__":
    main()
