import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_OUT = ROOT / "supabase" / "2026-07-14_movement_sources_question_wave_2.csv"
SQL_OUT = ROOT / "supabase" / "2026-07-14_movement_sources_question_wave_2.sql"

ROWS = [
    ("Ziman", 2, "Di armancên destpêkê yên Hawarê de, kîjan kom ji mijaran bi hev re hatibû dîtin?", "Belavkirina alfabeyê, lêkolîna ziman û wêje, û parastina dîrok û çandê", "Tenê bazirganiya pirtûkan û rêxistina bazaran", "Tenê perwerdehiya leşkerî û amadekirina nexşeyên şer", "Tenê nivîsandina helbestên olî bê mijarên civakî", "A", "Di destpêka Hawarê de belavkirina alfabeya nû bi lêkolîna ziman, wêje, stran, adet, dîrok û erdnîgariyê re hatibû girêdan.", "Hawar Archive – NYKCC", "https://nykcc.org/langauge/hawar-archive/", "Hawar’ın yayın hedeflerini tek bir alfabe bilgisine indirgemiyor; basın ile kültür arasındaki bağı ölçüyor."),
    ("Ziman", 2, "Li gorî belgeya Kongra Star, peyva «jineolojî» ji aliyê avakirina peyvê ve bi çi re tê girêdan?", "Bi «jin» (jin) û hêmanekî ku bi zanîn û lêkolînê re têkildar e", "Bi navê yek ji çiyayên Rojava û navê kovareke dîrokî", "Bi navê cureyekî stranê ku tenê bê amûr tê gotin", "Bi peyva ku tenê wateya rêxistin û komîteyê dide", "A", "Belgeya Kongra Star «jin» bi jinê re û «-olojî» bi zanîn û lêkolîna zanistî re girêdide; belge her wiha wateya tevgerê ya têgehê jî rave dike.", "Kongra Star – Jineology booklet", "https://internationalistcommune.com/wp-content/uploads/2023/12/k-star_compressed.pdf", "Terim bilgisi, hareketin kendi kitapçık metninden alındı; genel akademik tanım gibi sunulmadı."),
    ("Edebiyat", 3, "Kîjan rêza beşan bi pirtûka The Political Thought of Abdullah Öcalan re li gorî pêşkêşkirina weşangerê hevaheng e?", "Şer û aştiyê li Kurdistanê, Konfederalîzma Demokratîk, Şoreşa Jinê û Neteweya Demokratîk", "Rêziman, astronomî, botanîk û hesabên bazirganiyê", "Mem û Zîn, Nûbihara Biçûkan, Dîwana Cizîrî û Şêx Sen'an", "Dengbêjî, govend, tembûr û stranên Newrozê", "A", "Pluto Press di naveroka pirtûkê de perspektîfên li ser şer û aştiyê, konfederalîzma demokratîk, şoreşa jinê û neteweya demokratîk dide nîşandan.", "The Political Thought of Abdullah Öcalan – Pluto Press", "https://www.plutobooks.com/product/the-political-thought-of-abdullah-ocalan/", "Kitabın bölüm başlıklarını doğrudan yayınevi kaynağından ölçüyor; ideolojik değerlendirme eklemiyor."),
    ("Edebiyat", 3, "Di belgeya Jineolojî ya Kongra Star de, rexneyek bingehîn li ser hilberîna zanînê çi ye?", "Ku gotina bêalî û objektîf dikare dengên jinan û komên marjînal ji nav bibe.", "Ku hemû zanîn tenê bi helbestê tê hilberandin.", "Ku lêkolîn divê ji jiyana civakê bi tevahî dûr bimîne.", "Ku dîrok û ezmûna kesane di zanînê de qîmeta wan tune ye.", "A", "Belge rexne dike ku pergala zanînê ya serdest bi navê bêalîbûnê dikare ezmûn û dengên ne-serdest ji objeyên lêkolînê re bikemilîne.", "Kongra Star – Jineology booklet", "https://internationalistcommune.com/wp-content/uploads/2023/12/k-star_compressed.pdf", "Kuramsal bir pasajı, yazarın iddiası ile genel bilimsel uzlaşıyı karıştırmadan soruyor."),
    ("Dîrok", 2, "Kongra Star di destpêkê de bi kîjan navî di sala 2005an de hat damezrandin?", "Yêkitiya Star", "Hawar", "Jinên Kurdistanê", "Komîteya Arşîvê", "A", "Li gorî belgeya Kongra Star, rêxistin di sala 2005an de bi navê Yêkitiya Star hat damezrandin û paşê navê Kongra Star bi kar anî.", "Kongra Star – About Us", "https://kongra-star.org/eng/about-us/", "Kuruluş adı ve tarihini doğrudan kurumun öz tanımından alıyor."),
    ("Dîrok", 2, "Li gorî belgeya Kongra Star, di 19ê Tîrmeha 2012an de çi bû?", "Di destpêka şoreşa jinan li Rojava de, tevgera jinan roleke pêşeng lîst.", "Weşandina hejmara yekem a Hawarê li Şamê dest pê kir.", "Rojnameya Kurdistanê li Qahîreyê hat damezrandin.", "Komîteya Arşîvê ya Kongra Star hate damezrandin.", "A", "Belgeya Kongra Star 19ê Tîrmeha 2012an wekî destpêka şoreşa jinan li Rojava dide nîşandan û rola pêşeng a tevgera jinan vedibêje.", "Kongra Star – About Us", "https://kongra-star.org/eng/about-us/", "Tarihsel olay ile kurumun kendi anlatısı açıkça ayrıştırıldı."),
    ("Cografya", 2, "Kongra Star xebata xwe li kîjan qadê û bi kîjan torê herêmî pêşkêş dike?", "Li Rojava û bakur û rojhilatê Sûriyê; her wiha nivîsgehên wê li Başûrê Kurdistanê, Lubnanê û Ewropayê hene.", "Tenê li Şamê û bejahiyên Misrê.", "Tenê li herêmên ku Hawar di wan de hat çapkirin.", "Tenê li bajarên ku li ser çiyayên Zagrosê ne.", "A", "Di pênaseya xwe de Kongra Star xebata li Rojava, bakur û rojhilatê Sûriyê û nivîsgehên li Başûrê Kurdistanê, Lubnanê û Ewropayê dide nîşandan.", "Kongra Star – About Us", "https://kongra-star.org/eng/about-us/", "Kuruluşun coğrafi kapsamını tek bir bölgeye indirgeyen çeldiriciler kullanıldı."),
    ("Cografya", 3, "Di bultena salane ya Kongra Star de, civîna salane ya asta Rojava bi çi pêvajoyê re hatiye pêwendîkirin?", "Bi nirxandina rewşa siyasî, rewşa jinan û xebata sala borî; paşê bernameya sala bê bi hev re hatiye amadekirin.", "Bi tenê hilbijartina nûnerên komîteya arşîvê.", "Bi berhevkirina nexşeyên rêwîtiyê ji bo herêmên çiyayî.", "Bi guherandina alfabeya kovarên dîrokî.", "A", "Bultenê dibêje ku civîn rewşa siyasî, rewşa jinan û xebata sala borî nirxand û li ser bingeha van nirxandinan bernameya sala bê bi hev re pêk anî.", "Kongra Star – Women’s Revolution Newsletter", "https://kongra-star.org/eng/wp-content/uploads/2025/01/Annual-Newsletter-of-the-Womens-Revolution.pdf", "Güncel bir bülten maddesi, kurum içi değerlendirme süreci olarak soruldu."),
    ("Çand", 2, "Komîteya çapemeniyê ya Kongra Star li gorî pênaseya wê kîjan karî dike?", "Platformên çapemeniya jinan yên serbixwe pêş dixe û li dijî nîşandanên seksîst dixebite.", "Tenê amûrên muzîkê yên kevn kom dike.", "Tenê li ser dîroka çiyayên Zagrosê lêkolîn dike.", "Tenê pirtûkên edebiyata klasîk çap dike.", "A", "Komîteya çapemeniyê xwe ji bo pêşxistina çapemeniya alternatîf a jinan û rexnekirina nîşandanên seksîst di medyayê de berpirsiyar dide naskirin.", "Kongra Star – About", "https://kongra-star.org/eng/about/", "Basın komitesinin görevini kurumun medya metni üzerinden ölçüyor; slogan tekrarı yapmıyor."),
    ("Çand", 2, "Komîteya arşîvê ya Kongra Star çima belge, wêne û materyalên medyayê diparêze?", "Ji bo parastina bîranîna rêxistinê û ji bo ku ji bo lêkolîna paşerojê şahidî bimînin.", "Ji bo ku hemû materyal bêyî şert li ser medyaya civakî bên belavkirin.", "Ji bo ku cihê komîteyên nû bigirin.", "Ji bo ku nivîsên Hawarê ji nû ve bi alfabeya latînî wergerînin.", "A", "Li gorî pênaseya komîteyê, arşîv belge û wêneyên orîjînal diparêze da ku bîranîna rêxistinê bimîne û materyal ji bo analîza paşerojê amade be.", "Kongra Star – About", "https://kongra-star.org/eng/about/", "Arşiv işlevini görünür kılıyor; seçenekteki yanlışlar aynı kurumun görev alanlarından değil."),
    ("Muzîk", 3, "Di rapora ANFê de, stranê Canción sin miedo ji bo bîranîna Nagihan Akarsel û jinên hatine kuştin çi erkî digire ser xwe?", "Tenê ji bo kêfxweşiyê nîne; bîranîn, naskirina tundiyê û domandina berxwedanê bi hev ve girê dide.", "Tenê wekî straneke kevneşopî ya Newrozê tê pêşkêşkirin.", "Tenê ji bo reklama albûmeke nû hatiye çêkirin.", "Tenê bi armanca ku dengbêjî ji nav bibe hatiye gotin.", "A", "Raporek ANFê dibêje ku stran tenê ji bo bîranînê nehatiye gotin; ew bala li ser tundî û domandina berxwedana jinan jî dikişîne.", "ANF – Andrea Wolf Group releases Canción sin miedo", "https://anfenglishmobile.com/features/andrea-wolf-group-releases-cancion-sin-miedo-for-nagihan-akarsel-63293", "Müzik sorusu, parçayı yalnızca sanat türü olarak değil basın metnindeki toplumsal işleviyle ele alıyor."),
    ("Muzîk", 2, "Di heman rapora ANFê de, koma Andrea Wolf stranê ji bo kîjan kes û mijaran pêşkêş kir?", "Ji bo Nagihan Akarsel û hemû jinên ku hatine kuştin; bi mijara bîranîn û dijberiya li hember tundiyê.", "Ji bo tenê birêvebirên kovara Hawarê.", "Ji bo tenê şairên dibistana Kurmancî ya klasîk.", "Ji bo tenê komîteya dîrokê ya Rojava.", "A", "Raporek ANFê koma Andrea Wolfê bi stranê Nagihan Akarsel û hemû jinên ku hatine kuştin bi bîr tîne û li ser berdewamkirina têkoşînê raweste.", "ANF – Andrea Wolf Group releases Canción sin miedo", "https://anfenglishmobile.com/features/andrea-wolf-group-releases-cancion-sin-miedo-for-nagihan-akarsel-63293", "Doğru seçenek hem kişi hem tema bağını kuruyor; yanlışlar farklı kültür alanlarını karıştırıyor."),
    ("Siyaset", 3, "Li gorî pênaseya Kongra Star, rêxistin ji kîjan yekîneyan pêk tê?", "Komûn, meclîs, akademî, kooperatîf û komîte.", "Tenê parlamentoyek navendî û yek komîteya çapemeniyê.", "Tenê kovar, pirtûkxane û arşîv.", "Tenê dibistanên ziman û komên muzîkê.", "A", "Pênaseya Kongra Star komûn, meclîs, akademî, kooperatîf û komîteyan wekî beşên rêxistinê rêz dike; kongreya giştî jî her du salan carekê tê lidarxistin.", "Kongra Star – About Us", "https://kongra-star.org/eng/about-us/", "Kurumun yapısal bileşenlerini soruyor; doğru şıkta aynı işleyişin farklı katmanları birlikte verildi."),
    ("Siyaset", 3, "Di pênaseya Kongra Star de, «neteweya demokratîk» bi kîjan nêzîkatiyê re tê ravekirin?", "Gel bi avakirina sazîyên xweser ên xwe di civakê de netewe dike, bê ku tenê li hêz û dewletê piştrast bibe.", "Netewe tenê bi yek ziman û yek komê dide pênasekirin.", "Netewe bi rakirina hemû sazîyên civakî tê avakirin.", "Netewe bi şertê ku hemû biryar ji navendekê ve werin dayîn tê çêkirin.", "A", "Di pênaseya Kongra Star de neteweya demokratîk bi avakirina sazîyên xweser ên parastin, aborî, hiqûq, civak, dîplomasî û çandê re tê girêdan.", "Kongra Star – About Us", "https://kongra-star.org/eng/about-us/", "Kurumun kavramı, kurumsal metindeki açıklamasıyla sınırlandırıldı; dışarıdan tanım eklenmedi."),
    ("Paradigma", 3, "Li gorî pirtûka The Political Thought of Abdullah Öcalan, kîjan sê mijar di nav navê pirtûkê de bi hev re tên girêdan?", "Kurdistan, şoreşa jinê û konfederalîzma demokratîk.", "Hawar, Ferheng û dengbêjî.", "Zagros, Newroz û Memê Alan.", "Rêziman, muzîk û erdnîgarî.", "A", "Navê pirtûkê bi şêwazekî eşkere Kurdistan, şoreşa jinê û konfederalîzma demokratîk wekî sê mijarên sereke pêşkêş dike.", "The Political Thought of Abdullah Öcalan – Pluto Press", "https://www.plutobooks.com/product/the-political-thought-of-abdullah-ocalan/", "Kitabın başlığını ezber değil, kavramsal çerçeve olarak ölçüyor."),
    ("Paradigma", 3, "Di pirtûka The Sociology of Freedom de, li gorî ravekirina weşangerê, kîjan qadên fikirê derdikevin pêş?", "Hebûn û azadî, xwezayê û felsefe, anarsîzm û ekolojî.", "Tenê dîroka çapemeniyê û rêziman.", "Tenê teknîka avakirina amûrên muzîkê.", "Tenê rêbazên hilbijartina nûnerên parlamentoyê.", "A", "Ravekirina weşangerê The Sociology of Freedom mijarên wekî hebûn û azadî, xweza û felsefe, anarsîzm û ekolojî dide nîşandan.", "The Sociology of Freedom – Independent Publishers Group", "https://www.ipgbook.com/the-sociology-of-freedom-products-9781629637105.php", "Kitap kaynağıyla paradigma sorusunu destekliyor; cevapta kitabın konu alanları korunuyor."),
]

FIELDS = ["id", "category_key", "language_code", "prompt", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "difficulty", "source_title", "source_url", "publication_status", "quality_note"]

def q(value):
    return "'" + value.replace("'", "''") + "'"

def main():
    with CSV_OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        for i, row in enumerate(ROWS, 1):
            category, difficulty, prompt, a, b, c, d, correct, explanation, title, url, note = row
            w.writerow({"id": f"movement_000{i:02d}", "category_key": category, "language_code": "ku-kmr", "prompt": prompt, "option_a": a, "option_b": b, "option_c": c, "option_d": d, "correct_option": correct, "explanation": explanation, "difficulty": difficulty, "source_title": title, "source_url": url, "publication_status": "PENDING_EDITORIAL_APPROVAL", "quality_note": note})
    values = []
    for category, difficulty, prompt, a, b, c, d, correct, explanation, title, url, note in ROWS:
        values.append("(" + ", ".join(["(select id from public.categories where name = " + q(category) + ")", q("ku-kmr"), q(prompt), q(a), q(b), q(c), q(d), q(correct), q(explanation), str(difficulty), "false", q("multiple_choice"), "NULL", q("movement_sources_question_wave_2")]) + ")")
    SQL_OUT.write_text("-- Hareketa özgü basın, medya ve kitap kaynaklarından üretilen ikinci el yazımı paket.\n-- Canlı yayın için onaylanmadı.\ninsert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values\n" + ",\n".join(values) + ";\n", encoding="utf-8")
    print(f"wrote {len(ROWS)} rows")

if __name__ == "__main__":
    main()
