import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_3.csv"
SQL_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_3.sql"

ROWS = [
    ("Cografya", 1, "Di pergala rojê de, kîjan gerstêrk herî germ e, her çend Merkûr ji Rojê re nêzîktir be?", "Venûs.", "Merkûr.", "Erd.", "Mars.", "A", "NASA dibêje Venûs gerstêrka herî germ a pergala rojê ye, her çend Merkûr ji Rojê re nêzîktir be.", "Solar System Facts – NASA", "https://science.nasa.gov/solar-system/solar-system-facts/"),
    ("Cografya", 1, "Di pergala rojê de, kîjan gerstêrk herî mezin e?", "Jupiter.", "Saturn.", "Erd.", "Neptûn.", "A", "Li gorî NASA, Jupiter gerstêrka herî mezin a pergala rojê ye.", "About the Planets – NASA", "https://science.nasa.gov/solar-system/planets/"),
    ("Cografya", 2, "Di nav gerstêrkên pergala rojê de, kîjan çar gerstêrk wekî gerstêrkên zexm tên binavkirin?", "Merkûr, Venûs, Erd û Mars.", "Jupiter, Saturn, Uranus û Neptûn.", "Erd, Jupiter, Saturn û Pluto.", "Venûs, Mars, Uranus û Erîs.", "A", "NASA çar gerstêrkên nêzîkî Rojê wekî gerstêrkên zexm dide naskirin: Merkûr, Venûs, Erd û Mars.", "About the Planets – NASA", "https://science.nasa.gov/solar-system/planets/"),
    ("Cografya", 2, "Rûyê Erdê bi qasî çend ji sedî ji aliyê okyanûsan ve tê nixumandin?", "70 ji sedî.", "10 ji sedî.", "30 ji sedî.", "95 ji sedî.", "A", "UNESCO dibêje okyanûs nêzîkî 70 ji sedî rûyê gerstêrka Erdê nixumîne.", "Ocean Biodiversity – UNESCO", "https://www.unesco.org/en/query-list/o/ocean-biodiversity"),
    ("Ziman", 2, "Li gorî UNESCO, çima amûrên teknolojiyê yên zimanî dikarin zimanên kêm-bikarhatî alîkar bikin?", "Ji ber ku dikarin gihiştina agahiyê bi zimanên xwecihî û beşdarbûna dîjîtal zêde bikin.", "Ji ber ku hemû zimanên kêm-bikarhatî ji internetê derdixin.", "Ji ber ku tenê yek ziman ji bo teknolojiyê qebûl dikin.", "Ji ber ku zimanê axaftinê ji nivîsê bi tevahî cuda dikin.", "A", "UNESCO dibêje teknolojiyên zimanî dikarin gihiştina agahiyê bi zimanên xwecihî û beşdarbûna wekhev di qada dîjîtal de zêde bikin.", "Multilingualism and Linguistic Diversity – UNESCO", "https://www.unesco.org/en/multilingualism-linguistic-diversity?hub=67103"),
    ("Ziman", 3, "Li gorî NASA, peyva «exoplanet» çi dide naskirin?", "Gerstêrkek ku li derveyî pergala rojê li dora stêrkekî din digere.", "Gerstêrkek ku tenê di nav rojekê de ye.", "Navê din ê gerstêrka Erdê ye.", "Asteroîdek ku li dora Mêjûyê digere.", "A", "NASA exoplanetan wekî gerstêrkên li derveyî pergala rojê dide pênasekirin ku bi gelemperî li dora stêrkên din digerin.", "Planetary Systems – NASA", "https://science.nasa.gov/universe/stars/planetary-system/"),
    ("Ziman", 2, "Li gorî WHO, vaksîn çawa pergala berevaniyê ya laşê perwerde dike?", "Bi naskirina antîjenê û çêkirina antîbodiyan ku laş ji bo pêşerojê amade dikin.", "Bi rakirina hemû hucreyên laşê.", "Bi şertê ku nexweşî bi temamî were dayîn.", "Bi guhertina zimanê laşê.", "A", "WHO dibêje vaksîn pergala berevaniyê perwerde dike ku antîjenê nas bike, antîbodi çêbike û bîr bîne ka li dijî enfeksiyonê çawa berevanî bike.", "What is Vaccination? – WHO", "https://www.who.int/news-room/questions-and-answers/item/vaccines-and-immunization-what-is-vaccination"),
    ("Çand", 2, "Li gorî UNESCO, cûrbecûrbûna jiyana di okyanûsan de çi dihewîne?", "Cûrbecûrbûna di nav cûreyan, di hundirê cûreyan û di ekosîsteman de.", "Tenê hejmarên masiyan di yek deryayê de.", "Tenê şiklên kevirên li binê avê.", "Tenê rengên avê di demsalê de.", "A", "UNESCO biodiversîteya okyanûsê bi cûrbecûrbûna di nav cûreyan, di hundirê cûreyan û di ekosîsteman de pênase dike.", "Ocean Biodiversity – UNESCO", "https://www.unesco.org/en/query-list/o/ocean-biodiversity"),
    ("Çand", 3, "Di peyzajên çandî de, çima têkiliya mirov û hawirdorê wekî beşeke çandê tê dîtin?", "Ji ber ku jiyana civakî, karên erdê û bawerî dikarin li ser hawirdorê şop û wate bihêlin.", "Ji ber ku çand tenê di muzeyê de tê dîtin.", "Ji ber ku mirov qet hawirdorê naguherînin.", "Ji ber ku peyzajên çandî tenê bi avahiyên mezin ve têne pênasekirin.", "A", "UNESCO peyzajên çandî wekî karê hevparê mirov û xwezayê dide pênasekirin ku tê de karên erdê, civak û bawerî dikarin xuya bibin.", "Cultural Landscapes – UNESCO World Heritage Centre", "https://whc.unesco.org/en/culturallandscape"),
    ("Çand", 2, "Di dema veguhastina mirasa devkî de, çima çîrok dikare di her performansê de hinekî biguhere?", "Ji ber ku vegotin têkeliya dubarekirin, afirandin û improvîzasyonê dihewîne.", "Ji ber ku çîrok divê her tim bê deng were nivîsandin.", "Ji ber ku civak çîrokan qet naguhere.", "Ji ber ku performans ji çîrokê cuda ye.", "A", "UNESCO dibêje kevneşopiyên devkî di veguhastinê de dikarin dubarekirin, afirandin û improvîzasyonê bi hev re dihewînin.", "Oral Traditions and Expressions – UNESCO", "https://ich.unesco.org/en/oral-traditions-and-expressions-00053"),
    ("Paradigma", 2, "Li gorî IPCC, di guherîna avhewaya dawî de bandora mirovan çawa tê nirxandin?", "Delîlên zanistî bandoreke mirovan li ser guherîna avhewaya dawî nîşan didin.", "Bandora mirovan bi temamî nayê lêkolînkirin.", "Guherîna avhewayê tenê ji hereketên Rojê pêk tê.", "IPCC dibêje avhewa qet naguherî.", "A", "IPCC di raporên xwe de delîlên bandora mirovan li ser guherîna avhewaya dawî dide nîşandan.", "Climate Change 2021 – IPCC", "https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_SummaryVolume.pdf"),
    ("Paradigma", 3, "Li gorî IPCC, çima şert e ku dîroka avhewayê bi daneyên zanistî bê lêkolînkirin?", "Ji bo ku bandorên xwezayî û yên ji aliyê mirovan ve bi delîlên pîvanbar werin veqetandin.", "Ji bo ku hemû nêrînên zanistî bê delîl wekhev bên pejirandin.", "Ji bo ku daneyên avhewayê ji civakê ve bêne veşartin.", "Ji bo ku pêşbîniya avhewayê bi dîrokê re qet neyê girêdan.", "A", "Lêkolîna zanistî daneyan dike bingeh da ku sedem û bandorên guherîna avhewayê bi awayekî berawirdkar bêne nirxandin.", "Climate Change 2021 – IPCC", "https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_SummaryVolume.pdf"),
    ("Paradigma", 2, "Li gorî WHO, armanca sereke ya vaksînê çi ye?", "Parastina pêşî ji nexweşiyên zirardar, berî ku kes bi wan re rû bi rû bibe.", "Dermankirina her nexweşiyê piştî ku çêbûye.", "Rakirina hewcedariya hemû karên tenduristiyê.", "Guhertina hemû enfeksiyonan bo nexweşiyên sivik.", "A", "WHO vaksînê wekî rêbazeke ewle û bi bandor ji bo parastina pêşî li hember nexweşiyan dide pênasekirin.", "What is Vaccination? – WHO", "https://www.who.int/news-room/questions-and-answers/item/vaccines-and-immunization-what-is-vaccination"),
    ("Paradigma", 3, "Di zanistê de, çima divê encamên lêkolînê ji çavkaniya wan re bên girêdan?", "Ji bo ku kes bikare rêbaz, delîl û sînorên encamê binirxîne.", "Ji ber ku navê zanistvanê tenê bes e.", "Ji ber ku encamên zanistî qet naguhere.", "Ji ber ku delîl û rêbaz di zanistê de ne girîng in.", "A", "Girêdana encamê bi çavkaniya wê re dihêle rêbaz, delîl û sînorên lêkolînê bêne kontrolkirin û bi rexneyekî zanistî bêne nirxandin.", "General scientific reasoning – IPCC/WHO method context", "https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_SummaryVolume.pdf"),
    ("Cografya", 2, "Li gorî NASA, Erd di nav gerstêrkên pergala rojê de kîjan taybetmendiyê bi awayekî taybet nîşan dide?", "Ew tenê gerstêrka ku em li ser rûyê wê avêya şil dizanin e.", "Ew gerstêrka herî dûr ji Rojê ye.", "Ew yekane gerstêrka bê atmosfer e.", "Ew gerstêrka herî mezin a pergala rojê ye.", "A", "NASA dibêje Erd yekane gerstêrka pergala rojê ye ku em li ser rûyê wê avêya şil dizanin.", "Facts About Earth – NASA", "https://science.nasa.gov/earth/facts/"),
    ("Cografya", 3, "Pergala rojê bi qasî çend salan hewce dike ku carekê li dora navenda Rêya Şîrî bigere?", "Nêzîkî 230 milyon sal.", "Nêzîkî 230 sal.", "Nêzîkî 4,6 milyar sal.", "Nêzîkî 365 roj.", "A", "NASA dide nîşandan ku pergala rojê nêzîkî 230 milyon salan hewce dike da ku carekê li dora navenda galaksîya Rêya Şîrî bigere.", "Solar System Facts – NASA", "https://science.nasa.gov/solar-system/solar-system-facts/"),
    ("Siyaset", 2, "Li gorî UNESCO, parastina zimanên xwecihî bi kîjan mafê civakî re têkildar e?", "Bi mafê gihiştina agahî, perwerde û jiyana giştî bi zimanê ku kes hilbijêre.", "Bi qedexeya bikaranîna zimanê dayikê.", "Bi şertê ku zimanên xwecihî tenê di malê de bên bikaranîn.", "Bi rakirina zimanên xwecihî ji perwerdehiyê.", "A", "UNESCO mafê axaftin û afirandinê bi zimanê hilbijartî, bi taybetî zimanê dayikê, bi gihiştina perwerde û jiyana çandî re girê dide.", "Language Policy – UNESCO", "https://ich.unesco.org/doc/src/Language_policy_EN.pdf?t=1529081349"),
    ("Siyaset", 3, "Di parastina okyanûsan de, çima daneyên vekirî yên zanistî dikarin girîng bin?", "Ji bo ku lêkolîner û civak dikarin rewşa cûrbecûrbûna jiyanê bi hev re bişopînin û biryarên baştir bidin.", "Ji bo ku daneyên okyanûsê ji hemû kesan re bêne veşartin.", "Ji bo ku tenê yek sazî karibe li ser okyanûsê biryar bide.", "Ji bo ku cûrbecûrbûna jiyanê ji lêkolînê were derxistin.", "A", "UNESCO li ser girîngiya berhevkirin, parastin û gihiştina vekirî bo daneyên cûrbecûrbûna okyanûsê raweste.", "Ocean Biodiversity – UNESCO", "https://www.unesco.org/en/query-list/o/ocean-biodiversity"),
]

FIELDS = ["id", "category_key", "language_code", "prompt", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "difficulty", "source_title", "source_url", "publication_status", "quality_note"]

def q(v): return "'" + v.replace("'", "''") + "'"

def main():
    with CSV_OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS); w.writeheader()
        for i, row in enumerate(ROWS, 1):
            category, difficulty, prompt, a, b, c, d, correct, explanation, title, url = row
            w.writerow({"id": f"general3_{i:04d}", "category_key": category, "language_code": "ku-kmr", "prompt": prompt, "option_a": a, "option_b": b, "option_c": c, "option_d": d, "correct_option": correct, "explanation": explanation, "difficulty": difficulty, "source_title": title, "source_url": url, "publication_status": "PENDING_EDITORIAL_APPROVAL", "quality_note": "Bilim ve gündelik yaşam genel kültüründen, kapsayıcı ve kaynaklı biçimde elle yazıldı; ikinci editoryal kontrol bekliyor."})
    values=[]
    for category, difficulty, prompt, a, b, c, d, correct, explanation, title, url in ROWS:
        values.append("(" + ", ".join(["(select id from public.categories where name = " + q(category) + ")", q("ku-kmr"), q(prompt), q(a), q(b), q(c), q(d), q(correct), q(explanation), str(difficulty), "false", q("multiple_choice"), "NULL", q("general_culture_question_wave_3")]) + ")")
    SQL_OUT.write_text("-- Bilim, uzay, çevre ve sağlık okuryazarlığından üçüncü genel kültür paketi.\n-- Canlı yayın için onaylanmadı.\ninsert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values\n" + ",\n".join(values) + ";\n", encoding="utf-8")
    print(f"wrote {len(ROWS)} rows")

if __name__ == "__main__": main()
