import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_OUT = ROOT / "supabase" / "2026-07-14_movement_sources_question_wave_4.csv"
SQL_OUT = ROOT / "supabase" / "2026-07-14_movement_sources_question_wave_4.sql"

ROWS = [
    ("Ziman", 3, "Di lîsteya dosyayên Jineolojî Dergisî de, «Zanist û zimanê jiyanê» bi kîjan qadê re têkildar e?", "Bi lêkolîna ziman û zanînê wekî beşên jiyana civakî.", "Bi tenê nexşeyên rêwîtiyê yên çiyayên Zagrosê.", "Bi tenê rêzikên bazirganiya pirtûkan.", "Bi tenê dîroka çapkirina Rojnameya Kurdistanê.", "A", "Lîsteya kovarê «Zanist û zimanê jiyanê» wekî dosyayek li ser zanîn û ziman di çarçoveya jiyanê de dide naskirin.", "Jineolojî Magazine at 10 Years Old", "https://jineoloji.eu/en/2025/06/29/jineoloji-magazine-at-10-years-old-the-reunion-of-knowledge-stolen-from-women-with-women-part-1/"),
    ("Ziman", 2, "Di pirtûka danasîna Jineolojî de, çima ziman tenê wekî amûrekî teknîkî nayê dîtin?", "Ji ber ku ziman bi bîranîn, ezmûn û hilberîna zanîna civakê re têkildar e.", "Ji ber ku ziman tenê ji bo nivîsandina hejmaran e.", "Ji ber ku ziman ji çand û dîrokê bi tevahî cuda ye.", "Ji ber ku ziman di pirtûkê de qet nayê behskirin.", "A", "Danasîna Jineolojî zanîn û jiyanê bi ezmûna jinan û têkoşînên civakî re dide hev; di vê çarçoveyê de ziman tenê teknîk nîne.", "Kurdish Women’s Library – What is Jineolojî", "https://pirtukxaneyajinenkurdistan.com/en/post/what-is-jineoloji/"),
    ("Edebiyat", 2, "Pirtûka Revolution in Rojava bi kîjan awayî pêkhatina xweseriya demokratîk li Rojava dide naskirin?", "Wekî ceribandineke civakî ya ku bi demokrasiya komunal û azadiya jinan re tê girêdan.", "Wekî vegotineke tenê li ser hunera klasîk a Kurdî.", "Wekî ferhengoka peyvên Hawarê.", "Wekî raporek tenê li ser avhewaya Sûriyê.", "A", "Danasîna pirtûkê Rojava wekî ceribandineke xweseriya demokratîk û civakî pêşkêş dike, ne wekî pirtûkeke tenê hunerî an erdnîgarî.", "Revolution in Rojava – David Graeber", "https://davidgraeber.org/books/revolution-in-rojava/"),
    ("Edebiyat", 3, "Di pirtûka Women in the Kurdish Movement de, «nasnameya siyasî» di kîjan çarçoveyê de tê xwendin?", "Di çarçoveya guherîna rola jinan û têkoşîna wan li dijî rolên ferzkirî de.", "Di çarçoveya dabeşkirina peyvên Kurmancî û Soranî de.", "Di çarçoveya dîroka çiyayên Kurdistanê de.", "Di çarçoveya teknîka arşîvkirina wêneyan de.", "A", "Danasîna Springer pirtûkê li ser jinên ku rolên ferzkirî diguherînin û di tevgera siyasî de li pêş dikevin raweste.", "Women in the Kurdish Movement – Springer", "https://link.springer.com/book/10.1007/978-3-030-24744-7"),
    ("Dîrok", 3, "Li gorî lêkolîna Cambridge, piştî pêşketina Jineolojî çi cureyên çalakiyê hatine dîtin?", "Weşandina pirtûk û kovaran, konferans û avakirina komîteyên Jineolojî.", "Tenê komkirina amûrên muzîkê.", "Tenê çêkirina nexşeyên erdnîgarî.", "Tenê veguhastina kovara Hawarê bo alfabeya erebî.", "A", "Chaptersa Cambridge weşandina pirtûk û kovaran, lidarxistina konferansan û avakirina komîteyan wekî beşên pêşketina Jineolojî dide nîşandan.", "The Kurdish Women’s Freedom Movement – Cambridge", "https://www.cambridge.org/core/books/kurdish-womens-freedom-movement/pkk-a-womans-party/A154F270788B30BB87C8705A5C3E794C"),
    ("Dîrok", 2, "Di dîroka kovara Jineolojî de, kîjan mijar di nav dosyayên li ser herêmên Kurdistanê de hatine lîstekirin?", "Rojhilat, Bakur, Rojava û Başûr.", "Misr, Yewnan û Hindistan.", "Şam, Qahîre û Stenbol tenê.", "Zagros, Alborz û Taurus tenê.", "A", "Lîsteya dosyayên kovarê dosyayên taybet li ser Rojhilat, Bakur, Rojava û Başûr dide nîşandan.", "Jineolojî Magazine at 10 Years Old", "https://jineoloji.eu/en/2025/06/29/jineoloji-magazine-at-10-years-old-the-reunion-of-knowledge-stolen-from-women-with-women-part-1/"),
    ("Çand", 2, "Di lîsteya Jineolojî Dergisî de, dosyaya «Rêyên derketina ji krîza çandê» li ser çi raweste?", "Li ser krîza çandê û rêyên derketinê ji wê.", "Li ser rêzikên hesabkirina aborî.", "Li ser taybetmendiyên avhewaya Zagrosê.", "Li ser dîroka kovara Ronahî tenê.", "A", "Navê dosyayê bi awayekî rasterast krîza çandê û rêyên derketinê ji wê dide mijar kirin.", "Jineolojî Magazine at 10 Years Old", "https://jineoloji.eu/en/2025/06/29/jineoloji-magazine-at-10-years-old-the-reunion-of-knowledge-stolen-from-women-with-women-part-1/"),
    ("Çand", 3, "Li gorî pirtûkxaneya jinên Kurdistanê, Jineolojî bi têkoşînên jinên kîjan qadê re tê xwarin?", "Bi têkoşînên jinan li Kurdistanê û li cîhanê.", "Bi tenê têkoşîna yek komê li yek bajarê.", "Bi tenê dîroka akademiyên Ewropayê.", "Bi tenê nivîsarên ku li ser dîroka Hawarê ne.", "A", "Pirtûkxaneya Jinên Kurdistanê dibêje ku Jineolojî ji ezmûnên tevgera jinan li Kurdistanê û ji têkoşînên jinan li cîhanê xwar dibe.", "Kurdish Women’s Library – What is Jineolojî", "https://pirtukxaneyajinenkurdistan.com/en/post/what-is-jineoloji/"),
    ("Siyaset", 3, "Di lîsteya Jineolojî Dergisî de, «siyaseta demokratîk» wekî dosyayek çi nîşan dide?", "Ku siyaseta demokratîk wekî mijareke serbixwe ya lêkolînê û rêxistinê tê nîqaşkirin.", "Ku siyaset di naveroka kovarê de qet nayê behskirin.", "Ku siyaseta demokratîk tenê mijareke dîroka Hawarê ye.", "Ku siyaseta demokratîk bi muzîkê re heman wateyê dide.", "A", "Lîsteya kovarê «Siyaseta demokratîk» wekî dosyayeke cuda dide naskirin, li kêleka dosyayên aborî, ekolojî û civakî.", "Jineolojî Magazine at 10 Years Old", "https://jineoloji.eu/en/2025/06/29/jineoloji-magazine-at-10-years-old-the-reunion-of-knowledge-stolen-from-women-with-women-part-1/"),
    ("Siyaset", 3, "Di pirtûka The Political Thought of Abdullah Öcalan de, kîjan mijar bi navê «Neteweya Demokratîk» tê nîşandan?", "Wekî beşek ji gotûbêja li ser Kurdistan, şoreşa jinê û konfederalîzma demokratîk.", "Wekî beşek tenê ji ferhengoka Hawarê.", "Wekî beşek ji dîroka dengbêjî û tembûrê.", "Wekî beşek ji geologyaya çiyayên Bahtiyarî.", "A", "Pluto Press «Democratic Nation» wekî yek ji beşên pirtûkê li kêleka War and Peace in Kurdistan, Democratic Confederalism û Liberating Life dide lîstekirin.", "The Political Thought of Abdullah Öcalan – Pluto Press", "https://www.plutobooks.com/product/the-political-thought-of-abdullah-ocalan/"),
    ("Paradigma", 3, "Di lîsteya Jineolojî Dergisî de, «konfederalîzma jinan» bi kîjan qada fikirê re zêdetir tê girêdan?", "Bi awayên rêxistinkirina jinan û pêwendiya wan bi siyaset û civakê re.", "Bi tenê dîroka çiyayên Kurdistanê.", "Bi tenê rêzikên alfabeya latînî.", "Bi tenê berhevkirina stranên olî.", "A", "Navê dosyayê «Konfederalîzma jinan» nîqaşa li ser rêxistin û têkiliyên siyasî-civakî yên jinan dixe pêş.", "Jineolojî Magazine at 10 Years Old", "https://jineoloji.eu/en/2025/06/29/jineoloji-magazine-at-10-years-old-the-reunion-of-knowledge-stolen-from-women-with-women-part-1/"),
    ("Paradigma", 3, "Li gorî lêkolîna Cambridge, çima Jineolojî ne tenê wekî navê kovarekê tê fêmkirin?", "Ji ber ku ew bi hilberîna zanînê, pirtûk, konferans, komîte û avakirina civakeke wekhev re tê girêdan.", "Ji ber ku kovar qet nehat weşandin.", "Ji ber ku ew tenê navê alfabeyeke latînî ye.", "Ji ber ku ew tenê cureyekî muzîkê ye.", "A", "Lêkolîna Cambridge Jineolojî wekî pêvajoyeke hilberîna zanînê û rêxistinê dide xwendin ku pirtûk, kovar, konferans û komîteyan dihewîne.", "The Kurdish Women’s Freedom Movement – Cambridge", "https://www.cambridge.org/core/books/kurdish-womens-freedom-movement/pkk-a-womans-party/A154F270788B30BB87C8705A5C3E794C"),
]

FIELDS = ["id", "category_key", "language_code", "prompt", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "difficulty", "source_title", "source_url", "publication_status", "quality_note"]

def q(value):
    return "'" + value.replace("'", "''") + "'"

def main():
    with CSV_OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        for i, row in enumerate(ROWS, 1):
            category, difficulty, prompt, a, b, c, d, correct, explanation, title, url = row
            w.writerow({"id": f"movement4_{i:04d}", "category_key": category, "language_code": "ku-kmr", "prompt": prompt, "option_a": a, "option_b": b, "option_c": c, "option_d": d, "correct_option": correct, "explanation": explanation, "difficulty": difficulty, "source_title": title, "source_url": url, "publication_status": "PENDING_EDITORIAL_APPROVAL", "quality_note": "Hareket basın/yayın veya kitap kaynağından elle yazıldı; ikinci editoryal kontrol bekliyor."})
    values = []
    for category, difficulty, prompt, a, b, c, d, correct, explanation, title, url in ROWS:
        values.append("(" + ", ".join(["(select id from public.categories where name = " + q(category) + ")", q("ku-kmr"), q(prompt), q(a), q(b), q(c), q(d), q(correct), q(explanation), str(difficulty), "false", q("multiple_choice"), "NULL", q("movement_sources_question_wave_4")]) + ")")
    SQL_OUT.write_text("-- Hareket basın-yayın ve kitap kaynaklarından üretilen dördüncü el yazımı paket.\n-- Canlı yayın için onaylanmadı.\ninsert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values\n" + ",\n".join(values) + ";\n", encoding="utf-8")
    print(f"wrote {len(ROWS)} rows")

if __name__ == "__main__":
    main()
