import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_7.csv"
SQL_OUT = ROOT / "supabase" / "2026-07-14_general_culture_question_wave_7.sql"

ROWS = [
    ("Ziman", 1, "Li gorî Neteweyên Yekbûyî, çima Roj a Navneteweyî ya Zimanên Îşaretan tê pîroz kirin?", "Ji bo bal kişandina ser girîngiya zimanên îşaretan di temamkirina mafên mirovan ên kesên kerr de.", "Ji bo ku zimanên îşaretan ji perwerdehiyê bên rakirin.", "Ji bo ku hemû zimanên îşaretan bi zimanekî yekane bên guhartin.", "Ji bo ku zimanên axaftinê ji jiyana giştî bên dûrxistin.", "A", "Neteweyên Yekbûyî vê rojê ji bo bilindkirina hişyariya li ser girîngiya zimanên îşaretan û mafên mirovan ên kesên kerr hatine pêk anîn.", "International Day of Sign Languages – United Nations", "https://www.un.org/en/observances/sign-languages-day"),
    ("Ziman", 2, "Kîjan nêrîn li ser zimanên îşaretan rast e?", "Ew zimanên rastîn in ku dikarin ji bo derbirîn, têgihiştin û pêwendiyên civakî bên bikaranîn.", "Ew tenê şîfreyên ku ji bo peyamên kurt tên bikaranîn in.", "Ew li hemû welatan bi heman rêzimanê tên bikaranîn.", "Ew tenê alîkarên zimanên axaftinê ne û xwedî rêziman nînin.", "A", "UNESCO zimanên îşaretan di nav cûrbecûrbûna zimanî de dide naskirin; ew serişteyên pêwendiyê ne, ne tenê îşaretên alîkar.", "Sign languages – UNESCO Vocabularies", "https://vocabularies.unesco.org/unesco/en/page/concept17050"),
    ("Ziman", 2, "Di perwerdeya pirzimanî de, çima gihiştina xwendekaran bi zimanekî ku ew fam dikin girîng e?", "Ji ber ku têgihiştinê hêsan dike û dikare beşdarbûn û encamên fêrbûnê baştir bike.", "Ji ber ku divê xwendekar ji hemû zimanên din dûr bikeve.", "Ji ber ku zimanê ku xwendekar fam dike di dibistanê de ne girîng e.", "Ji ber ku fêrbûn tenê bi pîvanên yek zimanî pêkan e.", "A", "UNESCO mafê xwendekaran bi zimanên ku ew fam dikin bi fêrbûn û beşdarbûna berfireh re girêdide.", "Languages Matter – UNESCO", "https://www.unesco.org/en/articles/languages-matter-global-guidance-multilingual-education?hub=370"),
    ("Ziman", 3, "Çima parastina zimanên îşaretan dikare bi gihiştina agahiyê re têkildar be?", "Ji ber ku gihiştina perwerde, karûbarên giştî û naveroka dîjîtal bi zimanê xwe beşdarbûna wekhev hêsan dike.", "Ji ber ku zimanên îşaretan divê tenê di malê de bên bikaranîn.", "Ji ber ku agahî divê ji kesên kerr re bêne veşartin.", "Ji ber ku teknolocî nikare zimanê îşaretan piştgirî bike.", "A", "UNESCO mafê azadiya derbirînê bi zimanê hilbijartî û gihiştina agahiyê bi zimanên cuda re girêdide.", "Multilingualism and Linguistic Diversity – UNESCO", "https://www.unesco.org/en/multilingualism-linguistic-diversity?hub=418"),
    ("Çand", 1, "Li gorî UNESCO, kîjan ji van dikare bibe pratîkeke civakî, ayînî an festîvalî?", "Merasîma zewacê, lîstikên kevneşopî, cejnên demsalî û pratîkên civakî.", "Tenê berhemeke ku di depoyê de bê parastin.", "Tenê avahiyek ku qet nayê bikaranîn.", "Tenê belgeyek bê pêwendî bi civakê re.", "A", "UNESCO di nav qada pratîkên civakî, ayînî û festîvalî de merasîm, lîstik, cejnên demsalî û gelek pratîkên din dihesibîne.", "Social Practices, Rituals and Festive Events – UNESCO", "https://ich.unesco.org/en/social-practices-rituals-and-00055"),
    ("Çand", 2, "Çima koçberiya ciwanan dikare hin pratîkên mîrasa bê-maddî bixe xeterê?", "Ji ber ku dema hildêrên pratîkê ji civakê dûr dibin, veguhastina zanîn û jêhatîbûnê dikare qels bibe.", "Ji ber ku koçberî her tim mîrasê bi lez zêde dike.", "Ji ber ku pratîkên mîrasê tenê ji bo ciwanan in.", "Ji ber ku civak nikare mîrasê ji nifşekê re bigihîne.", "A", "UNESCO balê dikişîne ku koçberiya ciwanan dikare kesên pratîkê ji civaka xwe dûr bixe û domandina hin pratîkan zehmet bike.", "Social Practices, Rituals and Festive Events – UNESCO", "https://ich.unesco.org/en/social-practices-rituals-and-00055"),
    ("Çand", 2, "Di parastina cejnekê de, kîjan rêbaz bi wateya mîrasa zindî re li hev tê?", "Pratîkê bi beşdariya civakê bidomîne û rê bide ku ew bi şertên nû re biguheze.", "Pratîkê wekî tiştekî cemidî ji jiyana civakê veqetîne.", "Hemû guhertinên ku civak dixwaze bike qedexe bike.", "Cejnê tenê wekî berhemeke turîstîk biparêze.", "A", "Mîrasa bê-maddî di jiyana civakan de zindî ye; parastin dikare domandinê piştgirî bike bê ku pratîkê ji hildêrên wê veqetîne.", "What is Intangible Cultural Heritage? – UNESCO", "https://ich.unesco.org/en/what-is-intangible-heritage-00003?lang=en"),
    ("Çand", 3, "Çima di naskirina pratîkeke çandî de divê tu bi pirsê 'kî wê mîrasê nas dike?' dest pê bikî?", "Ji ber ku mîras bi wateya ku civak, kom an kesên hildêr didin wê ve tê pênasekirin.", "Ji ber ku tenê saziyên navneteweyî dikarin mîrasê pênase bikin.", "Ji ber ku mîras her tim bi heman awayî ji derveyî tê dîtin.", "Ji ber ku wateya pratîkê bi hildêrên wê re têkildar nîne.", "A", "UNESCO mîrasa bê-maddî wek pratîk, zanîn û jêhatîbûnên ku civak û kom wek beşeke mîrasa xwe nas dikin dide pênasekirin.", "What is Intangible Cultural Heritage? – UNESCO", "https://ich.unesco.org/en/what-is-intangible-heritage-00003?lang=en"),
    ("Paradigma", 1, "Li gorî UNESCO, çar aliyên bingehîn ên çarçoveya jêhatîbûna AI ya xwendekaran kîjan in?", "Ramana mirov-navend, etîka AI, teknîk û sepanên AI, û sêwirana pergala AI.", "Tenê kodkirin, reklâm, bazirganiyê û lîstik.", "Tenê matematîk, sport, muzîk û dîrok.", "Tenê bikaranîna telefon, çapkirin, wêne û deng.", "A", "UNESCO çar aliyên çarçoveyê wek ramana mirov-navend, etîka AI, teknîk û sepanên AI, û sêwirana pergala AI nîşan dide.", "AI Competency Framework for Students – UNESCO", "https://www.unesco.org/en/articles/ai-competency-framework-students?hub=66973"),
    ("Paradigma", 2, "Çima UNESCO di hînkirina AI de li ser 'dadweriya rexneyî' raweste?", "Ji bo ku xwendekar karibe encamên AI bi delîl, sînor, bandor û armancên wan re binirxîne.", "Ji bo ku xwendekar hemû encamên AI bê pirsîn rast qebûl bike.", "Ji bo ku AI ji hemû pêvajoyên biryardan bê derxistin.", "Ji bo ku tenê lez û hêsaniya sepanê bê pîvan.", "A", "Çarçoveya UNESCO xwendekaran wek bikarhênerên berpirsiyar û afirîner dibîne ku divê encam û bandorên AI bi nêrînekî rexneyî binirxînin.", "AI Competency Framework for Students – UNESCO", "https://www.unesco.org/en/articles/ai-competency-framework-students?hub=66973"),
    ("Paradigma", 2, "Di bikaranîna AI de, kîjan biryar bi rêya mirov-navend re guncaw e?", "Mirov armanc û nirxan destnîşan dike, encamên amûrê kontrol dike û berpirsiyariya biryara dawî digire ser xwe.", "Amûrê bê nêrîna mirovan biryara dawî dide.", "Mirov tenê encamê parve dike bê ku çavkaniyê binirxîne.", "Biryara dawî tenê bi pîvana lezê tê dayîn.", "A", "UNESCO xwendekaran wek hevkar û hemwelatiyên berpirsiyar dide naskirin; AI divê piştgiriyê bide kapasîteya mirovan, ne ku berpirsiyariyê ji holê rake.", "AI Competency Framework for Students – UNESCO", "https://www.unesco.org/en/articles/ai-competency-framework-students?hub=66973"),
    ("Paradigma", 3, "Çima di perwerdeya AI de aliyê etîkî ji aliyê teknîkî cuda nayê veqetandin?", "Ji ber ku çêkirin û bikaranîna AI dikare li ser maf, wekhevî, ewlehî û jiyana civakî bandor bike.", "Ji ber ku etîk tenê ji bo zanistên mirovan e.", "Ji ber ku teknîk qet bandorê li civakê nake.", "Ji ber ku çêkirina AI divê bê pirs û bê nirx bê kirin.", "A", "Çarçoveya UNESCO etîka AI û sêwirana berdewam û tevgerê bi jêhatîbûna teknîkî re hev girêdide.", "AI Competency Framework for Students – UNESCO", "https://www.unesco.org/en/articles/ai-competency-framework-students?hub=66973"),
    ("Muzîk", 1, "Li gorî UNESCO, muzîk çawa dikare beşek ji ayîn an cejnê be?", "Bi stran, ritm, dans û performansê re dikare bûyerê nîşan bide û civakê li hev bîne.", "Bi rakirina hemû tevgera civakî ji cejnê.", "Bi tenê bikaranîna amûrekî bê wate.", "Bi şertê ku muzîk ji her pratîka din bê veqetandin.", "A", "UNESCO muzîkê bi ayîn, bûyerên festîvalî, kevneşopiyên devkî û hunerên performansê re têkildar dike.", "Performing Arts – UNESCO", "https://ich.unesco.org/en/performing-arts-00054"),
    ("Muzîk", 2, "Di parastina muzîk û dansa kevneşopî de, çima performansa zindî hêja ye?", "Ji ber ku hereket, deng, têkiliya komê û şertên bûyerê di heman demê de dihêle bêne hînkirin û jiyîn.", "Ji ber ku performansa zindî hemû guhertinan qedexe dike.", "Ji ber ku muzîk tenê di tomarkirinê de wate heye.", "Ji ber ku şertên civakî di performansê de ne girîng in.", "A", "UNESCO hunerên performansê wek pratîkên zindî dide naskirin ku di nav civak, bûyer û têkiliya mirovan de tên jiyîn.", "Performing Arts – UNESCO", "https://ich.unesco.org/en/performing-arts-00054"),
    ("Cografya", 1, "Peyzajek çandî çi dide nîşandan ku nexşeyek tenê ya erdê nikare bi temamî nîşan bide?", "Têkiliya di navbera hawirdor, dîroka mirov, bikaranîna erdê û jiyana civakî de.", "Tenê bilindahiya çiyayan.", "Tenê sînorên siyasî yên li ser nexşeyê.", "Tenê rengê avê û axê.", "A", "UNESCO peyzajên çandî bi têkiliya mirov û hawirdorê û bi şopên jiyana civakî û dîrokî re pênase dike.", "Cultural Landscapes – UNESCO World Heritage Centre", "https://whc.unesco.org/en/culturallandscape"),
    ("Cografya", 2, "Di lêkolîna peyzajekî çandî de, çima dîroka bikaranîna erdê dikare wekî daneyeke girîng bê xwendin?", "Ji ber ku awayê çandin, avdan, rûniştin û parastina erdê têkiliya mirov û hawirdorê nîşan dide.", "Ji ber ku bikaranîna erdê tenê bi avahiyên nû re têkildar e.", "Ji ber ku dîrok nikare li ser hawirdorê bandor bike.", "Ji ber ku peyzaj divê ji civaka ku wê bikar tîne bê veqetandin.", "A", "UNESCO peyzajê wekî encama têkiliya dirêj a mirovan û hawirdorê dide naskirin; bikaranîna erdê beşek ji vê dîrokê ye.", "Cultural Landscapes – UNESCO World Heritage Centre", "https://whc.unesco.org/en/culturallandscape"),
]

FIELDS = ["id", "category_key", "language_code", "prompt", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "difficulty", "source_title", "source_url", "publication_status", "quality_note"]

def q(v):
    return "'" + v.replace("'", "''") + "'"

def main():
    with CSV_OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        for i, row in enumerate(ROWS, 1):
            category, difficulty, prompt, a, b, c, d, correct, explanation, title, url = row
            w.writerow({"id": f"general7_{i:04d}", "category_key": category, "language_code": "ku-kmr", "prompt": prompt, "option_a": a, "option_b": b, "option_c": c, "option_d": d, "correct_option": correct, "explanation": explanation, "difficulty": difficulty, "source_title": title, "source_url": url, "publication_status": "PENDING_EDITORIAL_APPROVAL", "quality_note": "Kategori bazlı, kaynaklı ve özgün olarak hazırlandı; ikinci editoryal kontrol bekliyor."})
    values = []
    for category, difficulty, prompt, a, b, c, d, correct, explanation, title, url in ROWS:
        values.append("(" + ", ".join(["(select id from public.categories where name = " + q(category) + ")", q("ku-kmr"), q(prompt), q(a), q(b), q(c), q(d), q(correct), q(explanation), str(difficulty), "false", q("multiple_choice"), "NULL", q(url)]) + ")")
    SQL_OUT.write_text("-- Ziman, çand, AI, muzîk û peyzajên çandî.\n-- Canli yayin icin onaylanmadi.\ninsert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values\n" + ",\n".join(values) + ";\n", encoding="utf-8")
    print(f"wrote {len(ROWS)} rows")

if __name__ == "__main__":
    main()
