# -*- coding: utf-8 -*-
"""Offline havuzdaki Türkçe şıkları Kurmancî'ye çevirir.

2026-07-24 editoryal denetim: 318 soruda gövde Kurmancî, şıklar Türkçeydi.
453 benzersiz şık metninin Türkçe olan 224'ü burada elle çevrildi; sözlük
tüm bankaya uygulanır.
"""
import json, re, sys

TR2KU = {
 # ── Muzîk ──
 "Kars, Ağrı ve Van yöresine özgü lirik müzik tarzı": "şêwaza muzîka lîrîk a taybetî ya herêma Qersê, Agirî û Wanê",
 "Kürt müziğine rock ve caz esintileri getiren sanatçı": "hunermendê ku bayê rock û caz anî muzîka kurdî",
 "daha çok aşk ve yiğitlik üzerine söylenen müzik türü": "cureya muzîkê ya ku bêtir li ser evîn û mêrxasiyê tê gotin",
 "Kürt müziğini dünyaya tanıtan en meşhur ses sanatçısı": "hunermendê dengî yê herî navdar ê ku muzîka kurdî da nasîn cîhanê",
 "dengbêjlerin söylediği destansı veya aşk temalı şarkı": "strana destanî an evînî ya ku dengbêj dibêjin",
 "Kürt müziğinde plak dolduran ilk Kürt kadın sanatçı": "yekem hunermenda kurd a jin a ku plak dagirt",
 "halaylarda çalınan hareketli ve ritmik halk şarkıları": "stranên gelêrî yên bilez û rîtmîk ên ku di govendê de tên lêxistin",
 "yüksek sesli, açık havada çalınan nefesli çalgı": "amûra pifê ya bidengê bilind a ku li derve tê lêxistin",
 "tek bir sanatçının şarkı söylemesi veya çalması": "stranbêjî an lêxistina bi tenê ya hunermendekî",
 "erken dönem Kürt müziği kayıtlarını yapan dengbêj": "dengbêjê ku tomarên destpêkê yên muzîka kurdî kirin",
 "Şırnak ve Cizre yöresinin ritmik ve makamsal müziği": "muzîka rîtmîk û makamî ya herêma Şirnex û Cizîrê",
 "Kürt coğrafyasında da çalınan yaylı çalgı": "amûra kevanî ya ku li erdnîgariya kurdî jî tê lêxistin",
 "kış gecesi sohbetlerinde icra edilen sözlü müzik": "muzîka devkî ya ku di şevbihêrkên zivistanê de tê gotin",
 "Türk ve Kürt müziğinde ezgisel yapıyı belirleyen sistem": "pergala ku di muzîka tirkî û kurdî de avahiya avazê diyar dike",
 "Kürt kadın dengbêj geleneğinin en bilinen temsilcilerinden": "yek ji nûnerên herî naskirî yên kevneşopiya dengbêjiya jinan",
 "Serhat bölgesinde yaygın olan bir Kürt halk ezgisi türü": "cureyekî avaza gelêrî ya kurdî ku li herêma Serhedê belav e",
 "geleneksel kaval benzeri çalgı": "amûra kevneşopî ya dişibe bilûrê",
 "kaval benzeri geleneksel üflemeli çalgı": "amûra pifê ya kevneşopî ya bilûrî",
 "Kürt halk müziğinde en kutsal sayılan telli saz": "sazê têlî yê ku di muzîka gelêrî ya kurdî de herî pîroz tê hesibandin",
 "Kürt tasavvuf ve halk müziğinde kullanılan vurmalı çalgı": "amûra lêdanê ya ku di muzîka tesewufî û gelêrî ya kurdî de tê bikaranîn",
 "müziği kağıda dökmek için kullanılan evrensel işaretler": "nîşanên gerdûnî yên ku ji bo nivîsandina muzîkê tên bikaranîn",
 "Kürt halk müziğinde bir başka ezgi tarzı": "şêwazeke din a avazê di muzîka gelêrî ya kurdî de",
 "90'larda Kürt müziğinde devrim yapan alternatif müzik grubu": "koma muzîkê ya alternatîf a ku di salên 90î de di muzîka kurdî de guhertin çêkir",
 "modern dönemde Kürt halk müziğini icra eden sanatçı": "hunermendê ku di serdema nûjen de muzîka gelêrî ya kurdî pêşkêş dike",
 "Dersim ve Bingöl yöresinde icra edilen Kürtçe müzik": "muzîka kurdî ya ku li herêma Dêrsim û Çewlîgê tê gotin",
 "antik Mezopotamya ve Kürt müziğinde kullanılan arp benzeri çalgı": "amûra arpî ya ku li Mezopotamyaya kevnar û di muzîka kurdî de hat bikaranîn",
 "Duhok ve Zaho yöresine has müzikal tarz": "şêwaza muzîkê ya taybetî ya herêma Dihok û Zaxoyê",
 "Bahdinan bölgesinin popüler klasik halk sanatçısı": "hunermendê gelêrî yê klasîk ê populer ê herêma Behdînan",
 "Van ve Diyarbakır'da dengbêjlerin dinlendiği kültürel mekan": "cihê çandî yê ku li Wan û Amedê dengbêj lê tên guhdarîkirin",
 "Kürt halk müziğinde ağıt benzeri ezgi": "avaza şînî ya di muzîka gelêrî ya kurdî de",
 "halk müziğinde yaygın olarak çalınan zilli tef": "erbaneya bi zil a ku di muzîka gelêrî de pir tê lêxistin",
 "topluluk halinde şarkı söyleme biçimi": "awayê stranbêjiya bi kom",
 "Enstrümansız ve doğaçlama ezgili": "bêyî amûr û bi avaza xweberî",
 "zurna ile birlikte çalınan ritim sazı": "sazê rîtmê yê ku bi zirneyê re tê lêxistin",
 "tarihteki ilk Kürt rock grubunun adı": "navê yekem koma rockê ya kurdî ya dîrokê",
 "tarihteki ilk Kürtçe rock grubunun adı": "navê yekem koma rocka kurdî di dîrokê de",
 "Kürt müziğini çok kültürlü ortamda icra eden grup": "koma ku muzîka kurdî di hawîrdoreke pirçandî de pêşkêş dike",
 "genel olarak şarkı okuyan, seslendiren kişi": "kesa ku bi giştî stranan dibêje",
 "ezgili sözlü anlatım yapan sanatçı": "hunermendê ku vegotina devkî ya bi avaz dike",
 "Müzik ve ritüel/ezgi geleneği": "kevneşopiya muzîk û rîtûel/avazê",
 "Sözlü/müzikal gelenek": "kevneşopiya devkî/muzîkal",
 "Sözlü anlatı ve ezgili hikâye aktarımı": "vegotina devkî û veguhastina çîroka bi avaz",
 "sözlü anlatım ve ezgili hikaye": "vegotina devkî û çîroka bi avaz",
 "Bireysel şarkı": "strana kesane",
 "Şiir okuma": "xwendina helbestê",
 "Toplu halk dansı": "reqsa gelêrî ya komî",
 # ── Edebiyat ──
 "Şerefname ve Mem û Zîn'i Soraniceye çeviren yazar": "nivîskarê ku Şerefname û Mem û Zîn wergerandin soranî",
 "Ehmedê Xanî'nin başlattığı edebi ve düşünsel ekol": "ekola wêjeyî û ramanî ya ku Ehmedê Xanî dest pê kir",
 "Kürt edebiyatının bilinen en eski klasik şairlerinden": "yek ji helbestvanên klasîk ên herî kevn ên wêjeya kurdî",
 "Kürt dili ve edebiyatı üzerine çalışan akademisyen": "akademîsyenê ku li ser ziman û wêjeya kurdî dixebite",
 "Ehmedê Xanî tarafından yazılan ilk Kürtçe sözlük": "yekem ferhenga kurdî ya ku Ehmedê Xanî nivîsî",
 "Soranice klasik şiir okulunun en büyük divan şairi": "helbestvanê dîwanê yê herî mezin ê dibistana helbesta klasîk a soranî",
 "modern Kürt şiirinde ve nesrinde iz bırakmış yazar": "nivîskarê ku di helbest û pexşana kurdî ya nûjen de şop hiştiye",
 "Modern dönemde roman/gazete gibi türlerin gelişmesi": "pêşketina cureyên wek roman û rojnameyê di serdema nûjen de",
 "17. yüzyılda Kürt aydınlanma fikrini yazan şair": "helbestvanê ku di sedsala 17em de ramana ronakbîriya kurdî nivîsî",
 "Doğu Kürdistan'ın meşhur modern şair ve yazarı": "helbestvan û nivîskarê nûjen ê navdar ê rojhilatê Kurdistanê",
 "Kürt sözlü edebiyatının en hüzünlü destanlarından biri": "yek ji destanên herî xemgîn ên wêjeya devkî ya kurdî",
 "mistik aşk ve felsefe içeren meşhur şiir divanı": "dîwana helbestan a navdar a ku evîna mîstîk û felsefeyê dihewîne",
 "tarihte divan yazmış ilk Kürt kadın tarihçi ve şair": "yekem dîroknas û helbestvana kurd a jin a ku dîwan nivîsî",
 "Şivanê Kurd adlı ilk Kürtçe romanın yazarı": "nivîskarê yekem romana kurdî ya bi navê Şivanê Kurmanca",
 "modern Kürt hikayeciliğinin kurucu isimlerinden": "yek ji navên damezrîner ên çîroknivîsiya kurdî ya nûjen",
 "klasik Kürt edebiyatında önemli yeri olan şair": "helbestvanê ku di wêjeya klasîk a kurdî de cihekî girîng digire",
 "Mevlid-i Şerif'i Kürtçe yazan klasik şair": "helbestvanê klasîk ê ku Mewlûda Şerîf bi kurdî nivîsî",
 "Kürt şiirine serbest tarzı getiren büyük şair": "helbestvanê mezin ê ku şêwaza azad anî helbesta kurdî",
 "Zazaca ilk mevlidi yazan şair ve din alimi": "helbestvan û alimê dîn ê ku yekem mewlûda kirmanckî nivîsî",
 "Kürtçe gramer kitapları yazan dilbilimci ve yazar": "zimannas û nivîskarê ku pirtûkên rêzimana kurdî nivîsî",
 "Kürt aydınlanmasını ve Latin alfabesini yayan edebi akım": "tevgera wêjeyî ya ku ronakbîrî û alfabeya latînî belav kir",
 "erken dönem Kürtçe edebi ve siyasi yayınlardan biri": "yek ji weşanên wêjeyî û siyasî yên destpêkê yên kurdî",
 "Şam'da Latin alfabesiyle çıkarılan edebi dergi": "kovara wêjeyî ya ku li Şamê bi alfabeya latînî derket",
 "Latin alfabesiyle basılan ilk Kürtçe dergi": "yekem kovara kurdî ya ku bi alfabeya latînî hat çapkirin",
 "Kürt tiyatrosunun kurucu oyun yazarlarından": "yek ji şanonivîsên damezrîner ên şanoya kurdî",
 "Erdelan beyliğinde yaşamış ünlü kadın şair": "helbestvana jin a navdar a ku li mîrektiya Erdelanê jiya",
 "Kürt edebiyatının en eski klasik rubai şairi": "helbestvanê rubaiyan ê klasîk ê herî kevn ê wêjeya kurdî",
 "Kürt klasik edebiyatının en büyük aşk destanı": "destana evînê ya herî mezin a wêjeya klasîk a kurdî",
 "1935 yılında basılan ilk modern Kürtçe roman": "yekem romana kurdî ya nûjen a ku di 1935an de hat çapkirin",
 "modern Kürt romanının kurucusu ve öncü romancı": "damezrîner û pêşengê romana kurdî ya nûjen",
 "kuşların diliyle yazan meşhur Kürt şair": "helbestvanê kurd ê navdar ê ku bi zimanê teyran dinivîsî",
 "klasik dönemde Kürtçe eserler yazmış şair": "helbestvanê ku di serdema klasîk de berhemên kurdî nivîsîn",
 "Kürt dilinin ve birliğinin değerini göstermek": "nîşandana nirxa ziman û yekîtiya kurdî",
 "Masallar, destanlar ve dengbêj anlatıları": "çîrok, destan û vegotinên dengbêjan",
 "Çîrok (masal) ve kilam/stran (ezgi)": "çîrok û kilam/stran",
 "Masal/hikâye anlatan kişi": "kesa ku çîrokan vedibêje",
 "Tasavvufi şiir (divan)": "helbesta tesewufî (dîwan)",
 "meşhur Kürt halk hikayesi": "çîroka gelêrî ya kurdî ya navdar",
 "destansı Kürt halk anlatısı": "vegotina gelêrî ya kurdî ya destanî",
 "Doğa ve kuşlar": "xweza û teyr",
 "Yazar ve aydın": "nivîskar û ronakbîr",
 "Mem ve Zîn": "Mem û Zîn",
 # ── Cografya ──
 "Fırat'ın kollarının suladığı büyük tarım ovası": "deşta çandiniyê ya mezin a ku bi çemikên Firatê tê avdan",
 "Karacadağ lavlarının oluşturduğu taşlık plato": "deşta keviran a ku ji lavên Karacadaxê pêk hatiye",
 "Musul ovasının ortasında yükselen stratejik dağ": "çiyayê stratejîk ê ku li navenda deşta Mûsilê bilind dibe",
 "Van gölü kuzeyinde yer alan sönmüş volkanik dağ": "çiyayê volkanîk ê nefeal ê li bakurê Gola Wanê",
 "Diyarbakır'ın antik çağdaki tarihi ismi ve kalesi": "navê dîrokî yê Amedê yê serdema kevnar û kela wê",
 "Dersim coğrafyasının en engebeli sıradağları": "rêzeçiyayên herî asê yên erdnîgariya Dêrsimê",
 "dünyanın en büyük ikinci krater gölüne sahip dağ": "çiyayê ku gola kraterê ya duyemîn a herî mezin a cîhanê lê ye",
 "Doğu Kürdistan'da yer alan tuzlu göl havzası": "hewza gola şor a li rojhilatê Kurdistanê",
 "Cizre ve Silopi düzlüklerini kapsayan verimli ova": "deşta bi bereket a ku deştên Cizîr û Silopiyê digire",
 "Elazığ sınırlarında yer alan tektonik göl": "gola tektonîk a di sînorên Elezîzê de",
 "Nuh'un gemisinin indiğine inanılan tarihi dağ": "çiyayê dîrokî yê ku tê bawerkirin keştiya Nuh lê daketiye",
 "Diyarbakır ve Şırnak'ı kapsayan nehir havzası": "hewza çem a ku Amed û Şirnexê digire",
 "krater gölüne sahip aktif volkanik dağ": "çiyayê volkanîk ê feal ê xwedî gola kraterê",
 "Güney Kürdistan'ın en verimli tarım ovası": "deşta çandiniyê ya herî bibereket a başûrê Kurdistanê",
 "Kürdistan dağlarının tipik bitki örtüsü ve ağacı": "nebat û dara tîpîk a çiyayên Kurdistanê",
 "Türkiye ve Irak sınırını çizen Dicle kolu": "çemikê Dîcleyê yê ku sînorê Tirkiye û Iraqê xêz dike",
 "dünyanın en büyük sodalı gölü olan havza": "hewza ku gola sodalî ya herî mezin a cîhanê ye",
 "Zaho ve Duhok civarındaki dağlık coğrafi alan": "herêma çiyayî ya derdora Zaxo û Dihokê",
 "Diyarbakır surlarının altından geçen nehir": "çemê ku ji bin sûrên Amedê derbas dibe",
 "Dicle ve Fırat çevresindeki tarihsel bölge": "herêma dîrokî ya derdora Dîcle û Firatê",
 "Kürdistan coğrafyasının en yüksek zirvesi": "lûtkeya herî bilind a erdnîgariya Kurdistanê",
 "Kars ve Iğdır sınırlarından geçip Hazar'a dökülen su": "ava ku ji sînorên Qers û Îdirê derbas dibe û dirijê Hezarê",
 "Taş mimarisi ve Mezopotamya manzarası": "mîmariya kevirî û dîmena Mezopotamyayê",
 "Botan emirliğinin ve tarihsel kültürün beşiği olan şehir": "bajarê ku dergûşa mîrektiya Botan û çanda dîrokî ye",
 "Êzidî Kürtlerin tarihsel yerleşim bölgesi ve kalesi": "herêma niştecihbûna dîrokî ya kurdên êzidî û kela wan",
 "Dünyanın en eski sürekli yerleşimlerinden biri olmasıyla": "bi yek ji cihên niştecihbûna berdewam a herî kevn a cîhanê bûyîna xwe",
 "dağ": "çiya",
 "Madrid ve Lizbon": "Madrîd û Lîzbon",
 "Kahire ve Şam": "Qahîre û Şam",
 "Roma ve Atina": "Roma û Atîna",
 "Pekin ve Tokyo": "Pekîn û Tokyo",
 "Mısır, Suriye ve çevresi": "Misir, Sûriye û derdor",
 # ── Dîrok / Siyaset ──
 "1946'da kurulan ilk kısa ömürlü Kürt devleti": "yekem dewleta kurdî ya kurtjiyan a ku di 1946an de hat damezrandin",
 "Zulme karşı direniş ve yeniden doğuş": "berxwedana li dijî zilmê û ji nû ve jidayikbûn",
 "Irak rejimi tarafından idam edilen Kürt kadın aktivist": "çalakvana kurd a jin a ku ji aliyê rejîma Iraqê ve hat îdamkirin",
 "Kürt alfabesini geliştiren yayıncı ve aydın": "weşanger û ronakbîrê ku alfabeya kurdî pêş xist",
 "Kürt hareketinin efsanevi askeri ve siyasi lideri": "serokê leşkerî û siyasî yê efsanewî yê tevgera kurdî",
 "1925 yılında Kürt hakları için isyan eden lider": "serokê ku di 1925an de ji bo mafên kurdan serî hilda",
 "Osmanlı ve Safevi sınırını belirleyen antlaşma": "peymana ku sînorê Osmanî û Sefewî diyar kir",
 "Dil ve alfabe çalışmalarını yaygınlaştırdığı için": "ji ber ku xebatên ziman û alfabeyê belav kir",
 "Kürdistan gazetesini çıkaran ilk Kürt gazeteci": "yekem rojnamevanê kurd ê ku rojnameya Kurdistanê derxist",
 "Kürt örf adetlerini derleyen ilk araştırmacı": "yekem lêkolînerê ku edet û kevneşopiyên kurdî berhev kirin",
 "Dersim bölgesinde yaşanan askeri harekat ve kriz": "operasyona leşkerî û krîza ku li herêma Dêrsimê qewimî",
 "Fiili özerk yönetim ve sonrasında KRG kurumlaşması": "rêveberiya xweser a fiîlî û paşê avabûna sazûmaniya Herêma Kurdistanê",
 "Kürt hanedan ve beyliklerinin tarihini": "dîroka xanedan û mîrektiyên kurdan",
 "20. yüzyıl başında kurulan Kürt örgütü": "rêxistina kurdî ya ku di destpêka sedsala 20em de hat damezrandin",
 "İlk Kürt gazetesi Kürdistan’ın yayımlanmasıyla ilişkilidir": "bi weşandina yekem rojnameya kurdî, Kurdistanê re girêdayî ye",
 "Osmanlı ve Kaçar merkezileşme politikaları": "siyasetên navendîkirinê yên Osmanî û Qacar",
 "Osmanlı-Safevi dönemi (16-19. yüzyıl)": "serdema Osmanî-Sefewî (sedsalên 16-19em)",
 "Osmanlı döneminde (16. yüzyıl)": "di serdema Osmanî de (sedsala 16em)",
 "Irak’ın 19. vilayeti/gubernatorluğu olarak ayrı statü kazandı": "wek parêzgeha 19em a Iraqê statuyeke cuda bi dest xist",
 "Demirci Kawa ile zalim Dehak": "Kawayê Hesinker û Dehaqê zalim",
 "Zalim bir kral/tiran": "padîşahekî/tîranekî zalim",
 "Bilge bir hâkim": "dadgerekî zana",
 "Kahraman bir asker": "leşkerekî mêrxas",
 "Cömert bir tüccar": "bazirganekî comerd",
 "16. yüzyıl": "sedsala 16em",
 "17. yüzyıl": "sedsala 17em",
 "15. yüzyıl": "sedsala 15em",
 "12. yüzyıl": "sedsala 12em",
 "19. yüzyıl": "sedsala 19em",
 "20. yüzyıl": "sedsala 20em",
 "Orta Çağ (10-11. yüzyıl)": "Serdema Navîn (sedsalên 10-11em)",
 # ── Çand ──
 "Halay çekilir ve ateşin üstünden atlanır": "govend tê girtin û li ser agir tê banzdan",
 "Halkın direnişini ve özgürlük umudunu": "berxwedana gel û hêviya azadiyê",
 "yiyecek taşımak için dokunan torba": "tûrikê ku ji bo hilgirtina xwarinê tê hûnandin",
 "Kültürel aidiyet ve coğrafi hafızayı": "aîdiyeta çandî û bîra erdnîgarî",
 "Sosyal örgütlenme, güvenlik, üretim ve siyasal ilişki ağı": "tora rêxistinbûna civakî, ewlehî, hilberîn û têkiliya siyasî",
 "Acıyı, kaybı ve toplumsal hafızayı aktarmak": "veguhastina êş, windahî û bîra civakî",
 "İranlılar ve birçok halk (Nevruz olarak)": "Îranî û gelek gelên din (wek Newrozê)",
 "Bölge, lehçe, iklim, tarım ve komşu mutfaklarla etkileşim farklı olduğu için": "ji ber ku herêm, zarava, avhewa, çandinî û danûstandina bi mitbaxên cîran re cuda ne",
 "Melek Tavus ve ışık/güneş motifi": "Melek Tawis û motîfa ronahî/rojê",
 "şırnak yöresine ait geleneksel dans": "reqsa kevneşopî ya herêma Şirnexê",
 "geleneksel çobanlık ve doğa bilgisi": "şivantiya kevneşopî û zanîna xwezayê",
 "Kürt halk takviminde yılbaşı kutlaması": "pîrozbahiya serê salê di salnameya gelêrî ya kurdî de",
 "kınalı keklik ve doğa sevgisi sembolü": "kewa bi hene û sembola hezkirina xwezayê",
 "Kürtçenin yazı, yayın, eğitim ve dijital üretimde görünürlüğünü artırmayı": "zêdekirina xuyabûna kurdî di nivîs, weşan, perwerde û hilberîna dîjîtal de",
 "Misafirperverlik ve ilişki kurma isteğini": "mêvanperwerî û daxwaza avakirina têkiliyê",
 "Özgün dini-kültürel topluluk ve tarihsel travmalar": "civaka olî-çandî ya taybet û trawmayên dîrokî",
 "Kültürel hafıza, edebiyat, sözlü anlatı ve aidiyet taşıdığı için": "ji ber ku bîra çandî, wêje, vegotina devkî û aîdiyetê hildigire",
 "Tavuk ve pirinçle yapılan geleneksel yemek": "xwarina kevneşopî ya ku bi mirîşk û birincê tê çêkirin",
 "Dil, kültür, yayıncılık, dayanışma ve kimlik aktarımı": "ziman, çand, weşangerî, hevgirtin û veguhastina nasnameyê",
 "geleneksel kadın oyunları veya dansları": "lîstik an reqsên kevneşopî yên jinan",
 "yabani gül ve bitkisel çay geleneği": "kevneşopiya gula çolê û çaya nebatî",
 "geleneksel ziyaret ve anma günü": "roja ziyaret û bibîranînê ya kevneşopî",
 "geleneksel erkek giyim takımı": "cilûbergê kevneşopî yê mêran",
 "ayran ve su ikram etme kültürü": "çanda pêşkêşkirina dew û avê",
 "koç katımı ve hayvancılık şenliği": "cejna berdana beran û ajaldariyê",
 "geleneksel hasat ve bereket şenliği": "cejna dirûn û bereketê ya kevneşopî",
 "duygu ve toplumsal hafıza": "hest û bîra civakî",
 "el sanatı ile ilişkilidir": "bi destkariyê re girêdayî ye",
 "gelenek ile ilişkilidir": "bi kevneşopiyê re girêdayî ye",
 "gündelik kültür ile ilişkilidir": "bi çanda rojane re girêdayî ye",
 "yerel yaşam ve paylaşım": "jiyana herêmî û parvekirin",
 "Köy odaları ve dîwanlar": "odeyên gund û dîwanxane",
 "göçer yaşam tarzı ve dans ritmi": "şêwaza jiyana koçerî û rîtma reqsê",
 "üç ayaklı geleneksel halk dansı": "reqsa gelêrî ya kevneşopî ya sê-pêyî",
 "yöresel halk dansları": "reqsên gelêrî yên herêmî",
 "kültürel sembol ve renk hafızası": "sembola çandî û bîra rengan",
 "Doğanın canlanışı ve bereket": "vejîna xwezayê û bereket",
 "komşuluk ve toplumsal yardımlaşma": "cîranî û alîkariya civakî",
 "Sığınak, özgürlük ve direnişi": "stargeh, azadî û berxwedan",
 "Toplu/kolektif bir kutlama": "pîrozbahiyeke komî/kolektîf",
 "Gündelik yaşam, motif ve yerel estetik bilgisini taşıdığı için": "ji ber ku zanîna jiyana rojane, motîf û estetîka herêmî hildigire",
 "Dağlık iklimde mevsimsel dayanıklılık ve gıda güvenliği sağladığı için": "ji ber ku li avhewaya çiyayî berxwedana demsalî û ewlehiya xwarinê peyda dike",
 "Yemek yasağını": "qedexeya xwarinê",
 "Topluluk ve aile bağlarını": "girêdanên civak û malbatê",
 "Müslüman çoğunluk yanında Ezidi, Alevi, Yarsanî/Ehl-i Hak ve başka inanç toplulukları da vardır": "li kêleka piraniya misilman, êzidî, elewî, yarsanî/Ehlê Heq û civakên baweriyê yên din jî hene",
 "Resmi arşivlerde görünmeyen deneyimleri ve hafızayı kaydedebildiği için": "ji ber ku ezmûn û bîra ku di arşîvên fermî de xuya nabe tomar dike",
 "Bahar, yenilenme ve özgürlük/direniş": "bihar, nûbûn û azadî/berxwedan",
 # ── Paradigma / Siyaset ──
 "Farklı halkların eşitlik ve barış içinde ortak yaşamını": "jiyana hevpar a gelên cuda di nav wekhevî û aştiyê de",
 "Piyasa, mülkiyet ve rekabet": "bazar, xwedîtî û pêşbazî",
 "Kadın özgürlüğü, ekoloji ve demokrasi": "azadiya jinê, ekolojî û demokrasî",
 "Sanayileşme, kalkınma ve refah": "pîşesazîbûn, pêşketin û refah",
 "Tek bir liderde": "di destê serokekî tenê de",
 "Eşit ve gönüllü birliktelikle": "bi yekbûna wekhev û bi dilxwazî",
 "Tam bir ayrışmayla": "bi veqetîneke tam",
 "Katı bir hiyerarşiyle": "bi hiyerarşiyeke hişk",
 "Demokrasi, kadın özgürlüğü ve ekoloji": "demokrasî, azadiya jinê û ekolojî",
 "Farklılıklara saygı ve eşitlik": "rêzgirtina li cudahiyan û wekhevî",
 "Kapitalist modernite ve merkezi ulus-devlet eleştirisi": "rexneya modernîteya kapîtalîst û dewleta neteweyî ya navendî",
 "Farklı kimlik ve inançların bir arada yaşamasını": "jiyana bi hev re ya nasname û baweriyên cuda",
 "Ekoloji, kadın ve demokrasi krizlerini": "krîzên ekolojî, jin û demokrasiyê",
 "Merkezîleşme ve doğrudan yönetim": "navendîbûn û rêveberiya rasterast",
 "Yerel meclis ve komünlerde": "di meclîs û komunên herêmî de",
 "Kadın kotası": "kota jinan",
 "Şiddet ve dayatmayı": "tundî û ferzkirin",
 "Borsa, döviz ve faiz sorunlarını": "pirsgirêkên borsa, dewîz û faîzê",
 "Spor, sanat ve turizm sorunlarını": "pirsgirêkên werzîş, huner û turîzmê",
 "Trafik, enflasyon ve işsizlik krizlerini": "krîzên trafîk, enflasyon û bêkariyê",
 "Sınır, ordu ve bayrağı": "sînor, ordû û ala",
 "Eşitlik, özgürlük ve barışı": "wekhevî, azadî û aştî",
 "Hiyerarşi, zenginlik ve gücü": "hiyerarşî, dewlemendî û hêz",
 "Rekabet, kâr ve mülkiyeti": "pêşbazî, qezenc û xwedîtî",
 "Siyah, kırmızı ve sarı": "reş, sor û zer",
 "Mavi, beyaz ve kırmızı": "şîn, spî û sor",
 "Kırmızı, beyaz ve yeşil": "sor, spî û kesk",
 "Yeşil, sarı ve mor": "kesk, zer û mor",
 "Kırmızı, yeşil ve sarı": "sor, kesk û zer",

 # ── İkinci geçiş (2026-07-24) ──
 "19. yüzyılda özerklik mücadelesi veren Kürt emiri": "mîrê kurd ê ku di sedsala 19em de têkoşîna xweseriyê da",
 "1927-1930 yılları arasında Ağrı dağı çevresindeki direniş": "berxwedana derdora Çiyayê Agirî ya di navbera 1927-1930î de",
 "Akdeniz'e yakın Kürt bölgelerinde görülen iklim": "avhewaya ku li herêmên kurdî yên nêzî Behra Spî tê dîtin",
 "Ankara Savaşı": "Şerê Enqereyê",
 "Antep (Gaziantep)": "Entab",
 "Araplar": "Ereb",
 "Azerbaycan/Tebriz çevresi": "Azerbaycan/derdora Tebrîzê",
 "Aşiretlerden oluşturulan süvari birlikleri": "yekîneyên siwar ên ku ji eşîretan hatibûn pêkanîn",
 "Bahdinan bölgesinin sevilen devrimci müzisyeni": "muzîkjenê şoreşger ê hezkirî yê herêma Behdînan",
 "Batı İran / Zagros çevresi": "rojavayê Îranê / derdora Zagrosê",
 "Bereketli Hilal/Mezopotamya": "Hîlala Bibereket/Mezopotamya",
 "Beyşehir Gölü": "Gola Beyşehîrê",
 "Birçok yazarın yurt dışında üretmesi nedeniyle": "ji ber ku gelek nivîskar li derveyî welêt berhem didin",
 "Botan çayının oluşturduğu derin kanyon vadi": "geliyê kanyonê yê kûr ê ku çemê Botan ava kiriye",
 "Botan/Cizre bölgesi (güneydoğu)": "herêma Botan/Cizîrê",
 "Cizre merkezli önemli Kürt beyliği": "mîrektiya kurd a girîng a bi navenda Cizîrê",
 "Deniz kızı efsanesi": "efsaneya keça deryayê",
 "Dev kuş efsanesi": "efsaneya teyrê dêw",
 "Diyala nehri üzerinde kurulmuş baraj gölü": "gola bendavê ya ku li ser çemê Diyalayê hatiye avakirin",
 "Diyarbakır merkezli ortaçağ Kürt hanedanlığı": "xanedaniya kurd a serdema navîn a bi navenda Amedê",
 "Diyarbakır ovasında yer alan yayvan bazaltik volkan": "volkana bazaltî ya berfireh a li deşta Amedê",
 "Döneminden kalan belge veya nesne (birincil kaynak)": "belge an tiştê ku ji wê serdemê maye (çavkaniya yekemîn)",
 "Ekşili/etli sebze yemeği veya yahni": "xwarina sebzeyê ya bi tirş/goşt an yaxnî",
 "Erbil": "Hewlêr",
 "Erbil (Hewlêr)": "Hewlêr",
 "Erivan'da uzun yıllar basılan Kürtçe gazete": "rojnameya kurdî ya ku bi salan li Erîvanê hat çapkirin",
 "Eğirdir Gölü": "Gola Egîrdîrê",
 "Güney (Irak Kürdistanı)": "Başûr (Kurdistana Iraqê)",
 "Hakkari emirliğinde yetişmiş klasik divan şairi": "helbestvanê dîwana klasîk ê ku li mîrektiya Colemêrgê perwerde bû",
 "Hawar dergisini çıkaran edebi ekolün kurucusu": "damezrînerê ekola wêjeyî ya ku kovara Hawarê derxist",
 "Haçlı seferlerine karşı mücadele": "têkoşîna li dijî seferên xaçparêzan",
 "Hoybun cemiyeti adına askeri liderlik yapan subay": "efserê ku bi navê komeleya Xoybûnê serokatiya leşkerî kir",
 "Hıttin Savaşı (1187)": "Şerê Hittînê (1187)",
 "Irak (Duhok çevresi)": "Iraq (derdora Dihokê)",
 "Irak Cumhurbaşkanı": "Serokkomarê Iraqê",
 "Irak Kürt ulusal hareketi": "tevgera neteweyî ya kurdên Iraqê",
 "Irak rejimi tarafından Kürtlere yönelik soykırım": "jenosîda ku rejîma Iraqê li dijî kurdan pêk anî",
 "Irak'ta kendini Kürdistan kralı ilan eden lider": "serokê ku li Iraqê xwe wek qralê Kurdistanê ragihand",
 "Irak-Suriye": "Iraq-Sûriye",
 "KYB (Kürdistan Yurtseverler Birliği)": "YNK (Yekîtiya Nîştimanî ya Kurdistanê)",
 "Kafkasya (Gence-Ani çevresi)": "Kafkasya (derdora Gence-Aniyê)",
 "Kahve likörü": "lîkora qehweyê",
 "Kanatlı at efsanesi": "efsaneya hespê bibask",
 "Kerkük": "Kerkûk",
 "Klasik Kürt şiiri": "helbesta klasîk a kurdî",
 "Kürdistan coğrafyasını baştan başa bölen dağlar": "çiyayên ku erdnîgariya Kurdistanê ji serî heta binî parçe dikin",
 "Kürdistan coğrafyasının kuzeybatı yüksek kesimi": "beşa bilind a bakurê rojavayê erdnîgariya Kurdistanê",
 "Kürt coğrafyasındaki dağlar": "çiyayên li erdnîgariya kurdî",
 "Kürt coğrafyasını dört devlete bölen antlaşma": "peymana ku erdnîgariya kurdî li çar dewletan parve kir",
 "Kürt halkının ulusal duygularını seslendiren ozan": "dengbêjê ku hestên neteweyî yên gelê kurd dianî ziman",
 "Kürt kökenli, dünya çapında tanınan usta romancı": "romannivîsê hoste yê bi eslê xwe kurd ê ku li cîhanê tê naskirin",
 "Kürt sözlü müziğini derleyen Ermeni asıllı dengbêj": "dengbêjê bi eslê xwe ermenî yê ku muzîka devkî ya kurdî berhev kir",
 "Kürt tasavvuf şiirinin klasik divan şairi": "helbestvanê dîwana klasîk ê helbesta tesewufî ya kurdî",
 "Kürtler": "Kurd",
 "Kürtlerin 'şahê dengbêjan' dediği güçlü ses": "dengê bihêz ê ku kurd jê re dibêjin 'şahê dengbêjan'",
 "Kürtçe şarkılarıyla tanınan Ermeni asıllı usta müzisyen": "muzîkjenê hoste yê bi eslê xwe ermenî yê ku bi stranên kurdî tê naskirin",
 "Kış / Aralık": "zivistan / Berfanbar",
 "Latin temelli Kürt alfabesinin yaygınlaşması": "belavbûna alfabeya kurdî ya bi bingehê latînî",
 "Lozan (1923)": "Lozan (1923)",
 "Mahabad Kürt Cumhuriyeti'nin cumhurbaşkanı": "serokkomarê Komara Kurd a Mehabadê",
 "Maraş (Kahramanmaraş)": "Meraş",
 "Med İmparatorluğu (Pers öncesi)": "Împeratoriya Medan (berî Faris)",
 "Medrese öğrencisi/talebe": "xwendekarê medreseyê / feqî",
 "Merkezî yönetime bağlanmış / tasfiye edilmiş yapı": "avahiya ku bi rêveberiya navendî ve hat girêdan / hat rakirin",
 "Musul": "Mûsil",
 "Mısır unu": "arê garisê",
 "Osmanlı döneminde özerk kalmış Kürt hükümdarlığı": "hukumdariya kurd a ku di serdema Osmanî de xweser mabû",
 "Ravanduz merkezli askeri güç biriktiren beylik": "mîrektiya bi navenda Rewandizê ya ku hêza leşkerî berhev kir",
 "Riha (Urfa)": "Riha",
 "Sadece limon kabuğu": "tenê qalikê lîmonê",
 "Selahaddin Eyyubi tarafından kurulan büyük devlet": "dewleta mezin a ku Selahedînê Eyûbî damezrand",
 "Sonbahar / Eylül": "payîz / Îlon",
 "Soran emirliğinin kör lakaplı güçlü lideri": "serokê bihêz ê mîrektiya Soranê yê bi leqeba kor",
 "Sorani Kürtçe şiirinde modernleşmenin öncüsü": "pêşengê nûjenbûnê di helbesta kurdî ya soranî de",
 "Süleymaniye": "Silêmanî",
 "Süleymaniye güneyindeki tarihi verimli düzlük": "deşta dîrokî ya bibereket a li başûrê Silêmaniyê",
 "Süleymaniye yakınlarında yer alan yapay baraj gölü": "gola bendavê ya çêkirî ya li nêzî Silêmaniyê",
 "Süryaniler": "Suryanî",
 "Telli": "têlî",
 "Tuz Gölü": "Gola Xwê",
 "Türkiye-Suriye": "Tirkiye-Sûriye",
 "Türkmenler": "Tirkmen",
 "Van Gölü": "Gola Wanê",
 "Van gölü güneyinde hüküm sürmüş Kürt beyliği": "mîrektiya kurd a ku li başûrê Gola Wanê hukum kir",
 "Vurmalı": "lêdanê",
 "Yaylı": "kevanî",
 "Yaz / Temmuz": "havîn / Tîrmeh",
 "Yaşlıları/ihtiyarları": "kal û pîran",
 "Yoğurt/ayran": "mast/dew",
 "Yukarı Mezopotamya": "Mezopotamyaya Jorîn",
 "ana düşünce": "ramana sereke",
 "antik çağda Zagros merkezli büyük güç": "hêza mezin a serdema kevnar a bi navenda Zagrosê",
 "ağıtlar": "şînî",
 "besteci": "bestekar",
 "bilmeceler": "tiştonek",
 "dansçı": "reqas",
 "davulcu": "deflêder",
 "destanlar": "destan",
 "erbane veya defi ustalıkla çalan ritim sanatçısı": "hunermendê rîtmê yê ku erbane an defê bi hostatî lê dide",
 "fıkralar": "pêkenok",
 "kahramanlık anlatısı": "vegotina lehengiyê",
 "kanıtlardan anlam çıkarma": "ji delîlan wate derxistin",
 "kilamların okunduğu serbest ritimli vokal tarzı": "şêwaza dengî ya bi rîtma azad a ku kilam pê tên gotin",
 "klasik Bahdinan müziğinin efsanevi sesi": "dengê efsanewî yê muzîka klasîk a Behdînan",
 "maddi kalıntılarla geçmişi araştırma": "lêkolîna borî bi rêya bermahiyên maddî",
 "mevsimlik ritüel": "rîtûela demsalî",
 "modern Kürt şiirinin öncü toplumcu şairi": "helbestvanê civakî yê pêşeng ê helbesta kurdî ya nûjen",
 "müzisyenlere para atarak taltif etme adeti": "edeta ku ji muzîkjenan re pere tê avêtin",
 "müziğin temelini oluşturan düzenli vuruşlar": "lêdanên birêkûpêk ên ku bingeha muzîkê ne",
 "ninniler": "lorî",
 "olayları zaman sırasına koyma": "rêzkirina bûyeran li gorî demê",
 "seslerin ardışık dizilmesiyle oluşan ezgi": "avaza ku ji rêzbûna dengan pêk tê",
 "tandırda pişirilen geleneksel ekmek": "nanê kevneşopî yê ku di tenûrê de tê patin",
 "toplumların birbirini etkilemesi": "bandorkirina civakan li hev",
 "toplumsal dayanışma": "hevgirtina civakî",
 "usta-çırak ilişkisiyle yürüyen müzikal aktarım": "veguhastina muzîkal a bi têkiliya hoste-şagird",
 "uzun anlatı": "vegotina dirêj",
 "yaşanmış ilginç olayların anlatımı": "vegotina bûyerên balkêş ên jiyayî",
 "Üflemeli": "pifê",
 "İlkbahar / Mart": "bihar / Adar",
 "İran-Irak": "Îran-Iraq",
 "İran-Türkiye": "Îran-Tirkiye",
 "İran’daki Kürt bölgesi": "herêma kurdî ya li Îranê",
 "Şahmaran": "Şahmaran",
 "Şeref Han (Bitlis beyi)": "Şerefxan (mîrê Bidlîsê)",
 "Şeref Han Bitlisi": "Şerefxanê Bidlîsî",
 "Şeref Han tarafından yazılan Kürt tarihi eseri": "berhema dîroka kurdan a ku Şerefxan nivîsî",
 "şarkıcı": "stranbêj",
 "Selahaddin Eyyubi": "Selahedînê Eyûbî",
}


def main():
    path = 'assets/data/offline_questions.json'
    data = json.load(open(path))
    changed_q = 0
    changed_s = 0
    collisions = 0
    for q in data:
        answers = list(q['answers'])
        correct = q['correctAnswer']
        new = [TR2KU.get(a, a) for a in answers]
        if new == answers:
            continue
        if len(set(new)) != len(new):
            collisions += 1
            continue
        idx = answers.index(correct)
        q['answers'] = new
        q['correctAnswer'] = new[idx]
        changed_q += 1
        changed_s += sum(1 for a, b in zip(answers, new) if a != b)
    json.dump(data, open(path, 'w'), ensure_ascii=False, indent=2)
    print('çevrilen soru:', changed_q)
    print('çevrilen şık:', changed_s)
    print('çakışma nedeniyle atlanan soru:', collisions)


if __name__ == '__main__':
    main()
