-- Hareket basın-yayın ve kitap kaynaklarından üretilen sekizinci el yazımı paket.
-- Canlı yayın için onaylanmadı.
insert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values
((select id from public.categories where name = 'Ziman'), 'ku-kmr', 'Li gorî arşîva Hawarê, hejmara yekem a kovarê kengî derket?', '15ê Gulana 1932an.', '22ê Nîsana 1898an.', '19ê Tîrmeha 2012an.', '1ê Çileya 1942an.', 'A', 'Arşîva Hawarê hejmara yekem di 15ê Gulana 1932an de li Şamê dide tomar kirin.', 2, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8'),
((select id from public.categories where name = 'Ziman'), 'ku-kmr', 'Di hejmara yekem a Hawarê de, armanca kovarê ji bo zimanê Kurmancî çi bû?', 'Belavkirin û hînkirina alfabeya nû û nivîsandina lêkolînên li ser ziman.', 'Rakirina hemû nivîsên Kurmancî ji çapemeniyê.', 'Bikaranîna tenê alfabeya erebî bê guherîn.', 'Çapkirina tenê nivîsarên aborî.', 'A', 'Arşîvê dibêje ku Hawar dixwest alfabeya nû belav bike û li ser ziman, wêje, adet, dîrok û erdnîgariyê lêkolîn bike.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8'),
((select id from public.categories where name = 'Edebiyat'), 'ku-kmr', 'Pirtûka Revolution in Rojava: Democratic Autonomy and Women’s Liberation cara yekem kengî hatiye weşandin?', 'Di Mijdara 2016an de.', 'Di Gulana 1932an de.', 'Di Nîsana 1898an de.', 'Di Tîrmeha 2022an de.', 'A', 'Danasîna pirtûkê li ser malpera David Graeber dide nîşandan ku weşana yekem di 15ê Mijdara 2016an de bû.', 2, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8'),
((select id from public.categories where name = 'Edebiyat'), 'ku-kmr', 'Di danasîna pirtûka Women in the Kurdish Movement de, kîjan sê peyv di sernavê de tên bikaranîn?', 'Dayik, heval û xwedawend.', 'Ziman, çiya û arşîv.', 'Kovar, ferheng û alfabe.', 'Ekolojî, aborî û dîroka çapemeniyê.', 'A', 'Sernavê pirtûkê bi sê peyvên Mothers, Comrades, Goddesses rola û nasnameyên cuda yên jinan di tevgerê de nîşan dide.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8'),
((select id from public.categories where name = 'Dîrok'), 'ku-kmr', 'Li gorî arşîva Hawarê, kovar piştî 1935an kengî dîsa dest bi weşandinê kir?', 'Di sala 1941an de.', 'Di sala 1898an de.', 'Di sala 1963an de.', 'Di sala 2025an de.', 'A', 'Hawar di navbera 1932 û 1935an de hat weşandin û piştî navberekê di sala 1941an de dîsa dest pê kir.', 2, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8'),
((select id from public.categories where name = 'Dîrok'), 'ku-kmr', 'Di gotûbêja li ser Jineolojî de, li gorî Cambridge, kovara Jineolojî ji kîjan salê ve tê weşandin?', 'Ji sala 2016an ve.', 'Ji sala 1941an ve.', 'Ji sala 1898an ve.', 'Ji sala 2005an ve.', 'A', 'Chaptersa Cambridge kovara Jineolojî wekî kovareke ku ji sala 2016an ve tê weşandin dide naskirin.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8'),
((select id from public.categories where name = 'Çand'), 'ku-kmr', 'Hawar di gotina xwe ya destpêkê de xwe bi kîjan dengî dide nasîn?', 'Wekî dengê zanînê, ne wekî organa partî an rêxistinek siyasî.', 'Wekî organa fermî ya yek partiyê.', 'Wekî kovareke tenê ji bo bazirganiyê.', 'Wekî arşîva tenê ya şer û çekan.', 'A', 'Arşîva Hawarê destnîşan dike ku kovar xwe wekî dengê zanînê dide nasîn û dixwest ji dengê partî an rêxistina siyasî cuda bimîne.', 2, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8'),
((select id from public.categories where name = 'Çand'), 'ku-kmr', 'Di lîsteya Jineolojî Dergisî de, kîjan dosya li ser têkiliya başî û estetîkê di jiyana civakî de raweste?', 'Etîk-estetîk I û II.', 'Tenê demografî.', 'Tenê Rojhilat û Bakur.', 'Tenê izolasyon û girtin.', 'A', 'Lîsteya kovarê du dosyayên etîk-estetîk dide nîşandan ku li ser başî, xweşî, ziman, kirin û teorî rawestin.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8'),
((select id from public.categories where name = 'Siyaset'), 'ku-kmr', 'The Sociology of Freedom li gorî danasîna weşangerê, beşa kîjan berhemê ye?', 'Cildê sêyem ê Manifestoya Şaristaniya Demokratîk.', 'Cildê yekem ê ferhengoka Hawarê.', 'Pêveka wêneyî ya Ronahî.', 'Cildê duyem ê pirtûka Women in the Kurdish Movement.', 'A', 'Independent Publishers Group The Sociology of Freedom wekî cildê sêyem ê berhema pênc-cildî ya Manifestoya Şaristaniya Demokratîk dide naskirin.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8'),
((select id from public.categories where name = 'Siyaset'), 'ku-kmr', 'Di sernavê pirtûka The Political Thought of Abdullah Öcalan de, «konfederalîzma demokratîk» bi kîjan mijaran re tê danîn?', 'Bi Kurdistan û şoreşa jinê re.', 'Bi Hawar û Ronahî re.', 'Bi geologyaya Zagrosê re.', 'Bi ferhengoka Nûbihara Biçûkan re.', 'A', 'Sernavê pirtûkê Kurdistan, şoreşa jinê û konfederalîzma demokratîk bi hev re dide nîşandan.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8'),
((select id from public.categories where name = 'Paradigma'), 'ku-kmr', 'Di danasîna The Sociology of Freedom de, kîjan qadên fikirê wekî mijarên sereke tên lîstekirin?', 'Hebûn û azadî, xweza û felsefe, anarsîzm û ekolojî.', 'Tenê alfabeya Hawarê û dîroka Ronahî.', 'Tenê muzîka dengbêjî û govend.', 'Tenê aboriya bazirganiyê û nivîsandina ferhengê.', 'A', 'Danasîna weşangerê mijarên hebûn û azadî, xweza û felsefe, anarsîzm û ekolojî wekî qadên fikirê dide naskirin.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8'),
((select id from public.categories where name = 'Paradigma'), 'ku-kmr', 'Li gorî lêkolîna Cambridge, Jineolojî di nav çi pêvajoyê de tê dîtin?', 'Di pêvajoya hilberîna zanîna femînîst û avakirina civakeke wekhev de.', 'Di pêvajoya rakirina zanînê ji civakê de.', 'Di pêvajoya dabeşkirina alfabeyan de.', 'Di pêvajoya tenê parastina arşîvan de.', 'A', 'Lêkolîna Cambridge Jineolojî bi hilberîna zanîna femînîst û hewildana avakirina civakeke wekhev re têkildar dike.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_8');
