-- Genel kültür, dünya hareketleri, halklar ve dillerden üretilen ilk paket.
-- Canlı yayın için onaylanmadı.
insert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values
((select id from public.categories where name = 'Ziman'), 'ku-kmr', 'Kîjan rêza zimanên fermî yên Neteweyên Yekbûyî rast e?', 'Erebî, Çînî, Îngilîzî, Fransî, Rûsî û Spanî.', 'Kurmancî, Soranî, Zazakî, Erebî, Îngilîzî û Fransî.', 'Latînî, Yewnanî, Farsî, Erebî, Rûsî û Çînî.', 'Îngilîzî, Almanî, Îtalî, Spanî, Japonî û Hindî.', 'A', 'Li gorî malpera Neteweyên Yekbûyî, şeş zimanên fermî Erebî, Çînî, Îngilîzî, Fransî, Rûsî û Spanî ne.', 1, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Ziman'), 'ku-kmr', 'Li gorî UNESCO, ziman di kevneşopiyên devkî de kîjan erkê girîng dike?', 'Wekî amûrekî veguhastina zanîn, nirxên civakî û bîranîna komî.', 'Wekî amûrekî ku çîrokên devkî ji civakê cuda dike.', 'Wekî şertê ku hemû çîrok tenê bi nivîsê werin vegotin.', 'Wekî navê yekîneyeke siyasî ya navneteweyî.', 'A', 'UNESCO dibêje kevneşopiyên devkî û ziman zanîn, nirxên civakî û bîranîna komî ji nifşekê bo nifşekî din digihînin.', 2, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Dîrok'), 'ku-kmr', 'Di Şoreşa Fransayê de, Danezana Mafên Mirov û Welatiyê di kîjan salê de hate pejirandin?', '1789an.', '1804an.', '1917an.', '1945an.', 'A', 'Danezana Mafên Mirov û Welatiyê di çarçoveya Şoreşa Fransayê de di sala 1789an de hate pejirandin.', 2, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Dîrok'), 'ku-kmr', 'Şoreşa Haîtî çi wekî encameke dîrokî girîng dide nîşandan?', 'Serhildana bi ser ketî ya koleyan li dijî serdestîya kolonyalî ya Fransayê û damezrandina Haîtî ya serbixwe di 1804an de.', 'Girtina Stenbolê ji aliyê Fransayê ve di 1789an de.', 'Damezrandina Neteweyên Yekbûyî di 1945an de.', 'Guherîna alfabeya Hawarê di 1932an de.', 'A', 'Şoreşa Haîtî ji 1791 heta 1804 dom kir û bi serketina serhildana koleyan û serxwebûna Haîtî re encam da.', 3, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Dîrok'), 'ku-kmr', 'Meşa Xwê ya Gandhi di sala 1930an de li dijî kîjan polîtîkayê bû?', 'Li dijî monopola û bacê xwê ya hukûmeta Brîtanyayê li Hindistanê.', 'Li dijî qedexeya zimanên herêmî ya UNESCO.', 'Li dijî avakirina Neteweyên Yekbûyî.', 'Li dijî weşandina kovara Hawarê.', 'A', 'Meşa Xwê çalakiyeke ne-şîddetî ya neobedîya medenî bû ku monopola xwê û bacê ya Brîtanyayê li Hindistanê dike hedef.', 2, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Dîrok'), 'ku-kmr', 'Di tevgera serxwebûna Hindistanê de, «neobedîya medenî» bi kîjan awayî tê fêmkirin?', 'Bi redkirina çalak a qanûnên adaletsiz û bi protestoya civakî, bi girîngiya rêbaza ne-şîddetî di hin qonaxan de.', 'Bi qebûlkirina bê şert a hemû qanûnên kolonyalî.', 'Bi rakirina hemû çalakiyên civakî ji tevgerê.', 'Bi tenê bi weşandina pirtûkên edebî.', 'A', 'Di çalakiyên serxwebûna Hindistanê de neobedîya medenî redkirina çalak a qanûnên kolonyalî bû; rêbaza ne-şîddetî di gelek qonaxan de girîng bû.', 3, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Cografya'), 'ku-kmr', 'Haîtî li ser kîjan giravê ye?', 'Li ser girava Hispaniola, di Karayîbê de.', 'Li ser girava Sicilia, di Deryaya Spî de.', 'Li ser girava Java, di Asyayê de.', 'Li ser girava Sakhalin, di Okyanûsa Pasîfîk de.', 'A', 'Haîtî li beşa rojavayî ya girava Hispaniola ya li Karayîbê ye; beşa rojhilatê giravê Komara Domînîkanê ye.', 2, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Cografya'), 'ku-kmr', 'Di çarçoveya UNESCO de, çima kevneşopiyên komên cuda bi heman navê «mirasê devkî» dikarin bên dîtin?', 'Ji ber ku mirasê devkî dikare di nav komên cuda de were parvekirin, were adaptekirin û bi nifşan re biguhere.', 'Ji ber ku UNESCO tenê mirasa yek welatê qebûl dike.', 'Ji ber ku kevneşopî divê her tim heman formê biparêze.', 'Ji ber ku mirasê devkî tenê li bajarên mezin heye.', 'A', 'UNESCO mirasa bê-maddî wekî tiştekî dinamik û berfireh dide pênasekirin ku dikare di nav komên cuda de were parvekirin û biguhere.', 2, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Çand'), 'ku-kmr', 'Li gorî UNESCO, kîjan yek ji qadên mirasa bê-maddî ye?', 'Kevneşopiyên devkî û hunerên performansê.', 'Tenê avahiyên kevirî yên kevn.', 'Tenê arşîvên dewletê.', 'Tenê pere û amûrên bazirganiyê.', 'A', 'UNESCO di nav qadên mirasa bê-maddî de kevneşopiyên devkî, hunerên performansê, pratîkên civakî, zanînên li ser xwezayê û hunera destkariyê dide hejmartin.', 2, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Çand'), 'ku-kmr', 'Li gorî UNESCO, çi taybetmendî mirasa bê-maddî ji miraseke tenê muze-yê cuda dike?', 'Ew di jiyanê de tê domandin, diguhere û ji nifşekê bo nifşekî din tê veguhastin.', 'Ew divê her tim bê guherîn bimîne.', 'Ew tenê li ser dîroka padîşahan raweste.', 'Ew tenê bi tiştên maddî tê pênasekirin.', 'A', 'UNESCO mirasa bê-maddî wekî miraseke zindî dide pênasekirin ku di veguhastinê de diguhere û di jiyana rojane ya koman de wate digire.', 3, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Muzîk'), 'ku-kmr', 'Li gorî UNESCO, stran û helbestên destanî di kîjan qadê de dikarin cih bigirin?', 'Di kevneşopiyên devkî û hunerên performansê de.', 'Tenê di arşîvên siyasî de.', 'Tenê di qadên geologyayê de.', 'Tenê di ferhengên aborî de.', 'A', 'UNESCO di nav kevneşopiyên devkî de stran, helbestên destanî, çîrok, lavik û performansên devkî dide nîşandan.', 2, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Muzîk'), 'ku-kmr', 'Di mirasa bê-maddî de, çima performansa stranekê tenê bi nivîsa wê nayê pîvan?', 'Ji ber ku deng, awayê gotinê, hereket, têkiliya hunermend û temaşevanan jî beşên performansê ne.', 'Ji ber ku nivîs û deng di hemû çandan de heman tişt in.', 'Ji ber ku stran divê bê temaşevan bê pêşkêşkirin.', 'Ji ber ku UNESCO hunerên performansê qebûl nake.', 'A', 'UNESCO balê dikişîne ser pêvajoya performansê û dibêje ku deng, intonasyon, hereket û têkiliya performêr û temaşevanan dikarin beşên mirasê bin.', 3, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Siyaset'), 'ku-kmr', 'Di rêxistina Neteweyên Yekbûyî de, zimanpirrî çi armancê alîkar dike?', 'Beşdarbûna wekhev û têgihiştina zelal di nav dewletên cuda de.', 'Kêmkirina hewcedariya wergerê bi rakirina zimanên din.', 'Hilbijartina yek ziman wekî zimanê hemû gelan.', 'Qedexekirina axaftina zimanên nefermî.', 'A', 'Neteweyên Yekbûyî dibêje zimanpirrî têgihiştin, tolerans û beşdarbûna dewletên endam di karê rêxistinê de zêde dike.', 2, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Siyaset'), 'ku-kmr', 'Di danezanê mafên mirovan a Şoreşa Fransayê de, kîjan têgeh bi taybetî tê pêşxistin?', 'Azadî û wekheviya mafan.', 'Serweriya kolonyalî û dabeşkirina nijadî.', 'Qanûna monopola xwê.', 'Rakirina zimanpirrî ji rêxistinên navneteweyî.', 'A', 'Danezana 1789an maf û azadiyê di nav têgehên bingehîn ên xwe de dixe pêş; ew nivîs di dîroka mafên mirovan de girîng e.', 3, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Paradigma'), 'ku-kmr', 'Çima divê Şoreşa Haîtî tenê wekî şerê serxwebûnê neyê xwendin?', 'Ji ber ku ew bi li dijî kolederiyê, serdestîya kolonyalî û mafên mirovan re jî têkildar bû.', 'Ji ber ku ew qet bi ser neket.', 'Ji ber ku ew tenê guhertina alfabeyê bû.', 'Ji ber ku ew tenê tevgera hunerî bû.', 'A', 'Şoreşa Haîtî hem li dijî serdestîya kolonyalî hem li dijî kolederiyê bû; ji ber vê yekê tenê bi serxwebûnê sînordar kirina wê kêm e.', 3, false, 'multiple_choice', NULL, 'general_culture_question_wave_1'),
((select id from public.categories where name = 'Paradigma'), 'ku-kmr', 'Di xwendina tevgerên gelan de, çima divê rêbaz û şertên her tevgerê ji hev bên veqetandin?', 'Ji ber ku dîrok, şertên civakî, armanc û rêbazên wan dikarin cuda bin.', 'Ji ber ku hemû tevgerên gelan heman encam û heman rêbaz hene.', 'Ji ber ku şertên herêmî di dîrokê de qet bandor nakin.', 'Ji ber ku tenê navê rêberê tevgerê dikare hemû tişt rave bike.', 'A', 'Lêkolîna tevgerên gelan divê şertên dîrokî, armanc, rêbaz û dengên komên cuda li ber çavan bigire; yek model ji bo hemû tevgeran kêm e.', 3, false, 'multiple_choice', NULL, 'general_culture_question_wave_1');
