-- İlk el yazımı soru paketi: 16 soru, her kategoriye iki soru.
-- is_approved bilerek false bırakıldı; canlı içeriğe alınmadan önce ikinci editoryal kontrol gerekir.
insert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values
((select id from public.categories where name = 'Ziman'), 'ku-kmr', 'Di kovara Hawarê de, piştî jimareya 23an çi guherî?', 'Kovara Hawarê bi tevahî rawestiya.', 'Hemû nivîs tenê bi alfabeya erebî hatin çapkirin.', 'Kovara Hawarê ji Şamê birêve çû Stenbolê.', 'Nivîsa Kurmancî tenê bi alfabeya latînî hate çapkirin.', 'D', 'Li gorî arşîva Hawarê, 23 jimareyên ewil bi her du alfabeyan hatin çapkirin; ji jimareya 24an ve kovar tenê alfabeya latînî bi kar anî.', 2, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Ziman'), 'ku-kmr', 'Li gorî lêkolîna li ser wêjeya nivîskî ya Kurdî, dibistana Kurmancî ya klasîk bi taybetî bi kîjan herêmê ve tê girêdan?', 'Herêma Jazira û Botan', 'Herêma Farsê ya navîn', 'Geliyê Nilê ya li Misrê', 'Giravên Egeyê', 'A', 'Lêkolîn dibêje ku dibistana Kurmancî ya klasîk zimanê edebî yê Jazira û Botan bikar aniye û navên wekî Melayê Cizîrî, Feqiyê Teyran û Ehmedê Xanî di nav pêşengên wê de ne.', 3, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Edebiyat'), 'ku-kmr', 'Kîjan taybetmendî forma helbestê ya Feqiyê Teyran girîng dike?', 'Ew yekem helbestvanê naskirî yê Kurdî ye ku ji bo helbestên vegotinê forma mesnewî bikar aniye.', 'Ew tenê nivîsarên rêzimanî di kovara Hawarê de diweşand.', 'Ew romana Mem û Zîn nivîsî.', 'Ew yekem nivîskarê Kurdî ye ku hemû berhemên xwe bi latînî nivîsî.', 'A', 'Encyclopaedia Iranica Feqiyê Teyran wekî yekem helbestvanê naskirî yê Kurdî dide nasîn ku forma mesnewî ji bo helbestên vegotinê bikar aniye.', 3, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Edebiyat'), 'ku-kmr', 'Berhema Nûbihara Biçûkan a Ehmedê Xanî bi çi awayî tê pênasekirin?', 'Destanek dirêj a li ser evîna Mem û Zînê', 'Ferhengokek bi helbestê ku peyvên erebî bi wateyên Kurmancî re dide hev.', 'Kovarek siyasî ya ku li Şamê dihat weşandin.', 'Dîwanek tenê ji gazelên Melayê Cizîrî pêkhatî.', 'B', 'Nûbihara Biçûkan ferhengokeke erebî-Kurmancî ye ku bi helbestê hatiye nivîsandin û ji bo xwendekarên dibistanê hatiye armanc kirin.', 2, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Dîrok'), 'ku-kmr', 'Dîroka weşandina Hawarê kîjan rêzê rast nîşan dide?', '1932–1935, paşê 1941–1943', '1898–1902, paşê 1910–1912', '1946–1950, paşê 1960–1963', '1919–1923 bê rawestan', 'A', 'Hawar li Şamê di navbera 1932 û 1935an de, û piştî navberekê dîsa di navbera 1941 û 1943an de hate weşandin.', 2, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Dîrok'), 'ku-kmr', 'Rojnameya Kurdistanê ya ku di sala 1898an de dest pê kir, li ku derê hat weşandin û kî wê damezrand?', 'Li Qahîreyê, ji aliyê Mîqdat Midhat Bedirxan ve', 'Li Şamê, ji aliyê Celadet Bedirxan ve', 'Li Silêmaniyê, ji aliyê Pîremêrd ve', 'Li Stenbolê, ji aliyê Melayê Cizîrî ve', 'A', 'Rojnameya Kurdistanê di sala 1898an de li Qahîreyê ji aliyê Mîqdat Midhat Bedirxan ve hate destpêkirin.', 3, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Cografya'), 'ku-kmr', 'Di dîroka erdnîgariya îslamî de, navê Jibal bi kîjan herêmê re zêdetir tê girêdan?', 'Bi beşa navîn a zincîra Zagrosê, ku Kurdistan û Luristan dihewîne', 'Bi deşta Nilê ya li bakurê Afrîkayê', 'Bi herêma peravê ya li rojhilatê Deryaya Reş', 'Bi giravên ku li navbera Hindistan û Sri Lanka ne', 'A', 'Di bikaranîna dîrokî de Jibal navê herêmeke çiyayî û newalî bû ku beşa navîn a Zagrosê, di nav de Kurdistan û Luristan, dihewand.', 3, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Cografya'), 'ku-kmr', 'Kîjan agahî li ser Çiyayên Bahtiyarî rast e?', 'Ew beşek navîn a zincîra Zagrosê ne û Zardkûh li wan e.', 'Ew li navenda deşta Mezopotamyayê ne û çiyayên Zagrosê ji wan dûr in.', 'Ew navê çemekî ye ku ji Deryaya Reş derdikeve.', 'Ew zincîra çiyayên li bakurê Ewropayê ye.', 'A', 'Çiyayên Bahtiyarî beşa navîn û herî bilind a pergala Zagrosê pêk tînin; Zardkûh jî li vê pergala çiyayî ye.', 3, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Çand'), 'ku-kmr', 'Di çîroka populer a Memê Alan de, çima tê gotin ku wê çîrokê bi taybetî li herêmên Kurmancîaxê re têkildar e?', 'Ji ber ku gelek guhertoyên devkî yên çîrokê li wan herêman hatine tomarkirin.', 'Ji ber ku çîrok tenê di kovara Hawarê de hatiye nivîsandin.', 'Ji ber ku Memê Alan navê yek ji çiyayên Zagrosê ye.', 'Ji ber ku çîrok bi eslê xwe ferhengokeke erebî ye.', 'A', 'Lêkolînên li ser Memê Alan dibêjin ku di forma populer de ev romans bi taybetî bi herêmên Kurmancîaxê re tê girêdan; ew tenê berhemeke nivîskî nîne.', 3, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Çand'), 'ku-kmr', 'Dengbêjî di çanda devkî de bi kîjan erkê herî baş tê şirovekirin?', 'Bi veguhastina çîrok, destan, stran û bîranînan bi deng û gotinê', 'Bi nivîsandina hemû berhemên edebî bi yek alfabeyê', 'Bi amadekirina nexşeyên erdnîgarî ji bo rêwîtiyê', 'Bi komkirina tenê amûrên muzîkê yên kevn', 'A', 'Dengbêjî kevneşopiyeke devkî ye ku çîrok, destan, stran û bîranîn bi deng, vegotin û tomarkirina hafîzeyê digihîne nifşên din.', 2, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Muzîk'), 'ku-kmr', 'Di performansa dengbêj de kîjan taybetmendî bingehîn e, lê amûra muzîkê şert nîne?', 'Amûra muzîkê ya ku her tim li pey dengê stranbêj dikeve.', 'Vegotina bi deng, bi stran û bi gotinê.', 'Pêdiviya ku hemû stran tenê bi notayên nivîskî bêne pêşkêşkirin.', 'Bikaranîna orkestraya mezin di her performansê de.', 'B', 'Di kevneşopiya dengbêj de deng û vegotin bingeh in; hin performans dikarin bê amûrên muzîkê jî bêne kirin, ji ber vê yekê amûr şertê bingehîn nîne.', 2, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Muzîk'), 'ku-kmr', 'Di peyva «dengbêj» de, «deng» û «bej» bi kîjan wateyên bingehîn re têne girêdan?', 'Reng û dîtin', 'Deng û gotin', 'Çiya û av', 'Roj û şev', 'B', 'Di ravekirina peyvê de «deng» bi dengê mirovan, û «bej» bi gotin an vegotinê re tê girêdan; ev yek ji aliyên wateya dengbêjî ye.', 2, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Siyaset'), 'ku-kmr', 'Li gorî çarçoveya mafên mirovan, mafê beşdarbûna siyasî kîjan komê mafan dihewîne?', 'Tenê mafê dengdanê, bê mafê namzedbûnê', 'Beşdarbûna rasterast an bi nûnerên azad hilbijartî, dengdan û gihiştina wekhev bo karên giştî', 'Tenê mafê karê di sazîyekê de, bê mafê axaftinê', 'Tenê mafê endamtiya di partiyekê de, bê mafê dengdanê', 'B', 'OHCHR beşdarbûna siyasî bi beşdarbûna rasterast an bi nûneran, mafê dengdanê û mafê gihiştina wekhev bo karên xizmeta giştî ve girê dide.', 3, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Siyaset'), 'ku-kmr', 'Kîjan rewş mînakek ji beşdarbûna siyasî ya rasterast e?', 'Hemwelatiyek pêşniyarekê ji sazîya giştî re dişîne û di civînekî giştî de beşdar dibe.', 'Kesek tenê navê xwe di lîsteya stranên guhdarîkirî de dinivîse.', 'Kesek nexşeya malê xwe diguhezîne.', 'Kesek li ser dîroka malbata xwe dixwîne.', 'A', 'Beşdarbûna siyasî ya rasterast dikare bi daxwaz, pêşniyar, axaftina giştî, kombûn an çalakiyên aştiyane yên civakî bê kirin; ew tenê dengdan nîne.', 3, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Paradigma'), 'ku-kmr', 'Di analîza intersectionality de, çima tenê li ser yek cudahiyê, wekî zayendê, rawestan dikare kêmasî be?', 'Ji ber ku hemû kes di civakê de heman ezmûnê dijîn.', 'Ji ber ku şertên wekî zayend, nijad, çîn û seqemahî dikarin bi hev re bandorê li ezmûn û hêzê bikin.', 'Ji ber ku analîz divê tenê li ser dîroka dewletan be.', 'Ji ber ku cudahiyên civakî bi awayekî zanistî nayên lêkolînkirin.', 'B', 'Intersectionality dişopîne ka çawa gelek xetên nasname û tunekirinê bi hev re û ne tenê bi awayekî cudaye bandorê li jiyana mirovan dikin.', 3, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1'),
((select id from public.categories where name = 'Paradigma'), 'ku-kmr', 'Di felsefeya siyasî ya femînîst de, berfirehkirina qada «siyasetê» çi tê wate kirin?', 'Tenê karên parlamentoyê siyasî tên hesibandin.', 'Têkiliyên hêzê di civaka sivîl û malbatê de jî dikarin bibin mijara lêkolîna siyasî.', 'Siyaset ji her cure têkiliya civakî tamamen cuda ye.', 'Lêkolîn divê tenê li ser qanûnên aborî raweste.', 'B', 'Felsefeya siyasî ya femînîst balê dikişîne ser vê yekê ku hêz û rêveberî tenê di dewletê de nayên dîtin; civaka sivîl û qada malbatê jî dikarin têkiliyên hêzê hilberînin.', 3, false, 'multiple_choice', NULL, 'handcrafted_question_wave_1');
