-- Hareket basın-yayın kaynaklarından üretilen beşinci el yazımı paket.
-- Canlı yayın için onaylanmadı.
insert into public.questions (category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty, is_approved, question_type, image_url, source_url) values
((select id from public.categories where name = 'Ziman'), 'ku-kmr', 'Di lîsteya Jineolojî Dergisî de, «Rastiya jinê bingehê rêbazê ye» bi kîjan mijarê re tê girêdan?', 'Bi rêbazeke ku ezmûna jinan di hilberîna zanînê de dixe navendê.', 'Bi rêbazeke ku ezmûna jinan ji lêkolînê dûr dixe.', 'Bi rêbazeke ku ziman tenê wekî kodê teknîkî dibîne.', 'Bi rêbazeke ku dîrokê ji civakê cuda dike.', 'A', 'Navê dosyayê li ser rêbaz û rastiya jinan raweste; ev nîşan dide ku ezmûna jinan wekî çavkaniya zanînê tê dîtin.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5'),
((select id from public.categories where name = 'Ziman'), 'ku-kmr', 'Di dosyaya «Perwerdehiya zimanê jiyanê» de, ziman bi kîjan têgehê re têkildar tê xwendin?', 'Bi jiyan, perwerde û hilberîna zanînê re.', 'Bi tenê rêzikên alfabeyê bê jiyana civakî.', 'Bi tenê rêyên bazirganiyê.', 'Bi tenê dîroka çiyayên Zagrosê.', 'A', 'Navê dosyayê zimanê bi jiyan û perwerdehiya civakî re dide hev; ew zimanê wekî mijareke jêbirî nayê dîtin.', 2, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5'),
((select id from public.categories where name = 'Edebiyat'), 'ku-kmr', 'Di dosyaya «Jineolojî wekî xweparastinê» de, xweparastin çi tê wate kirin?', 'Tenê parastina leşkerî nîne; zanîn, rêxistin û parastina jiyanê jî dihewîne.', 'Tenê parastina arşîvan e.', 'Tenê parastina peyvên klasîk ên edebiyatê ye.', 'Tenê parastina mal û milkê kesane ye.', 'A', 'Lîsteya kovarê xweparastinê wekî mijareke Jineolojî dide nîşandan; di vê çarçoveyê de ew dikare zanîn, rêxistin û parastina jiyanê jî dihewîne.', 2, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5'),
((select id from public.categories where name = 'Edebiyat'), 'ku-kmr', 'Di pirtûka Women in the Kurdish Movement de, rola jinan di tevgerê de bi kîjan du aliyan re tê xwendin?', 'Bi dijberiya rolên ferzkirî û avakirina nasnameyên siyasî yên nû.', 'Bi tenê bi dabeşkirina navên bajar û çiyayan.', 'Bi tenê bi karê arşîvkirina wêneyan.', 'Bi tenê bi guherandina alfabeya kovaran.', 'A', 'Danasîna pirtûkê li ser jinên ku rolên li ser wan hatine ferz kirin diguherînin û di tevgera siyasî de nasnameyên xwe ava dikin raweste.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5'),
((select id from public.categories where name = 'Dîrok'), 'ku-kmr', 'Li gorî lîsteya dosyayên Jineolojî Dergisî, kîjan mijar bi perwerdehiya civakî re rasterast têkildar e?', 'Polîtîkayên perwerdehiyê.', 'Tenê dîroka ronahiyê.', 'Tenê geologyaya çiyan.', 'Tenê rêzikên çapkirina rojnameyan.', 'A', 'Di lîsteya kovarê de «Polîtîkayên perwerdehiyê» wekî dosyayeke cuda hatiye lîstekirin û mijara perwerdehiya civakî dixe pêş.', 2, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5'),
((select id from public.categories where name = 'Dîrok'), 'ku-kmr', 'Di lîsteya kovarê de, «Sedsala jinan» wekî çi tê pêşkêşkirin?', 'Wekî mijareke li ser rola jinan û dîroka civakî di sedsala 21an de.', 'Wekî navê kovara Hawarê ya sala 1932an.', 'Wekî navê yek ji çiyayên Rojava.', 'Wekî ferhengoka Ehmedê Xanî.', 'A', 'Dosyaya «Sedsala jinan» mijara jinan di sedsala 21an de dixe navendê; ew ne navê kovar, çiya an ferhengokê ye.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5'),
((select id from public.categories where name = 'Çand'), 'ku-kmr', 'Di dosyaya «Civîna azad; çima û çawa?» de, mijara sereke çi ye?', 'Çawa dikare jiyana hevpar li ser bingehên azadî û wekheviyê bê avakirin.', 'Çawa dikare tenê yek kom li ser hemû civakê biryar bide.', 'Çawa dikare kovar bêyî nivîskar bêne çapkirin.', 'Çawa dikare çiyayek bê nexşe bê pîvan.', 'A', 'Navê dosyayê pirsa çima û çawa ya civîna azad dike pêş; ev mijar li ser awayên jiyana hevpar û têkiliyên wekhev raweste.', 2, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5'),
((select id from public.categories where name = 'Çand'), 'ku-kmr', 'Di lîsteya Jineolojî Dergisî de, «krîza çandê» bi kîjan nêzîkatiyê re tê pêşkêşkirin?', 'Bi lêgerîna rêyên derketinê ji krîzê.', 'Bi qebûlkirina krîzê wekî tiştekî ku nayê lêkolînkirin.', 'Bi veguhastina krîza çandê bo mijara geologyayê.', 'Bi rakirina çandê ji her gotûbêjê.', 'A', 'Dîroka kovarê dosyayek bi navê «Krîza çandê û rêyên derketinê» dide naskirin; navê wê lêkolîn û çareseriyê bi hev re dike.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5'),
((select id from public.categories where name = 'Siyaset'), 'ku-kmr', 'Di lîsteya dosyayên Jineolojî Dergisî de, «siyaseta demokratîk» bi kîjan mijarê re dikare were xwendin?', 'Bi awayên beşdarbûn û biryargirtina civakê.', 'Bi tenê dîroka çapemeniyê.', 'Bi tenê teknîka stranbêjiyê.', 'Bi tenê şertên avhewaya herêmê.', 'A', 'Dosyaya siyaseta demokratîk di çarçoveya kovarê de bi mijarên civakî û rêxistinî re tê xwendin; beşdarbûn û biryargirtin du aliyên wê ne.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5'),
((select id from public.categories where name = 'Siyaset'), 'ku-kmr', '«Aboriya komunal a demokratîk» di lîsteya Jineolojî Dergisî de çi dide nîşandan?', 'Aboriyê wekî mijareke civakî û rêxistinkirina hevpar dide nîqaşkirin.', 'Aboriyê tenê wekî karê kesane dide pênasekirin.', 'Aboriyê ji ekolojî û civakê bi tevahî cuda dike.', 'Aboriyê tenê bi dîroka Hawarê re girê dide.', 'A', 'Navê dosyayê aboriya komunal û demokratîk bi hev re dide nîqaşkirin; ev nêzîkatî aboriyê di nav têkiliyên civakî de dixwîne.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5'),
((select id from public.categories where name = 'Paradigma'), 'ku-kmr', 'Di lîsteya Jineolojî Dergisî de, «jiyana ekolojîk» ji kîjan duduya têgehî re nêzîk e?', 'Ji têkiliya civakê, jinan û xwezayê re.', 'Ji têkiliya alfabeyê û hesabkirina bacan re.', 'Ji têkiliya dîroka Hawarê û muzîka klasîk re.', 'Ji têkiliya bajarên Ewropayê û ferhengokên erebî re.', 'A', 'Dosyaya jiyana ekolojîk di lîsteya kovarê de li kêleka dosyayên jin, civak û jiyanê tê dîtin; ev yek têkiliya civak û xwezayê dixe pêş.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5'),
((select id from public.categories where name = 'Paradigma'), 'ku-kmr', 'Di lîsteya kovarê de, «organîzekirina potansiyela azadiyê: tevgerên civakî» li ser çi raweste?', 'Li ser hêza rêxistin û tevgerên civakî ji bo avakirina azadiyê.', 'Li ser tenê pêvajoya çapkirina pirtûkekê.', 'Li ser tenê dabeşkirina navên çiyan.', 'Li ser tenê formên muzîka klasîk.', 'A', 'Navê dosyayê potansiyela azadiyê bi rêxistin û tevgerên civakî re girêdide; azadî li vir wekî pêvajoya hevpar tê xwendin.', 3, false, 'multiple_choice', NULL, 'movement_sources_question_wave_5');
