-- 2026-08-01: source-verified Kurmancî question wave.
-- Generated from the reviewed agent wave; the transaction aborts unless all 91
-- category joins and inserts are accounted for.
BEGIN;
SET LOCAL ROLE postgres;

CREATE TEMP TABLE _agent_question_wave_source (
  source_id text PRIMARY KEY,
  category_name text NOT NULL,
  language_code text NOT NULL,
  prompt text NOT NULL,
  option_a text NOT NULL,
  option_b text NOT NULL,
  option_c text NOT NULL,
  option_d text NOT NULL,
  correct_option text NOT NULL,
  explanation text NOT NULL,
  difficulty integer NOT NULL,
  source_url text NOT NULL
) ON COMMIT DROP;

INSERT INTO _agent_question_wave_source (
  source_id, category_name, language_code, prompt, option_a, option_b,
  option_c, option_d, correct_option, explanation, difficulty, source_url
) VALUES
('cografya_20260801_0001', 'Cografya', 'ku-kmr', 'Li gorî nivîsa Encyclopaedia Iranica, lêkolîna erdnasiya Îranê li ser kîjan sê mijaran disekine?', 'Avahiyên erdnasî, xeterên xwezayî û çavkaniyên xwezayî', 'Ziman, huner û mûzîk', 'Bazirganî, spor û perwerde', 'Dîroka şaredariyan, qanûn û aboriyê', 'A', 'Nivîs sê qadên sereke dide naskirin: avahiya erdnasî û cudabûna çiya û avê, xeterên xwezayî, û çavkaniyên erdnasî yên wekî madenan.', 1, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0002', 'Cografya', 'ku-kmr', 'Di aliyê erdnasî de Îran bi kîjan du taybetmendiyan tê danasîn?', 'Deryaya Qezwînê û deşta Hindistanê', 'Rêzeya çiyayên Tertiyerî ya Ewrûsyayê û platoya mezin a Îranî', 'Tenê çiyayên volkanîk û qada şor', 'Bajarên kevnar û şaxên bazirganiyê', 'B', 'Nivîs dibêje ku Îran hem beşek ji rêzeya çiyayên Tertiyerî ya Ewrûsyayê ye û hem jî platoyeke fireh a Îranî dihewîne.', 2, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0003', 'Cografya', 'ku-kmr', 'Kîjan du rêzeyên çiyayî di nivîsê de wekî hêmanên geologîk ên ciwan ên Îranê tên nîşandan?', 'Hindûkuş û Himalaya', 'Alp û And', 'Elborz û Zagros', 'Kawkaz û Karpat', 'C', 'Nivîs rêzeyên çiyayî yên Elborz û Zagrosê wekî hêmanên Tertiyerî yên geologîk ên ciwan dide naskirin.', 2, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0004', 'Cografya', 'ku-kmr', 'Bingehê Precambriyen ê ku di nivîsê de tê behskirin çi ye?', 'Rûberê avê yê deryaya Qezwînê', 'Herikîna heriyê di nav geliyekê de', 'Rêgezek ji bo veguhestina neftê', 'Parçeyek ji avahiyeke kevn a ku platoya Îranî li ser wê hatiye avakirin', 'D', 'Nivîs platoya Îranî bi komkirina bingehê Precambriyen ve girê dide û wê wekî avahiyeke geologîk a kevn dide ravekirin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0005', 'Cografya', 'ku-kmr', 'Li gorî dîtina nivîsê, Elborz û Îrana Navîn di warê çi de ji hev re girêdayîtir in?', 'Di stratigrafî û avahiyê de', 'Di ziman û edebiyatê de', 'Di bazirganiyê û rêyên deryayî de', 'Di avakirina bajarên nû de', 'A', 'Nivîs dibêje ku Elborz û Îrana Navîn di stratigrafî û avahiyê de ji ya ku berê dihate texmînkirin nêzîktir in.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0007', 'Cografya', 'ku-kmr', 'Qalindahiya navîn a sedimentên Îrana Navîn li gorî nivîsê çiqas e?', 'Nêzîkî 30 heta 40 metre', 'Nêzîkî 300 heta 400 metre', 'Nêzîkî 3 000 heta 4 000 metre', 'Zêdetirî 40 000 metre', 'C', 'Nivîs qalindahiya navîn a sedimentên Îrana Navîn bi 3 000 heta 4 000 metreyî dide diyarkirin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0010', 'Cografya', 'ku-kmr', 'Stöcklin di dabeşkirina avahiya geologîk a Îranê de çend herêmên avahiyê cuda dike?', 'Pênc herêm', 'Neh herêm', 'Heft herêm', 'Du herêm', 'B', 'Nivîs li gorî Stöcklin neh herêmên avahiyê dide lîstekirin؛ dabeşkirin ji deşta Şatt al-Arabê heta rêzeyên Makranê digihîje.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0011', 'Cografya', 'ku-kmr', 'Harrison di analîza geologîk a Îranê de çend herêmên avahiyê cuda dike?', 'Neh herêm', 'Çar herêm', 'Heşt herêm', 'Duazdeh herêm', 'C', 'Harrison di nivîsê de bi dabeşkirineke cuda heşt herêmên avahiyê dide naskirin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0012', 'Cografya', 'ku-kmr', 'Kîjan navnîşana li jêr yek ji pênc herêmên xwezayî yên Îranê ye?', 'Deryaya Baltîkê', 'Deşta Amazonyayê', 'Çiyayên Andê', 'Deştên kêmav ên deryaya Qezwînê', 'D', 'Nivîs pênc herêmên xwezayî dide naskirin û deştên kêmav ên deryaya Qezwînê yek ji wan in.', 2, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0015', 'Cografya', 'ku-kmr', 'Kîjan rêzeya çiyayî bi tevahî di avakirina astengiya geologîk a nav Îranê de roleke giring heye?', 'And û Alp', 'Ural û Kawkaz', 'Elborz û Zagros-Makran', 'Himalaya û Karakoram', 'C', 'Nivîs dibêje ku Elborz li bakur û Zagros-Makran li rojava û başûr astengiyeke geologîk û geomorfologîk çêdikin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0017', 'Cografya', 'ku-kmr', 'Qada Mezin a Kavîrê li gorî nivîsê ji bo çi taybet e?', 'Ji ber ku rûbera wê ji 200 000 km² mezintir e', 'Ji ber ku ew qada herî bilind a Îranê ye', 'Ji ber ku hemû avên wê ber bi deryayê ve diherikin', 'Ji ber ku tenê ji çiyayên volkanîk pêk tê', 'A', 'Nivîs Qada Mezin a Kavîrê wekî hewzeke hundirîn a ji 200 000 km² mezintir dide naskirin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0018', 'Cografya', 'ku-kmr', 'Rûbera Kavîrê Lûtê li gorî nivîsê nêzîkî çiqas e?', '16 616 km²', '166 160 km²', '1 661 km²', '1 661 600 km²', 'B', 'Nivîs rûbera Kavîrê Lûtê 166 160 km² dide nivîsandin û wê bi rêzeyên çiyayî yên cuda ve girê dide.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0020', 'Cografya', 'ku-kmr', 'Çalakiya erdhejî ya li Îranê di nivîsê de çawa tê nirxandin?', 'Ew tenê di dema zivistanê de çêdibe', 'Ew li Îranê qet nayê dîtin', 'Ew tenê li ser deryayê çêdibe', 'Ew pir caran çêdibe û dikare bandorên mezin li mirovan û jîngehê bike', 'D', 'Nivîs erdhejan li Îranê pir caran dibîne û balê dikişîne ser windabûna mirovan, mal û torên ragihandinê û encamên jîngehî.', 2, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0021', 'Cografya', 'ku-kmr', 'Herikîna heriyê û axa şil li gorî nivîsê di kîjan şertan de zêdetir xuya dibe?', 'Li ser axên heriyê yên şil û li cihên ku av û cemed têkel dibin', 'Tenê li ser zinarên hişk û zuha', 'Di nav qada bazirganiyê de', 'Li ser rûbera ku tu şilî tune ye', 'A', 'Nivîs dibêje ku herikînên heriyê û axê li axên heriyê yên şil û li depoyên ku av an cemed tê de hene hêsantir çêdibin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0024', 'Cografya', 'ku-kmr', 'Li gorî nivîsê, çavkaniyên madenî yên Îranê çawa belav bûne?', 'Tenê li bakurê welatê ne', 'Tenê li nav bajarên mezin in', 'Tenê li dora deryaya Qezwînê ne', 'Li seranserê welatê belav in', 'D', 'Nivîs dibêje ku dewlemendiya madenî bi geşedana erdnasî ve girêdayî ye û çavkaniyên madenî li seranserê welatê belav in.', 2, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0025', 'Cografya', 'ku-kmr', 'Kîjan kom ji çavkaniyên erdnasî re di nivîsê de ji hêla aborî ve giringtir tê hesibandin?', 'Köm, neft û gaz', 'Qûm, heriyê û ax', 'Dar, gîha û berf', 'Sangê sivik, av û bayê', 'A', 'Nivîs dibêje ku ji bilî kömê, neft û gazê, madencî li gelek deveran aboriya kêm girîngtir heye.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0027', 'Cografya', 'ku-kmr', 'Madenên Bafqê ji bo kîjan navenda pîşesaziya hesinê girîng in?', 'Kargeha Çimentoyê ya Şîrazê', 'Benderê Bazirganî yê Tebrizê', 'Kargeha Poladê ya Îsfahanê', 'Navenda Neftê ya Makranê', 'C', 'Nivîs Bafqê wekî peydakerekî girîng ji bo Kargeha Poladê ya Îsfahanê dide naskirin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0028', 'Cografya', 'ku-kmr', 'Madenên misê li gorî nivîsê bi taybetî bi kîjan cûreya zinarê re têkildar in?', 'Zinarên qeşayî yên Antarktîkayê', 'Zinarên bazaltî yên deryaya Qezwînê', 'Zinarên şor ên deştê', 'Zinarên volkanîk ên Tertiyerî', 'D', 'Nivîs dibêje ku depoyên misê bi girîngî di herêmên zinarên volkanîk ên Tertiyerî de tên dîtin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0030', 'Cografya', 'ku-kmr', 'Depoyên ser û zincê li gorî nivîsê bi taybetî li kîjan beşa Îranê kom dibin?', 'Tenê li deştên Qezwînê de', 'Di Îrana Navîn de', 'Li ser hemû giravên Kendava Farisî', 'Tenê li başûrê Makranê', 'B', 'Nivîs ser û zincê bi taybetî li Îrana Navîn kom dibin û li hin deveran kargeh tên plansazkirin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0031', 'Cografya', 'ku-kmr', 'Kîjan maden li nêzîkî Bāft, Sabzavār û Bandar-e ʿAbbās di nivîsê de tê behskirin?', 'Fosfat', 'Köm', 'Kromît', 'Hesin', 'C', 'Nivîs kromîtê li nêzîkî Bāft, Sabzavār û Bandar-e ʿAbbās di nav çavkaniyên din ên madenî de dide lîstekirin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0032', 'Cografya', 'ku-kmr', 'Madencîna kömê li gorî nivîsê ji kîjan serdemê ve bûye karêkî girîng?', 'Ji sedsala pêncan ve', 'Tenê piştî sala 2000 ve', 'Ji dema antîkê ve bê rawestan', 'Ji sedsala nozdehan ve', 'D', 'Nivîs dibêje ku ji sedsala nozdehan ve madencîna kömê, bi taybetî li derdora Tehran û Elborzê, bûye kareke girîng.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0033', 'Cografya', 'ku-kmr', 'Kîjan herêmên kömê di nivîsê de tên naskirin?', 'Elborz, derdora Tehran û parêzgeha Kermanê', 'Deştên Qezwînê û deryaya Bengalê', 'Çiyayên Andê û Alpê', 'Kawkaz û giravên Okyanûsa Pasîfîkê', 'A', 'Nivîs çavkaniyên kömê li Elborzê, li derdora Tehranê û her ku diçe zêdetir li parêzgeha Kermanê dide naskirin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0035', 'Cografya', 'ku-kmr', 'Bafq di belavbûna fosfatê de çi cih digire?', 'Tenê navendeke kömê ye', 'Ji herêmên ku fosfat lê tune ye', 'Yek ji navendên sereke yên fosfatê ye', 'Navendeke tenê ji bo kromîtê ye', 'C', 'Nivîs Bafqê li parêzgeha Yazdê wekî yek ji navendên sereke yên depoyên fosfatê dide naskirin.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0036', 'Cografya', 'ku-kmr', 'Neft û gaz di avahiya geologîk a Îranê de bi kîjan pêvajoyê re têkildar in?', 'Bi kêm bûna rêzeya Elborzê', 'Bi çêbûna deştên Qezwînê', 'Bi qeşabûna çiyayên Khorasanê', 'Bi bilindbûna rêzeya çiyayên Zagrosê', 'D', 'Nivîs rezervên neft û gazê bi bilindbûna pergala çiyayî ya Zagrosê ve girê dide.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0038', 'Cografya', 'ku-kmr', 'Di nivîsê de kîjan herêm wekî herêma ku ji derya û okyanûsan re têkiliya rasterast tune ye tê ravekirin?', 'Deştên Kendava Farisî', 'Îrana Navîn û platoya wê', 'Deryaya Qezwînê', 'Kembera Volkanîk', 'B', 'Avahiya çiyayên derdorê Îrana Navîn dike hewzeke hundirîn û rê li ber têkiliya rasterast bi okyanûsan re digire.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('cografya_20260801_0040', 'Cografya', 'ku-kmr', 'Li gorî nivîsê, avahiya geologîk ji bo xeterên xwezayî çima girîng e?', 'Ji ber ku ew tenê rengê axê diguhere', 'Ji ber ku ew hemû baranê ji welatê dûr dixe', 'Ji ber ku ew çemên nû bê sedem çêdike', 'Ji ber ku ew şertên erdhej, herikîna axê û şemitîna axê bandor dike', 'D', 'Nivîs pêwendiya nêzîk a avahiya geologîk bi erdhejan, herikînên axê û şemitîna axê re nîşan dide.', 3, 'https://www.iranicaonline.org/articles/geology/'),
('agent_dirok_20260801_0001', 'Dîrok', 'ku-kmr', 'Li gorî nivîsa Encyclopaedia Iranica, mijara serdest a gelek berhemên li ser dîroka nûjen a Kurdan çi ye?', 'Pêşketina bazirganiya navçeyî', 'Têkoşîna ji bo diyarkirina çarenûsa xwe', 'Dîroka hunera mîmarî', 'Danasîna şervanên serdema kevn', 'B', 'Nivîsê dibêje ku mijara sereke ya gelek lêkolînan têkoşîna Kurdan ji bo diyarkirina çarenûsa wan e.', 2, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0002', 'Dîrok', 'ku-kmr', 'Di nivîsê de dîroka nûjen a Kurdan bi taybetî li ser kîjan çar welatan tê nîqaşkirin?', 'Iraq, Sûriye, Lubnan û Misir', 'Tirkiye, Iraq, Îran û Sûriye', 'Îran, Afganistan, Ermenistan û Gurcistan', 'Tirkiye, Iraq, Urdun û Sûriye', 'B', 'Nivîsê van çar welatan wekî cihên ku Kurd lê beşeke girîng a nifûsê pêk tînin nîşan dide.', 2, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0003', 'Dîrok', 'ku-kmr', 'Hemû berhemên ku di lêkolîna kurt a nivîsê de hatine nîqaşkirin, piştî kîjan salê hatine weşandin?', '1900', '1923', '1950', '2000', 'C', 'Di destpêka nivîsê de tê gotin ku hemû berhemên di vê lêkolîna kurtê de piştî sala 1950an hatine weşandin.', 2, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0004', 'Dîrok', 'ku-kmr', 'Kîjan pirtûk di nivîsê de wekî rêberê herî berfireh ji bo dîroka nûjen a Kurdan tê pêşniyarkirin?', 'Agha, Shaikh and State', 'A Modern History of the Kurds', 'The Kurdish Republic of 1946', 'Nationalism and Language in Kurdistan, 1918-1985', 'B', 'Nivîsê pirtûka David McDowall wekî yek ji rêberên herî berfireh ji bo dîroka nûjen a Kurdan binav dike.', 2, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0005', 'Dîrok', 'ku-kmr', 'Li gorî nivîsê, David McDowall berî Şerê Cîhanê Yê Yekem bi giranî kîjan serdemê dinivîse?', 'Sedsala 16an', 'Sedsala 17an', 'Sedsala 19an', 'Piştî sala 2000an', 'C', 'Nivîsê dibêje ku McDowall ji bo dayîna çarçoveyeke giştî bi giranî li ser sedsala 19an û dîroka berî Şerê Cîhanê Yê Yekem radiweste.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0006', 'Dîrok', 'ku-kmr', 'Pirtûka Agha, Shaikh and State ya Martin van Bruinessen bi taybetî çi dide ber çavan?', 'Têkiliya eşîran, dewletê û tevgera neteweyî ya Kurdî', 'Dîroka şanoya klasîk a Kurdî', 'Pêşketina pergala perwerdehiya Japonê', 'Danasîna deryayên rojhilatê Îranê', 'A', 'Nivîsê balê dikişîne ser eşîr û ne-eşîr, têkiliya eşîran bi dewletê re û rewşa tevgera neteweyî ya Kurdî.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0007', 'Dîrok', 'ku-kmr', 'Li gorî nivîsê, tevgera Şêx Said di kîjan salê de tê nîqaşkirin?', '1912', '1925', '1946', '1970', 'B', 'Nivîsê diyar dike ku van Bruinessen têkiliya mijarên civakî û siyasî di serhildana Şêx Said a sala 1925an de nîşan dide.', 2, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0008', 'Dîrok', 'ku-kmr', 'Kîjan berhem di nivîsê de wekî teza doktorayê ya ku di sala 1960an de hat pêşkêşkirin tê naskirin?', 'The Kurdish National Movement: Its Origins and Development', 'Kurdish Notables and the Ottoman State', 'Trapped between the Map and Reality', 'The Kurdish Question and the 2003 Iraqi War', 'A', 'Nivîsê berhema Wadie Jwaideh wekî teza doktorayê ya sala 1960an bi nav dike.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0009', 'Dîrok', 'ku-kmr', 'Wadie Jwaideh di lêkolîna xwe de ji kîjan komê çavkaniyan sûd werdigire?', 'Tenê ji belgeyên Fransî û Almanî', 'Ji çavkaniyên Îngilîzî, Fransî, Erebî, Kurdî û Farisî', 'Tenê ji gotinên devkî yên Sûriyeyê', 'Ji nivîsarên latînî yên serdema Romayê', 'B', 'Nivîsê dibêje ku Jwaideh ji çavkaniyên bi Îngilîzî, Fransî, Erebî, Kurdî û Farisî sûd wergirtiye.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0010', 'Dîrok', 'ku-kmr', 'Pirtûka Nationalism and Language in Kurdistan, 1918-1985 ya Amir Hassanpour kîjan serdemê digire nav xwe?', '1918 heta 1985', '1880 heta 1925', '1923 heta 1945', '1960 heta 1980', 'A', 'Navê pirtûkê bi xwe navbera salên 1918 û 1985an nîşan dide.', 2, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0011', 'Dîrok', 'ku-kmr', 'Li gorî nivîsê, Amir Hassanpour di pirtûka xwe de kîjan hêmanan wekî alîkarên domandina têkoşîna nasnameya Kurdî vedikole?', 'Ziman û çand', 'Bazirganî û avahîsazî', 'Şerê deryayî û bazirganiya navneteweyî', 'Stêrnasî û derman', 'A', 'Nivîsê rola girîng a ziman û çandê di domandina têkoşîna Kurdan ji bo piştrastkirina nasnameya wan de destnîşan dike.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0012', 'Dîrok', 'ku-kmr', 'Kîjan mijarên li ser siyasetên dewletê, çapkirina pirtûkan, çapemeniya rojnameyê û perwerdehiyê di nivîsê de bi kîjan berhemê re têkildar in?', 'Nationalism and Language in Kurdistan, 1918-1985', 'A Modern History of the Kurds', 'The Kurdish Republic of 1946', 'Historical Dictionary of the Kurds', 'A', 'Nivîsê van mijaran di beşa berhema Amir Hassanpour de bi rêza ziman û çandê re girê dide.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0014', 'Dîrok', 'ku-kmr', 'O’Shea ji bo pêvajoya lêkolîna xwe li ser Kurdistanê ji kîjan qadên zanistê sûd wergirtiye?', 'Antropolojî, cografya û dîrok', 'Kimya, biyolojî û jeolojî', 'Matematîk, fîzîk û astronomî', 'Hiqûq, muzîk û mîmarî', 'A', 'Nivîsê dibêje ku O’Shea daneyên antropolojî û cografyayê bi dîrokê re bikar aniye.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0015', 'Dîrok', 'ku-kmr', 'Pirtûka Kurdistan: In the Shadow of History ya Susan Meiselas li ser kîjan demê çalakiyên Kurdistanê rawestiyaye?', 'Ji Şerê Cîhanê Yê Yekem heta sala 2004an', 'Ji sala 1597an heta 1700an', 'Tenê di dema Şerê Cîhanê Yê Duyem de', 'Ji sala 1970an heta 1975an', 'A', 'Nivîsê dibêje ku Meiselas wêne û nivîsarên rojnameyên hevdem ên bûyerên Kurdistanê ji Şerê Cîhanê Yê Yekem heta 2004an berhev kiriye.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0018', 'Dîrok', 'ku-kmr', 'Hamit Bozarslan di La Question kurde de mijara Kurdan li kîjan welatan digere?', 'Tirkiye, Iraq, Îran û Sûriye', 'Tenê Tirkiye û Iraq', 'Îran, Ermenistan û Gurcistan', 'Misir, Lubnan û Urdun', 'A', 'Nivîsê berhema Bozarslan wekî lêkolînek li ser siyaseta Kurdan û rewşa hindikayetan di van çar welatan de nîşan dide.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0019', 'Dîrok', 'ku-kmr', 'Di lêkolîna Gunter Behrendt de, serhildana ku di sala 1880an de bi taybetî tê nîqaşkirin ji aliyê kî ve hatibû rêberîkirin?', 'Ubaydullah', 'Malmîsanij', 'David McDowall', 'William Eagleton', 'A', 'Nivîsê Ubaydullah wekî rêberê serhildana mezin a sala 1880an binav dike.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0020', 'Dîrok', 'ku-kmr', 'Berhema Robert Olson The Emergence of Kurdish Nationalism and the Sheikh Said Rebellion kîjan navbera salan digire nav xwe?', '1880-1925', '1918-1985', '1923-1945', '1960-1970', 'A', 'Nivîsê berhema Olson bi navberê 1880 heta 1925 ve girê dide û wê bi serhildana Şêx Said re têkildar dike.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0026', 'Dîrok', 'ku-kmr', 'Li gorî nivîsê, berhema William Eagleton li ser kîjan bûyerê ye?', 'Hebûna kurt a Komara Mehabadê li Îranê di sala 1946an de', 'Rojnameya yekem a Kurdî li Qahîreyê', 'Rêxistina Hêvî ya xwendekaran', 'Peymana navdewletî ya sala 1923an', 'A', 'Nivîsê berhema Eagleton wekî hesabekî ji bo hebûna kurt a Komara Mehabadê ya sala 1946an li Îranê pêşkêş dike.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('agent_dirok_20260801_0029', 'Dîrok', 'ku-kmr', 'The Journal of Kurdish Studies di nivîsê de bi kîjan agahiyê tê naskirin?', 'Ji sala 1597an ve li Amedê hatiye weşandin', 'Pêncî hejmarên li ser dîroka Romayê çap kiriye', 'Şeş hejmar di navbera 1995 û 2008an de li Louvainê çap kiriye', 'Tenê di sala 1970an de li Baghdadê hatiye weşandin', 'C', 'Nivîsê dibêje ku kovara The Journal of Kurdish Studies şeş hejmarên xwe di navbera 1995 û 2008an de li Louvainê çap kiriye.', 3, 'https://www.iranicaonline.org/articles/kurds-studies-of-modern-kurdish-history/'),
('es_20260801_0001', 'Edebiyat', 'ku-kmr', 'Berî sedsala 20an, kîjan cureya wêjeya nivîskî ya Kurdî zêdetir pêşketibû?', 'Helbest', 'Roman', 'Şanogerî', 'Rojnamevanî', 'A', 'Li gorî gotarê, berhema nivîskî ya Kurdî berî sedsala 20an bi piranî ji helbestê pêk dihat; wêjeya pexşan paşê pêş ket.', 1, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0002', 'Edebiyat', 'ku-kmr', 'Pêşketina wêjeya pexşana Kurdî di sedsala 20an de bi kîjan pêvajoyan re tê girêdan?', 'Bi pêvajoyên civakî û siyasî re', 'Bi bazirganiya deryayî re', 'Bi pêşketina avahiyên leşkerî re', 'Bi guhertina demsalan re', 'A', 'Gotar pêşketina pexşanê di her du zaravayên sereke de bi pêvajoyên civakî û siyasî re girê dide.', 2, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0003', 'Edebiyat', 'ku-kmr', 'Çima şêwaz û wêneyên helbesta nivîskî ya herî kevn a Kurdî bi helbesta Erebî-Farisî re nêzîk in?', 'Ji ber bandora modelên helbesta Erebî-Farisî', 'Ji ber ku hemû helbest bi zimanê Farisî hatine nivîsandin', 'Ji ber ku tenê helbesta devkî hebû', 'Ji ber ku pîvana deh-hejmarî tenê pîvana Kurdî ye', 'A', 'Gotar dibêje ku şêwaz, ziman û wêneyên helbesta kevn bi modelên helbesta Erebî-Farisî re dişibin.', 3, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0004', 'Edebiyat', 'ku-kmr', 'Kîjan nav di nav pênc helbestvanên destpêkê yên dibistana Kormancî de tê dîtin?', 'Melayê Cizîrî', 'Nalî', 'Goran', 'Şêx Reza Talebanî', 'A', 'Melayê Cizîrî, Faqiyê Teyran, Melayê Bateyî, Ehmedê Xanî û Elî Herîrî di nav pênc navên destpêkê yên dibistana Kormancî de ne.', 2, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0005', 'Edebiyat', 'ku-kmr', 'Dibistana Kormancî kîjan zaravayê wekî zimanê wêjeyî bikar dianî?', 'Zaravayê Kormancî yê Cizîra-Botanê', 'Zaravayê Goranî yê Silemaniyê', 'Zaravayê Soranî yê Hewlêrê', 'Zaravayê Erebî yê Şamê', 'A', 'Gotar dibêje ku dibistana Kormancî zaravayê Kormancî yê Cizîra-Botanê wekî zimanê wêjeyî bikar dianî.', 2, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0006', 'Edebiyat', 'ku-kmr', 'Di berhemên Melayê Cizîrî de kîjan cureyên helbestê tên naskirin?', 'Qesîde û xezel', 'Roman û dram', 'Mewlûd û çîrok', 'Rojname û kovar', 'A', 'Li gorî gotarê, berhemên Melayê Cizîrî qesîde û xezel dihewînin û bandora helbesta Farisî li ser wî hebû.', 3, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0008', 'Edebiyat', 'ku-kmr', 'Kîjan berhem di nav berhemên ku ji Faqiyê Teyran re tên dayîn de ye?', 'Hekayeta Şêxê Senan', 'Mem û Zîn', 'Berbang', 'Jani gel', 'A', 'Hekayeta Şêxê Senan di nav berhemên mayî yên ku ji Faqiyê Teyran re tên dayîn de tê nivîsandin.', 3, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0010', 'Edebiyat', 'ku-kmr', 'Mem û Zîn ya Ehmedê Xanî di gotarê de çawa tê şirovekirin?', 'Wekî destaneke evînî ya dirêj li ser evîna ne gengaz a du malbatên payebilind', 'Wekî kovareke siyasî ya li Şamê', 'Wekî pirtûka rêzimana Kurdî', 'Wekî çîrokeke tenê li ser bazirganiyê', 'A', 'Gotar Mem û Zîn wekî destaneke evînî ya dirêj û çîroka evîna ne gengaz a du kesên ji malbatên payebilind nîşan dide.', 2, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0011', 'Edebiyat', 'ku-kmr', 'Kîjan du berhemên din ji Ehmedê Xanî re tên dayîn?', 'Nûbehara Pêçûkan û Eqîdeya Îmanê', 'Berbang û Jani gel', 'Kordistan û Hawar', 'Hekayeta Şêxê Senan û Zambilfroş', 'A', 'Ji bilî Mem û Zîn, gotar Nûbehara Pêçûkan û berhema olî Eqîdeya Îmanê jî ji Ehmedê Xanî re dide nasîn.', 3, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0012', 'Edebiyat', 'ku-kmr', 'Melayê Bateyî bi kîjan cureya berhemê tê naskirin?', 'Bi nivîsandina mewlûdekê li ser jidayikbûna Pêxemberê Mihemed', 'Bi damezrandina dibistana Nalî', 'Bi nivîsandina romana Jani gel', 'Bi pêşxistina kovara Riya taze', 'A', 'Gotar dibêje ku Melayê Bateyî mewlûdek, ango helbestek li ser jidayikbûna Pêxemberê Mihemed, nivîsandiye.', 2, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0014', 'Edebiyat', 'ku-kmr', 'Kîjan helbestvan wekî damezrîner û nûnerê yekem ê dibistana Goranî tê naskirin?', 'Yûsif Yaska', 'Nalî', 'Cegerxwîn', 'Hecî Qadirî Koyî', 'A', 'Li gorî gotarê, Yûsif Yaska damezrîner û nûnerê yekem ê dibistana Goranî bû û xezel nivîsand.', 3, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0015', 'Edebiyat', 'ku-kmr', 'Navenda dibistana helbesta Soranî ya Nalî li kîjan bajarî bû?', 'Silêmanî', 'Diyarbekir', 'Qahîreyê', 'Erevan', 'A', 'Gotar dibêje ku dibistana helbesta Soranî ya Nalî navenda xwe li Silêmaniyê hebû.', 2, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0016', 'Edebiyat', 'ku-kmr', 'Nalî bi kîjan cureya helbestê zêdetir tê naskirin?', 'Bi helbesta lîrîk', 'Bi romana dîrokî', 'Bi mewlûda olî', 'Bi nivîsa rêzimanî', 'A', 'Her çend Nalî formên qesîde û xezelê bikar anîbe jî, gotar wî bi taybetî bi helbesta lîrîk re nas dike.', 3, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0017', 'Edebiyat', 'ku-kmr', 'Şêx Reza Talebanî di helbesta Kurdî de bi kîjan taybetmendiyê tê girêdan?', 'Bi danasîna satîrê', 'Bi damezrandina çapxaneya yekem', 'Bi nivîsandina Mem û Zîn', 'Bi pêşxistina kovara Sirwe', 'A', 'Li gorî gotarê, Şêx Reza Talebanî satîrê di helbesta Kurdî de pêşkêş kir û di berhemên wî de hêmanên otobiyografîk jî hene.', 3, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0019', 'Edebiyat', 'ku-kmr', 'Kordistan, wekî yekem rojnameya Kurdî ya ku di gotarê de tê behskirin, di sala 1898an de li kîjan bajarî hate çapkirin?', 'Qahîreyê', 'Şamê', 'Silêmaniyê', 'Parîsê', 'A', 'Li gorî gotarê, yekem rojnameya Kurdî Kordistan di sala 1898an de li Qahîreyê hate çapkirin.', 2, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0020', 'Edebiyat', 'ku-kmr', 'Kovara Hawarê di kîjan dem û li kîjan bajarî derket?', 'Li Şamê, di navbera 1935 û 1943an de', 'Li Qahîreyê, di navbera 1898 û 1902an de', 'Li Parîsê, di navbera 1983 û 1987an de', 'Li Silêmaniyê, di navbera 1919 û 1920an de', 'A', 'Gotar Hawarê wekî kovareke li Şamê di navbera 1935 û 1943an de derketî dide nasîn.', 2, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0022', 'Edebiyat', 'ku-kmr', 'Kîjan helbestvan di nav dibistana Hawarê de tê hilbijartin?', 'Cegerxwîn', 'Nalî', 'Yûsif Yaska', 'Şêx Reza Talebanî', 'A', 'Gotar Cegerxwîn, bi navê xwe yê Şêxmûs Hesen, wekî yek ji helbestvanên dibistana Hawarê dide nasîn.', 3, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0024', 'Edebiyat', 'ku-kmr', 'Jani gel, ku di gotarê de wekî yekem romana Soranî tê binavkirin, di sala 1973an de kê nivîsandiye?', 'Îbrahîm Ehmed', 'Mehmed Uzun', 'Cegerxwîn', 'Mûsa Entêr', 'A', 'Li gorî gotarê, Jani gel yekem romana Soranî ye û di sala 1973an de Îbrahîm Ehmed nivîsandiye.', 3, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0025', 'Edebiyat', 'ku-kmr', 'Di sala 1970an de, Kurdî li Iraqê wekî kîjan statuyê hate nasîn?', 'Wekî zimanê fermî yê duyem', 'Wekî zimanê tenê yê dadgehê', 'Wekî zimanê ku tenê di malê de tê axaftin', 'Wekî zimanê ku li Iraqê hat qedexekirin', 'A', 'Gotar dibêje ku di sala 1970an de Kurdî wekî zimanê fermî yê duyem ê Iraqê hate nasîn.', 2, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0026', 'Edebiyat', 'ku-kmr', 'Mehmed Uzun di gotarê de di nav kîjan komê de tê naskirin?', 'Di nav nivîskarên Kormancî yên diasporayê de', 'Di nav damezrînerên dibistana Goranî de', 'Di nav rojnamevanên Kordistanê yên 1898an de', 'Di nav helbestvanên Soranî yên sedsala 18an de', 'A', 'Gotar Mehmed Uzun wekî nivîskarekî navdar ê Kormancî di diasporayê de dide nasîn û dibêje ku berhemên wî bo çend zimanan hatine wergerandin.', 3, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0029', 'Edebiyat', 'ku-kmr', 'Di sala 1983an de li Parîsê kîjan saziya çandî hate damezrandin?', 'Enstîtuya Kurdî', 'Kovara Kordistanê', 'Dibistana Hawarê', 'Akademiya Zanistên Kurdî ya Bexdayê', 'A', 'Li gorî gotarê, Enstîtuya Kurdî li Parîsê di sala 1983an de hate damezrandin û bi çalakiyên wêjeyî yên Kurdî re girîng bû.', 2, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0030', 'Edebiyat', 'ku-kmr', 'Kîjan cureya helbestê di berhemên Goran de di salên 1930an de tê nimûnekirin?', 'Helbesta azad û ya hejmariyê', 'Tenê xezelên Farisî', 'Tenê helbesta mewlûdê', 'Helbesta bêyî ziman û bêyî pîvan', 'A', 'Gotar Goran wekî nimûneyek ji derketina helbesta azad û ya hejmariyê di salên 1930an de dide.', 3, 'https://www.iranicaonline.org/articles/kurdish-written-literature/'),
('es_20260801_0031', 'Siyaset', 'ku-kmr', 'Li gorî gotara ANFê, projeya KJAR ji bo pêşxistina şoreşa jinan çend alî hebû?', 'Deh alî', 'Pênc alî', 'Heft alî', 'Sêzdeh alî', 'A', 'Di sernavê gotarê de projeya KJAR wekî projeyeke deh-alî ji bo şoreşa jinan tê pêşkêşkirin.', 1, 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521'),
('es_20260801_0032', 'Siyaset', 'ku-kmr', 'Kîjan kom ji hêmanên ku KJAR di projeya xwe de pêşniyar kiriye pêk tê?', 'Komîteyên hemû gelan, komûnên jinan, perwerdehiya alternatîf û komîteya piştgiriya civaka şoreşger', 'Tenê komîteyên leşkerî û bazirganiyê', 'Komîteyên werzîşê bêyî beşdariya civakê', 'Saziyên çapemeniya derveyî bêyî komîteyên herêmî', 'A', 'Li gorî gotarê, pêşniyara KJAR komîteyên hemû gelan, komûnên jinan, perwerdehiya alternatîf, komîteyên bawerî û çandê û piştgiriya civaka şoreşger dihewîne.', 2, 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521'),
('es_20260801_0033', 'Siyaset', 'ku-kmr', 'Di xalê yekem ê projeya KJAR de, ji bo kîjan komê azadî tê xwestin?', 'Ji bo girtiyên siyasî, di nav de girtiyên siyasî yên jin', 'Ji bo tenê endamên komîteyên perwerdehiyê', 'Ji bo tenê mamosteyên zanîngehê', 'Ji bo tenê rêveberên saziyên çandî', 'A', 'Xala yekem daxwaza azadiya girtiyên siyasî û hemû girtiyên siyasî, di nav de Zeynep Celaliyan, dike.', 3, 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521'),
('es_20260801_0035', 'Siyaset', 'ku-kmr', 'Di xala sêyem de xweparastin çawa tê pênasekirin?', 'Wekî mafekî bingehîn û bingeha rêxistinkirina civakê', 'Wekî karê tenê yê hêzên dewletê', 'Wekî çalakiyeke tenê ji bo zanîngehê', 'Wekî pêdiviyeke bê têkiliya bi civakê re', 'A', 'Gotar xweparastinê mafekî bingehîn dide nasîn û rêxistinkirina jinan, gelan û ciwanan li ser vê hişmendiyê girê dide.', 3, 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521'),
('es_20260801_0037', 'Siyaset', 'ku-kmr', 'Di xala pêncem de kîjan koman têne bangkirin ku encûmen û komîteyên xwe ava bikin?', 'Hunermend, werzişkar, mamoste, karker, doktor û çalakvanên ekolojiyê', 'Tenê rojnamevan û bazirgan', 'Tenê mamoste û xwendekar', 'Tenê rêveberên saziyên olî', 'A', 'Gotar hunermend, werzişkar, mamoste, karker, doktor û çalakvanên ekolojiyê wekî komên ku divê encûmen û komîteyên xwe ava bikin dide nav.', 2, 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521'),
('es_20260801_0038', 'Siyaset', 'ku-kmr', 'Di xala şeşem de ji bo perwerdehiya azad û demokratîk kîjan pêşniyar tê kirin?', 'Avakirina komîteyên perwerdehiyê ji bo mamoste, xwendekar, rewşenbîr û akademîsyenan', 'Girtina hemû dibistanan bêyî alternatîf', 'Pêşkêşkirina perwerdehiyê tenê bi rêya saziyên leşkerî', 'Rakirinên hemû komîteyên herêmî', 'A', 'Xala şeşem avakirina komîteyên perwerdehiyê û pêşxistina perwerdehiya alternatîf ji bo mamoste, xwendekar, rewşenbîr û akademîsyenan pêşniyar dike.', 3, 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521'),
('es_20260801_0039', 'Siyaset', 'ku-kmr', 'Di xala heftem de jinên Rojhilatê Kurdistanê û Îranê ji bo pêşeroja xwe çi dikin?', 'Komûn, yekîneyên xwe û yekîneyên şûrayê ava dikin', 'Tenê kovarên wêjeyî çap dikin', 'Tenê ji komîteyên perwerdehiyê dûr dimînin', 'Tenê saziyên bazirganiyê ava dikin', 'A', 'Li gorî gotarê, xala heftem jinan bang dike ku li her derê komûn, yekîneyên xwe û yekîneyên şûrayê ava bikin û pêşeroja xwe rêxistin bikin.', 3, 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521'),
('es_20260801_0040', 'Siyaset', 'ku-kmr', 'Di xala heştem de malbat di pêvajoya guhertinê de çi rolekê heye?', 'Malbat wekî hêmaneke sereke ji bo xurtkirina komîteyên malbatê tê dîtin', 'Malbat ji hemû pêvajoyan tê derxistin', 'Malbat tenê ji bo çandê, bêyî rola civakî, tê dîtin', 'Malbat wekî saziyeke ku divê were rakirin tê pêşkêşkirin', 'A', 'Gotar malbatê wekî hêmaneke sereke dide nasîn û xurtkirina komîteyên malbatê û prensîba malbata demokratîk pêşniyar dike.', 3, 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521'),
('es_20260801_0042', 'Siyaset', 'ku-kmr', 'Xala dehem a projeya KJAR kîjan komîteyê pêşniyar dike?', 'Komîteya piştgiriya civaka şoreşger', 'Komîteya bazirganiya deryayî', 'Komîteya tenê ya kovarên wêjeyî', 'Komîteya rêveberiya zanîngehê', 'A', 'Xala dehem komîteya piştgiriya civaka şoreşger e ku ji bo arîkariya pêdiviyên jiyanê yên civak û malbatên di tengasiyê de tê pêşniyarkirin.', 3, 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521'),
('es_20260801_0043', 'Siyaset', 'ku-kmr', 'KJAR di gotara ANFê de projeya xwe ji bo kîjan pêvajoyê wekî pêşniyarekê pêşkêş dike?', 'Ji bo avakirina jiyana azad û pêşxistina şoreşa jinan', 'Ji bo pêşxistina tenê bazirganiya herêmî', 'Ji bo berfirehkirina tenê çalakiyên wêjeyî', 'Ji bo guhertina pîvanên helbestê', 'A', 'Gotar dibêje ku KJAR projeya deh-alî ji bo meşandina şoreşa jinan û avakirina jiyana azad pêşniyar kiriye.', 2, 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521'),
('es_20260801_0044', 'Siyaset', 'ku-kmr', 'Di gotara KJAR de, çi kom ji bo avakirina komîteyên perwerdehiyê wekî beşdar tên navandin?', 'Mamoste, xwendekar, rewşenbîr û akademîsyen', 'Tenê parêzer û pêşengên ol', 'Tenê hunermend û werzişkar', 'Tenê karker û doktor', 'A', 'Di xala şeşem de mamoste, xwendekar, rewşenbîr û akademîsyen wekî kesên ku divê komîteyên perwerdehiyê ava bikin tên navandin.', 2, 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521'),
('wave2_08751', 'Paradigma', 'ku-kmr', 'Di destpêkê de, kîjan vebijark di çarçoveya paradigma de wateya têgeha ''Konfederalîzma Demokratîk'' bi awayekî herî rast nîşan dide?', 'hişmendiya zanistî ya ku ji bin tekelên desthilatê derketiye û ji civakê re xizmet dike', 'prensîba azadiya jin û mêr û wekheviya wan a di her qada jiyanê de', 'Ew wekî ''modela birêvebirina civakê ya li derveyî sîstema dewlet-neteweyê'' tê pênasekirin.', 'analîzkirin û hilweşandina sîstema serdest a mêr a li ser civakê', 'C', 'Têgeha ''Konfederalîzma Demokratîk'' di bin sîwana paradigma de xwedî roleke giring e.', 1, 'https://kongra-star.org/eng/about/'),
('wave2_08762', 'Paradigma', 'ku-kmr', 'Di asta bingehîn de, têgeha ''Moderniteya Demokratîk'' a ku di qada paradigma de derdikeve pêş, çi nîşan dide?', 'modela alternatîf a jiyanê ya li dijî kapîtalîzma modern', 'civaka azad a ku biryarên xwe bi hişmendiya exlakî û polîtîk dide', 'prensîba azadiya jin û mêr û wekheviya wan a di her qada jiyanê de', 'hişmendiya zanistî ya ku ji bin tekelên desthilatê derketiye û ji civakê re xizmet dike', 'A', 'Têgeha ''Moderniteya Demokratîk'' di bin sîwana paradigma de xwedî roleke giring e.', 2, 'https://kongra-star.org/eng/about/'),
('wave2_08753', 'Paradigma', 'ku-kmr', 'Di destpêkê de, têgeha ''Jineolojî'' a ku di qada paradigma de derdikeve pêş, çi nîşan dide?', 'di gotûbêja tevgerê de nêzîkatiyek ku azadiya civakê bi azadiya jinê ve girê dide', 'civaka azad a ku biryarên xwe bi hişmendiya exlakî û polîtîk dide', 'hişmendiya zanistî ya ku ji bin tekelên desthilatê derketiye û ji civakê re xizmet dike', 'têkiliya hevseng û dostane ya di navbera civakê û xwezayê de', 'A', 'Têgeha ''Jineolojî'' di bin sîwana paradigma de xwedî roleke giring e.', 3, 'https://kongra-star.org/eng/about/'),
('wave2_08846', 'Paradigma', 'ku-kmr', 'Di nirxandina zanînê de, têgeha ''civaka exlaqî-polîtîk'' a ku di qada paradigma de derdikeve pêş, çi nîşan dide?', 'analîzkirin û hilweşandina sîstema serdest a mêr a li ser civakê', 'têkiliya hevseng û dostane ya di navbera civakê û xwezayê de', 'modela birêvebirina civakê ya li derveyî sîstema dewlet-neteweyê', 'civaka azad a ku biryarên xwe bi hişmendiya exlakî û polîtîk dide', 'D', 'Têgeha ''civaka exlaqî-polîtîk'' di bin sîwana paradigma de xwedî roleke giring e.', 1, 'https://kongra-star.org/eng/about/'),
('wave2_08827', 'Paradigma', 'ku-kmr', 'Di bîranîna dîrokî de, di warê paradigma de têgeha ''rexneya patriyarkayê'' bi kîjan pênaseya xwe ya bingehîn tê naskirin?', 'di gotûbêja tevgerê de nêzîkatiyek ku azadiya civakê bi azadiya jinê ve girê dide', 'analîzkirin û hilweşandina sîstema serdest a mêr a li ser civakê', 'modela birêvebirina civakê ya li derveyî sîstema dewlet-neteweyê', 'hişmendiya zanistî ya ku ji bin tekelên desthilatê derketiye û ji civakê re xizmet dike', 'B', 'Têgeha ''rexneya patriyarkayê'' di bin sîwana paradigma de xwedî roleke giring e.', 2, 'https://kongra-star.org/eng/about/'),
('ziman_wave2_0001', 'Ziman', 'ku-kmr', 'Kovara Hawarê li Şamê di kîjan du serdeman de hate weşandin?', '1925–1929 û 1936–1939', '1932–1935 û 1941–1943', '1930–1933 û 1945–1948', '1935–1940 û 1944–1949', 'B', 'Çavkaniyê dibêje ku Hawar di Şamê de ji 1932 heta 1935 û paşê ji 1941 heta 1943 hate weşandin.', 2, 'https://nykcc.org/oldsite/hawar-archive/'),
('ziman_wave2_0002', 'Ziman', 'ku-kmr', 'Kî di Hawarê de wekî edîtorê damezrîner tê naskirin?', 'Şêx Sait Pîran', 'Ehmedê Xanî', 'Celadet Alî Bedirxan', 'Mela Mehmûdê Bayezîdî', 'C', 'Li gorî çavkaniyê, Celadet Alî Bedirxan edîtorê damezrînerê Hawarê bû.', 2, 'https://nykcc.org/oldsite/hawar-archive/'),
('ziman_wave2_0003', 'Ziman', 'ku-kmr', 'Hejmarê yekem ê Hawarê di kîjan rojê de derket?', '15ê Gulana 1932', '1ê Rêbendana 1935', '15ê Tebaxa 1941', '24ê Gulanê 1932', 'A', 'Çavkaniyê destnîşan dike ku hejmarê yekem di 15ê Gulana 1932 de derket.', 2, 'https://nykcc.org/oldsite/hawar-archive/'),
('ziman_wave2_0004', 'Ziman', 'ku-kmr', 'Celadet Alî Bedirxan ji bo nivîsandina Kurmancî çi alfabeyek nû amade kir?', 'Alfabeyeke bi tîpên kîrîlî', 'Alfabeyeke tenê bi tîpên erebî', 'Alfabeyeke bi nîşanên matematîkî', 'Alfabeyeke bi tîpên latînî', 'D', 'Li gorî çavkaniyê, Celadet Alî Bedirxan alfabeyeke nû bi tîpên latînî amade kir.', 2, 'https://nykcc.org/oldsite/hawar-archive/'),
('ziman_wave2_0005', 'Ziman', 'ku-kmr', 'Heta hejmarên 23an, di Hawarê de nivîsên Kurmancî bi kîjan du alfabeyan dihatin çapkirin?', 'Tenê bi latînî û kîrîlî', 'Bi alfabeya latînî û alfabeya erebî-farisî', 'Bi yewnanî û latînî', 'Tenê bi alfabeya erebî', 'B', 'Çavkaniyê dibêje ku 23 hejmarên yekem rûpelên Kurmancî bi her du alfabeyên latînî û erebî-farisî dihewandin.', 3, 'https://nykcc.org/oldsite/hawar-archive/'),
('ziman_wave2_0006', 'Ziman', 'ku-kmr', 'Ji hejmar 24an ve, nivîsên Kurmancî yên Hawarê tenê bi kîjan alfabeyê hatin çapkirin?', 'Bi alfabeya latînî', 'Bi alfabeya erebî-farisî', 'Bi alfabeya kîrîlî', 'Bi alfabeya yewnanî', 'A', 'Ji hejmar 24an ve, li gorî çavkaniyê, Hawar tenê alfabeya latînî bi kar anî.', 3, 'https://nykcc.org/oldsite/hawar-archive/'),
('ziman_wave2_0008', 'Ziman', 'ku-kmr', 'Di edîtoriyala yekem a Hawarê de, yek ji armancên sereke çi bû?', 'Girtina hemû kovarên din', 'Sazkirina partiyeke siyasî', 'Belavkirin û hînkirina alfabeya nû', 'Ji bo zanîngehê dersên matematîkê amadekirin', 'C', 'Di edîtoriyala yekem de, ji bo belavkirin û hînkirina alfabeya nû armanc hat diyarkirin.', 3, 'https://nykcc.org/oldsite/hawar-archive/'),
('ziman_wave2_0011', 'Ziman', 'ku-kmr', 'NYKCC di rûpela Hawarê de çend hejmarên ji sala yekem a kovarê pêşkêş dike?', 'Du', 'Sê', 'Heft', 'Pênc', 'D', 'Çavkaniyê dibêje ku NYKCC pênc hejmarên ji sala yekem a Hawarê ji raya giştî re pêşkêş dike.', 1, 'https://nykcc.org/oldsite/hawar-archive/');

CREATE TEMP TABLE _agent_question_wave_inserted (question_id uuid) ON COMMIT DROP;

WITH inserted AS (
  INSERT INTO public.questions (
    category_id, language_code, prompt, option_a, option_b, option_c, option_d,
    correct_option, explanation, difficulty, is_approved, question_type,
    image_url, source_url, review_status, dialect, source_title,
    source_reference, quality_version, last_content_check_at
  )
  SELECT
    c.id, s.language_code, s.prompt, s.option_a, s.option_b, s.option_c,
    s.option_d, s.correct_option, s.explanation, s.difficulty, true,
    'multiple_choice', NULL, s.source_url, 'approved', 'Kurmancî',
    'Agent editorial wave — 2026-08-01', s.source_url, 1, now()
  FROM _agent_question_wave_source s
  JOIN public.categories c ON c.name = s.category_name
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.questions q
    WHERE q.language_code = s.language_code
      AND lower(trim(q.prompt)) = lower(trim(s.prompt))
  )
  RETURNING id
)
INSERT INTO _agent_question_wave_inserted (question_id)
SELECT id FROM inserted;

DO $$
DECLARE
  source_count integer;
  inserted_count integer;
  missing_categories integer;
BEGIN
  SELECT count(*) INTO source_count FROM _agent_question_wave_source;
  SELECT count(*) INTO inserted_count FROM _agent_question_wave_inserted;
  SELECT count(*) INTO missing_categories
  FROM _agent_question_wave_source s
  LEFT JOIN public.categories c ON c.name = s.category_name
  WHERE c.id IS NULL;

  IF source_count <> 91 OR missing_categories <> 0 OR inserted_count <> 91 THEN
    RAISE EXCEPTION 'Agent wave guard failed: source=%, inserted=%, missing_categories=%',
      source_count, inserted_count, missing_categories;
  END IF;
END $$;

COMMIT;
