-- ============================================================
-- ZanKurd: Tekrar soru temizligi (deduplication) migrasyonu
-- Tarih: 2026-07-22
-- Kaynak: tools/reports/exact_duplicates.csv
-- ============================================================
--
-- Toplam tekrar kümesi:          405
-- Devre disi birakilacak soru:    1211
-- Korunacak temsilci soru:        405
-- (Tek üyeli kümeler dahil degil — onlar zaten essiz.)
--
-- Yöntem:
--   - Her küme icin 1 temsilci korunur (en düsük offline ID).
--   - Diger küme üyeleri prompt eslesmesiyle bulunur ve
--     is_approved=false, review_status=rejected yapilir.
--   - Sorular SILINMEZ, sadece devre disi birakilir.
-- ============================================================

-- ============================================================
-- BOLUM 1: DRY-RUN — Etkilenecek sorulari göster (calistirma)
-- ============================================================

-- Asagidaki SELECT sorgusu hangi sorularin etkilenecegini gösterir.
-- Sonuc kumesini incele, beklenen sayilarla eslesiyorsa Bolum 2 yi calistir.

SELECT q.id, q.prompt, q.difficulty, q.question_type,
       q.is_approved, q.review_status, q.source_url
FROM public.questions q
WHERE q.is_approved = true
  AND lower(trim(q.prompt)) IN (
    lower(trim(E'What is the area of Sudan?')),
    lower(trim(E'Who painted the Mona Lisa?')),
    lower(trim(E'What is the area of Mexico?')),
    lower(trim(E'What is the area of Latvia?')),
    lower(trim(E'Peyva "av" "su" anlamına gelir.')),
    lower(trim(E'Peyva "rû" "yüz" anlamına gelir.')),
    lower(trim(E'Peyva "roj" "ev" anlamına gelir.')),
    lower(trim(E'Peyva "dê" "anne" anlamına gelir.')),
    lower(trim(E'Peyva "çav" "göz" anlamına gelir.')),
    lower(trim(E'Peyva "pir" "çok" anlamına gelir.')),
    lower(trim(E'Peyva "hesp" "at" anlamına gelir.')),
    lower(trim(E'Peyva "por" "saç" anlamına gelir.')),
    lower(trim(E'Peyva "duh" "dün" anlamına gelir.')),
    lower(trim(E'Peyva "heyv" "ay" anlamına gelir.')),
    lower(trim(E'Peyva "gul" "gül" anlamına gelir.')),
    lower(trim(E'Peyva "îro" "dün" anlamına gelir.')),
    lower(trim(E'Peyva "pê" "ayak" anlamına gelir.')),
    lower(trim(E'Peyva "dev" "diş" anlamına gelir.')),
    lower(trim(E'Peyva "guh" "göz" anlamına gelir.')),
    lower(trim(E'Peyva "çem" "vadi" anlamına gelir.')),
    lower(trim(E'Peyva "poz" "ağız" anlamına gelir.')),
    lower(trim(E'Peyva "pîr" "genç" anlamına gelir.')),
    lower(trim(E'Peyva "dev" "ağız" anlamına gelir.')),
    lower(trim(E'Peyva "dar" "ağaç" anlamına gelir.')),
    lower(trim(E'Peyva "deng" "ses" anlamına gelir.')),
    lower(trim(E'Peyva "bav" "dede" anlamına gelir.')),
    lower(trim(E'Peyva "gund" "köy" anlamına gelir.')),
    lower(trim(E'Peyva "wêne" "ses" anlamına gelir.')),
    lower(trim(E'What is the capital city of Yemen?')),
    lower(trim(E'Peyva "mêr" "aile" anlamına gelir.')),
    lower(trim(E'Peyva "kal" "dede" anlamına gelir.')),
    lower(trim(E'Peyva "deşt" "ova" anlamına gelir.')),
    lower(trim(E'Peyva "stêrk" "ay" anlamına gelir.')),
    lower(trim(E'Peyva "nan" "ekmek" anlamına gelir.')),
    lower(trim(E'Peyva "dest" "ayak" anlamına gelir.')),
    lower(trim(E'Peyva "huner" "yüz" anlamına gelir.')),
    lower(trim(E'Peyva "baran" "kar" anlamına gelir.')),
    lower(trim(E'Peyva "sar" "küçük" anlamına gelir.')),
    lower(trim(E'Peyva "sar" "soğuk" anlamına gelir.')),
    lower(trim(E'Peyva "diran" "diş" anlamına gelir.')),
    lower(trim(E'Peyva "kar" "sanat" anlamına gelir.')),
    lower(trim(E'Peyva "poz" "burun" anlamına gelir.')),
    lower(trim(E'Peyva "hewa" "hava" anlamına gelir.')),
    lower(trim(E'Peyva "derî" "kapı" anlamına gelir.')),
    lower(trim(E'Peyva "nav" "çocuk" anlamına gelir.')),
    lower(trim(E'Peyva "ba" "yağmur" anlamına gelir.')),
    lower(trim(E'Peyva "mal" "kitap" anlamına gelir.')),
    lower(trim(E'Peyva "dapîr" "köy" anlamına gelir.')),
    lower(trim(E'Peyva "îro" "bugün" anlamına gelir.')),
    lower(trim(E'Peyva "deşt" "kaya" anlamına gelir.')),
    lower(trim(E'Peyva "agir" "ateş" anlamına gelir.')),
    lower(trim(E'Peyva "şev" "deniz" anlamına gelir.')),
    lower(trim(E'Peyva "nanpêj" "iş" anlamına gelir.')),
    lower(trim(E'Peyva "şêr" "köpek" anlamına gelir.')),
    lower(trim(E'Peyva "hatin" "dağ" anlamına gelir.')),
    lower(trim(E'Peyva "ba" "rüzgar" anlamına gelir.')),
    lower(trim(E'Peyva "ziman" "dil" anlamına gelir.')),
    lower(trim(E'Peyva "newal" "ova" anlamına gelir.')),
    lower(trim(E'Peyva "reng" "renk" anlamına gelir.')),
    lower(trim(E'Peyva "şêr" "aslan" anlamına gelir.')),
    lower(trim(E'Peyva "berf" "ateş" anlamına gelir.')),
    lower(trim(E'Peyva "kûçik" "kedi" anlamına gelir.')),
    lower(trim(E'How many sides does a heptagon have?')),
    lower(trim(E'Peyva "pisîk" "kedi" anlamına gelir.')),
    lower(trim(E'Peyva "zinar" "kaya" anlamına gelir.')),
    lower(trim(E'Peyva "çûn" "gitmek" anlamına gelir.')),
    lower(trim(E'Peyva "ziman" "okul" anlamına gelir.')),
    lower(trim(E'Peyva "rast" "doğru" anlamına gelir.')),
    lower(trim(E'Peyva "teşt" "leğen" anlamına gelir.')),
    lower(trim(E'Peyva "ciwan" "genç" anlamına gelir.')),
    lower(trim(E'What is the capital city of Bolivia?')),
    lower(trim(E'Peyva "hesp" "aslan" anlamına gelir.')),
    lower(trim(E'Peyva "kevin" "eski" anlamına gelir.')),
    lower(trim(E'Peyva "heval" "şehir" anlamına gelir.')),
    lower(trim(E'Peyva "cîhan" "dünya" anlamına gelir.')),
    lower(trim(E'Peyva "dil" "arkadaş" anlamına gelir.')),
    lower(trim(E'Peyva "bajar" "şehir" anlamına gelir.')),
    lower(trim(E'Peyva "malbat" "aile" anlamına gelir.')),
    lower(trim(E'Peyva "agir" "toprak" anlamına gelir.')),
    lower(trim(E'Peyva "huner" "sanat" anlamına gelir.')),
    lower(trim(E'Peyva "zarok" "çocuk" anlamına gelir.')),
    lower(trim(E'Peyva "nav" "ad/isim" anlamına gelir.')),
    lower(trim(E'Peyva "por" "bina/ev" anlamına gelir.')),
    lower(trim(E'Peyva "bajar" "ekmek" anlamına gelir.')),
    lower(trim(E'Peyva "kûçik" "köpek" anlamına gelir.')),
    lower(trim(E'Peyva "rê" "teşekkür" anlamına gelir.')),
    lower(trim(E'Peyva "welat" "dünya" anlamına gelir.')),
    lower(trim(E'Peyva "pisîk" "nehir" anlamına gelir.')),
    lower(trim(E'Peyva "pê" "baş/kafa" anlamına gelir.')),
    lower(trim(E'Peyva "duh" "ad/isim" anlamına gelir.')),
    lower(trim(E'Peyva "pênûs" "kalem" anlamına gelir.')),
    lower(trim(E'Peyva "ciwan" "kadın" anlamına gelir.')),
    lower(trim(E'What is the capital city of Eswatini?')),
    lower(trim(E'Peyva "derya" "deniz" anlamına gelir.')),
    lower(trim(E'Peyva "kursî" "yatak" anlamına gelir.')),
    lower(trim(E'Peyva "bihîstin" "su" anlamına gelir.')),
    lower(trim(E'Peyva "heyv" "rüzgar" anlamına gelir.')),
    lower(trim(E'Peyva "biçûk" "küçük" anlamına gelir.')),
    lower(trim(E'Peyva "çûn" "oturmak" anlamına gelir.')),
    lower(trim(E'Peyva "derî" "pencere" anlamına gelir.')),
    lower(trim(E'Peyva "derya" "yıldız" anlamına gelir.')),
    lower(trim(E'Peyva "stêrk" "yıldız" anlamına gelir.')),
    lower(trim(E'Peyva "av" "gün/güneş" anlamına gelir.')),
    lower(trim(E'Peyva "zanîn" "gelmek" anlamına gelir.')),
    lower(trim(E'Peyva "hatin" "gelmek" anlamına gelir.')),
    lower(trim(E'Peyva "dil" "kalp/dil" anlamına gelir.')),
    lower(trim(E'What is the capital city of Palestine?')),
    lower(trim(E'Peyva "mamoste" "gece" anlamına gelir.')),
    lower(trim(E'What is the capital city of Sri Lanka?')),
    lower(trim(E'Peyva "zanîn" "bilmek" anlamına gelir.')),
    lower(trim(E'Peyva "xanî" "bina/ev" anlamına gelir.')),
    lower(trim(E'Peyva "cîhan" "sevmek" anlamına gelir.')),
    lower(trim(E'Peyva "dîtin" "işitmek" anlamına gelir.')),
    lower(trim(E'Peyva "roj" "gün/güneş" anlamına gelir.')),
    lower(trim(E'Peyva "pirtûk" "bilmek" anlamına gelir.')),
    lower(trim(E'Peyva "mase" "sandalye" anlamına gelir.')),
    lower(trim(E'Peyva "zarok" "öğrenci" anlamına gelir.')),
    lower(trim(E'What is the elevation listed for Manuk?')),
    lower(trim(E'Peyva "pir" "başlangıç" anlamına gelir.')),
    lower(trim(E'Peyva "spas" "teşekkür" anlamına gelir.')),
    lower(trim(E'Peyva "dibistan" "okul" anlamına gelir.')),
    lower(trim(E'Peyva "çiya" "kalp/dil" anlamına gelir.')),
    lower(trim(E'Peyva "heval" "arkadaş" anlamına gelir.')),
    lower(trim(E'Peyva "kursî" "sandalye" anlamına gelir.')),
    lower(trim(E'What is the elevation listed for Tacora?')),
    lower(trim(E'Peyva "xweş" "güzel/iyi" anlamına gelir.')),
    lower(trim(E'Peyva "xwendin" "okumak" anlamına gelir.')),
    lower(trim(E'Peyva "xwendin" "yazmak" anlamına gelir.')),
    lower(trim(E'Peyva "axaftin" "görmek" anlamına gelir.')),
    lower(trim(E'Peyva "nanpêj" "fırıncı" anlamına gelir.')),
    lower(trim(E'Peyva "teşt" "yemekhane" anlamına gelir.')),
    lower(trim(E'Peyva "gund" "ülke/vatan" anlamına gelir.')),
    lower(trim(E'Peyva "xwendekar" "doğru" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "rû" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "xwendegeh" "kalem" anlamına gelir.')),
    lower(trim(E'What is the elevation listed for Ollagüe?')),
    lower(trim(E'Di Kurmancî de peyva "ax" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "av" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "hezkirin" "sevmek" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "rê" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "bira" "kız kardeş" anlamına gelir.')),
    lower(trim(E'What is the capital city of South Africa?')),
    lower(trim(E'Peyva "hezkirin" "okumak" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "dê" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "pê" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "rûniştin" "oturmak" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "nan" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kal" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "sar" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "şêr" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "çav" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "nav" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "îro" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "dar" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "mal" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "guh" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "jin" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "mêr" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "kanî" "çeşme/pınar" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "bav" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "dev" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "mamoste" "öğretmen" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "ser" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "roj" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kar" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "poz" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "çûn" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "rûniştin" "kalkmak" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "pir" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "axaftin" "konuşmak" anlamına gelir.')),
    lower(trim(E'What is the elevation listed for Damavand?')),
    lower(trim(E'Di Kurmancî de peyva "duh" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "pîr" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "dil" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "xwîşk" "kız kardeş" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "şev" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "dest" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "reng" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "hesp" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "çiya" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "pîr" "yaşlı/ihtiyar" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "bira" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "dibistan" "öğretmen" anlamına gelir.')),
    lower(trim(E'Peyva "nivîsandin" "yazmak" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "hewa" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "heyv" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "teşt" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "mase" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "derî" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "deşt" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kanî" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "nanxane" "yemekhane" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "xanî" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "xweş" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "bira" "erkek kardeş" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "berf" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "destpêk" "başlangıç" anlamına gelir.')),
    lower(trim(E'Peyva "xwendekar" "öğrenci" anlamına gelir.')),
    lower(trim(E'Peyva "nivîsandin" "gitmek" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "deng" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kurd" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "wêne" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "zarok" bi Tirkî çi ye?')),
    lower(trim(E'What is the elevation listed for Acamarachi?')),
    lower(trim(E'Di Kurmancî de peyva "kevin" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "bajar" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "cîhan" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "stêrk" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "diran" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "heval" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "derya" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "nivîn" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "rabûn" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "newal" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "xwîşk" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "hatin" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kaxiz" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kûçik" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "huner" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kursî" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "ciwan" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "pênûs" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "zanîn" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "welat" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "baran" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "biçûk" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "reng" "yaşlı/ihtiyar" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "dîtin" bi Tirkî çi ye?')),
    lower(trim(E'What is the elevation listed for Mount Agung?')),
    lower(trim(E'Peyva "wêne" "resim/fotoğraf" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "malbat" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "malbat" "erkek kardeş" anlamına gelir.')),
    lower(trim(E'What is the elevation listed for Olca-Paruma?')),
    lower(trim(E'What is the elevation listed for Karangetang?')),
    lower(trim(E'Di Kurmancî de peyva "pirtûk" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "xwendin" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "nanxane" "okul/akademi" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "axaftin" bi Tirkî çi ye?')),
    lower(trim(E'What is the capital city of Kashmir Sultanate?')),
    lower(trim(E'What is the elevation listed for Popocatépetl?')),
    lower(trim(E'Di Kurmancî de peyva "pencere" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "nanxane" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "mamoste" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "kaxiz" "resim/fotoğraf" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "destpêk" bi Tirkî çi ye?')),
    lower(trim(E'What is the elevation listed for Sarychev Peak?')),
    lower(trim(E'What is the elevation listed for Mount Sumbing?')),
    lower(trim(E'"su" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Di Kurmancî de peyva "bihîstin" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "hezkirin" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "rûniştin" bi Tirkî çi ye?')),
    lower(trim(E'"ev" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"diş" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"dil" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yol" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Peyva "xwendegeh" "okul/akademi" anlamına gelir.')),
    lower(trim(E'"saç" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"çok" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"köy" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Di Kurmancî de peyva "xwendekar" bi Tirkî çi ye?')),
    lower(trim(E'"göz" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"dağ" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Di Kurmancî de peyva "xwendegeh" bi Tirkî çi ye?')),
    lower(trim(E'"dede" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ağaç" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"eski" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"Kürt" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kapı" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"anne" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Di Kurmancî de peyva "nivîsandin" bi Tirkî çi ye?')),
    lower(trim(E'"renk" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Peyva "dapîr" "anneanne/babaanne" anlamına gelir.')),
    lower(trim(E'"genç" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"baba" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ateş" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"okul" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kaya" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kedi" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ayak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"aile" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ağız" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"hava" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"masa" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"çocuk" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kağıt" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"sanat" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"erkek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"küçük" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"leğen" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"aslan" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"soğuk" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"bugün" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yatak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kulak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"deniz" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kitap" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kalem" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"dünya" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"şehir" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"doğru" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ekmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"görmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'What is the atomic number of the element strontium?')),
    lower(trim(E'"sevmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"toprak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"gelmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"gitmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"bilmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"okumak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yağmur" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"rüzgar" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yazmak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"öğrenci" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"arkadaş" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"bina/ev" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'What is the capital city of Principality of Waldeck?')),
    lower(trim(E'"pencere" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"işitmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"oturmak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ad/isim" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kalkmak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"fırıncı" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"baş/kafa" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"sandalye" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"öğretmen" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kalp/dil" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"teşekkür" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"güzel/iyi" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yemekhane" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"gün/güneş" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"başlangıç" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ülke/vatan" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"çeşme/pınar" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"erkek kardeş" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"okul/akademi" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yaşlı/ihtiyar" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'What is an official or national language associated with Iraq?')),
    lower(trim(E'What is an official or national language associated with Chad?')),
    lower(trim(E'What is an official or national language associated with Mali?')),
    lower(trim(E'What is an official or national language associated with Malta?')),
    lower(trim(E'What is an official or national language associated with Palau?')),
    lower(trim(E'What is an official or national language associated with Haiti?')),
    lower(trim(E'What is an official or national language associated with Nauru?')),
    lower(trim(E'What is an official or national language associated with India?')),
    lower(trim(E'What is an official or national language associated with Kenya?')),
    lower(trim(E'What is an official or national language associated with Brunei?')),
    lower(trim(E'What is an official or national language associated with Cyprus?')),
    lower(trim(E'What is an official or national language associated with Norway?')),
    lower(trim(E'What is an official or national language associated with Mexico?')),
    lower(trim(E'What is an official or national language associated with Canada?')),
    lower(trim(E'What is an official or national language associated with Finland?')),
    lower(trim(E'What is an official or national language associated with Belgium?')),
    lower(trim(E'What is an official or national language associated with Jamaica?')),
    lower(trim(E'What is an official or national language associated with Grenada?')),
    lower(trim(E'What is an official or national language associated with Ecuador?')),
    lower(trim(E'What is an official or national language associated with Ireland?')),
    lower(trim(E'What is an official or national language associated with Belarus?')),
    lower(trim(E'What is an official or national language associated with Austria?')),
    lower(trim(E'What is an official or national language associated with Bolivia?')),
    lower(trim(E'What is an official or national language associated with Zimbabwe?')),
    lower(trim(E'What is an official or national language associated with Pakistan?')),
    lower(trim(E'What is an official or national language associated with Paraguay?')),
    lower(trim(E'What is an official or national language associated with Barbados?')),
    lower(trim(E'What is an official or national language associated with Tanzania?')),
    lower(trim(E'What is an official or national language associated with Venezuela?')),
    lower(trim(E'What is an official or national language associated with Australia?')),
    lower(trim(E'What is an official or national language associated with Sri Lanka?')),
    lower(trim(E'What is an official or national language associated with Singapore?')),
    lower(trim(E'What is an official or national language associated with Luxembourg?')),
    lower(trim(E'What is an official or national language associated with Azerbaijan?')),
    lower(trim(E'What is an official or national language associated with Kazakhstan?')),
    lower(trim(E'What is an official or national language associated with Timor-Leste?')),
    lower(trim(E'What is an official or national language associated with Philippines?')),
    lower(trim(E'What is an official or national language associated with Afghanistan?')),
    lower(trim(E'What is an official or national language associated with New Zealand?')),
    lower(trim(E'What is an official or national language associated with South Korea?')),
    lower(trim(E'What is an official or national language associated with Switzerland?')),
    lower(trim(E'What is an official or national language associated with South Africa?')),
    lower(trim(E'What is an official or national language associated with Vatican City?')),
    lower(trim(E'What is an official or national language associated with United States?')),
    lower(trim(E'What is an official or national language associated with North Macedonia?')),
    lower(trim(E'What is an official or national language associated with Marshall Islands?')),
    lower(trim(E'What is an official or national language associated with Papua New Guinea?')),
    lower(trim(E'What is an official or national language associated with Bosnia and Herzegovina?')),
    lower(trim(E'What is an official or national language associated with Central African Republic?'))
  )
ORDER BY q.prompt, q.created_at;

-- ============================================================
-- BOLUM 2: UPDATE — Tekrar sorulari devre disi birak
-- ============================================================

BEGIN;
-- Hata olursa asagidaki satirin yorumunu kaldir ve calistir:
-- ROLLBACK;

-- 1211 soru devre disi birakilacak.
-- 405 temsilci korunacak.

UPDATE public.questions
SET is_approved = false,
    review_status = 'rejected',
    reviewed_by = 'dedup_migration',
    reviewed_at = NOW()
WHERE is_approved = true
  AND lower(trim(prompt)) IN (
    lower(trim(E'What is the area of Sudan?')),
    lower(trim(E'Who painted the Mona Lisa?')),
    lower(trim(E'What is the area of Mexico?')),
    lower(trim(E'What is the area of Latvia?')),
    lower(trim(E'Peyva "av" "su" anlamına gelir.')),
    lower(trim(E'Peyva "rû" "yüz" anlamına gelir.')),
    lower(trim(E'Peyva "roj" "ev" anlamına gelir.')),
    lower(trim(E'Peyva "dê" "anne" anlamına gelir.')),
    lower(trim(E'Peyva "çav" "göz" anlamına gelir.')),
    lower(trim(E'Peyva "pir" "çok" anlamına gelir.')),
    lower(trim(E'Peyva "hesp" "at" anlamına gelir.')),
    lower(trim(E'Peyva "por" "saç" anlamına gelir.')),
    lower(trim(E'Peyva "duh" "dün" anlamına gelir.')),
    lower(trim(E'Peyva "heyv" "ay" anlamına gelir.')),
    lower(trim(E'Peyva "gul" "gül" anlamına gelir.')),
    lower(trim(E'Peyva "îro" "dün" anlamına gelir.')),
    lower(trim(E'Peyva "pê" "ayak" anlamına gelir.')),
    lower(trim(E'Peyva "dev" "diş" anlamına gelir.')),
    lower(trim(E'Peyva "guh" "göz" anlamına gelir.')),
    lower(trim(E'Peyva "çem" "vadi" anlamına gelir.')),
    lower(trim(E'Peyva "poz" "ağız" anlamına gelir.')),
    lower(trim(E'Peyva "pîr" "genç" anlamına gelir.')),
    lower(trim(E'Peyva "dev" "ağız" anlamına gelir.')),
    lower(trim(E'Peyva "dar" "ağaç" anlamına gelir.')),
    lower(trim(E'Peyva "deng" "ses" anlamına gelir.')),
    lower(trim(E'Peyva "bav" "dede" anlamına gelir.')),
    lower(trim(E'Peyva "gund" "köy" anlamına gelir.')),
    lower(trim(E'Peyva "wêne" "ses" anlamına gelir.')),
    lower(trim(E'What is the capital city of Yemen?')),
    lower(trim(E'Peyva "mêr" "aile" anlamına gelir.')),
    lower(trim(E'Peyva "kal" "dede" anlamına gelir.')),
    lower(trim(E'Peyva "deşt" "ova" anlamına gelir.')),
    lower(trim(E'Peyva "stêrk" "ay" anlamına gelir.')),
    lower(trim(E'Peyva "nan" "ekmek" anlamına gelir.')),
    lower(trim(E'Peyva "dest" "ayak" anlamına gelir.')),
    lower(trim(E'Peyva "huner" "yüz" anlamına gelir.')),
    lower(trim(E'Peyva "baran" "kar" anlamına gelir.')),
    lower(trim(E'Peyva "sar" "küçük" anlamına gelir.')),
    lower(trim(E'Peyva "sar" "soğuk" anlamına gelir.')),
    lower(trim(E'Peyva "diran" "diş" anlamına gelir.')),
    lower(trim(E'Peyva "kar" "sanat" anlamına gelir.')),
    lower(trim(E'Peyva "poz" "burun" anlamına gelir.')),
    lower(trim(E'Peyva "hewa" "hava" anlamına gelir.')),
    lower(trim(E'Peyva "derî" "kapı" anlamına gelir.')),
    lower(trim(E'Peyva "nav" "çocuk" anlamına gelir.')),
    lower(trim(E'Peyva "ba" "yağmur" anlamına gelir.')),
    lower(trim(E'Peyva "mal" "kitap" anlamına gelir.')),
    lower(trim(E'Peyva "dapîr" "köy" anlamına gelir.')),
    lower(trim(E'Peyva "îro" "bugün" anlamına gelir.')),
    lower(trim(E'Peyva "deşt" "kaya" anlamına gelir.')),
    lower(trim(E'Peyva "agir" "ateş" anlamına gelir.')),
    lower(trim(E'Peyva "şev" "deniz" anlamına gelir.')),
    lower(trim(E'Peyva "nanpêj" "iş" anlamına gelir.')),
    lower(trim(E'Peyva "şêr" "köpek" anlamına gelir.')),
    lower(trim(E'Peyva "hatin" "dağ" anlamına gelir.')),
    lower(trim(E'Peyva "ba" "rüzgar" anlamına gelir.')),
    lower(trim(E'Peyva "ziman" "dil" anlamına gelir.')),
    lower(trim(E'Peyva "newal" "ova" anlamına gelir.')),
    lower(trim(E'Peyva "reng" "renk" anlamına gelir.')),
    lower(trim(E'Peyva "şêr" "aslan" anlamına gelir.')),
    lower(trim(E'Peyva "berf" "ateş" anlamına gelir.')),
    lower(trim(E'Peyva "kûçik" "kedi" anlamına gelir.')),
    lower(trim(E'How many sides does a heptagon have?')),
    lower(trim(E'Peyva "pisîk" "kedi" anlamına gelir.')),
    lower(trim(E'Peyva "zinar" "kaya" anlamına gelir.')),
    lower(trim(E'Peyva "çûn" "gitmek" anlamına gelir.')),
    lower(trim(E'Peyva "ziman" "okul" anlamına gelir.')),
    lower(trim(E'Peyva "rast" "doğru" anlamına gelir.')),
    lower(trim(E'Peyva "teşt" "leğen" anlamına gelir.')),
    lower(trim(E'Peyva "ciwan" "genç" anlamına gelir.')),
    lower(trim(E'What is the capital city of Bolivia?')),
    lower(trim(E'Peyva "hesp" "aslan" anlamına gelir.')),
    lower(trim(E'Peyva "kevin" "eski" anlamına gelir.')),
    lower(trim(E'Peyva "heval" "şehir" anlamına gelir.')),
    lower(trim(E'Peyva "cîhan" "dünya" anlamına gelir.')),
    lower(trim(E'Peyva "dil" "arkadaş" anlamına gelir.')),
    lower(trim(E'Peyva "bajar" "şehir" anlamına gelir.')),
    lower(trim(E'Peyva "malbat" "aile" anlamına gelir.')),
    lower(trim(E'Peyva "agir" "toprak" anlamına gelir.')),
    lower(trim(E'Peyva "huner" "sanat" anlamına gelir.')),
    lower(trim(E'Peyva "zarok" "çocuk" anlamına gelir.')),
    lower(trim(E'Peyva "nav" "ad/isim" anlamına gelir.')),
    lower(trim(E'Peyva "por" "bina/ev" anlamına gelir.')),
    lower(trim(E'Peyva "bajar" "ekmek" anlamına gelir.')),
    lower(trim(E'Peyva "kûçik" "köpek" anlamına gelir.')),
    lower(trim(E'Peyva "rê" "teşekkür" anlamına gelir.')),
    lower(trim(E'Peyva "welat" "dünya" anlamına gelir.')),
    lower(trim(E'Peyva "pisîk" "nehir" anlamına gelir.')),
    lower(trim(E'Peyva "pê" "baş/kafa" anlamına gelir.')),
    lower(trim(E'Peyva "duh" "ad/isim" anlamına gelir.')),
    lower(trim(E'Peyva "pênûs" "kalem" anlamına gelir.')),
    lower(trim(E'Peyva "ciwan" "kadın" anlamına gelir.')),
    lower(trim(E'What is the capital city of Eswatini?')),
    lower(trim(E'Peyva "derya" "deniz" anlamına gelir.')),
    lower(trim(E'Peyva "kursî" "yatak" anlamına gelir.')),
    lower(trim(E'Peyva "bihîstin" "su" anlamına gelir.')),
    lower(trim(E'Peyva "heyv" "rüzgar" anlamına gelir.')),
    lower(trim(E'Peyva "biçûk" "küçük" anlamına gelir.')),
    lower(trim(E'Peyva "çûn" "oturmak" anlamına gelir.')),
    lower(trim(E'Peyva "derî" "pencere" anlamına gelir.')),
    lower(trim(E'Peyva "derya" "yıldız" anlamına gelir.')),
    lower(trim(E'Peyva "stêrk" "yıldız" anlamına gelir.')),
    lower(trim(E'Peyva "av" "gün/güneş" anlamına gelir.')),
    lower(trim(E'Peyva "zanîn" "gelmek" anlamına gelir.')),
    lower(trim(E'Peyva "hatin" "gelmek" anlamına gelir.')),
    lower(trim(E'Peyva "dil" "kalp/dil" anlamına gelir.')),
    lower(trim(E'What is the capital city of Palestine?')),
    lower(trim(E'Peyva "mamoste" "gece" anlamına gelir.')),
    lower(trim(E'What is the capital city of Sri Lanka?')),
    lower(trim(E'Peyva "zanîn" "bilmek" anlamına gelir.')),
    lower(trim(E'Peyva "xanî" "bina/ev" anlamına gelir.')),
    lower(trim(E'Peyva "cîhan" "sevmek" anlamına gelir.')),
    lower(trim(E'Peyva "dîtin" "işitmek" anlamına gelir.')),
    lower(trim(E'Peyva "roj" "gün/güneş" anlamına gelir.')),
    lower(trim(E'Peyva "pirtûk" "bilmek" anlamına gelir.')),
    lower(trim(E'Peyva "mase" "sandalye" anlamına gelir.')),
    lower(trim(E'Peyva "zarok" "öğrenci" anlamına gelir.')),
    lower(trim(E'What is the elevation listed for Manuk?')),
    lower(trim(E'Peyva "pir" "başlangıç" anlamına gelir.')),
    lower(trim(E'Peyva "spas" "teşekkür" anlamına gelir.')),
    lower(trim(E'Peyva "dibistan" "okul" anlamına gelir.')),
    lower(trim(E'Peyva "çiya" "kalp/dil" anlamına gelir.')),
    lower(trim(E'Peyva "heval" "arkadaş" anlamına gelir.')),
    lower(trim(E'Peyva "kursî" "sandalye" anlamına gelir.')),
    lower(trim(E'What is the elevation listed for Tacora?')),
    lower(trim(E'Peyva "xweş" "güzel/iyi" anlamına gelir.')),
    lower(trim(E'Peyva "xwendin" "okumak" anlamına gelir.')),
    lower(trim(E'Peyva "xwendin" "yazmak" anlamına gelir.')),
    lower(trim(E'Peyva "axaftin" "görmek" anlamına gelir.')),
    lower(trim(E'Peyva "nanpêj" "fırıncı" anlamına gelir.')),
    lower(trim(E'Peyva "teşt" "yemekhane" anlamına gelir.')),
    lower(trim(E'Peyva "gund" "ülke/vatan" anlamına gelir.')),
    lower(trim(E'Peyva "xwendekar" "doğru" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "rû" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "xwendegeh" "kalem" anlamına gelir.')),
    lower(trim(E'What is the elevation listed for Ollagüe?')),
    lower(trim(E'Di Kurmancî de peyva "ax" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "av" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "hezkirin" "sevmek" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "rê" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "bira" "kız kardeş" anlamına gelir.')),
    lower(trim(E'What is the capital city of South Africa?')),
    lower(trim(E'Peyva "hezkirin" "okumak" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "dê" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "pê" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "rûniştin" "oturmak" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "nan" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kal" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "sar" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "şêr" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "çav" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "nav" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "îro" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "dar" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "mal" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "guh" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "jin" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "mêr" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "kanî" "çeşme/pınar" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "bav" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "dev" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "mamoste" "öğretmen" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "ser" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "roj" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kar" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "poz" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "çûn" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "rûniştin" "kalkmak" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "pir" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "axaftin" "konuşmak" anlamına gelir.')),
    lower(trim(E'What is the elevation listed for Damavand?')),
    lower(trim(E'Di Kurmancî de peyva "duh" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "pîr" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "dil" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "xwîşk" "kız kardeş" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "şev" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "dest" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "reng" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "hesp" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "çiya" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "pîr" "yaşlı/ihtiyar" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "bira" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "dibistan" "öğretmen" anlamına gelir.')),
    lower(trim(E'Peyva "nivîsandin" "yazmak" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "hewa" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "heyv" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "teşt" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "mase" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "derî" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "deşt" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kanî" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "nanxane" "yemekhane" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "xanî" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "xweş" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "bira" "erkek kardeş" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "berf" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "destpêk" "başlangıç" anlamına gelir.')),
    lower(trim(E'Peyva "xwendekar" "öğrenci" anlamına gelir.')),
    lower(trim(E'Peyva "nivîsandin" "gitmek" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "deng" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kurd" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "wêne" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "zarok" bi Tirkî çi ye?')),
    lower(trim(E'What is the elevation listed for Acamarachi?')),
    lower(trim(E'Di Kurmancî de peyva "kevin" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "bajar" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "cîhan" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "stêrk" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "diran" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "heval" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "derya" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "nivîn" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "rabûn" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "newal" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "xwîşk" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "hatin" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kaxiz" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kûçik" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "huner" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "kursî" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "ciwan" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "pênûs" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "zanîn" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "welat" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "baran" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "biçûk" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "reng" "yaşlı/ihtiyar" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "dîtin" bi Tirkî çi ye?')),
    lower(trim(E'What is the elevation listed for Mount Agung?')),
    lower(trim(E'Peyva "wêne" "resim/fotoğraf" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "malbat" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "malbat" "erkek kardeş" anlamına gelir.')),
    lower(trim(E'What is the elevation listed for Olca-Paruma?')),
    lower(trim(E'What is the elevation listed for Karangetang?')),
    lower(trim(E'Di Kurmancî de peyva "pirtûk" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "xwendin" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "nanxane" "okul/akademi" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "axaftin" bi Tirkî çi ye?')),
    lower(trim(E'What is the capital city of Kashmir Sultanate?')),
    lower(trim(E'What is the elevation listed for Popocatépetl?')),
    lower(trim(E'Di Kurmancî de peyva "pencere" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "nanxane" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "mamoste" bi Tirkî çi ye?')),
    lower(trim(E'Peyva "kaxiz" "resim/fotoğraf" anlamına gelir.')),
    lower(trim(E'Di Kurmancî de peyva "destpêk" bi Tirkî çi ye?')),
    lower(trim(E'What is the elevation listed for Sarychev Peak?')),
    lower(trim(E'What is the elevation listed for Mount Sumbing?')),
    lower(trim(E'"su" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Di Kurmancî de peyva "bihîstin" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "hezkirin" bi Tirkî çi ye?')),
    lower(trim(E'Di Kurmancî de peyva "rûniştin" bi Tirkî çi ye?')),
    lower(trim(E'"ev" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"diş" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"dil" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yol" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Peyva "xwendegeh" "okul/akademi" anlamına gelir.')),
    lower(trim(E'"saç" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"çok" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"köy" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Di Kurmancî de peyva "xwendekar" bi Tirkî çi ye?')),
    lower(trim(E'"göz" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"dağ" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Di Kurmancî de peyva "xwendegeh" bi Tirkî çi ye?')),
    lower(trim(E'"dede" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ağaç" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"eski" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"Kürt" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kapı" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"anne" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Di Kurmancî de peyva "nivîsandin" bi Tirkî çi ye?')),
    lower(trim(E'"renk" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'Peyva "dapîr" "anneanne/babaanne" anlamına gelir.')),
    lower(trim(E'"genç" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"baba" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ateş" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"okul" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kaya" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kedi" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ayak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"aile" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ağız" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"hava" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"masa" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"çocuk" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kağıt" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"sanat" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"erkek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"küçük" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"leğen" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"aslan" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"soğuk" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"bugün" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yatak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kulak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"deniz" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kitap" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kalem" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"dünya" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"şehir" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"doğru" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ekmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"görmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'What is the atomic number of the element strontium?')),
    lower(trim(E'"sevmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"toprak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"gelmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"gitmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"bilmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"okumak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yağmur" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"rüzgar" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yazmak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"öğrenci" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"arkadaş" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"bina/ev" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'What is the capital city of Principality of Waldeck?')),
    lower(trim(E'"pencere" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"işitmek" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"oturmak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ad/isim" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kalkmak" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"fırıncı" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"baş/kafa" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"sandalye" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"öğretmen" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"kalp/dil" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"teşekkür" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"güzel/iyi" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yemekhane" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"gün/güneş" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"başlangıç" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"ülke/vatan" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"çeşme/pınar" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"erkek kardeş" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"okul/akademi" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'"yaşlı/ihtiyar" anlamına gelen Kurmancî kelime hangisidir?')),
    lower(trim(E'What is an official or national language associated with Iraq?')),
    lower(trim(E'What is an official or national language associated with Chad?')),
    lower(trim(E'What is an official or national language associated with Mali?')),
    lower(trim(E'What is an official or national language associated with Malta?')),
    lower(trim(E'What is an official or national language associated with Palau?')),
    lower(trim(E'What is an official or national language associated with Haiti?')),
    lower(trim(E'What is an official or national language associated with Nauru?')),
    lower(trim(E'What is an official or national language associated with India?')),
    lower(trim(E'What is an official or national language associated with Kenya?')),
    lower(trim(E'What is an official or national language associated with Brunei?')),
    lower(trim(E'What is an official or national language associated with Cyprus?')),
    lower(trim(E'What is an official or national language associated with Norway?')),
    lower(trim(E'What is an official or national language associated with Mexico?')),
    lower(trim(E'What is an official or national language associated with Canada?')),
    lower(trim(E'What is an official or national language associated with Finland?')),
    lower(trim(E'What is an official or national language associated with Belgium?')),
    lower(trim(E'What is an official or national language associated with Jamaica?')),
    lower(trim(E'What is an official or national language associated with Grenada?')),
    lower(trim(E'What is an official or national language associated with Ecuador?')),
    lower(trim(E'What is an official or national language associated with Ireland?')),
    lower(trim(E'What is an official or national language associated with Belarus?')),
    lower(trim(E'What is an official or national language associated with Austria?')),
    lower(trim(E'What is an official or national language associated with Bolivia?')),
    lower(trim(E'What is an official or national language associated with Zimbabwe?')),
    lower(trim(E'What is an official or national language associated with Pakistan?')),
    lower(trim(E'What is an official or national language associated with Paraguay?')),
    lower(trim(E'What is an official or national language associated with Barbados?')),
    lower(trim(E'What is an official or national language associated with Tanzania?')),
    lower(trim(E'What is an official or national language associated with Venezuela?')),
    lower(trim(E'What is an official or national language associated with Australia?')),
    lower(trim(E'What is an official or national language associated with Sri Lanka?')),
    lower(trim(E'What is an official or national language associated with Singapore?')),
    lower(trim(E'What is an official or national language associated with Luxembourg?')),
    lower(trim(E'What is an official or national language associated with Azerbaijan?')),
    lower(trim(E'What is an official or national language associated with Kazakhstan?')),
    lower(trim(E'What is an official or national language associated with Timor-Leste?')),
    lower(trim(E'What is an official or national language associated with Philippines?')),
    lower(trim(E'What is an official or national language associated with Afghanistan?')),
    lower(trim(E'What is an official or national language associated with New Zealand?')),
    lower(trim(E'What is an official or national language associated with South Korea?')),
    lower(trim(E'What is an official or national language associated with Switzerland?')),
    lower(trim(E'What is an official or national language associated with South Africa?')),
    lower(trim(E'What is an official or national language associated with Vatican City?')),
    lower(trim(E'What is an official or national language associated with United States?')),
    lower(trim(E'What is an official or national language associated with North Macedonia?')),
    lower(trim(E'What is an official or national language associated with Marshall Islands?')),
    lower(trim(E'What is an official or national language associated with Papua New Guinea?')),
    lower(trim(E'What is an official or national language associated with Bosnia and Herzegovina?')),
    lower(trim(E'What is an official or national language associated with Central African Republic?'))
  )
  AND id NOT IN (
    -- Her tekrar kümesinden 1 temsilci korunur
    SELECT DISTINCT ON (lower(trim(prompt))) id
    FROM public.questions
    WHERE is_approved = true
    ORDER BY lower(trim(prompt)),
             COALESCE(quality_version, 0) DESC,
             created_at ASC,
             id ASC
  );

-- ============================================================
-- BOLUM 3: DOGRULAMA — Etki raporu
-- ============================================================

SELECT
  count(*) AS toplam_soru,
  count(*) FILTER (WHERE is_approved = true) AS onayli_soru,
  count(*) FILTER (WHERE is_approved = false) AS devre_disi_soru,
  count(*) FILTER (WHERE reviewed_by = 'dedup_migration') AS bu_migrasyon_etkilenen
FROM public.questions;

COMMIT;

