-- 2026-07-16 Editoryal içerik düzeltmesi (canlı `questions` tablosu)
-- Kapsam:
--   * 98 adet '"X" anlamına gelen Kurmancî kelime hangisidir?' sorusu:
--     Kurmancî prompt ('Bi Kurmancî "X" çi ye?') + tamamı Kurmancî,
--     anlamca ilgili çeldiriciler. Doğru şıkkın metni ve harfi DEĞİŞMEZ
--     (her UPDATE 'and correct_option = ...' guard'ı taşır).
--   * 25 adet 'Görsel etiketi "X" ...' görsel sorusu: Kurmancî prompt +
--     makul Türkçe anlam çeldiricileri; kendi kelimesini sızdıran şıklar
--     temizlendi.
--   * 1 adet 'Azadî' sorusu (Paradigma) aynı biçimde.
--   * 67 adet şablon/meta çöp soru onaydan kaldırıldı (is_approved=false):
--     40 'Görseldeki ... etiketi hangi kategoriye aittir' (cevap kendini
--     söylüyor), 10 'kavramının en uygun açıklaması' (alakasız çeldirici),
--     7 uygulama-meta soru, 3 tutarsız çeldiricili şablon, 7 Cografya
--     kelime kopyası (Ziman'da temiz eşleri var/oluşturuldu).
-- GERİ ALMA: önce aşağıdaki yedek tablo oluşur; geri almak için
--   update questions q set (prompt, option_a, option_b, option_c, option_d,
--     explanation, explanation_ku, explanation_tr, is_approved) =
--     (b.prompt, b.option_a, b.option_b, b.option_c, b.option_d,
--      b.explanation, b.explanation_ku, b.explanation_tr, b.is_approved)
--   from questions_editorial_backup_20260716 b where b.id = q.id;

begin;

-- 0) Yedek
create table if not exists questions_editorial_backup_20260716
  as select * from questions where false;
insert into questions_editorial_backup_20260716
select q.* from questions q
where (q.prompt ~ '(anlamına gelen Kurmancî kelime hangisidir|Görsel etiketi|için en uygun Kurmancî kelime hangisidir)'
   or q.prompt like 'Görseldeki%'
   or q.id in ('864fb775-5b1b-44fd-9639-8063354cf5ee','062bae5f-d77b-4036-941f-b88f9404c8d2','83c425e3-2f4e-480e-ae4d-5a5cca36a6f5','afaebb4b-f289-4a90-9eef-3a7826f10ff5','0bc50001-3f83-4921-b171-f26e3982dfa7','5ea9ca1c-5156-4864-b7b2-e0c523b6397b','0990fe06-0f38-4e76-b864-3ea9cdac5b5b','9d5633ab-7200-4d19-9c47-424ddae1b8a0','45b54f6d-d525-4b9f-8dc0-4b1ebb36b17e','4da636fc-baed-4c8b-9795-a98ca709f11b','fbca7a26-c71f-4580-9a93-25377d77bf89','0df0734e-919d-4c55-9582-aba44d08888c','ba67c63d-4ec7-479d-aa8d-f7616eae68e5','335fcaa5-a4a1-4abe-817f-6e5f098dfe55','82101517-b74d-468c-8dce-66469c95a6bb','b534f72b-4bdd-428a-880c-4ed7f5ab0235','de027933-ef50-4f3f-bb71-ec36b81ebabe','7e509c37-d251-4f4c-85df-df55f423afcc','1e7b509a-3cb6-4f08-8611-0e336538571c','23a787d9-9597-4e58-bc4d-68ef35498146','6229c06e-c055-4769-8e26-71ec63f84aba'))
  and not exists (select 1 from questions_editorial_backup_20260716 b where b.id = q.id);

-- 1) Düzeltmeler
update questions set prompt = 'Bi Kurmancî "ad/isim" çi ye?', option_a = 'Deng', option_b = 'Reng', option_c = 'Nav', option_d = 'Peyv', explanation = '"Nav", Türkçe "ad/isim" demektir.', explanation_ku = '"Nav" bi Tirkî "ad/isim" e.', explanation_tr = '"Nav", Türkçe "ad/isim" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '24966e14-dcc0-485f-8558-22a97ad743c1' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "ağaç" çi ye?', option_a = 'Dar', option_b = 'Kulîlk', option_c = 'Gul', option_d = 'Giya', explanation = '"Dar", Türkçe "ağaç" demektir.', explanation_ku = '"Dar" bi Tirkî "ağaç" e.', explanation_tr = '"Dar", Türkçe "ağaç" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '672d345c-8804-46ee-9c43-72fab80625a5' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "ağız" çi ye?', option_a = 'Dev', option_b = 'Çav', option_c = 'Guh', option_d = 'Poz', explanation = '"Dev", Türkçe "ağız" demektir.', explanation_ku = '"Dev" bi Tirkî "ağız" e.', explanation_tr = '"Dev", Türkçe "ağız" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '4b7932bc-372b-4ee7-a159-613c669fa339' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "aile" çi ye?', option_a = 'Heval', option_b = 'Malbat', option_c = 'Cîran', option_d = 'Mêvan', explanation = '"Malbat", Türkçe "aile" demektir.', explanation_ku = '"Malbat" bi Tirkî "aile" e.', explanation_tr = '"Malbat", Türkçe "aile" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'a5f6b694-0e03-4e8b-a644-4930a95ff9e6' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "anne" çi ye?', option_a = 'Dê', option_b = 'Xwîşk', option_c = 'Met', option_d = 'Xaltî', explanation = '"Dê", Türkçe "anne" demektir.', explanation_ku = '"Dê" bi Tirkî "anne" e.', explanation_tr = '"Dê", Türkçe "anne" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '371dbc0d-f360-4e9b-bb3a-4a0cfa8608e6' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "arkadaş" çi ye?', option_a = 'Cîran', option_b = 'Mêvan', option_c = 'Bira', option_d = 'Heval', explanation = '"Heval", Türkçe "arkadaş" demektir.', explanation_ku = '"Heval" bi Tirkî "arkadaş" e.', explanation_tr = '"Heval", Türkçe "arkadaş" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '3595a796-44b0-43a9-bd92-6b2c42bb4239' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "aslan" çi ye?', option_a = 'Şêr', option_b = 'Gur', option_c = 'Rovî', option_d = 'Hirç', explanation = '"Şêr", Türkçe "aslan" demektir.', explanation_ku = '"Şêr" bi Tirkî "aslan" e.', explanation_tr = '"Şêr", Türkçe "aslan" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '40b9cb58-abad-4422-a544-aa16f9ac32b5' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "at" çi ye?', option_a = 'Hesp', option_b = 'Ker', option_c = 'Çêlek', option_d = 'Mî', explanation = '"Hesp", Türkçe "at" demektir.', explanation_ku = '"Hesp" bi Tirkî "at" e.', explanation_tr = '"Hesp", Türkçe "at" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '236e7770-36b9-4a6f-b9bb-75fcdedf1529' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "ateş" çi ye?', option_a = 'Dûman', option_b = 'Tav', option_c = 'Berf', option_d = 'Agir', explanation = '"Agir", Türkçe "ateş" demektir.', explanation_ku = '"Agir" bi Tirkî "ateş" e.', explanation_tr = '"Agir", Türkçe "ateş" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '578aa4d7-4637-4144-88eb-cf43821f9d38' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "ay" çi ye?', option_a = 'Heyv', option_b = 'Roj', option_c = 'Stêrk', option_d = 'Esman', explanation = '"Heyv", Türkçe "ay" demektir.', explanation_ku = '"Heyv" bi Tirkî "ay" e.', explanation_tr = '"Heyv", Türkçe "ay" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '64dbfe63-b56f-4579-a2d8-85d85be4f228' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "ayak" çi ye?', option_a = 'Dest', option_b = 'Pê', option_c = 'Ser', option_d = 'Guh', explanation = '"Pê", Türkçe "ayak" demektir.', explanation_ku = '"Pê" bi Tirkî "ayak" e.', explanation_tr = '"Pê", Türkçe "ayak" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '30ee3f19-003f-49c8-b003-d852ba072f01' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "baba" çi ye?', option_a = 'Ap', option_b = 'Bav', option_c = 'Xal', option_d = 'Kal', explanation = '"Bav", Türkçe "baba" demektir.', explanation_ku = '"Bav" bi Tirkî "baba" e.', explanation_tr = '"Bav", Türkçe "baba" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '22cee8e3-9b46-4d5d-a18e-3c9f2a5d066e' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "baş/kafa" çi ye?', option_a = 'Ser', option_b = 'Dest', option_c = 'Pê', option_d = 'Mil', explanation = '"Ser", Türkçe "baş/kafa" demektir.', explanation_ku = '"Ser" bi Tirkî "baş/kafa" e.', explanation_tr = '"Ser", Türkçe "baş/kafa" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '5f4d7b0a-3703-4220-a1b7-b87dc8d9add1' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "başlangıç" çi ye?', option_a = 'Dawî', option_b = 'Destpêk', option_c = 'Encam', option_d = 'Navîn', explanation = '"Destpêk", Türkçe "başlangıç" demektir.', explanation_ku = '"Destpêk" bi Tirkî "başlangıç" e.', explanation_tr = '"Destpêk", Türkçe "başlangıç" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '9730f150-65ad-4538-bc3d-d4ccfd469bac' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "bilmek" çi ye?', option_a = 'Dîtin', option_b = 'Zanîn', option_c = 'Bihîstin', option_d = 'Xwendin', explanation = '"Zanîn", Türkçe "bilmek" demektir.', explanation_ku = '"Zanîn" bi Tirkî "bilmek" e.', explanation_tr = '"Zanîn", Türkçe "bilmek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '19438b91-de82-47cb-bbc5-a21bb2f484fb' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "bina/ev" çi ye?', option_a = 'Kon', option_b = 'Xanî', option_c = 'Gund', option_d = 'Derî', explanation = '"Xanî", Türkçe "bina/ev" demektir.', explanation_ku = '"Xanî" bi Tirkî "bina/ev" e.', explanation_tr = '"Xanî", Türkçe "bina/ev" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'f64f5017-d2a4-4be2-baac-b2e641e8bdf9' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "bugün" çi ye?', option_a = 'Duh', option_b = 'Îro', option_c = 'Sibe', option_d = 'Êvar', explanation = '"Îro", Türkçe "bugün" demektir.', explanation_ku = '"Îro" bi Tirkî "bugün" e.', explanation_tr = '"Îro", Türkçe "bugün" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '87cc6939-6331-41b6-b1ac-8088d92f0138' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "çeşme/pınar" çi ye?', option_a = 'Kanî', option_b = 'Çem', option_c = 'Gol', option_d = 'Bîr', explanation = '"Kanî", Türkçe "çeşme/pınar" demektir.', explanation_ku = '"Kanî" bi Tirkî "çeşme/pınar" e.', explanation_tr = '"Kanî", Türkçe "çeşme/pınar" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '463497f4-2e4d-411f-abc1-563555a98679' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "çocuk" çi ye?', option_a = 'Ciwan', option_b = 'Zarok', option_c = 'Pîr', option_d = 'Dapîr', explanation = '"Zarok", Türkçe "çocuk" demektir.', explanation_ku = '"Zarok" bi Tirkî "çocuk" e.', explanation_tr = '"Zarok", Türkçe "çocuk" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '1ec99f5d-e809-4b54-beb8-217a609c0669' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "çok" çi ye?', option_a = 'Hindik', option_b = 'Biçûk', option_c = 'Pir', option_d = 'Mezin', explanation = '"Pir", Türkçe "çok" demektir.', explanation_ku = '"Pir" bi Tirkî "çok" e.', explanation_tr = '"Pir", Türkçe "çok" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '31b42f81-3193-4861-8baf-9e69e49a4610' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "dağ" çi ye?', option_a = 'Deşt', option_b = 'Newal', option_c = 'Çiya', option_d = 'Gir', explanation = '"Çiya", Türkçe "dağ" demektir.', explanation_ku = '"Çiya" bi Tirkî "dağ" e.', explanation_tr = '"Çiya", Türkçe "dağ" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '4639fe38-7fd5-4ee2-b21e-5bc97d970560' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "dede" çi ye?', option_a = 'Bav', option_b = 'Ap', option_c = 'Kal', option_d = 'Xal', explanation = '"Kal", Türkçe "dede" demektir.', explanation_ku = '"Kal" bi Tirkî "dede" e.', explanation_tr = '"Kal", Türkçe "dede" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '31aa9ce1-32d6-4b0b-b42f-f134694f6906' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "deniz" çi ye?', option_a = 'Derya', option_b = 'Çem', option_c = 'Gol', option_d = 'Kanî', explanation = '"Derya", Türkçe "deniz" demektir.', explanation_ku = '"Derya" bi Tirkî "deniz" e.', explanation_tr = '"Derya", Türkçe "deniz" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '5e9c2063-2628-4c33-b32c-0d7b4c86aef3' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "dil" çi ye?', option_a = 'Deng', option_b = 'Peyv', option_c = 'Nav', option_d = 'Ziman', explanation = '"Ziman", Türkçe "dil" demektir.', explanation_ku = '"Ziman" bi Tirkî "dil" e.', explanation_tr = '"Ziman", Türkçe "dil" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '10b11d50-3fbd-4237-aacf-939e58b88e04' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "diş" çi ye?', option_a = 'Diran', option_b = 'Lêv', option_c = 'Dev', option_d = 'Ziman', explanation = '"Diran", Türkçe "diş" demektir.', explanation_ku = '"Diran" bi Tirkî "diş" e.', explanation_tr = '"Diran", Türkçe "diş" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '6d047d31-a47c-422a-9155-97e42b5d3d89' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "doğru" çi ye?', option_a = 'Çewt', option_b = 'Xwar', option_c = 'Rast', option_d = 'Şaş', explanation = '"Rast", Türkçe "doğru" demektir.', explanation_ku = '"Rast" bi Tirkî "doğru" e.', explanation_tr = '"Rast", Türkçe "doğru" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '8cc40821-75a5-4e21-a39d-44d195a3951e' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "dün" çi ye?', option_a = 'Îro', option_b = 'Sibe', option_c = 'Êvar', option_d = 'Duh', explanation = '"Duh", Türkçe "dün" demektir.', explanation_ku = '"Duh" bi Tirkî "dün" e.', explanation_tr = '"Duh", Türkçe "dün" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '009cca2c-d8e6-40e2-8ddf-fce65e7c14ef' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "dünya" çi ye?', option_a = 'Cîhan', option_b = 'Welat', option_c = 'Bajar', option_d = 'Esman', explanation = '"Cîhan", Türkçe "dünya" demektir.', explanation_ku = '"Cîhan" bi Tirkî "dünya" e.', explanation_tr = '"Cîhan", Türkçe "dünya" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '73b0407e-2fd2-48f1-882a-e2498275f8bf' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "ekmek" çi ye?', option_a = 'Av', option_b = 'Şîr', option_c = 'Goşt', option_d = 'Nan', explanation = '"Nan", Türkçe "ekmek" demektir.', explanation_ku = '"Nan" bi Tirkî "ekmek" e.', explanation_tr = '"Nan", Türkçe "ekmek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '64533626-beef-40c3-ba6e-d21a48e69c2b' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "el" çi ye?', option_a = 'Pê', option_b = 'Ser', option_c = 'Dest', option_d = 'Guh', explanation = '"Dest", Türkçe "el" demektir.', explanation_ku = '"Dest" bi Tirkî "el" e.', explanation_tr = '"Dest", Türkçe "el" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '9f41d3e1-d80f-4417-a9ba-808df31043f6' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "erkek kardeş" çi ye?', option_a = 'Bira', option_b = 'Ap', option_c = 'Xal', option_d = 'Kur', explanation = '"Bira", Türkçe "erkek kardeş" demektir.', explanation_ku = '"Bira" bi Tirkî "erkek kardeş" e.', explanation_tr = '"Bira", Türkçe "erkek kardeş" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'adfe41f7-d9e6-4a18-be48-364fae6942a9' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "erkek" çi ye?', option_a = 'Mêr', option_b = 'Jin', option_c = 'Zarok', option_d = 'Kal', explanation = '"Mêr", Türkçe "erkek" demektir.', explanation_ku = '"Mêr" bi Tirkî "erkek" e.', explanation_tr = '"Mêr", Türkçe "erkek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '8715e8be-b602-4b4b-95d0-d20c21f48271' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "eski" çi ye?', option_a = 'Kevin', option_b = 'Nû', option_c = 'Ciwan', option_d = 'Germ', explanation = '"Kevin", Türkçe "eski" demektir.', explanation_ku = '"Kevin" bi Tirkî "eski" e.', explanation_tr = '"Kevin", Türkçe "eski" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'aa8135cf-8770-44e6-93e7-1773e4038870' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "ev" çi ye?', option_a = 'Mal', option_b = 'Kon', option_c = 'Gund', option_d = 'Bajar', explanation = '"Mal", Türkçe "ev" demektir.', explanation_ku = '"Mal" bi Tirkî "ev" e.', explanation_tr = '"Mal", Türkçe "ev" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '3f92ab64-576c-41b2-80c2-2fe2b6cbd010' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "fırıncı" çi ye?', option_a = 'Cotkar', option_b = 'Şivan', option_c = 'Karker', option_d = 'Nanpêj', explanation = '"Nanpêj", Türkçe "fırıncı" demektir.', explanation_ku = '"Nanpêj" bi Tirkî "fırıncı" e.', explanation_tr = '"Nanpêj", Türkçe "fırıncı" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '5c204abc-f350-48d7-83a8-627e3aa633d5' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "gece" çi ye?', option_a = 'şev', option_b = 'roj', option_c = 'sibe', option_d = 'êvar', explanation = '"şev", Türkçe "gece" demektir.', explanation_ku = '"şev" bi Tirkî "gece" e.', explanation_tr = '"şev", Türkçe "gece" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '4cc49390-695c-475f-8001-5ee7b9f184b2' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "gelmek" çi ye?', option_a = 'Çûn', option_b = 'Rabûn', option_c = 'Hatin', option_d = 'Rûniştin', explanation = '"Hatin", Türkçe "gelmek" demektir.', explanation_ku = '"Hatin" bi Tirkî "gelmek" e.', explanation_tr = '"Hatin", Türkçe "gelmek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '62f0ea5d-6c44-432f-b2fe-182eec186d8c' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "genç" çi ye?', option_a = 'Pîr', option_b = 'Kal', option_c = 'Biçûk', option_d = 'Ciwan', explanation = '"Ciwan", Türkçe "genç" demektir.', explanation_ku = '"Ciwan" bi Tirkî "genç" e.', explanation_tr = '"Ciwan", Türkçe "genç" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '6fbc0500-b0b7-40c1-afc1-d61244f7867a' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "gitmek" çi ye?', option_a = 'Hatin', option_b = 'Çûn', option_c = 'Man', option_d = 'Rabûn', explanation = '"Çûn", Türkçe "gitmek" demektir.', explanation_ku = '"Çûn" bi Tirkî "gitmek" e.', explanation_tr = '"Çûn", Türkçe "gitmek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '5a75806c-14f2-49f3-b725-ed7938d292e2' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "görmek" çi ye?', option_a = 'Dîtin', option_b = 'Bihîstin', option_c = 'Zanîn', option_d = 'Gotin', explanation = '"Dîtin", Türkçe "görmek" demektir.', explanation_ku = '"Dîtin" bi Tirkî "görmek" e.', explanation_tr = '"Dîtin", Türkçe "görmek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '67fddfa1-1f55-4861-b341-a7c69f401139' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "göz" çi ye?', option_a = 'Guh', option_b = 'Poz', option_c = 'Çav', option_d = 'Dev', explanation = '"Çav", Türkçe "göz" demektir.', explanation_ku = '"Çav" bi Tirkî "göz" e.', explanation_tr = '"Çav", Türkçe "göz" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '855c5e93-1311-460b-a74a-22a4b1080b8a' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "gül" çi ye?', option_a = 'Dar', option_b = 'Gul', option_c = 'Giya', option_d = 'Baran', explanation = '"Gul", Türkçe "gül" demektir.', explanation_ku = '"Gul" bi Tirkî "gül" e.', explanation_tr = '"Gul", Türkçe "gül" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'cdbb4d51-fca5-4a63-bdc7-cc9ee5755c23' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "gün/güneş" çi ye?', option_a = 'Şev', option_b = 'Heyv', option_c = 'Stêrk', option_d = 'Roj', explanation = '"Roj", Türkçe "gün/güneş" demektir.', explanation_ku = '"Roj" bi Tirkî "gün/güneş" e.', explanation_tr = '"Roj", Türkçe "gün/güneş" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'a13226aa-8ea5-4835-8a91-de913fdad9bd' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "güzel/iyi" çi ye?', option_a = 'Nexweş', option_b = 'Kirêt', option_c = 'Xweş', option_d = 'Sar', explanation = '"Xweş", Türkçe "güzel/iyi" demektir.', explanation_ku = '"Xweş" bi Tirkî "güzel/iyi" e.', explanation_tr = '"Xweş", Türkçe "güzel/iyi" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '098be855-3175-4262-a9bc-35ddd32ca3d9' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "hava" çi ye?', option_a = 'Av', option_b = 'Hewa', option_c = 'Ax', option_d = 'Agir', explanation = '"Hewa", Türkçe "hava" demektir.', explanation_ku = '"Hewa" bi Tirkî "hava" e.', explanation_tr = '"Hewa", Türkçe "hava" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '8d7f34a4-4185-42e4-84f4-9580abf6f7d8' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "iş" çi ye?', option_a = 'Rê', option_b = 'Mal', option_c = 'Kar', option_d = 'Dibistan', explanation = '"Kar", Türkçe "iş" demektir.', explanation_ku = '"Kar" bi Tirkî "iş" e.', explanation_tr = '"Kar", Türkçe "iş" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'defd34ed-0d06-4f98-92c3-b57e797a93f3' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "işitmek" çi ye?', option_a = 'Dîtin', option_b = 'Gotin', option_c = 'Axaftin', option_d = 'Bihîstin', explanation = '"Bihîstin", Türkçe "işitmek" demektir.', explanation_ku = '"Bihîstin" bi Tirkî "işitmek" e.', explanation_tr = '"Bihîstin", Türkçe "işitmek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '491f7aab-a854-4239-b345-53d1268ef653' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "kadın" çi ye?', option_a = 'Mêr', option_b = 'Jin', option_c = 'Zarok', option_d = 'Keç', explanation = '"Jin", Türkçe "kadın" demektir.', explanation_ku = '"Jin" bi Tirkî "kadın" e.', explanation_tr = '"Jin", Türkçe "kadın" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '840105d2-7180-436d-9508-293e8613af8c' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "kağıt" çi ye?', option_a = 'Pênûs', option_b = 'Pirtûk', option_c = 'Mase', option_d = 'Kaxiz', explanation = '"Kaxiz", Türkçe "kağıt" demektir.', explanation_ku = '"Kaxiz" bi Tirkî "kağıt" e.', explanation_tr = '"Kaxiz", Türkçe "kağıt" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '21ba1bca-9d85-4c46-acce-22d41db0141d' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "kalem" çi ye?', option_a = 'Pênûs', option_b = 'Kaxiz', option_c = 'Pirtûk', option_d = 'Kursî', explanation = '"Pênûs", Türkçe "kalem" demektir.', explanation_ku = '"Pênûs" bi Tirkî "kalem" e.', explanation_tr = '"Pênûs", Türkçe "kalem" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'd6723b7d-ec63-4018-8cf5-c004f490ae8b' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "kalkmak" çi ye?', option_a = 'Rûniştin', option_b = 'Razan', option_c = 'Rabûn', option_d = 'Man', explanation = '"Rabûn", Türkçe "kalkmak" demektir.', explanation_ku = '"Rabûn" bi Tirkî "kalkmak" e.', explanation_tr = '"Rabûn", Türkçe "kalkmak" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'b59151bc-d964-458b-ae10-6e23e74eec4d' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "kalp/dil" çi ye?', option_a = 'Ser', option_b = 'Dil', option_c = 'Dest', option_d = 'Çav', explanation = '"Dil", Türkçe "kalp/dil" demektir.', explanation_ku = '"Dil" bi Tirkî "kalp/dil" e.', explanation_tr = '"Dil", Türkçe "kalp/dil" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'a17fd371-d38b-4d7a-b9b7-573273c03069' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "kapı" çi ye?', option_a = 'Pace', option_b = 'Dîwar', option_c = 'Ban', option_d = 'Derî', explanation = '"Derî", Türkçe "kapı" demektir.', explanation_ku = '"Derî" bi Tirkî "kapı" e.', explanation_tr = '"Derî", Türkçe "kapı" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '11cee6ed-b83c-4058-979f-b478f63a63f3' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "kaya" çi ye?', option_a = 'Ax', option_b = 'Zinar', option_c = 'Gir', option_d = 'Dar', explanation = '"Zinar", Türkçe "kaya" demektir.', explanation_ku = '"Zinar" bi Tirkî "kaya" e.', explanation_tr = '"Zinar", Türkçe "kaya" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'f6e90143-91bb-4bbf-b602-e2f06bfacad5' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "kedi" çi ye?', option_a = 'Pisîk', option_b = 'Kûçik', option_c = 'Mişk', option_d = 'Mirîşk', explanation = '"Pisîk", Türkçe "kedi" demektir.', explanation_ku = '"Pisîk" bi Tirkî "kedi" e.', explanation_tr = '"Pisîk", Türkçe "kedi" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '925d044e-8b8f-4d5a-a7b5-3d138a36b40c' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "kitap" çi ye?', option_a = 'Kovar', option_b = 'Rojname', option_c = 'Pênûs', option_d = 'Pirtûk', explanation = '"Pirtûk", Türkçe "kitap" demektir.', explanation_ku = '"Pirtûk" bi Tirkî "kitap" e.', explanation_tr = '"Pirtûk", Türkçe "kitap" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '2d90e6d7-62d2-483d-b2e1-9a01def9f620' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "kız kardeş" çi ye?', option_a = 'Xwîşk', option_b = 'Met', option_c = 'Xaltî', option_d = 'Dapîr', explanation = '"Xwîşk", Türkçe "kız kardeş" demektir.', explanation_ku = '"Xwîşk" bi Tirkî "kız kardeş" e.', explanation_tr = '"Xwîşk", Türkçe "kız kardeş" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'fbd814a2-17e4-4ea6-b615-8c3bd257ba4e' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "konuşmak" çi ye?', option_a = 'Axaftin', option_b = 'Bihîstin', option_c = 'Xwendin', option_d = 'Nivîsandin', explanation = '"Axaftin", Türkçe "konuşmak" demektir.', explanation_ku = '"Axaftin" bi Tirkî "konuşmak" e.', explanation_tr = '"Axaftin", Türkçe "konuşmak" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'c100232b-7be4-4096-aa8e-61fe3dfbdda3' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "köpek" çi ye?', option_a = 'Pisîk', option_b = 'Kûçik', option_c = 'Gur', option_d = 'Rovî', explanation = '"Kûçik", Türkçe "köpek" demektir.', explanation_ku = '"Kûçik" bi Tirkî "köpek" e.', explanation_tr = '"Kûçik", Türkçe "köpek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '9cf54995-fec6-414a-a4e3-87fc3173b8b0' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "köy" çi ye?', option_a = 'Bajar', option_b = 'Mal', option_c = 'Welat', option_d = 'Gund', explanation = '"Gund", Türkçe "köy" demektir.', explanation_ku = '"Gund" bi Tirkî "köy" e.', explanation_tr = '"Gund", Türkçe "köy" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'fde53291-d803-461c-991f-f12c2d36ede7' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "küçük" çi ye?', option_a = 'Mezin', option_b = 'Dirêj', option_c = 'Kurt', option_d = 'Biçûk', explanation = '"Biçûk", Türkçe "küçük" demektir.', explanation_ku = '"Biçûk" bi Tirkî "küçük" e.', explanation_tr = '"Biçûk", Türkçe "küçük" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'd6897084-c3ec-4ca5-b1c4-84b6f85523be' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "kulak" çi ye?', option_a = 'Guh', option_b = 'Çav', option_c = 'Poz', option_d = 'Dev', explanation = '"Guh", Türkçe "kulak" demektir.', explanation_ku = '"Guh" bi Tirkî "kulak" e.', explanation_tr = '"Guh", Türkçe "kulak" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '2e170532-6a7e-45a7-9e65-db0c9235b066' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "Kürt" çi ye?', option_a = 'Kurd', option_b = 'Welat', option_c = 'Ziman', option_d = 'Gel', explanation = '"Kurd", Türkçe "Kürt" demektir.', explanation_ku = '"Kurd" bi Tirkî "Kürt" e.', explanation_tr = '"Kurd", Türkçe "Kürt" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '56e70621-385a-4626-80a7-c19e67a74a1a' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "leğen" çi ye?', option_a = 'Beroş', option_b = 'Kevçî', option_c = 'Teşt', option_d = 'Firaq', explanation = '"Teşt", Türkçe "leğen" demektir.', explanation_ku = '"Teşt" bi Tirkî "leğen" e.', explanation_tr = '"Teşt", Türkçe "leğen" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'fefc58fb-a00c-4b3f-a706-9566b71dc186' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "masa" çi ye?', option_a = 'Kursî', option_b = 'Nivîn', option_c = 'Mase', option_d = 'Derî', explanation = '"Mase", Türkçe "masa" demektir.', explanation_ku = '"Mase" bi Tirkî "masa" e.', explanation_tr = '"Mase", Türkçe "masa" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'ac251ddd-5f4a-4446-acf9-27a88b66a485' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "nehir" çi ye?', option_a = 'Çem', option_b = 'Gol', option_c = 'Kanî', option_d = 'Derya', explanation = '"Çem", Türkçe "nehir" demektir.', explanation_ku = '"Çem" bi Tirkî "nehir" e.', explanation_tr = '"Çem", Türkçe "nehir" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'ec2f82e8-362e-49b6-8fa9-0107a965bd17' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "öğrenci" çi ye?', option_a = 'Mamoste', option_b = 'Dibistan', option_c = 'Pirtûk', option_d = 'Xwendekar', explanation = '"Xwendekar", Türkçe "öğrenci" demektir.', explanation_ku = '"Xwendekar" bi Tirkî "öğrenci" e.', explanation_tr = '"Xwendekar", Türkçe "öğrenci" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '18b86fc3-eb36-4445-94de-665ef5364528' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "öğretmen" çi ye?', option_a = 'Xwendekar', option_b = 'Bijîşk', option_c = 'Parêzer', option_d = 'Mamoste', explanation = '"Mamoste", Türkçe "öğretmen" demektir.', explanation_ku = '"Mamoste" bi Tirkî "öğretmen" e.', explanation_tr = '"Mamoste", Türkçe "öğretmen" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '774c3f94-c847-4d0e-b575-3d066a0abfea' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "okul" çi ye?', option_a = 'Xanî', option_b = 'Nexweşxane', option_c = 'Dibistan', option_d = 'Pirtûkxane', explanation = '"Dibistan", Türkçe "okul" demektir.', explanation_ku = '"Dibistan" bi Tirkî "okul" e.', explanation_tr = '"Dibistan", Türkçe "okul" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'f95c93a5-09c4-47a8-bb6a-84a345b3e033' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "okul/akademi" çi ye?', option_a = 'Nexweşxane', option_b = 'Pirtûkxane', option_c = 'Aşxane', option_d = 'Xwendegeh', explanation = '"Xwendegeh", Türkçe "okul/akademi" demektir.', explanation_ku = '"Xwendegeh" bi Tirkî "okul/akademi" e.', explanation_tr = '"Xwendegeh", Türkçe "okul/akademi" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '6d9d3d82-d2f2-4769-90dd-4001fdd47c94' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "okumak" çi ye?', option_a = 'Nivîsandin', option_b = 'Axaftin', option_c = 'Xwendin', option_d = 'Bihîstin', explanation = '"Xwendin", Türkçe "okumak" demektir.', explanation_ku = '"Xwendin" bi Tirkî "okumak" e.', explanation_tr = '"Xwendin", Türkçe "okumak" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'dded1f26-f4ae-4dda-955b-b6f88721da39' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "oturmak" çi ye?', option_a = 'Rabûn', option_b = 'Razan', option_c = 'Rûniştin', option_d = 'Meşîn', explanation = '"Rûniştin", Türkçe "oturmak" demektir.', explanation_ku = '"Rûniştin" bi Tirkî "oturmak" e.', explanation_tr = '"Rûniştin", Türkçe "oturmak" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '9be11f77-dbe3-4b0f-8615-ac6aca17a5bd' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "ova" çi ye?', option_a = 'Çiya', option_b = 'Deşt', option_c = 'Newal', option_d = 'Gir', explanation = '"Deşt", Türkçe "ova" demektir.', explanation_ku = '"Deşt" bi Tirkî "ova" e.', explanation_tr = '"Deşt", Türkçe "ova" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '7af49cde-cf77-4d9b-b56d-eefa65f656d9' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "renk" çi ye?', option_a = 'Deng', option_b = 'Reng', option_c = 'Nav', option_d = 'Wêne', explanation = '"Reng", Türkçe "renk" demektir.', explanation_ku = '"Reng" bi Tirkî "renk" e.', explanation_tr = '"Reng", Türkçe "renk" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'c8fb4ca4-1142-422c-bdf1-008cb584d18b' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "resim/fotoğraf" çi ye?', option_a = 'Reng', option_b = 'Wêne', option_c = 'Pirtûk', option_d = 'Kaxiz', explanation = '"Wêne", Türkçe "resim/fotoğraf" demektir.', explanation_ku = '"Wêne" bi Tirkî "resim/fotoğraf" e.', explanation_tr = '"Wêne", Türkçe "resim/fotoğraf" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '7f65ae6a-7ec5-45b9-8f0c-0d3c10c8bf77' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "rüzgar" çi ye?', option_a = 'baran', option_b = 'ba', option_c = 'berf', option_d = 'mij', explanation = '"ba", Türkçe "rüzgar" demektir.', explanation_ku = '"ba" bi Tirkî "rüzgar" e.', explanation_tr = '"ba", Türkçe "rüzgar" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '31cb4364-425c-454e-9f70-6ca818408d9a' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "saç" çi ye?', option_a = 'Rû', option_b = 'Por', option_c = 'Ser', option_d = 'Çav', explanation = '"Por", Türkçe "saç" demektir.', explanation_ku = '"Por" bi Tirkî "saç" e.', explanation_tr = '"Por", Türkçe "saç" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '32dd2fdd-e976-45ab-bff4-2ef3524033f6' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "sanat" çi ye?', option_a = 'Kar', option_b = 'Dîrok', option_c = 'Huner', option_d = 'Ziman', explanation = '"Huner", Türkçe "sanat" demektir.', explanation_ku = '"Huner" bi Tirkî "sanat" e.', explanation_tr = '"Huner", Türkçe "sanat" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '5c6f7891-1bf6-43bf-84a3-0d28a6a9908c' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "sandalye" çi ye?', option_a = 'Kursî', option_b = 'Mase', option_c = 'Nivîn', option_d = 'Derî', explanation = '"Kursî", Türkçe "sandalye" demektir.', explanation_ku = '"Kursî" bi Tirkî "sandalye" e.', explanation_tr = '"Kursî", Türkçe "sandalye" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '4dc53c94-48c0-4cd8-a308-0668e88888b3' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "şehir" çi ye?', option_a = 'Gund', option_b = 'Welat', option_c = 'Bajar', option_d = 'Kolan', explanation = '"Bajar", Türkçe "şehir" demektir.', explanation_ku = '"Bajar" bi Tirkî "şehir" e.', explanation_tr = '"Bajar", Türkçe "şehir" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '590a943c-7f79-4458-b45f-fa4d7ca0451f' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "ses" çi ye?', option_a = 'Reng', option_b = 'Nav', option_c = 'Deng', option_d = 'Peyv', explanation = '"Deng", Türkçe "ses" demektir.', explanation_ku = '"Deng" bi Tirkî "ses" e.', explanation_tr = '"Deng", Türkçe "ses" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '4e3ce00f-b18c-4241-a060-79635a14d2bd' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "sevmek" çi ye?', option_a = 'Dîtin', option_b = 'Zanîn', option_c = 'Hezkirin', option_d = 'Xwestin', explanation = '"Hezkirin", Türkçe "sevmek" demektir.', explanation_ku = '"Hezkirin" bi Tirkî "sevmek" e.', explanation_tr = '"Hezkirin", Türkçe "sevmek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '5ad1300d-9eba-4091-ae7f-f4131eb9eb93' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "soğuk" çi ye?', option_a = 'Germ', option_b = 'Xweş', option_c = 'Nû', option_d = 'Sar', explanation = '"Sar", Türkçe "soğuk" demektir.', explanation_ku = '"Sar" bi Tirkî "soğuk" e.', explanation_tr = '"Sar", Türkçe "soğuk" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '341758a6-3b88-4c5b-bfb6-3994e3f907c4' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "su" çi ye?', option_a = 'Şîr', option_b = 'Çay', option_c = 'Nan', option_d = 'Av', explanation = '"Av", Türkçe "su" demektir.', explanation_ku = '"Av" bi Tirkî "su" e.', explanation_tr = '"Av", Türkçe "su" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '44e6f9ee-affe-4fa6-89ac-a5490dc297d4' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "teşekkür" çi ye?', option_a = 'Spas', option_b = 'Silav', option_c = 'Bibore', option_d = 'Kerema te', explanation = '"Spas", Türkçe "teşekkür" demektir.', explanation_ku = '"Spas" bi Tirkî "teşekkür" e.', explanation_tr = '"Spas", Türkçe "teşekkür" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '8e518bd7-b150-453c-8a1b-aa704a47bd9e' and correct_option = 'A';
update questions set prompt = 'Bi Kurmancî "toprak" çi ye?', option_a = 'Av', option_b = 'Ax', option_c = 'Agir', option_d = 'Ba', explanation = '"Ax", Türkçe "toprak" demektir.', explanation_ku = '"Ax" bi Tirkî "toprak" e.', explanation_tr = '"Ax", Türkçe "toprak" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'd71f9c6d-77a9-460e-b9eb-46090d281659' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "ülke/vatan" çi ye?', option_a = 'Bajar', option_b = 'Gund', option_c = 'Cîhan', option_d = 'Welat', explanation = '"Welat", Türkçe "ülke/vatan" demektir.', explanation_ku = '"Welat" bi Tirkî "ülke/vatan" e.', explanation_tr = '"Welat", Türkçe "ülke/vatan" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '0e90b0c0-0691-4f7e-9cf0-148586bbf348' and correct_option = 'D';
update questions set prompt = 'Bi Kurmancî "vadi" çi ye?', option_a = 'Çiya', option_b = 'Deşt', option_c = 'Newal', option_d = 'Gir', explanation = '"Newal", Türkçe "vadi" demektir.', explanation_ku = '"Newal" bi Tirkî "vadi" e.', explanation_tr = '"Newal", Türkçe "vadi" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '0f5f8dba-ce28-425a-b25c-ef8dcf483099' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "yağmur" çi ye?', option_a = 'Berf', option_b = 'Ba', option_c = 'Baran', option_d = 'Mij', explanation = '"Baran", Türkçe "yağmur" demektir.', explanation_ku = '"Baran" bi Tirkî "yağmur" e.', explanation_tr = '"Baran", Türkçe "yağmur" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'fa5c8264-33ea-4a73-92d4-b7fbcae0abfe' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "yaşlı/ihtiyar" çi ye?', option_a = 'Ciwan', option_b = 'Zarok', option_c = 'Pîr', option_d = 'Nû', explanation = '"Pîr", Türkçe "yaşlı/ihtiyar" demektir.', explanation_ku = '"Pîr" bi Tirkî "yaşlı/ihtiyar" e.', explanation_tr = '"Pîr", Türkçe "yaşlı/ihtiyar" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '393ab3c6-0c79-412d-a2a8-d2e6764158a9' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "yatak" çi ye?', option_a = 'Kursî', option_b = 'Mase', option_c = 'Nivîn', option_d = 'Balîf', explanation = '"Nivîn", Türkçe "yatak" demektir.', explanation_ku = '"Nivîn" bi Tirkî "yatak" e.', explanation_tr = '"Nivîn", Türkçe "yatak" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '26bd6c80-f680-450c-9c64-2417069ebbf7' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "yazmak" çi ye?', option_a = 'Xwendin', option_b = 'Axaftin', option_c = 'Nivîsandin', option_d = 'Bihîstin', explanation = '"Nivîsandin", Türkçe "yazmak" demektir.', explanation_ku = '"Nivîsandin" bi Tirkî "yazmak" e.', explanation_tr = '"Nivîsandin", Türkçe "yazmak" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '547fbbf6-2926-4b8a-9e76-6aa14cb31f1e' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "yemekhane" çi ye?', option_a = 'Nexweşxane', option_b = 'Nanxane', option_c = 'Pirtûkxane', option_d = 'Çayxane', explanation = '"Nanxane", Türkçe "yemekhane" demektir.', explanation_ku = '"Nanxane" bi Tirkî "yemekhane" e.', explanation_tr = '"Nanxane", Türkçe "yemekhane" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '2beb2880-6623-4789-b82e-62846bea02ad' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "yıldız" çi ye?', option_a = 'Heyv', option_b = 'Roj', option_c = 'Stêrk', option_d = 'Esman', explanation = '"Stêrk", Türkçe "yıldız" demektir.', explanation_ku = '"Stêrk" bi Tirkî "yıldız" e.', explanation_tr = '"Stêrk", Türkçe "yıldız" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '12cd4547-3b25-4ab2-91fa-8b31f50b12db' and correct_option = 'C';
update questions set prompt = 'Bi Kurmancî "yol" çi ye?', option_a = 'Kolan', option_b = 'Rê', option_c = 'Çem', option_d = 'Deşt', explanation = '"Rê", Türkçe "yol" demektir.', explanation_ku = '"Rê" bi Tirkî "yol" e.', explanation_tr = '"Rê", Türkçe "yol" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'b57501de-a0a7-4577-97d7-f416b8e91fc9' and correct_option = 'B';
update questions set prompt = 'Di wêneyê de "av" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Ekmek', option_b = 'Süt', option_c = 'Su', option_d = 'Ateş', explanation = '"av", Türkçe "Su" demektir.', explanation_ku = '"av" bi Tirkî "Su" e.', explanation_tr = '"av", Türkçe "Su" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '59014146-690c-4ca1-b099-b129679295c4' and correct_option = 'C';
update questions set prompt = 'Di wêneyê de "bajar" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Köy', option_b = 'Ülke', option_c = 'Sokak', option_d = 'Şehir', explanation = '"bajar", Türkçe "Şehir" demektir.', explanation_ku = '"bajar" bi Tirkî "Şehir" e.', explanation_tr = '"bajar", Türkçe "Şehir" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '36137171-4652-4adc-b350-2a58c25061f5' and correct_option = 'D';
update questions set prompt = 'Di wêneyê de "biçûk" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Büyük', option_b = 'Uzun', option_c = 'Küçük', option_d = 'Kısa', explanation = '"biçûk", Türkçe "Küçük" demektir.', explanation_ku = '"biçûk" bi Tirkî "Küçük" e.', explanation_tr = '"biçûk", Türkçe "Küçük" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '2df1f9cc-2086-4608-a470-cb1630e97c33' and correct_option = 'C';
update questions set prompt = 'Di wêneyê de "çiya" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Ova', option_b = 'Vadi', option_c = 'Dağ', option_d = 'Deniz', explanation = '"çiya", Türkçe "Dağ" demektir.', explanation_ku = '"çiya" bi Tirkî "Dağ" e.', explanation_tr = '"çiya", Türkçe "Dağ" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '6e00a574-9e5d-4f23-b3b2-35f2150b5d9b' and correct_option = 'C';
update questions set prompt = 'Di wêneyê de "destpêk" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Başlangıç', option_b = 'Son', option_c = 'Orta', option_d = 'Sonuç', explanation = '"destpêk", Türkçe "Başlangıç" demektir.', explanation_ku = '"destpêk" bi Tirkî "Başlangıç" e.', explanation_tr = '"destpêk", Türkçe "Başlangıç" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'b3e05f56-fda1-427a-9442-6bdb08c838dd' and correct_option = 'A';
update questions set prompt = 'Di wêneyê de "dil" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Kalp/dil', option_b = 'El', option_c = 'Baş', option_d = 'Göz', explanation = '"dil", Türkçe "Kalp/dil" demektir.', explanation_ku = '"dil" bi Tirkî "Kalp/dil" e.', explanation_tr = '"dil", Türkçe "Kalp/dil" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'c55997b5-3537-4a00-a60c-47204cec22ad' and correct_option = 'A';
update questions set prompt = 'Di wêneyê de "duh" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Bugün', option_b = 'Yarın', option_c = 'Dün', option_d = 'Akşam', explanation = '"duh", Türkçe "Dün" demektir.', explanation_ku = '"duh" bi Tirkî "Dün" e.', explanation_tr = '"duh", Türkçe "Dün" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '76a8c0cd-7b79-4b4b-998a-16befd9b93fa' and correct_option = 'C';
update questions set prompt = 'Di wêneyê de "hatin" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Gitmek', option_b = 'Kalkmak', option_c = 'Gelmek', option_d = 'Oturmak', explanation = '"hatin", Türkçe "Gelmek" demektir.', explanation_ku = '"hatin" bi Tirkî "Gelmek" e.', explanation_tr = '"hatin", Türkçe "Gelmek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '5d3fac1d-8d8a-478e-aaaa-588292f3b3fd' and correct_option = 'C';
update questions set prompt = 'Di wêneyê de "heval" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Komşu', option_b = 'Arkadaş', option_c = 'Misafir', option_d = 'Kardeş', explanation = '"heval", Türkçe "Arkadaş" demektir.', explanation_ku = '"heval" bi Tirkî "Arkadaş" e.', explanation_tr = '"heval", Türkçe "Arkadaş" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '182430f0-6d80-4b1e-a8d6-fba85f2b3023' and correct_option = 'B';
update questions set prompt = 'Di wêneyê de "îro" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Dün', option_b = 'Yarın', option_c = 'Bugün', option_d = 'Sabah', explanation = '"îro", Türkçe "Bugün" demektir.', explanation_ku = '"îro" bi Tirkî "Bugün" e.', explanation_tr = '"îro", Türkçe "Bugün" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'dd71cbce-9958-4391-b589-40dbfa306601' and correct_option = 'C';
update questions set prompt = 'Di wêneyê de "kevin" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Yeni', option_b = 'Genç', option_c = 'Eski', option_d = 'Sıcak', explanation = '"kevin", Türkçe "Eski" demektir.', explanation_ku = '"kevin" bi Tirkî "Eski" e.', explanation_tr = '"kevin", Türkçe "Eski" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '6ce7c7bf-08b3-4a6d-a71a-a2f844d8263d' and correct_option = 'C';
update questions set prompt = 'Di wêneyê de "mal" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Ev', option_b = 'Köy', option_c = 'Şehir', option_d = 'Kapı', explanation = '"mal", Türkçe "Ev" demektir.', explanation_ku = '"mal" bi Tirkî "Ev" e.', explanation_tr = '"mal", Türkçe "Ev" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '75d2cd9e-2ab7-4bbe-969b-7741c87c6a8d' and correct_option = 'A';
update questions set prompt = 'Di wêneyê de "nan" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Su', option_b = 'Süt', option_c = 'Ekmek', option_d = 'Et', explanation = '"nan", Türkçe "Ekmek" demektir.', explanation_ku = '"nan" bi Tirkî "Ekmek" e.', explanation_tr = '"nan", Türkçe "Ekmek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '6f65da37-528c-41fe-8d34-890af9b45739' and correct_option = 'C';
update questions set prompt = 'Di wêneyê de "nav" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Ses', option_b = 'Renk', option_c = 'Ad/isim', option_d = 'Söz', explanation = '"nav", Türkçe "Ad/isim" demektir.', explanation_ku = '"nav" bi Tirkî "Ad/isim" e.', explanation_tr = '"nav", Türkçe "Ad/isim" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '50feea8b-4d22-4ccd-b667-8e84cd072911' and correct_option = 'C';
update questions set prompt = 'Di wêneyê de "pir" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Az', option_b = 'Küçük', option_c = 'Büyük', option_d = 'Çok', explanation = '"pir", Türkçe "Çok" demektir.', explanation_ku = '"pir" bi Tirkî "Çok" e.', explanation_tr = '"pir", Türkçe "Çok" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'b58e31e0-3976-464b-b97a-0f2b43561132' and correct_option = 'D';
update questions set prompt = 'Di wêneyê de "pirtûk" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Dergi', option_b = 'Gazete', option_c = 'Kitap', option_d = 'Kalem', explanation = '"pirtûk", Türkçe "Kitap" demektir.', explanation_ku = '"pirtûk" bi Tirkî "Kitap" e.', explanation_tr = '"pirtûk", Türkçe "Kitap" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '841666fd-8421-481f-bf3a-d25895e435e1' and correct_option = 'C';
update questions set prompt = 'Di wêneyê de "rast" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Doğru', option_b = 'Yanlış', option_c = 'Eğri', option_d = 'Ters', explanation = '"rast", Türkçe "Doğru" demektir.', explanation_ku = '"rast" bi Tirkî "Doğru" e.', explanation_tr = '"rast", Türkçe "Doğru" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'a00c8ba0-06a4-44c6-ac52-5f353a7e26a1' and correct_option = 'A';
update questions set prompt = 'Di wêneyê de "rê" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Sokak', option_b = 'Nehir', option_c = 'Köprü', option_d = 'Yol', explanation = '"rê", Türkçe "Yol" demektir.', explanation_ku = '"rê" bi Tirkî "Yol" e.', explanation_tr = '"rê", Türkçe "Yol" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '663ba095-fd69-40c9-b800-410e43cd5b28' and correct_option = 'D';
update questions set prompt = 'Di wêneyê de "roj" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Gece', option_b = 'Gün/güneş', option_c = 'Ay', option_d = 'Yıldız', explanation = '"roj", Türkçe "Gün/güneş" demektir.', explanation_ku = '"roj" bi Tirkî "Gün/güneş" e.', explanation_tr = '"roj", Türkçe "Gün/güneş" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '54525b44-bb2f-404f-a7db-8f20e7683291' and correct_option = 'B';
update questions set prompt = 'Di wêneyê de "sar" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Sıcak', option_b = 'Soğuk', option_c = 'Ilık', option_d = 'Kuru', explanation = '"sar", Türkçe "Soğuk" demektir.', explanation_ku = '"sar" bi Tirkî "Soğuk" e.', explanation_tr = '"sar", Türkçe "Soğuk" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '6d305bf2-cbcf-4fa8-9808-61ccf57772c2' and correct_option = 'B';
update questions set prompt = 'Di wêneyê de "spas" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Teşekkür', option_b = 'Selam', option_c = 'Özür', option_d = 'Rica', explanation = '"spas", Türkçe "Teşekkür" demektir.', explanation_ku = '"spas" bi Tirkî "Teşekkür" e.', explanation_tr = '"spas", Türkçe "Teşekkür" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'c029f2f5-76a6-4538-9f94-30a7ba846f3d' and correct_option = 'A';
update questions set prompt = 'Di wêneyê de "xwendekar" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Öğrenci', option_b = 'Öğretmen', option_c = 'Doktor', option_d = 'Avukat', explanation = '"xwendekar", Türkçe "Öğrenci" demektir.', explanation_ku = '"xwendekar" bi Tirkî "Öğrenci" e.', explanation_tr = '"xwendekar", Türkçe "Öğrenci" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'eb8921d8-180a-44b8-b1d7-26e62280551c' and correct_option = 'A';
update questions set prompt = 'Di wêneyê de "xweş" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Çirkin', option_b = 'Güzel/iyi', option_c = 'Kötü', option_d = 'Soğuk', explanation = '"xweş", Türkçe "Güzel/iyi" demektir.', explanation_ku = '"xweş" bi Tirkî "Güzel/iyi" e.', explanation_tr = '"xweş", Türkçe "Güzel/iyi" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '21894286-1b42-446a-9f10-aad86f829d30' and correct_option = 'B';
update questions set prompt = 'Di wêneyê de "zanîn" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Bilmek', option_b = 'Görmek', option_c = 'Duymak', option_d = 'Okumak', explanation = '"zanîn", Türkçe "Bilmek" demektir.', explanation_ku = '"zanîn" bi Tirkî "Bilmek" e.', explanation_tr = '"zanîn", Türkçe "Bilmek" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'd3a84799-f48d-435d-aa2a-02292c1833bb' and correct_option = 'A';
update questions set prompt = 'Di wêneyê de "zarok" tê nîşandan. Wateya wê bi Tirkî çi ye?', option_a = 'Genç', option_b = 'Çocuk', option_c = 'Yaşlı', option_d = 'Kadın', explanation = '"zarok", Türkçe "Çocuk" demektir.', explanation_ku = '"zarok" bi Tirkî "Çocuk" e.', explanation_tr = '"zarok", Türkçe "Çocuk" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '5b7a0cf8-349b-4abc-a38e-fcca378db8ad' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "göl" çi ye?', option_a = 'Çem', option_b = 'Gol', option_c = 'Derya', option_d = 'Kanî', explanation = '"Gol", Türkçe "göl" demektir.', explanation_ku = '"Gol" bi Tirkî "göl" e.', explanation_tr = '"Gol", Türkçe "göl" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'bcfba095-b33a-45e1-ba35-09df1d63218c' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "orman" çi ye?', option_a = 'Deşt', option_b = 'Daristan', option_c = 'Çiya', option_d = 'Newal', explanation = '"Daristan", Türkçe "orman" demektir.', explanation_ku = '"Daristan" bi Tirkî "orman" e.', explanation_tr = '"Daristan", Türkçe "orman" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = 'a8da9433-4e62-4d9f-b704-bb12b3678aa9' and correct_option = 'B';
update questions set prompt = 'Bi Kurmancî "sınır" çi ye?', option_a = 'Rê', option_b = 'Sînor', option_c = 'Welat', option_d = 'Çem', explanation = '"Sînor", Türkçe "sınır" demektir.', explanation_ku = '"Sînor" bi Tirkî "sınır" e.', explanation_tr = '"Sînor", Türkçe "sınır" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '97449f1a-cb9c-4d74-9984-d0151fba46cf' and correct_option = 'B';
update questions set prompt = 'Wateya peyva "Azadî" bi Tirkî çi ye?', option_a = 'Özgürlük', option_b = 'Eşitlik', option_c = 'Adalet', option_d = 'Barış', explanation = '"Azadî", Türkçe "özgürlük" demektir.', explanation_ku = '"Azadî" bi Tirkî "özgürlük" e.', explanation_tr = '"Azadî", Türkçe "özgürlük" demektir.', quality_version = coalesce(quality_version,0) + 1, updated_at = now() where id = '6229c06e-c055-4769-8e26-71ec63f84aba' and correct_option = 'A';
update questions set is_approved = false, updated_at = now() where id in ('864fb775-5b1b-44fd-9639-8063354cf5ee', '062bae5f-d77b-4036-941f-b88f9404c8d2', '83c425e3-2f4e-480e-ae4d-5a5cca36a6f5', 'afaebb4b-f289-4a90-9eef-3a7826f10ff5', '0bc50001-3f83-4921-b171-f26e3982dfa7', '5ea9ca1c-5156-4864-b7b2-e0c523b6397b', '0990fe06-0f38-4e76-b864-3ea9cdac5b5b', '9d5633ab-7200-4d19-9c47-424ddae1b8a0', '45b54f6d-d525-4b9f-8dc0-4b1ebb36b17e', '4da636fc-baed-4c8b-9795-a98ca709f11b', 'fbca7a26-c71f-4580-9a93-25377d77bf89', '0df0734e-919d-4c55-9582-aba44d08888c', 'ba67c63d-4ec7-479d-aa8d-f7616eae68e5', '335fcaa5-a4a1-4abe-817f-6e5f098dfe55', '82101517-b74d-468c-8dce-66469c95a6bb', 'b534f72b-4bdd-428a-880c-4ed7f5ab0235', 'de027933-ef50-4f3f-bb71-ec36b81ebabe', '7e509c37-d251-4f4c-85df-df55f423afcc', '1e7b509a-3cb6-4f08-8611-0e336538571c', '23a787d9-9597-4e58-bc4d-68ef35498146', '2b7ba4c9-1c95-4bfd-8495-d135ad22fc37', '6c9bbcbb-fe49-4a14-85c6-86886a3f939a', '9cd6c0b5-8f0d-4bcb-9cc0-2b36f1ef141c', 'd1261e34-3e92-4bfb-b765-0be2dd880a89', '2a634f6f-85dc-48ba-a486-1f1215829c38', 'e3141fcc-74de-4611-b010-c67b7bfe5876', '6b46ec1b-0033-4112-bcec-5604de302818');
update questions set is_approved = false, updated_at = now() where is_approved and (prompt like 'Görseldeki%etiketi%kategori%' or prompt like 'Görseldeki%etiketi%alana yakındır%');

commit;
