-- 2026-10-01: yerel denetlenmiş bankanın sunucuda EKSİK 40 Paradigma sorusu (canlı sunucu).
--
-- NİÇİN: oda ve düello soruları sunucudaki `questions` tablosundan oynanır;
-- kaynak doğru ise denetlenmiş yerel bankadır (question_bank_assets.dart ∖
-- retired_question_ids.dart ∖ QuestionContentPolicy.isPlayable dışı).
-- Sunucuda bu kategorideki yerel sorunun onaylı karşılığı (uuid5 ya da aynı
-- kategoride aynı soru metni) bulunmayanlar burada; oyuncu tek başına
-- gördüğü soruyu odada/düelloda görmüyordu. Kategori başına ayrı dosyadır
-- (her biri kendi önkoşulu ve kesin sayı doğrulamasıyla; kısmi uygulama olur).
--
-- KAÇ SATIR: 40 (multiple_choice 30, true_false 10). Sınıf: sunucuda hiç yok (c) 39;
-- sunucuda yalnız onaysız ve başka yazımda (b_varyant) 1;
-- özdeş onaysız (b_ozdes, yalnız --include-unapproved-identical) 0.
--
-- ONAYSIZ SATIRLAR (b): sunucuda içeriği yereldekiyle ÖZDEŞ ve onaysız duran
-- sorulara DOKUNULMADI (onay kaldırma editoryal bir karardı). Başka yazımda
-- onaysız duranlar için eski satır yeniden onaylanmaz (eski metin canlıya
-- çıkardı); yerel sürüm yeni uuid5 satırı olarak eklenir, eski satır onaysız
-- kalır. Böylece aynı sorunun iki ONAYLI kopyası oluşmaz.
--
-- GÖRSELLİ SORULAR BU DOSYADA YOK: yerelde bu kategoride 0 görselli
-- (`asset://`) soru atlandı. Mağazadaki eski uygulama sürümlerinde yeni görsel
-- dosyaları paketli değil; oda/düelloda kırık görsel çıkardı. 2.0.0 yayına
-- çıkınca ayrı bir göçle (`--include-visual`) eklenecek. Boşluk doldurma ve
-- cümle dizme gibi sunucu şemasına sığmayan türler de atlandı.
--
-- KATEGORİ: `categories.name` ile aranır; yoksa hiçbir şey eklenmeden işlem
-- geri alınır. Kategori OLUŞTURMAZ.
--
-- TEKRAR ÇALIŞTIRILABİLİR: `on conflict (id) do nothing`; ikinci çalıştırma
-- satır eklemez. Doğrulama bloğu bu dosyadaki 40 kimliğin hepsinin kategoride
-- ONAYLI durduğunu denetler; tutmazsa işlem geri alınır.
--
-- GERİ ALMA (yalnız bu göçün satırları):
--   delete from questions where id in (<bu dosyadaki kimlikler>);
--
-- Üretici: tool/sync_local_parity_to_server.py (YEREL_OYNANABILIR: 2579)
-- Uygulama: supabase db query --linked -f supabase/2026-10-01_local_parity_sync_paradigma.sql

begin;

-- Önkoşul: kategori sunucuda var (bu göç oluşturmaz).
do $$
begin
  if not exists (select 1 from categories where name = 'Paradigma') then
    raise exception 'Eksik kategori: Paradigma';
  end if;
end
$$;

insert into questions (id, category_id, language_code, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, explanation_ku, explanation_tr, difficulty, is_approved, question_type, image_url, source_url, source_title, source_reference, review_status, dialect, quality_version, last_content_check_at)
values
('c92ad542-44a5-5e8e-8de2-fa98bfe80754', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Kîjan ravekirin ji bo "xwe-rêxistin" rast e?', 'Maf û erkên xwe bi hevkarî rêxistin kirin', 'Biryarên hemû kesan ji kesekê re hiştin', 'Ji civakê dûrketin', 'Tenê li ser navên kesan nivîsandin', 'A', '"Xwe-rêxistin" tê wateya ku kes û kom bi hevkarî kar û biryarên xwe bi xwe rêxistin dikin.', '"Xwe-rêxistin" tê wateya ku kes û kom bi hevkarî kar û biryarên xwe bi xwe rêxistin dikin.', '"Xwe-rêxistin", kişi ve grupların işlerini ve kararlarını dayanışmayla kendilerinin örgütlemesidir.', 2, true, 'multiple_choice', NULL, NULL, 'KJAR movement statement + supporting academic context', 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521; Cambridge History of the Kurds, Kurdish Women’s Freedom Movement chapter', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_movement_0005
('f1aadc8a-c7d6-5a52-916b-8aeb903694a2', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Di vê hevokê de peyva "berxwedan" çi dide zanîn? "Berxwedana wan dom kir."', 'Ragirtina li hember zordariyê', 'Rêwîtiya bi balafirê', 'Kirîna tiştan', 'Xwarina taştê', 'A', '"Berxwedan" di vê hevokê de wateya rawestan û li hember zordariyê ragirtinê dide.', '"Berxwedan" di vê hevokê de wateya rawestan û li hember zordariyê ragirtinê dide.', '"Berxwedan" bu cümlede direnmek ve baskı karşısında ayakta kalmak anlamındadır.', 2, true, 'multiple_choice', NULL, NULL, 'KJAR movement statement + supporting academic context', 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521; Cambridge History of the Kurds, Kurdish Women’s Freedom Movement chapter', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_movement_0006
('44f5b3ec-2270-5937-a2a0-2be65e453235', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Kîjan hevok li ser "demokratîk konfederalîzm" bi awayekî herî rast têgihiştinê dide?', 'Modela hevkarî û meclîsan a ku ji civakê ber bi jor ve ava dibe', 'Rêbazek ku hemû biryarên civakê dide destê yek kesî', 'Tenê rêbazek ji bo hilbijartina futbolê', 'Navê pergaleke meteorolojiyê', 'A', 'Ev têgeh bi meclîs, komîn, hevkarî û biryargirtina ji jêr ve tê şirovekirin.', 'Ev têgeh bi meclîs, komîn, hevkarî û biryargirtina ji jêr ve tê şirovekirin.', 'Bu kavram meclis, komün, dayanışma ve aşağıdan karar almayla açıklanır.', 4, true, 'multiple_choice', NULL, NULL, 'Kongra Star institutional publications + supporting research', 'https://kongra-star.org/eng/about/; https://kongra-star.org/eng/wp-content/uploads/2025/01/Annual-Newsletter-of-the-Womens-Revolution.pdf; Cambridge History of the Kurds, Kurdish Women’s Freedom Movement chapter', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_movement_0011
('de546122-b7bd-555a-ae98-36c8a4a20953', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Rast e yan şaş e? "Xwe-rêxistin tenê ji bo kesên ku li bajarên mezin dijîn e."', 'Rast', 'Şaş', '-', '-', 'B', 'Xwe-rêxistin di cihên cuda de, di nav kom û civakan de bi awayên cuda tê bikaranîn.', 'Xwe-rêxistin di cihên cuda de, di nav kom û civakan de bi awayên cuda tê bikaranîn.', 'Öz örgütlenme; farklı yerlerde, farklı grup ve toplumlarda farklı biçimlerde uygulanır.', 2, true, 'true_false', NULL, NULL, 'Jineolojî movement media + supporting academic context', 'https://anfenglishmobile.com/features/twitterkurds-takes-the-civil-disobedience-campaign-online-3254; https://kongra-star.org/eng/wp-content/uploads/2025/01/Annual-Newsletter-of-the-Womens-Revolution.pdf; Cambridge, Beyond Feminism? Jineolojî and the Kurdish Women’s Freedom Movement', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_movement_0015
('8c4bbd0e-34d9-5dcc-a89d-484efaa40f91', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Peyva "jineolojî" çi tê de ye?', 'Zanistiya jinê', 'Zanistiya azadiyê', 'Zanistiya xwezayê', 'Zanistiya hunerê', 'A', 'Jineolojî ji "jin" û "lojî" (zanist) pêk tê; zanistiya jinê û rêxistinkirina civaka azad e.', 'Jineolojî ji "jin" û "lojî" (zanist) pêk tê; zanistiya jinê û rêxistinkirina civaka azad e.', 'Jineolojî "jin" (kadın) ve "loji" (bilim) sözcüklerinden oluşur; kadın bilimi ve özgür toplumun örgütlenmesidir.', 1, true, 'multiple_choice', NULL, NULL, 'Jineolojî movement media + supporting academic context', 'https://anfenglishmobile.com/features/twitterkurds-takes-the-civil-disobedience-campaign-online-3254; https://kongra-star.org/eng/wp-content/uploads/2025/01/Annual-Newsletter-of-the-Womens-Revolution.pdf; Cambridge, Beyond Feminism? Jineolojî and the Kurdish Women’s Freedom Movement', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_paradigma_0001
('3736ddc3-402a-5cea-95a8-4a22e12bacd7', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Kîjan têgeh bi "konfederalîzm"ê re herî nêzîk e?', 'Rêxistinên xwe-bi-xwe yên herêmî', 'Serfkarî', 'Yek serwer', 'Kolonyalîzm', 'A', 'Konfederalîzm modelek e ku rêxistinên herêmî yên xwe-bi-xwe li ser bingeha wekheviyê bi hev ve girê dide.', 'Konfederalîzm modelek e ku rêxistinên herêmî yên xwe-bi-xwe li ser bingeha wekheviyê bi hev ve girê dide.', 'Konfederalizm, yerel öz örgütlenmeleri eşitlik temelinde birbirine bağlayan bir modeldir.', 2, true, 'multiple_choice', NULL, NULL, 'ANF movement media + supporting academic context', 'https://anfenglishmobile.com/kadin/k-176492; Cambridge History of the Kurds, Kurdish Women’s Freedom Movement chapter', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_paradigma_0002
('ac77fa76-0c60-57ab-93f1-9a2dbaa2160c', (select id from categories where name = 'Paradigma'), 'ku-kmr', '"Hevaltî" di vê paradîgmayê de çi dixwaze?', 'Wekhevî û pîvana rêxistinê', 'Tenê pûl bi pûl', 'Betalbûna hemû endamên rêxistinê', 'Mîrata dadwerî', 'A', 'Hevaltî endamên rêxistinê li ser bingeha wekheviyê digihîne hev, ne li ser serdestiyê.', 'Hevaltî endamên rêxistinê li ser bingeha wekheviyê digihîne hev, ne li ser serdestiyê.', 'Yoldaşlık, örgüt üyelerini tahakküm üzerine değil eşitlik üzerine birleştirir.', 2, true, 'multiple_choice', NULL, NULL, 'Jineolojî movement media + supporting academic context', 'https://anfenglishmobile.com/features/twitterkurds-takes-the-civil-disobedience-campaign-online-3254; https://kongra-star.org/eng/wp-content/uploads/2025/01/Annual-Newsletter-of-the-Womens-Revolution.pdf; Cambridge, Beyond Feminism? Jineolojî and the Kurdish Women’s Freedom Movement', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_paradigma_0003
('c78cf9a6-d577-5bbb-9e6a-76c0d297fb72', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Abdullah Öcalan di gotarên xwe de kîjan "-îzm"ê pêşniyar kir?', 'Konfederalîzma demokratîk', 'Liberalîzm', 'Sosyalîzma dewletê', 'Neteweperestî', 'A', 'Di konfederalîzma demokratîk de civak bi rêxistinên xwe-bi-xwe tê organîzekirin, ne bi dewletê.', 'Di konfederalîzma demokratîk de civak bi rêxistinên xwe-bi-xwe tê organîzekirin, ne bi dewletê.', 'Demokratik konfederalizmde toplum devletle değil, öz örgütlenmelerle düzenlenir.', 2, true, 'multiple_choice', NULL, NULL, 'ANF movement media + supporting academic context', 'https://anfenglishmobile.com/kadin/k-176492; Cambridge History of the Kurds, Kurdish Women’s Freedom Movement chapter', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_paradigma_0004
('e67ab304-9e45-53d9-b7e4-48984ccb3e72', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Li şûna netewe-dewletê kîjan model tê pêşniyarkirin?', 'Belavkirina rêxistinî ya biratiyê', 'Demokratîkbûna gelemperî', 'Pileyên leşkerî', 'Hiqûqa malbatê ya veşartî', 'B', 'Paradîgmaya civaka demokratîk rêxistinên demokratîk û biryardana gelemperî digire nav xwe.', 'Paradîgmaya civaka demokratîk rêxistinên demokratîk û biryardana gelemperî digire nav xwe.', 'Demokratik toplum paradigması, demokratik örgütlenmeleri ve ortak karar almayı kapsar.', 3, true, 'multiple_choice', NULL, NULL, 'ANF movement media + supporting academic context', 'https://anfenglishmobile.com/kadin/k-176492; Cambridge History of the Kurds, Kurdish Women’s Freedom Movement chapter', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_paradigma_0005
('6093f353-ef60-5fe9-a160-f7c2b5b27341', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Jineolojî di Şoreşa Rojavayê de çi rollî leyîst?', 'Avakirina parastina jinê û şoreşa civakî', 'Tenê kontrolên leşkerî', 'Dîrok-Nivîskarî', 'Peydakerî û bazirganî', 'A', 'Jineolojî li Rojavayê Kurdistanê bû pîvana azadiya jinê, ziman û rêxistinbûna wan.', 'Jineolojî li Rojavayê Kurdistanê bû pîvana azadiya jinê, ziman û rêxistinbûna wan.', 'Jineolojî, Batı Kürdistan’da kadın özgürlüğünün, dilinin ve örgütlenmesinin ölçüsü hâline geldi.', 2, true, 'multiple_choice', NULL, NULL, 'Kongra Star institutional publications + supporting research', 'https://kongra-star.org/eng/about/; https://kongra-star.org/eng/wp-content/uploads/2025/01/Annual-Newsletter-of-the-Womens-Revolution.pdf; Cambridge History of the Kurds, Kurdish Women’s Freedom Movement chapter', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_paradigma_0006
('d9f2629c-cdef-5f47-b594-0c2ed0cc2ffa', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Bê "ekolojî" di paradîgmayê de çi wateye?', 'Hemahengbûna jiyanê bi xwezayê re (ne serdestî)', 'Tenê kimya', 'Bazirganîna aboriyê', 'Veşartina topan', 'A', 'Ekolojiya demokratîk dixwaze mirov bi xwezayê re lihevhatî bijî, ne bi serdestiyê.', 'Ekolojiya demokratîk dixwaze mirov bi xwezayê re lihevhatî bijî, ne bi serdestiyê.', 'Demokratik ekoloji, insanın doğaya tahakküm etmeden onunla uyum içinde yaşamasını ister.', 2, true, 'multiple_choice', NULL, NULL, 'Ansiklopedîk çavkanî (Kürt Ansiklopedisi, Encyclopaedia Britannica — Kurdish)', 'https://www.britannica.com/topic/Kurd; Kürt Ansiklopedisi (2009-2012 cild I-VI)', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_paradigma_0007
('7c7bbbb5-f8af-5536-b169-2576591932db', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Peyva "pîvana rast" ji bo rêxistinkirina civaka demokratîk çi wateyê dide?', 'Fermana yekdest û teslîmbûn', 'Lihevkirin û biryara herêmî', 'Serdestiya serokê meclîsê', 'Girtinên giştî', 'B', 'Biryarên civakî bi rêya lihevkirin û gotûbêjê tên girtin, ne bi ferzkirinê.', 'Biryarên civakî bi rêya lihevkirin û gotûbêjê tên girtin, ne bi ferzkirinê.', 'Toplumsal kararlar dayatmayla değil, uzlaşı ve tartışmayla alınır.', 3, true, 'multiple_choice', NULL, NULL, 'ANF movement media + supporting academic context', 'https://anfenglishmobile.com/kadin/k-176492; Cambridge History of the Kurds, Kurdish Women’s Freedom Movement chapter', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_paradigma_0008
('005a95d6-0e8c-58c0-9a4d-18f796dee23f', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Kîjan bûyer bi sloganê "Jin, Jiyan, Azadî" re pir girêdayî ye?', 'Berxwedana jinên Kobanî (2014)', 'Peymana Lozanê (1923)', 'Şoreşa Şêx Said (1925)', 'Damezirandina Komara Mehabadê (1946)', 'A', 'Jinên di berxwedana Kobanê de bûne sembola gotina "jin, jiyan, azadî".', 'Jinên di berxwedana Kobanê de bûne sembola gotina "jin, jiyan, azadî".', 'Kobanê direnişindeki kadınlar "jin, jiyan, azadî" sözünün simgesi hâline geldi.', 2, true, 'multiple_choice', NULL, NULL, 'KJAR movement statement + supporting academic context', 'https://anfenglishmobile.com/kurdIstan/kjar-dan-10-boyutlu-bir-devrim-projesi-177521; Cambridge History of the Kurds, Kurdish Women’s Freedom Movement chapter', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_paradigma_0009
('f6d29730-f83d-528b-87c6-ea9e11c939b9', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Sembola jinên Şoreşa Rojavayê çi derdixe pêş?', 'Cilê rengîn', 'Hirça mezin', 'Jinên di xebat û parastinê de', 'Zelata zîv', 'C', 'Sembol nîşana parastina jinê ye û azadî û cihgirtina wê ya civakî destnîşan dike.', 'Sembol nîşana parastina jinê ye û azadî û cihgirtina wê ya civakî destnîşan dike.', 'Simge, kadın savunmasının işaretidir ve kadının özgürlüğünü ile toplumsal yerini gösterir.', 2, true, 'multiple_choice', NULL, NULL, 'Kongra Star institutional publications + supporting research', 'https://kongra-star.org/eng/about/; https://kongra-star.org/eng/wp-content/uploads/2025/01/Annual-Newsletter-of-the-Womens-Revolution.pdf; Cambridge History of the Kurds, Kurdish Women’s Freedom Movement chapter', 'approved', 'Kurmancî', 1, now()), -- yerel: curated_paradigma_0010
('a7c1dfda-3160-5e5e-b3d3-5ad9fc027540', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Peyva "jiyan" bi Tirkî çi tê wateyê?', 'özgürlük', 'toplum', 'yaşam', 'doğa', 'C', '"Jiyan" bi tirkî "yaşam/hayat" e.', '"Jiyan" bi tirkî "yaşam/hayat" e.', '"Jiyan" Türkçede "yaşam/hayat" demektir.', 2, true, 'multiple_choice', NULL, NULL, 'Paradîgmaya netewa demokratîk — çavkanî û şirove', 'Cambridge, Beyond Feminism? Jineolojî and the Kurdish Women''s Freedom Movement; https://kongra-star.org/eng/about/', 'approved', 'Kurmancî', 2, now()), -- yerel: edit_paradigma_0009
('666675eb-d3c2-5186-8ac3-22102dbea065', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Peyva "xweza" bi Tirkî çi tê wateyê?', 'şehir', 'doğa', 'insan', 'toplum', 'B', '"Xweza" bi Tirkî "doğa" ye; tê wateya dar, çiya, çem û hemû jîngehê. Mînak: "Xweza bedew e."', '"Xweza" bi Tirkî "doğa" ye; tê wateya dar, çiya, çem û hemû jîngehê. Mînak: "Xweza bedew e."', '"Xweza" Türkçede "doğa" demektir; ağaç, dağ, ırmak ve tüm çevre anlamına gelir. Örnek: "Xweza bedew e." (Doğa güzeldir.)', 2, true, 'multiple_choice', NULL, NULL, 'Paradîgmaya netewa demokratîk — çavkanî û şirove', 'Cambridge, Beyond Feminism? Jineolojî and the Kurdish Women''s Freedom Movement; https://kongra-star.org/eng/about/', 'approved', 'Kurmancî', 2, now()), -- yerel: edit_paradigma_0014
('8e1c374e-4eb3-5a01-b314-215c28f55bae', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Derbarê "azadîxwaziya zayendî" de agahiya herî rast kîjan e?', 'prensîbeke wekhevîxwaz a li dijî tepserî û cudakariya zayendî', 'modeleke pîşesaziyê ya ji bo qezencê xwezayê xera dike', 'beşdariya civaka herêmî di pêvajoyên biryarê de', 'helwesteke li dijî mantiqê qezenc û mêtinkirinê yê kapîtalîzmê', 'A', 'Azadîxwaziya zayendî prensîbeke wekheviyê ye; ew li dijî tepeserî û cudakariya li ser bingeha zayendê ye û azadiya her kesî diparêze.', 'Azadîxwaziya zayendî prensîbeke wekheviyê ye; ew li dijî tepeserî û cudakariya li ser bingeha zayendê ye û azadiya her kesî diparêze.', 'Cinsiyet özgürlükçülüğü eşitlikçi bir ilkedir; cinsiyete dayalı baskı ve ayrımcılığa karşı durur ve herkesin özgürlüğünü savunur.', 2, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_11587
('7b26ded7-27b6-5ce7-817d-e027b96677b5', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Bi "rexneya patriyarkayê" çi tê xwestin?', 'federasyoneke ne-dewletgir a li ser bingeha binî', 'rolên çêkirî yên ku civakê ji jin û mêr re diyar kiriye', 'eşkerekirina avahiya pergala serdestiya zilaman', 'yek pirrengî-dilxwazî ye, ya din yekreng-mecbûrî ye', 'C', 'Rexneya patriyarkayê tê wateya eşkerekirina pergala serdestiya zilaman; ew dipirse çima mêr di civakê de xwedî hêz û îmtiyaz in.', 'Rexneya patriyarkayê tê wateya eşkerekirina pergala serdestiya zilaman; ew dipirse çima mêr di civakê de xwedî hêz û îmtiyaz in.', 'Patriyarka eleştirisi, erkek egemenliği sisteminin yapısını açığa çıkarmak anlamına gelir; erkeklerin toplumda neden güç ve ayrıcalığa sahip olduğunu sorgular.', 5, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_11597
('d7d0cb69-399a-55ac-b1f1-316565247d35', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Dema "zayenda civakî" tê gotin, çi tê xwestin?', 'krîza navendîbûna aborî û siyasî ya destekî yekane', 'sîstema jiyanê ya alternatîf a modernîteya kapîtalîst', 'rolên çêkirî yên ku civakê ji jin û mêr re diyar kiriye', 'pergaleke civakî ku zilam serdest dike û jinê tepeser dike', 'C', 'Zayenda civakî behsa rolên çêkirî dike ku civak ji jin û mêran hêvî dike; ev rol ne xwezayî ne, fêrbûyî ne.', 'Zayenda civakî behsa rolên çêkirî dike ku civak ji jin û mêran hêvî dike; ev rol ne xwezayî ne, fêrbûyî ne.', 'Toplumsal cinsiyet, toplumun kadınlardan ve erkeklerden beklediği kurgulanmış rolleri ifade eder; bu roller doğal değildir, sonradan öğrenilmiştir.', 5, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_11957
('1972a59b-f6ae-59e8-876e-e283e3617f43', (select id from categories where name = 'Paradigma'), 'ku-kmr', '"antîkapîtalîzm" çi îfade dike?', 'ku rêxistinbûna demokratîk tenê bi dewleta navendî re sînordar nîne', 'beşdariya gel a rasterast di rêveberî û pêvajoyên biryarê de', 'nêrîna ku li dora zanista jinê û rexneya baviksalariyê pêş dikeve', 'helwesteke li dijî mantiqê qezenc û mêtinkirinê yê kapîtalîzmê', 'D', 'Antîkapîtalîzm helwesteke li dijî pergala kapîtalîst e; ew li dijî mantiqê qezencê û mêtinkirina ked û xwezayê derdikeve.', 'Antîkapîtalîzm helwesteke li dijî pergala kapîtalîst e; ew li dijî mantiqê qezencê û mêtinkirina ked û xwezayê derdikeve.', 'Antikapitalizm, kapitalist sisteme karşı bir tutumdur; kâr mantığına, emeğin ve doğanın sömürülmesine karşı çıkar.', 4, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_11996
('070752cc-ae4d-565c-a6b2-af697ee89cad', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Derbarê "patriyarka" de vebijêrka rast kîjan e?', 'pergaleke civakî ku zilam serdest dike û jinê tepeser dike', 'nîzameke wekhev a bêyî serdestî û mêtinkirinê', 'li seranserê cîhanê bûye sembola azadiya jinê', 'prensîbeke wekhevîxwaz a li dijî tepeserî û cudakariya zayendî', 'A', 'Patriyarka pergaleke civakî ye ku tê de zilam xwedî desthilat in û jin tên tepeserkirin; ev newekhevî di malbat, kar û siyasetê de xuya dike.', 'Patriyarka pergaleke civakî ye ku tê de zilam xwedî desthilat in û jin tên tepeserkirin; ev newekhevî di malbat, kar û siyasetê de xuya dike.', 'Ataerkillik, erkeğin egemen olup kadının bastırıldığı toplumsal sistemdir; bu eşitsizlik aile, iş ve siyasette kendini gösterir.', 3, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_12122
('9a715381-0f05-5dac-aa69-18916a7b713f', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Derbarê "demokrasiya rasterast" de agahiya herî rast kîjan e?', 'têkiliya di navbera serdestiyê û xerakirina xwezayê de', 'beşdariya civaka herêmî di pêvajoyên biryarê de', 'biryargirtina rasterast a gel bêyî nûneran', 'sêalîtiya pîşesazîparêziyê, netew-dewlet û kapîtalîzmê', 'C', 'Demokrasiya rasterast tê wateya ku gel bi xwe, bê navbeynkariya nûneran, bi civîn û dengdanê biryaran dide.', 'Demokrasiya rasterast tê wateya ku gel bi xwe, bê navbeynkariya nûneran, bi civîn û dengdanê biryaran dide.', 'Doğrudan demokrasi, halkın temsilciler olmadan bizzat toplantı ve oyla karar vermesidir.', 1, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_12331
('d98d7c23-daca-5618-a097-8b06bbf11463', (select id from categories where name = 'Paradigma'), 'ku-kmr', '"Civaka Ekolojîk" ji civaka pîşesaziyê bi kîjan aliyê ve cuda dibe?', 'Ji ber ku xwezayê tenê wek tiştê mêtinkirinê nabîne', 'Geşkirina hişmendiya civakî û ramana azad', 'Li seranserê cîhanê bûye sembola azadiya jinê', 'Mafê civakê yê xweparastin û xwerêxistinê', 'A', 'Civaka ekolojîk, ji civaka pîşesaziyê bi wê cudahiyê vediqete ku xwezayê wek tiştekî ji bo mêtinkirina bêsînor nabîne.', 'Civaka ekolojîk, ji civaka pîşesaziyê bi wê cudahiyê vediqete ku xwezayê wek tiştekî ji bo mêtinkirina bêsînor nabîne.', 'Ekolojik toplum, sanayi toplumundan doğayı sınırsız sömürülecek bir nesne olarak görmemesiyle ayrılır.', 4, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_2682
('89db67ef-40b9-53d5-9ede-0635a8e43e20', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Di nav van armancan de kîjan ne armanca "femînîzmê" ye?', 'wekheviya mafên jin û mêran', 'bidawîkirina cudakariya ku li ser jinan tê kirin', 'parastina serdestiya mêran di nav malbatê de', 'beşdariya jinan a di biryarên civakî de', 'C', 'Femînîzm ji bo rakirina cudakariya zayendî xebat dike; ew serdestiya mêran naparêze, wê dixe ber pirsê. Peyv ji latînî "femina" tê.', 'Femînîzm ji bo rakirina cudakariya zayendî xebat dike; ew serdestiya mêran naparêze, wê dixe ber pirsê. Peyv ji latînî "femina" tê.', 'Feminizm cinsiyet ayrımcılığını ortadan kaldırmak için çalışır; erkek egemenliğini korumaz, tersine onu sorgular. Terim Latince "femina" (kadın) sözcüğünden gelir.', 2, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2001
('d2d7fd02-6aac-57b2-ac64-c1e3b292f9e0', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Kîjan taybetî "demokrasiya nûnertiyê" ji demokrasiya rasterast cuda dike?', 'gel rasterast bi referandûmê biryarê dide', 'biryar bi destê kesên hilbijartî tên girtin', 'biryarên herêmî di civînên gundan de tên girtin', 'her kes di civîna giştî de dengê xwe bilind dike', 'B', 'Di nûnertiyê de gel hêza xwe ya biryarê dide çend kesan û ew li şûna wî diaxivin; di ya rasterast de ev hêz li ba gel dimîne.', 'Di nûnertiyê de gel hêza xwe ya biryarê dide çend kesan û ew li şûna wî diaxivin; di ya rasterast de ev hêz li ba gel dimîne.', 'Temsili demokraside halk karar yetkisini seçtiği kişilere devreder ve onlar halk adına konuşur; doğrudan demokraside bu yetki halkın kendisinde kalır.', 3, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2002
('ac298928-32c6-5078-8f75-e45ba45954bf', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Di ramana civakî de "şoreşa neolîtîk" çima wek qonaxeke veguherînê tê dîtin?', 'nivîs hat vedîtin û dewletên yekem hatin damezrandin', 'mirov dest bi çandiniyê û xwedîkirina ajalan kir', 'bajarên mezin ên pîşesaziyê li kêleka çeman ava bûn', 'hesin hat helandin û çekên nû derketin', 'B', 'Bi çandiniyê re mirov li cihekî man, embar dagirtin û zêdehiya hilberînê derket; gava ku hin kes destê xwe danîn ser wê zêdehiyê, ji bo kombûna dewlemendiyê û zêdebûna newekheviyê şert û mercên nû çêbûn.', 'Bi çandiniyê re mirov li cihekî man, embar dagirtin û zêdehiya hilberînê derket; gava ku hin kes destê xwe danîn ser wê zêdehiyê, ji bo kombûna dewlemendiyê û zêdebûna newekheviyê şert û mercên nû çêbûn.', 'Tarımla birlikte insanlar bir yere yerleşti, ambarlar doldu ve artı ürün ortaya çıktı; o artı ürüne el koyanların belirmesiyle birçok toplumda servet birikimi ve eşitsizliğin artması için yeni koşullar doğdu.', 5, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2005
('5fb6e686-9a0f-5971-ae3a-c28b2a3de216', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Hin kes dibêjin "hemwelatî" tenê bi cihê jidayikbûnê tê diyarkirin. Ev îdîa rast e?', 'Rast', 'Şaş', '-', '-', 'B', 'Hemwelatîbûn TENÊ bi cihê jidayikbûnê nayê diyarkirin; li gorî pergala hiqûqî bi cihê jidayikbûnê, bi rêza malbatê an bi wergirtina paşerojê tê bidestxistin.', 'Hemwelatîbûn TENÊ bi cihê jidayikbûnê nayê diyarkirin; li gorî pergala hiqûqî bi cihê jidayikbûnê, bi rêza malbatê an bi wergirtina paşerojê tê bidestxistin.', 'Yurttaşlık YALNIZCA doğum yeriyle belirlenmez; hukuk sistemine göre doğum yeri (jus soli), soy bağı (jus sanguinis) ya da sonradan vatandaşlığa alınma yollarından biriyle kazanılır.', 2, true, 'true_false', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2006
('fac5392a-fe83-55d1-b3dd-8229ceb6164a', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Peyva "utopya" yekem car di pirtûka kê de wek navê giravekê derbas bû?', 'Thomas More', 'Karl Marx', 'Jean-Jacques Rousseau', 'Aristoteles', 'A', 'Thomas More di sala 1516an de pirtûka xwe "Utopia" nivîsî; nav ji yewnanî tê û tê wateya "cihê ku tune ye". Ji wê rojê ve peyv ji bo civaka xeyalkirî tê bikaranîn.', 'Thomas More di sala 1516an de pirtûka xwe "Utopia" nivîsî; nav ji yewnanî tê û tê wateya "cihê ku tune ye". Ji wê rojê ve peyv ji bo civaka xeyalkirî tê bikaranîn.', 'Thomas More 1516''da "Utopia" adlı kitabını yazdı; ad Yunancadan gelir ve "olmayan yer" anlamındadır. O gün bugündür sözcük, kurulmamış ama düşünülmüş toplumu anlatır.', 4, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2007
('680c774c-37d3-5579-889d-47ad2f895c1f', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Li gorî hinekan "anarşîzm" hem dewletê hem jî her cure rêxistinbûna civakî red dike. Ev nirxandin durist e?', 'Rast', 'Şaş', '-', '-', 'B', 'Anarşîzm desthilata ji jor ve red dike, lê rêxistina ji jêr ve — sendîka, kooperatîf, komîn — ji xwe re dike bingeh. Ya ku red dike ne rêxistin e, hiyerarşiya bi zorê ye.', 'Anarşîzm desthilata ji jor ve red dike, lê rêxistina ji jêr ve — sendîka, kooperatîf, komîn — ji xwe re dike bingeh. Ya ku red dike ne rêxistin e, hiyerarşiya bi zorê ye.', 'Anarşizm yukarıdan gelen iktidarı reddeder, ama aşağıdan örgütlenmeyi — sendika, kooperatif, komün — kendine temel alır. Reddettiği örgüt değil, zorla kurulan hiyerarşidir.', 4, true, 'true_false', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2008
('5ee114d2-8d1c-5d13-970f-f10cd2c7bf52', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Kîjan bingeh di ramana "lîberalîzmê" de cih nagire?', 'azadiya kesane li hember dewletê', 'aboriya bazara reqabeta azad', 'wekheviya hemû kesan li ber qanûnê', 'milkiyeta hevpar a amûrên hilberînê', 'D', 'Lîberalîzm azadiya kesane û milkiyeta taybet dixe navendê; milkiyeta hevpar a amûrên hilberînê taybetmendiya ramanên sosyalîst e.', 'Lîberalîzm azadiya kesane û milkiyeta taybet dixe navendê; milkiyeta hevpar a amûrên hilberînê taybetmendiya ramanên sosyalîst e.', 'Liberalizm bireysel özgürlüğü ve özel mülkiyeti merkeze alır; üretim araçlarının ortak mülkiyeti sosyalist düşüncelerin ayırt edici savıdır.', 5, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2009
('0eb3bd01-50a3-50e1-b2d7-bae00f4ed8f7', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Gava mirov dadperweriya civakî ji xêrxwaziyê cuda dike, xala herî bingehîn kîjan e?', 'ew mafek e ku divê bê dayîn, ne bexşîşek e', 'ew tenê ji aliyê dewletê ve tê birêvebirin', 'ew li ser dilxwaziya kesên dewlemend ava dibe', 'ew tenê di dema krîzên aborî de tê nîqaşkirin', 'A', 'Xêrxwazî ji dilê kesekî tê û her gav dikare bê birîn; dadperwerî erkek e ku civak deyndara wê ye û bi rêbazên hevpar tê pêkanîn.', 'Xêrxwazî ji dilê kesekî tê û her gav dikare bê birîn; dadperwerî erkek e ku civak deyndara wê ye û bi rêbazên hevpar tê pêkanîn.', 'Hayırseverlik kişinin gönlünden gelir ve her an kesilebilir; toplumsal adalet ise toplumun borçlu olduğu bir yükümlülüktür ve ortak kurallarla yerine getirilir.', 4, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2010
('35914acb-1c4f-5eea-acfc-8bb38c3dbb3e', (select id from categories where name = 'Paradigma'), 'ku-kmr', '"Çîna civakî" di nêrîna Marksîst de ne bi dilxwaziya kesan, lê bi cihê wan ê di têkiliyên hilberînê de tê diyarkirin. Ev gotin durist e?', 'Rast', 'Şaş', '-', '-', 'A', 'Di vê nêrînê de çîn ne hilbijartina kesekî ye: bi xwedîtiya amûrên hilberînê û bi rola di xebatê de tê danîn. Loma mirov li cihekî radiweste ku ne bi dilê wî ve girêdayî ye.', 'Di vê nêrînê de çîn ne hilbijartina kesekî ye: bi xwedîtiya amûrên hilberînê û bi rola di xebatê de tê danîn. Loma mirov li cihekî radiweste ku ne bi dilê wî ve girêdayî ye.', 'Bu görüşte sınıf kişinin seçimi değildir: üretim araçlarına sahiplikle ve emek sürecindeki rolle belirlenir. Bu yüzden kişi kendini nasıl gördüğünden bağımsız bir yerde durur.', 3, true, 'true_false', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2011
('742f8d34-1227-5396-b66b-00697604573a', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Ziman, dîrok û bîra hevpar hêmanên "nasnameya civakî" ne. Ev gotin durist e?', 'Rast', 'Şaş', '-', '-', 'A', 'Nasname ne tenê hilbijartineke kesane ye; di nav ziman, bîra hevpar û jiyana bi hev re de tê avakirin. Loma windabûna zimên pirsgirêkeke nasnameyê ye.', 'Nasname ne tenê hilbijartineke kesane ye; di nav ziman, bîra hevpar û jiyana bi hev re de tê avakirin. Loma windabûna zimên pirsgirêkeke nasnameyê ye.', 'Kimlik yalnız kişisel bir tercih değildir; dilin, ortak belleğin ve birlikte yaşamanın içinde kurulur. Bu yüzden dil kaybı bir kimlik meselesi sayılır.', 1, true, 'true_false', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2012
('ba73f592-3672-5e8a-bd7f-557b4622484c', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Li bajarekî çend ziman, çend ol û çend çand bi hev re dijîn; ev rewş bi kîjan têgehê tê binavkirin?', 'pirrengî', 'yekrengî', 'asîmîlasyon', 'navendîbûn', 'A', 'Pirrengî tê wê wateyê ku cudahî wek dewlemendî tên dîtin; li hemberî wê yekrengî hemû cudahiyan dixe bin qalibekî.', 'Pirrengî tê wê wateyê ku cudahî wek dewlemendî tên dîtin; li hemberî wê yekrengî hemû cudahiyan dixe bin qalibekî.', 'Çoğulluk, farklılıkların zenginlik sayılmasıdır; karşısındaki tekçilik ise bütün farklılıkları tek kalıba sokmayı hedefler.', 1, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2013
('75b92360-c70d-54dd-a8f6-e0fd7f464b89', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Gundiyên gundekî bi hev re nexweşxaneyeke biçûk ava dikin û lêçûnê parve dikin; ev helwest kîjan nirxa civakî nîşan dide?', 'reqabet', 'serdestî', 'hevgirtin', 'bêaliyî', 'C', 'Hevgirtin ne alîkariya ji jor ve ye; barê giran bi hev re hilgirtin e — her kes hem dide hem jî werdigire, kes deyndar namîne.', 'Hevgirtin ne alîkariya ji jor ve ye; barê giran bi hev re hilgirtin e — her kes hem dide hem jî werdigire, kes deyndar namîne.', 'Dayanışma yukarıdan yapılan bir yardım değildir; ağır yükü birlikte taşımaktır — herkes hem verir hem alır, kimse borçlu duruma düşmez.', 2, true, 'multiple_choice', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_par_2014
('c26112be-a6f5-5751-ac91-927b9d343f47', (select id from categories where name = 'Paradigma'), 'ku-kmr', '"veqetandina hêzan" parvekirina desthilatê di navbera qanûndanîn, rêveberî û dadgehê de ye. Ev rast e an şaş e?', 'Rast', 'Şaş', '-', '-', 'A', 'Rast e. Ji heman qadê têgeheke din "hişmendiya ekolojîk" e: zanîna ku mirov beşek ji xwezayê ye, ne xwediyê wê.', 'Rast e. Ji heman qadê têgeheke din "hişmendiya ekolojîk" e: zanîna ku mirov beşek ji xwezayê ye, ne xwediyê wê.', 'Doğru. Aynı alandan bir başka kavram "hişmendiya ekolojîk"tir: insanın doğanın sahibi değil parçası olduğu bilincidir.', 3, true, 'true_false', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_tf_par_0010
('8d5af883-de8a-50a0-ab3e-36fbddc79c97', (select id from categories where name = 'Paradigma'), 'ku-kmr', '"veqetandina hêzan" zanîna ku mirov beşek ji xwezayê ye, ne xwediyê wê ye. Ev rast e an şaş e?', 'Rast', 'Şaş', '-', '-', 'B', 'Na — ev ravekirina "hişmendiya ekolojîk" e; "veqetandina hêzan" parvekirina desthilatê di navbera qanûndanîn, rêveberî û dadgehê de ye.', 'Na — ev ravekirina "hişmendiya ekolojîk" e; "veqetandina hêzan" parvekirina desthilatê di navbera qanûndanîn, rêveberî û dadgehê de ye.', 'Hayır — bu tanım "hişmendiya ekolojîk"e aittir; "veqetandina hêzan", iktidarın yasama, yürütme ve yargı arasında bölünmesidir.', 4, true, 'true_false', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_tf_par_0011
('2816274a-3269-5f14-804b-811a6ddc0ef0', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Ev ravekirin ji bo "zayenda civakî" rast e an şaş e: komek saziyên ku ne dewlet in û ne jî bazar in?', 'Rast', 'Şaş', '-', '-', 'B', 'Na — ev ravekirina "civaka sivîl" e; "zayenda civakî" tê vê wateyê: rolên ku civak li jin û mêran bar dike, ne yên xwezayî.', 'Na — ev ravekirina "civaka sivîl" e; "zayenda civakî" tê vê wateyê: rolên ku civak li jin û mêran bar dike, ne yên xwezayî.', 'Hayır — bu tanım "civaka sivîl" kavramına ait; "zayenda civakî" şu anlama gelir: toplumun kadın ve erkeğe yüklediği, doğal olmayan roller.', 5, true, 'true_false', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_tf_par_0023
('5417fe74-a2cd-59a2-a1dc-a02183315611', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Rast e an şaş e: "civaka sivîl" komeke saziyan e ku ne dewlet in û ne jî bazar in.', 'Rast', 'Şaş', '-', '-', 'A', 'Rast e, ravekirin li cih e. "zayenda civakî" têgeheke cuda ye: rolên ku civak li jin û mêran bar dike, ne yên xwezayî.', 'Rast e, ravekirin li cih e. "zayenda civakî" têgeheke cuda ye: rolên ku civak li jin û mêran bar dike, ne yên xwezayî.', 'Doğru, tanım yerinde. "zayenda civakî" ayrı bir kavramdır: toplumun kadın ve erkeğe yüklediği, doğal olmayan rollerdir.', 3, true, 'true_false', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()), -- yerel: offline_tf_par_0024
('b7b5bcce-bd48-597e-8765-706488898469', (select id from categories where name = 'Paradigma'), 'ku-kmr', 'Rast e an şaş e: "civaka sivîl" kombûna desthilat an sermayeyê di destê hindik kesan de ye.', 'Rast', 'Şaş', '-', '-', 'B', 'Na — ev ravekirina "tekelparêzî" ye; "civaka sivîl" komek saziyan e ku ne dewlet in û ne jî bazar in.', 'Na — ev ravekirina "tekelparêzî" ye; "civaka sivîl" komek saziyan e ku ne dewlet in û ne jî bazar in.', 'Hayır — bu tanım "tekelparêzî"ye aittir; "civaka sivîl", ne devlet ne pazar olan kurumlar bütünüdür.', 4, true, 'true_false', NULL, NULL, NULL, NULL, 'approved', 'Kurmancî', 1, now()) -- yerel: offline_tf_par_0025
on conflict (id) do nothing;

-- Doğrulama: bu dosyadaki kimliklerin hepsi Paradigma kategorisinde onaylı olmalı.
do $$
declare
  v_count integer;
begin
  select count(*) into v_count
  from questions
  where id in ('c92ad542-44a5-5e8e-8de2-fa98bfe80754', 'f1aadc8a-c7d6-5a52-916b-8aeb903694a2', '44f5b3ec-2270-5937-a2a0-2be65e453235', 'de546122-b7bd-555a-ae98-36c8a4a20953', '8c4bbd0e-34d9-5dcc-a89d-484efaa40f91', '3736ddc3-402a-5cea-95a8-4a22e12bacd7', 'ac77fa76-0c60-57ab-93f1-9a2dbaa2160c', 'c78cf9a6-d577-5bbb-9e6a-76c0d297fb72', 'e67ab304-9e45-53d9-b7e4-48984ccb3e72', '6093f353-ef60-5fe9-a160-f7c2b5b27341', 'd9f2629c-cdef-5f47-b594-0c2ed0cc2ffa', '7c7bbbb5-f8af-5536-b169-2576591932db', '005a95d6-0e8c-58c0-9a4d-18f796dee23f', 'f6d29730-f83d-528b-87c6-ea9e11c939b9', 'a7c1dfda-3160-5e5e-b3d3-5ad9fc027540', '666675eb-d3c2-5186-8ac3-22102dbea065', '8e1c374e-4eb3-5a01-b314-215c28f55bae', '7b26ded7-27b6-5ce7-817d-e027b96677b5', 'd7d0cb69-399a-55ac-b1f1-316565247d35', '1972a59b-f6ae-59e8-876e-e283e3617f43', '070752cc-ae4d-565c-a6b2-af697ee89cad', '9a715381-0f05-5dac-aa69-18916a7b713f', 'd98d7c23-daca-5618-a097-8b06bbf11463', '89db67ef-40b9-53d5-9ede-0635a8e43e20', 'd2d7fd02-6aac-57b2-ac64-c1e3b292f9e0', 'ac298928-32c6-5078-8f75-e45ba45954bf', '5fb6e686-9a0f-5971-ae3a-c28b2a3de216', 'fac5392a-fe83-55d1-b3dd-8229ceb6164a', '680c774c-37d3-5579-889d-47ad2f895c1f', '5ee114d2-8d1c-5d13-970f-f10cd2c7bf52', '0eb3bd01-50a3-50e1-b2d7-bae00f4ed8f7', '35914acb-1c4f-5eea-acfc-8bb38c3dbb3e', '742f8d34-1227-5396-b66b-00697604573a', 'ba73f592-3672-5e8a-bd7f-557b4622484c', '75b92360-c70d-54dd-a8f6-e0fd7f464b89', 'c26112be-a6f5-5751-ac91-927b9d343f47', '8d5af883-de8a-50a0-ab3e-36fbddc79c97', '2816274a-3269-5f14-804b-811a6ddc0ef0', '5417fe74-a2cd-59a2-a1dc-a02183315611', 'b7b5bcce-bd48-597e-8765-706488898469')
    and category_id = (select id from categories where name = 'Paradigma')
    and is_approved = true;
  if v_count <> 40 then
    raise exception 'Paradigma: beklenen 40 onayli soru, bulunan %', v_count;
  end if;
end
$$;

commit;
