// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfbM_MumCIpUy-4iWO5EWXilVux5rHZvA',
    appId: '1:419853194959:web:ba480f941a9a4f9b1289ba',
    messagingSenderId: '419853194959',
    projectId: 'zankurd-eb5f9',
    authDomain: 'zankurd-eb5f9.firebaseapp.com',
    storageBucket: 'zankurd-eb5f9.firebasestorage.app',
    measurementId: 'G-Q6V8QS8DGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrQ6z8J1FlCQyCAjcXJ-OfAtsM87JD2wQ',
    appId: '1:419853194959:android:5bc65b029a53abad1289ba',
    messagingSenderId: '419853194959',
    projectId: 'zankurd-eb5f9',
    storageBucket: 'zankurd-eb5f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHYWuyKYxJgFWDwuv5wIQQc8j2rG8hU28',
    appId: '1:419853194959:ios:d41a7d30b71e1fd91289ba',
    messagingSenderId: '419853194959',
    projectId: 'zankurd-eb5f9',
    storageBucket: 'zankurd-eb5f9.firebasestorage.app',
    iosClientId:
        '419853194959-f0sft2254sc155j2rcv323r3ejg5kkqv.apps.googleusercontent.com',
    iosBundleId: 'com.zankurd.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHYWuyKYxJgFWDwuv5wIQQc8j2rG8hU28',
    appId: '1:419853194959:ios:d41a7d30b71e1fd91289ba',
    messagingSenderId: '419853194959',
    projectId: 'zankurd-eb5f9',
    storageBucket: 'zankurd-eb5f9.firebasestorage.app',
    iosClientId:
        '419853194959-f0sft2254sc155j2rcv323r3ejg5kkqv.apps.googleusercontent.com',
    iosBundleId: 'com.zankurd.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfbM_MumCIpUy-4iWO5EWXilVux5rHZvA',
    appId: '1:419853194959:web:4fad5fc2f754477f1289ba',
    messagingSenderId: '419853194959',
    projectId: 'zankurd-eb5f9',
    authDomain: 'zankurd-eb5f9.firebaseapp.com',
    storageBucket: 'zankurd-eb5f9.firebasestorage.app',
    measurementId: 'G-R4SRXWPEM7',
  );
}
