#!/usr/bin/env python3
"""Normalize the JSON question source and regenerate the Dart runtime bank."""

import json
import re
import sys
import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = ROOT / "assets" / "data" / "offline_questions.json"
DART_FILE = ROOT / "lib" / "src" / "data" / "offline_question_bank.dart"

TERM_FIXES = {
    "yerel kıyafetler": "cilûbergên herêmî",
    "masal anlatımı": "vegotina çîrokan",
    "bayramlaşma": "pîrozkirina cejnê",
    "halk mutfağı": "mitbaxa gel",
    "yerleşik yaşam": "jiyana nîştecih",
    "kültürel etkileşim": "bandora çandî",
    "anlatıcı": "vebêj",
    "toplumsal cinsiyet": "zayenda civakî",
    "demokratik konfederalizm": "konfederalîzma demokratîk",
    "kapitalist modernite": "modernîteya kapîtalîst",
    "özgür eş yaşam": "jiyana hevpar a azad",
}


def normalize(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().lower())


def fix_prompt(prompt: str) -> str:
    prompt = prompt.replace(
        "jiyana آزاد (jiyana hevewîya azad)", "jiyana hevpar a azad"
    ).replace("konfederalîzma demokratîkin", "konfederalîzma demokratîk")
    for turkish, kurmanci in TERM_FIXES.items():
        prompt = re.sub(re.escape(turkish), kurmanci, prompt, flags=re.IGNORECASE)
    return prompt


def displayed_correct_index(question: dict) -> int:
    answers = question["answers"]
    offset = sum(map(ord, question["id"])) % len(answers)
    if offset == 0:
        offset = 1
    rotated = answers[offset:] + answers[:offset]
    return rotated.index(question["correctAnswer"])


def prepare(questions: list[dict]) -> tuple[list[dict], int]:
    unique: list[dict] = []
    seen: set[tuple[str, str]] = set()
    for raw in questions:
        question = dict(raw)
        question["prompt"] = fix_prompt(question.get("prompt", ""))
        key = (question.get("category", ""), normalize(question["prompt"]))
        if key in seen:
            continue
        seen.add(key)
        question["answers"] = list(question["answers"])
        unique.append(question)

    four_choice_index = 0
    for question in unique:
        answers = question["answers"]
        if len(answers) != 4:
            continue
        target_display_index = four_choice_index % 4
        four_choice_index += 1
        offset = sum(map(ord, question["id"])) % 4
        if offset == 0:
            offset = 1
        target_stored_index = (target_display_index + offset) % 4
        current_index = answers.index(question["correctAnswer"])
        answers[current_index], answers[target_stored_index] = (
            answers[target_stored_index],
            answers[current_index],
        )

    return unique, len(questions) - len(unique)


def dart_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("$", "\\$")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )
    return f"'{escaped}'"


def render_dart(questions: list[dict]) -> str:
    lines = [
        "// Generated by tool/verify_and_fix_question_bank.py. Do not edit by hand.",
        "import '../models/quiz_question.dart';",
        "",
        "const offlineQuestionBank = <QuizQuestion>[",
    ]
    for question in questions:
        answers = ", ".join(dart_string(value) for value in question["answers"])
        lines.extend(
            [
                "  QuizQuestion(",
                f"    id: {dart_string(question['id'])},",
                f"    category: {dart_string(question['category'])},",
                f"    prompt: {dart_string(question['prompt'])},",
                f"    answers: [{answers}],",
                f"    correctAnswer: {dart_string(question['correctAnswer'])},",
                f"    explanation: {dart_string(question.get('explanation', ''))},",
            ]
        )
        if question.get("explanationKu") is not None:
            lines.append(
                f"    explanationKu: {dart_string(question['explanationKu'])},"
            )
        if question.get("explanationTr") is not None:
            lines.append(
                f"    explanationTr: {dart_string(question['explanationTr'])},"
            )
        lines.append(
            f"    type: QuestionType.{question.get('type', 'multipleChoice')},"
        )
        if question.get("imageUrl") is not None:
            lines.append(f"    imageUrl: {dart_string(question['imageUrl'])},")
        lines.extend(
            [
                f"    difficulty: {int(question.get('difficulty', 2))},",
                "  ),",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Offline soru bankasını doğrula veya deterministik üret."
    )
    parser.add_argument(
        "--fix",
        action="store_true",
        help="JSON ve Dart çıktılarını kanonik içerikle yeniden yazar.",
    )
    args = parser.parse_args()

    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    questions = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    prepared, removed = prepare(questions)
    expected_json = json.dumps(prepared, ensure_ascii=False, indent=2) + "\n"
    expected_dart = render_dart(prepared)

    if args.fix:
        DATA_FILE.write_text(expected_json, encoding="utf-8")
        DART_FILE.write_text(expected_dart, encoding="utf-8")
    else:
        mismatches = []
        if DATA_FILE.read_text(encoding="utf-8") != expected_json:
            mismatches.append(str(DATA_FILE.relative_to(ROOT)))
        if DART_FILE.read_text(encoding="utf-8") != expected_dart:
            mismatches.append(str(DART_FILE.relative_to(ROOT)))
        if mismatches:
            print(
                "[HATA] Kanonik olmayan soru bankası çıktısı: "
                + ", ".join(mismatches)
                + ". Düzeltmek için --fix kullanın.",
                file=sys.stderr,
            )
            raise SystemExit(1)

    positions = [0, 0, 0, 0]
    for question in prepared:
        if len(question["answers"]) == 4:
            positions[displayed_correct_index(question)] += 1
    print(
        f"[OK] {len(prepared)} soru doğrulandı; {removed} tekrar adayı; "
        f"görünen doğru şık dağılımı: {positions}"
    )


if __name__ == "__main__":
    main()
